id: issues-00-conventions
name: GitOps.PullRequestIssueManagement
description: Handles when an issue follows predetermined conventions
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When an issue has a specific title prefix, add a label
        if:
          - payloadType: Issues
        then:
          # bicep
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Bicep Registry\]'
                      isRegex: true
                  - titleContains:
                      pattern: '^\[Bicep\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /bicep/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Skill: DevOps'
          # devops
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[DevOps\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /DevOps/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Skill: DevOps'
          # hubs
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Hubs\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /Hubs/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: FinOps hubs'
          # open data
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Open data\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /Open data set/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: Open data'
          # powershell
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[PowerShell\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /PowerShell/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: PowerShell'
          # workbooks
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Workbooks\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /workbooks/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Skill: Workbooks'
onFailure:
onSuccess:
