id: issues-01-new
name: GitOps.PullRequestIssueManagement
description: Handles when an issue is first opened
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When an author creates a new issue:
          - Label with `Needs: Triage 🔍`
          - Add a welcome comment
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - not: isAssignedToSomeone
          - not:
              hasLabel:
                label: 'Needs: Information'
          - not:
              hasLabel:
                label: 'Status: ✍️ Spec in progress'
          - not:
              hasLabel:
                label: 'Status: 🔭 Spec review'
          - not:
              hasLabel:
                label: 'Status: ▶️ Ready'
          - not:
              hasLabel:
                label: 'Status: 🔄️ In progress'
          - not:
              hasLabel:
                label: 'Status: 🔬 Code review'
          - not:
              hasLabel:
                label: 'Good first issue 🏆'
          - not:
              hasLabel:
                label: 'Skill: DevOps'
          - not:
              hasLabel:
                label: 'Skill: Documentation'
          - not:
              hasLabel:
                label: 'Tool: Bicep Registry'
          - not:
              hasLabel:
                label: 'Tool: FinOps guide'
          - not:
              hasLabel:
                label: 'Tool: FinOps hubs'
          - not:
              hasLabel:
                label: 'Tool: Governance workbook'
          - not:
              hasLabel:
                label: 'Tool: Open data'
          - not:
              hasLabel:
                label: 'Tool: Optimization Engine'
          - not:
              hasLabel:
                label: 'Tool: Optimization workbook'
          - not:
              hasLabel:
                label: 'Tool: Power BI'
          - not:
              hasLabel:
                label: 'Tool: PowerShell'
          - not:
              hasLabel:
                label: 'Tool: Workbooks'
        then:
          - addLabel:
              label: 'Needs: Triage 🔍'
          - addReply:
              reply: |
                Thank you for submitting this issue! We try to respond within 3 business days. In the meantime:

                - 📖 Check the [troubleshooting guide](https://aka.ms/ftk/trouble) for common issues
                - 💬 Ask questions in [Discussions](https://github.com/microsoft/finops-toolkit/discussions)
                - 📅 Join our [biweekly office hours](https://aka.ms/ftk/office-hours) for live help from the team
onFailure:
onSuccess:
