id: issues-00-conventions
name: GitOps.PullRequestIssueManagement
description: Handles when an issue follows predetermined conventions
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When an issue has a specific title prefix, add a label
        if:
          - payloadType: Issues
        then:
          # aoe
          - if:
              - or:
                  - titleContains:
                      pattern: /(aoe|optimization engine)/i
                      isRegex: true
                  - bodyContains:
                      pattern: /(aoe|optimization engine)/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: Optimization Engine'
          # bicep / terraform
          - if:
              - or:
                  - titleContains:
                      pattern: /(bicep|terraform)/i
                      isRegex: true
                  - bodyContains:
                      pattern: /(bicep|terraform)/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Skill: Deployment'
          - if:
              - or:
                  - titleContains:
                      pattern: /bicep registry/i
                      isRegex: true
                  - bodyContains:
                      pattern: /bicep registry/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: Bicep Registry'
          # devops
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[DevOps\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /devops/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Skill: DevOps'
          # hubs
          - if:
              - or:
                  - titleContains:
                      pattern: /hubs/i
                      isRegex: true
                  - bodyContains:
                      pattern: /hubs/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: FinOps hubs'
          # open data
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Open data\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /Open data set/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: Open data'
          # powershell
          - if:
              - or:
                  - titleContains:
                      pattern: /PowerShell/i
                      isRegex: true
                  - bodyContains:
                      pattern: /PowerShell/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: PowerShell'
          # workbooks
          - if:
              - or:
                  - titleContains:
                      pattern: '^\[Workbooks\]'
                      isRegex: true
                  - bodyContains:
                      pattern: /workbooks/i
                      isRegex: true
            then:
              - addLabel:
                  label: 'Tool: Workbooks'
onFailure:
onSuccess:
