name: PR lifecycle
description: Pull request lifecycle
resource: repository

configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - and:
              - or:
                  - targetsBranch:
                      branch: dev
                  - targetsBranch:
                      branch: features/*
              - or:
                  - isAction:
                      action: Opened
                  - isAction:
                      action: Synchronize
        then:
          - addLabel:
              label: 'Needs: Review 👀'
          - assignTo:
              user: ankur-ms
          - assignTo:
              user: flanakin
          - assignTo:
              user: sreenav
          - assignTo:
              user: tsilvers-ms
          - requestReview:
              reviewer: ankur-ms
          - requestReview:
              reviewer: flanakin
          - requestReview:
              reviewer: sreenav
          - requestReview:
              reviewer: tsilvers-ms
