id: pulls-06-contrib
name: GitOps.PullRequestIssueManagement
description: Handles when a PR is opened with specific file paths
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When a PR is reviewed, add as review contributor
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
          - or:
              - isAction:
                  action: Submitted # for reviews
              - isAction:
                  action: Created # for comments
          - not:
              targetsBranch:
                branch: main
          - isActivitySender:
              issueAuthor: false
          - not:
              or:
                - isActivitySender:
                    user: allcontributors
                - isActivitySender:
                    user: aromano2
                - isActivitySender:
                    user: benshy
                - isActivitySender:
                    user: flanakin
                - isActivitySender:
                    user: helderpinto
                - isActivitySender:
                    user: msbrett
                - isActivitySender:
                    user: springstone
        then:
          - addReply:
              reply: '@all-contributors please add ${contextualAuthor} for review'
      - description: When a PR is closed, add as contributor
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Closed
          - not:
              targetsBranch:
                branch: main
        then:
          # all code
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^(\.build|\.github|\.vscode|src\/scripts)\/.*
                  - filesMatchPattern:
                      pattern: ^src\/.*
              - not:
                  or:
                    - isActivitySender:
                        user: aromano2
                    - isActivitySender:
                        user: arthurclares
                    - isActivitySender:
                        user: didayal-msft
                    - isActivitySender:
                        user: flanakin
                    - isActivitySender:
                        user: msbrett
                    - isActivitySender:
                        user: nteyan
                    - isActivitySender:
                        user: saadmsft
                    - isActivitySender:
                        user: sebassem
                    - isActivitySender:
                        user: springstone
            then:
              - addReply:
                  reply: '@all-contributors please add ${issueAuthor} for code'
          # docs
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|docs-mslearn|docs-wiki)\/.*
              - not:
                  or:
                    - isActivitySender:
                        user: aromano2
                    - isActivitySender:
                        user: benshy
                    - isActivitySender:
                        user: flanakin
                    - isActivitySender:
                        user: helderpinto
                    - isActivitySender:
                        user: msbrett
                    - isActivitySender:
                        user: springstone
            then:
              - addReply:
                  reply: '@all-contributors please add ${issueAuthor} for doc'
onFailure:
onSuccess:
