id: pulls-00-file-paths
name: GitOps.PullRequestIssueManagement
description: Handles when a PR is opened with specific file paths
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When a PR is reviewed, add as review contributor
        if:
          - or:
              - payloadType: Pull_Request_Review
              - payloadType: Pull_Request_Review_Comment
          - or:
              - isAction:
                  action: Submitted # for reviews
              - isAction:
                  action: Created # for comments
          - not:
              targetsBranch:
                branch: main
          - not:
              or:
                - isActivitySender:
                    user: allcontributors
                - isActivitySender:
                    user: aromano2
                - isActivitySender:
                    user: benshy
                - isActivitySender:
                    user: flanakin
                - isActivitySender:
                    user: msbrett
                - isActivitySender:
                    user: springstone
        then:
          - addReply:
              reply: '@all-contributors please add ${contextualAuthor} for review'
      - description: When a PR is closed, add as contributor
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Closed
          - not:
              targetsBranch:
                branch: main
        then:
          # all code
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^(.build|.github|.vscode|src\/scripts)\/.*
                  - filesMatchPattern:
                      pattern: ^src\/.*
              - not:
                  or:
                    - isActivitySender:
                        user: aromano2
                    - isActivitySender:
                        user: arthurclares
                    - isActivitySender:
                        user: didayal-msft
                    - isActivitySender:
                        user: flanakin
                    - isActivitySender:
                        user: msbrett
                    - isActivitySender:
                        user: nteyan
                    - isActivitySender:
                        user: saadmsft
                    - isActivitySender:
                        user: sebassem
                    - isActivitySender:
                        user: springstone
            then:
              - addReply:
                  reply: '@all-contributors please add ${issueAuthor} for code'
          # docs
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|docs-wiki)\/.*
              - not:
                  or:
                    - isActivitySender:
                        user: aromano2
                    - isActivitySender:
                        user: benshy
                    - isActivitySender:
                        user: flanakin
                    - isActivitySender:
                        user: helderpinto
                    - isActivitySender:
                        user: msbrett
                    - isActivitySender:
                        user: springstone
            then:
              - addReply:
                  reply: '@all-contributors please add ${issueAuthor} for doc'
      - description: When a PR is opened, add labels based on file paths
        if:
          - payloadType: Pull_Request
          - not:
              targetsBranch:
                branch: main
        then:
          # all paths -- Michael
          - if:
              - not:
                  isActivitySender:
                    user: flanakin
            then:
              - requestReview:
                  reviewer: flanakin
              - assignTo:
                  user: flanakin
          # devops
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^(.build|.github|.vscode|src\/scripts)\/.*
                  - filesMatchPattern:
                      pattern: ^src\/([^\/]+\/)?[^\/]+.md$
            then:
              - addLabel:
                  label: 'Area: DevOps'
              # Anthony
              - if:
                  - not:
                      isActivitySender:
                        user: aromano2
                then:
                  - requestReview:
                      reviewer: aromano2
                  - assignTo:
                      user: aromano2
          # docs
          - if:
              - filesMatchPattern:
                  pattern: ^docs\/.*
            then:
              - addLabel:
                  label: 'Area: Documentation'
          # bicep
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|src)\/bicep-registry\/.*
            then:
              - addLabel:
                  label: 'Solution: Bicep Registry'
          # hubs
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs\/finops-hub\/.*
                  - filesMatchPattern:
                      pattern: ^src\/templates\/finops-hub\/.*
                  - filesMatchPattern:
                      pattern: ^src\/powershell\/(Public|Private)\/[^-]+-FinOpsHub[^\.]*\.ps1
            then:
              - addLabel:
                  label: 'Solution: FinOps hubs'
              # Brett
              - if:
                  - not:
                      isActivitySender:
                        user: msbrett
                then:
                  - requestReview:
                      reviewer: msbrett
                  - assignTo:
                      user: msbrett
          # open data
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|src)\/open-data\/.*
            then:
              - addLabel:
                  label: 'Solution: Open data'
          # powershell
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|src)\/powershell\/.*
            then:
              - addLabel:
                  label: 'Area: PowerShell'
              # Anthony
              - if:
                  - not:
                      isActivitySender:
                        user: aromano2
                then:
                  - requestReview:
                      reviewer: aromano2
                  - assignTo:
                      user: aromano2
              # Arthur
              - if:
                  - not:
                      isActivitySender:
                        user: arthurclares
                then:
                  - requestReview:
                      reviewer: arthurclares
                  - assignTo:
                      user: arthurclares
              # Divyadeep
              - if:
                  - not:
                      isActivitySender:
                        user: didayal-msft
                then:
                  - requestReview:
                      reviewer: didayal-msft
                  - assignTo:
                      user: didayal-msft
              # Saad
              - if:
                  - not:
                      isActivitySender:
                        user: saadmsft
                then:
                  - requestReview:
                      reviewer: saadmsft
                  - assignTo:
                      user: saadmsft
              # Sacha
              - if:
                  - not:
                      isActivitySender:
                        user: springstone
                then:
                  - requestReview:
                      reviewer: springstone
                  - assignTo:
                      user: springstone
              # Seif
              - if:
                  - not:
                      isActivitySender:
                        user: sebassem
                then:
                  - requestReview:
                      reviewer: sebassem
                  - assignTo:
                      user: sebassem
          # workbooks
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs\/[^-]+-workbook\/.*
                  - filesMatchPattern:
                      pattern: ^src\/workbooks\/.*
            then:
              - addLabel:
                  label: 'Solution: Workbooks'
              # Arthur
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs\/optimization-workbook\/.*
                      - filesMatchPattern:
                          pattern: ^src\/workbooks\/(\.scaffold|optimization)\/.*
                  - not:
                      isActivitySender:
                        user: arthurclares
                then:
                  - requestReview:
                      reviewer: arthurclares
                  - assignTo:
                      user: arthurclares
              # Nicolas
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs\/governance-workbook\/.*
                      - filesMatchPattern:
                          pattern: ^src\/workbooks\/(\.scaffold|governance)\/.*
                  - not:
                      isActivitySender:
                        user: nteyan
                then:
                  - requestReview:
                      reviewer: nteyan
                  - assignTo:
                      user: nteyan
              # Seif
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs\/optimization-workbook\/.*
                      - filesMatchPattern:
                          pattern: ^src\/workbooks\/(\.scaffold|optimization)\/.*
                  - not:
                      isActivitySender:
                        user: sebassem
                then:
                  - requestReview:
                      reviewer: sebassem
                  - assignTo:
                      user: sebassem
onFailure:
onSuccess:
