id: pulls-02-reviewers
name: GitOps.PullRequestIssueManagement
description: Handles when a PR is opened with specific file paths
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When a PR is opened, add reviewers and labels based on file paths
        if:
          - payloadType: Pull_Request
          - not:
              targetsBranch:
                branch: main
        then:
          # all paths -- Arthur
          - if:
              - not:
                  isActivitySender:
                    user: arthurclares
            then:
              - requestReview:
                  reviewer: arthurclares
              - assignTo:
                  user: arthurclares
          # all paths -- Michael
          - if:
              - not:
                  isActivitySender:
                    user: flanakin
            then:
              - requestReview:
                  reviewer: flanakin
              - assignTo:
                  user: flanakin
          # devops
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^(\.build|\.github|\.vscode|src\/scripts)\/.*
                  - filesMatchPattern:
                      pattern: ^src\/([^\/]+\/)?[^\/]+.md$
                  - filesMatchPattern:
                      pattern: ^package.json$
            then:
              - addLabel:
                  label: 'Skill: DevOps'
              # Anthony
              - if:
                  - not:
                      isActivitySender:
                        user: aromano2
                  # VS Code settings and PowerShell scripts only
                  - filesMatchPattern:
                      pattern: ^(\.vscode/.*\.json|(\.build|src\/scripts)\/.*\.ps[dm]?1)$
                then:
                  - requestReview:
                      reviewer: aromano2
                  - assignTo:
                      user: aromano2
          # docs
          - if:
              - filesMatchPattern:
                  pattern: ^docs\/.*
            then:
              - addLabel:
                  label: 'Skill: Documentation'
          - if:
              - filesMatchPattern:
                  pattern: ^(docs\/(_docs|_guide)|docs-mslearn\/framework|docs-mslearn\/focus)\/.*
            then:
              - addLabel:
                  label: 'Tool: FinOps guide'
              # Jared
              - if:
                  - not:
                      isActivitySender:
                        user: caddyg
                  # Framework capabilities only
                  - filesMatchPattern:
                      pattern: ^(docs\/_docs|docs-mslearn)\/framework/.*
                then:
                  - requestReview:
                      reviewer: caddyg
                  - assignTo:
                      user: caddyg
              # Kevin
              - if:
                  - not:
                      isActivitySender:
                        user: kevindlr
                  # Framework capabilities only
                  - filesMatchPattern:
                      pattern: ^(docs\/_docs|docs-mslearn)\/framework/.*
                then:
                  - requestReview:
                      reviewer: kevindlr
                  - assignTo:
                      user: kevindlr
              # Nicolas
              - if:
                  - not:
                      isActivitySender:
                        user: nteyan
                  # Best practice library only
                  - filesMatchPattern:
                      pattern: ^(docs\/_docs|docs-mslearn)\/best-practices/.*
                then:
                  - requestReview:
                      reviewer: nteyan
                  - assignTo:
                      user: nteyan
          # bicep
          - if:
              - filesMatchPattern:
                  pattern: ^src\/.*\.bicep
            then:
              - addLabel:
                  label: 'Skill: Deployment'
              # Zach
              - if:
                  - not:
                      isActivitySender:
                        user: fallenhoot
                then:
                  - requestReview:
                      reviewer: fallenhoot
                  - assignTo:
                      user: fallenhoot
          - if:
              - filesMatchPattern:
                  pattern: ^(docs\/_automation|docs-mslearn\/toolkit|src)\/bicep-registry\/.*
            then:
              - addLabel:
                  label: 'Tool: Bicep Registry'
              # Zach
              - if:
                  - not:
                      isActivitySender:
                        user: fallenhoot
                then:
                  - requestReview:
                      reviewer: fallenhoot
                  - assignTo:
                      user: fallenhoot
          # hubs
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^(docs\/_reporting\/hubs|src\/templates\/finops-hub)\/.*
                  - filesMatchPattern:
                      pattern: ^src\/powershell\/.*Hub.*
            then:
              - addLabel:
                  label: 'Tool: FinOps hubs'
              # Brett
              - if:
                  - not:
                      isActivitySender:
                        user: msbrett
                then:
                  - requestReview:
                      reviewer: msbrett
                  - assignTo:
                      user: msbrett
              # Helder
              - if:
                  - not:
                      isActivitySender:
                        user: helderpinto
                then:
                  - requestReview:
                      reviewer: helderpinto
                  - assignTo:
                      user: helderpinto
              # Robel
              - if:
                  - not:
                      isActivitySender:
                        user: ro100e
                then:
                  - requestReview:
                      reviewer: ro100e
                  - assignTo:
                      user: ro100e
              # Roland
              - if:
                  - not:
                      isActivitySender:
                        user: rolandkrummenacher
                then:
                  - requestReview:
                      reviewer: rolandkrummenacher
                  - assignTo:
                      user: rolandkrummenacher
          # kql
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^.*\.kql$
                  - filesMatchPattern:
                      pattern: ^src\/templates\/finops-hub\/modules\/dataExplorer\.bicep$
            then:
              - addLabel:
                  label: 'Skill: KQL'
              # Brad
              - if:
                  - not:
                      isActivitySender:
                        user: bwatts64
                then:
                  - requestReview:
                      reviewer: bwatts64
                  - assignTo:
                      user: bwatts64
          # open data
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs\/_reporting\/data\/.*
                  - filesMatchPattern:
                      pattern: ^docs-mslearn\/toolkit\/open-data.md$
                  - filesMatchPattern:
                      pattern: ^src\/open-data\/.*
            then:
              - addLabel:
                  label: 'Tool: Open data'
          # power-bi
          - if:
              - filesMatchPattern:
                  pattern: ^(docs\/_reporting|docs-mslearn\/toolkit|src)\/power-bi\/.*
            then:
              - addLabel:
                  label: 'Tool: Power BI'
              # Chris
              - if:
                  - not:
                      isActivitySender:
                        user: chris-bowman
                then:
                  - requestReview:
                      reviewer: chris-bowman
                  - assignTo:
                      user: chris-bowman
          # powershell
          - if:
              - filesMatchPattern:
                  pattern: ^(docs\/_automation|docs-mslearn\/toolkit|src)\/powershell\/.*
            then:
              - addLabel:
                  label: 'Tool: PowerShell'
              # Anthony
              - if:
                  - not:
                      isActivitySender:
                        user: aromano2
                then:
                  - requestReview:
                      reviewer: aromano2
                  - assignTo:
                      user: aromano2
              # Divyadeep
              - if:
                  - not:
                      isActivitySender:
                        user: didayal-msft
                then:
                  - requestReview:
                      reviewer: didayal-msft
                  - assignTo:
                      user: didayal-msft
              # Helder
              - if:
                  - not:
                      isActivitySender:
                        user: helderpinto
                then:
                  - requestReview:
                      reviewer: helderpinto
                  - assignTo:
                      user: helderpinto
              # Sacha
              - if:
                  - not:
                      isActivitySender:
                        user: springstone
                then:
                  - requestReview:
                      reviewer: springstone
                  - assignTo:
                      user: springstone
          # optimization engine
          - if:
              - filesMatchPattern:
                  pattern: ^(docs\/_optimize|docs-mslearn\/toolkit|src)\/optimization-engine\/.*
            then:
              - addLabel:
                  label: 'Tool: Optimization Engine'
              # Helder
              - if:
                  - not:
                      isActivitySender:
                        user: helderpinto
                then:
                  - requestReview:
                      reviewer: helderpinto
                  - assignTo:
                      user: helderpinto
          # terraform
          - if:
              - filesMatchPattern:
                  pattern: ^src\/.*\.tf
            then:
              - addLabel:
                  label: 'Skill: Deployment'
              # Divyadeep
              - if:
                  - not:
                      isActivitySender:
                        user: didayal-msft
                then:
                  - requestReview:
                      reviewer: didayal-msft
                  - assignTo:
                      user: didayal-msft
              # Sacha
              - if:
                  - not:
                      isActivitySender:
                        user: springstone
                then:
                  - requestReview:
                      reviewer: springstone
                  - assignTo:
                      user: springstone
          # web
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^src\/web\/.*
            then:
              - addLabel:
                  label: 'Tool: Web app'
              # Ivan
              - if:
                  - not:
                      isActivitySender:
                        user: ivanmtta
                then:
                  - requestReview:
                      reviewer: ivanmtta
                  - assignTo:
                      user: ivanmtta
              # Jamel
              - if:
                  - not:
                      isActivitySender:
                        user: jamelachahbar
                then:
                  - requestReview:
                      reviewer: jamelachahbar
                  - assignTo:
                      user: jamelachahbar
              # Orthodoxos
              - if:
                  - not:
                      isActivitySender:
                        user: akiskips
                then:
                  - requestReview:
                      reviewer: akiskips
                  - assignTo:
                      user: akiskips
          # workbooks
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs\/_optimize\/workbooks\/.*
                  - filesMatchPattern:
                      pattern: ^docs\/_optimize\/[^-]+-workbook\/.*
                  - filesMatchPattern:
                      pattern: ^src\/scripts\/Build-Workbook.ps1$
                  - filesMatchPattern:
                      pattern: ^src\/workbooks\/.*
            then:
              - addLabel:
                  label: 'Tool: Workbooks'
              - if:
                  - filesMatchPattern:
                      pattern: ^(docs\/_optimize\/optimization-workbook|src\/workbooks\/optimization)\/.*
                then:
                  - addLabel:
                      label: 'Tool: Optimization workbook'
              - if:
                  - filesMatchPattern:
                      pattern: ^(docs\/_optimize\/governance-workbook|docs-mslearn\/toolkit\/governance-workbook|src\/workbooks\/governance)\/.*
                then:
                  - addLabel:
                      label: 'Tool: Governance workbook'
              # Nicolas
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^(docs\/_optimize|docs-mslearn\/toolkit)\/governance-workbook\/.*
                      - filesMatchPattern:
                          pattern: ^src\/scripts\/Build-Workbook.ps1$
                      - filesMatchPattern:
                          pattern: ^src\/workbooks\/(\.scaffold|governance)\/.*
                  - not:
                      isActivitySender:
                        user: nteyan
                then:
                  - requestReview:
                      reviewer: nteyan
                  - assignTo:
                      user: nteyan
              # Seif
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^(docs\/_optimize|docs-mslearn\/toolkit)\/optimization-workbook\/.*
                      - filesMatchPattern:
                          pattern: ^src\/scripts\/Build-Workbook.ps1$
                      - filesMatchPattern:
                          pattern: ^src\/workbooks\/(\.scaffold|optimization)\/.*
                  - not:
                      isActivitySender:
                        user: sebassem
                then:
                  - requestReview:
                      reviewer: sebassem
                  - assignTo:
                      user: sebassem
onFailure:
onSuccess:
