// ============================================================================
// Query: Effective Average Compute Cost per Core and Hourly Cost per CPU Core
// Description:
//   Computes two compute-efficiency KPIs from FinOps Hub cost records in one pass over Costs().
//   It summarizes compute usage cost, unused commitment cost, and computed core-hours by billing currency.
// KPI: Effective Average Compute Cost per Core; Hourly Cost per CPU Core
// Formula:
//   HourlyCostPerCore = sum(EffectiveCost for compute usage rows) / sum(x_ConsumedCoreHours for compute usage rows)
//   EffectiveAverageCostPerCore = (sum(EffectiveCost for compute usage rows) + sum(EffectiveCost where CommitmentDiscountStatus=='Unused' AND isnotempty(CommitmentDiscountCategory))) / sum(x_ConsumedCoreHours for compute usage rows)
// Author: FinOps toolkit
// Parameters:
//   startDate: datetime; start of the reporting period (default: startofmonth(ago(30d)))
//   endDate: datetime; end of the reporting period, exclusive (default: startofmonth(now()))
// Output:
//   One row per BillingCurrency with BillingCurrency, TotalEffectiveCostUSDLike, UnusedCommitmentCost, TotalCoreHours, HourlyCostPerCore, and EffectiveAverageCostPerCore.
// Usage:
//   Use this query to compare amortized compute spend per consumed vCPU-hour with and without unused commitment cost.
// Scope Notes:
//   Azure-only VM usage detection uses x_SkuMeterCategory in ('Virtual Machines', 'Virtual Machine Licenses') with ChargeCategory == 'Usage'.
//   UnusedCommitmentCost is restricted to unused compute commitments (CommitmentDiscountStatus == 'Unused' AND the
//   commitment SKU is itself in the compute meter categories), so non-compute commitment waste does not inflate
//   compute unit economics. Wave-boundary fix (T-3000.12 cross-model review): gpt-5.5 flagged that the prior
//   un-scoped predicate mixed non-compute waste into the compute denominator.
//   Core counts reflect billed VCPUs/vCores from x_SkuDetails, and all monetary values remain denominated in BillingCurrency rather than normalized USD.
// Last Tested: 2026-05-28 against msbwftktreyhub.westus.kusto.windows.net/Hub (1,366,763 cost rows in 2026-04 window). UAT result: PASS — 1 row returned; HourlyCostPerCore=0.019 USD
// =========================================================================
let startDate = startofmonth(ago(30d));
let endDate = startofmonth(now());
Costs()
| where ChargePeriodStart >= startDate and ChargePeriodStart < endDate
| where not(ChargeCategory == 'Purchase' and isnotempty(CommitmentDiscountCategory))
| extend tmp_IsVMUsage            = x_SkuMeterCategory in ('Virtual Machines', 'Virtual Machine Licenses') and ChargeCategory == 'Usage'
| extend tmp_IsComputeCommitment  = x_SkuMeterCategory in ('Virtual Machines', 'Virtual Machine Licenses')
| extend x_SkuCoreCount           = iff(tmp_IsVMUsage, toint(coalesce(x_SkuDetails.VCPUs, x_SkuDetails.vCores)), toint(''))
| extend x_ConsumedCoreHours      = iff(tmp_IsVMUsage and isnotempty(x_SkuCoreCount), toreal(x_SkuCoreCount * ConsumedQuantity), toreal(''))
| summarize
    TotalEffectiveCostUSDLike = todouble(sumif(EffectiveCost, tmp_IsVMUsage)),
    UnusedCommitmentCost = todouble(sumif(EffectiveCost, CommitmentDiscountStatus == 'Unused' and isnotempty(CommitmentDiscountCategory) and tmp_IsComputeCommitment)),
    TotalCoreHours = todouble(sum(x_ConsumedCoreHours))
    by BillingCurrency
| extend HourlyCostPerCore = todouble(iff(isnull(TotalCoreHours) or TotalCoreHours == 0.0, 0.0, TotalEffectiveCostUSDLike / TotalCoreHours))
| extend EffectiveAverageCostPerCore = todouble(iff(isnull(TotalCoreHours) or TotalCoreHours == 0.0, 0.0, (TotalEffectiveCostUSDLike + UnusedCommitmentCost) / TotalCoreHours))
| project BillingCurrency, TotalEffectiveCostUSDLike, UnusedCommitmentCost, TotalCoreHours, HourlyCostPerCore, EffectiveAverageCostPerCore
