.create-or-alter function
with (docstring = 'Gets all cost and usage records with the latest supported version of the FOCUS schema.', folder = 'Ingestion')
Costs()
{
    database('ingestion').Costs_1_0
}

.create-or-alter function
with (docstring = 'Gets all recommendations aligned with the latest supported version of the FOCUS schema.', folder = 'Ingestion')
Recommendations()
{
    database('ingestion').Recommendations_1_0
}
