// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// resource_type
.create-or-alter function 
with (docstring = 'Return details about the specified ID.', folder = 'OpenData')
resource_type(id: string) {
    dynamic({
        "microsoft.aad/domainservices": { "SingularDisplayName": "Microsoft Entra Domain Services" }
        ,"microsoft.aadiam/diagnosticsettings": { "SingularDisplayName": "Microsoft.aadiam diagnostic setting" }
        ,"microsoft.aadiam/privatelinkforazuread": { "SingularDisplayName": "Private Link for Microsoft Entra ID" }
        ,"microsoft.alertsmanagement/actionrules": { "SingularDisplayName": "Alert processing rule" }
        ,"microsoft.alertsmanagement/alerts": { "SingularDisplayName": "Microsoft.AlertsManagement alert" }
        ,"microsoft.alertsmanagement/alerts/enrichments": { "SingularDisplayName": "Microsoft.AlertsManagement alerts enrichment" }
        ,"microsoft.alertsmanagement/prometheusrulegroups": { "SingularDisplayName": "Prometheus rule group" }
        ,"microsoft.alertsmanagement/smartdetectoralertrules": { "SingularDisplayName": "Smart detector alert rule" }
        ,"microsoft.alertsmanagement/smartgroups": { "SingularDisplayName": "Microsoft.AlertsManagement smart group" }
        ,"microsoft.alertsmanagement/tenantactivitylogalerts": { "SingularDisplayName": "Microsoft.AlertsManagement tenant activity log alert" }
        ,"microsoft.all/arcvirtualmachines": { "SingularDisplayName": "Azure Arc virtual machine" }
        ,"microsoft.all/hcivirtualmachines": { "SingularDisplayName": "Azure Stack HCI Virtual Machine - Azure Arc" }
        ,"microsoft.all/virtualmachines": { "SingularDisplayName": "Virtual machine" }
        ,"microsoft.analysisservices/servers": { "SingularDisplayName": "Analysis Services server" }
        ,"microsoft.anybuild/clusters": { "SingularDisplayName": "AnyBuild cluster" }
        ,"microsoft.apicenter/deletedservices": { "SingularDisplayName": "Microsoft.ApiCenter deleted service" }
        ,"microsoft.apicenter/services": { "SingularDisplayName": "API Center" }
        ,"microsoft.apicenter/services/workspaces": { "SingularDisplayName": "Workspace" }
        ,"microsoft.apimanagement/gateways": { "SingularDisplayName": "API Management gateway" }
        ,"microsoft.apimanagement/gateways/configconnections": { "SingularDisplayName": "Microsoft.ApiManagement gateways config connection" }
        ,"microsoft.apimanagement/service": { "SingularDisplayName": "API Management service" }
        ,"microsoft.apimanagement/service/workspaces": { "SingularDisplayName": "Workspace" }
        ,"microsoft.apisecurity/defendersettings": { "SingularDisplayName": "Microsoft.ApiSecurity defender setting" }
        ,"microsoft.app/builders": { "SingularDisplayName": "Microsoft.App builder" }
        ,"microsoft.app/builders/builds": { "SingularDisplayName": "Microsoft.App builders build" }
        ,"microsoft.app/connectedenvironments": { "SingularDisplayName": "Container Apps Connected Environment" }
        ,"microsoft.app/containerapps": { "SingularDisplayName": "Container App" }
        ,"microsoft.app/jobs": { "SingularDisplayName": "Container App Job" }
        ,"microsoft.app/logicapps": { "SingularDisplayName": "Logic app" }
        ,"microsoft.app/logicapps/workflows": { "SingularDisplayName": "Logic app workflow" }
        ,"microsoft.app/managedenvironments": { "SingularDisplayName": "Container Apps Environment" }
        ,"microsoft.app/sessionpools": { "SingularDisplayName": "Container App Session Pool" }
        ,"microsoft.app/spaces": { "SingularDisplayName": "App Space" }
        ,"microsoft.batch/batchaccounts": { "SingularDisplayName": "Batch account" }
        ,"microsoft.billing/billingaccounts": { "SingularDisplayName": "Microsoft.Billing billing account" }
        ,"microsoft.billing/billingaccounts/agreements": { "SingularDisplayName": "Microsoft.Billing billing accounts agreement" }
        ,"microsoft.billing/billingaccounts/associatedtenants": { "SingularDisplayName": "Microsoft.Billing billing accounts associated tenant" }
        ,"microsoft.billing/billingaccounts/availablebalance": { "SingularDisplayName": "Microsoft.Billing billing accounts available balance" }
        ,"microsoft.billing/billingaccounts/billingprofiles": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profile" }
        ,"microsoft.billing/billingaccounts/billingprofiles/availablebalance": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles available balance" }
        ,"microsoft.billing/billingaccounts/billingprofiles/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles billing role assignment" }
        ,"microsoft.billing/billingaccounts/billingprofiles/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles billing role definition" }
        ,"microsoft.billing/billingaccounts/billingprofiles/billingsubscriptions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles billing subscription" }
        ,"microsoft.billing/billingaccounts/billingprofiles/customers": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles customer" }
        ,"microsoft.billing/billingaccounts/billingprofiles/customers/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles customers billing role assignment" }
        ,"microsoft.billing/billingaccounts/billingprofiles/customers/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles customers billing role definition" }
        ,"microsoft.billing/billingaccounts/billingprofiles/customers/transfers": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles customers transfer" }
        ,"microsoft.billing/billingaccounts/billingprofiles/instructions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles instruction" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoices": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice section" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice sections billing role assignment" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice sections billing role definition" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections/billingsubscriptions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice sections billing subscription" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections/products": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice sections product" }
        ,"microsoft.billing/billingaccounts/billingprofiles/invoicesections/transfers": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles invoice sections transfer" }
        ,"microsoft.billing/billingaccounts/billingprofiles/paymentmethodlinks": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles payment method link" }
        ,"microsoft.billing/billingaccounts/billingprofiles/policies": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles policy" }
        ,"microsoft.billing/billingaccounts/billingprofiles/transactions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing profiles transaction" }
        ,"microsoft.billing/billingaccounts/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts billing role assignment" }
        ,"microsoft.billing/billingaccounts/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing role definition" }
        ,"microsoft.billing/billingaccounts/billingsubscriptionaliases": { "SingularDisplayName": "Microsoft.Billing billing accounts billing subscription aliase" }
        ,"microsoft.billing/billingaccounts/billingsubscriptions": { "SingularDisplayName": "Microsoft.Billing billing accounts billing subscription" }
        ,"microsoft.billing/billingaccounts/billingsubscriptions/invoices": { "SingularDisplayName": "Microsoft.Billing billing accounts billing subscriptions invoice" }
        ,"microsoft.billing/billingaccounts/customers": { "SingularDisplayName": "Microsoft.Billing billing accounts customer" }
        ,"microsoft.billing/billingaccounts/customers/billingsubscriptions": { "SingularDisplayName": "Microsoft.Billing billing accounts customers billing subscription" }
        ,"microsoft.billing/billingaccounts/customers/policies": { "SingularDisplayName": "Microsoft.Billing billing accounts customers policy" }
        ,"microsoft.billing/billingaccounts/customers/products": { "SingularDisplayName": "Microsoft.Billing billing accounts customers product" }
        ,"microsoft.billing/billingaccounts/departments": { "SingularDisplayName": "Microsoft.Billing billing accounts department" }
        ,"microsoft.billing/billingaccounts/departments/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts departments billing role assignment" }
        ,"microsoft.billing/billingaccounts/departments/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts departments billing role definition" }
        ,"microsoft.billing/billingaccounts/departments/enrollmentaccounts": { "SingularDisplayName": "Microsoft.Billing billing accounts departments enrollment account" }
        ,"microsoft.billing/billingaccounts/enrollmentaccounts": { "SingularDisplayName": "Microsoft.Billing billing accounts enrollment account" }
        ,"microsoft.billing/billingaccounts/enrollmentaccounts/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing accounts enrollment accounts billing role assignment" }
        ,"microsoft.billing/billingaccounts/enrollmentaccounts/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing accounts enrollment accounts billing role definition" }
        ,"microsoft.billing/billingaccounts/incentiveschedules": { "SingularDisplayName": "Incentive Schedule" }
        ,"microsoft.billing/billingaccounts/incentiveschedules/milestones": { "SingularDisplayName": "Milestone" }
        ,"microsoft.billing/billingaccounts/invoices": { "SingularDisplayName": "Microsoft.Billing billing accounts invoice" }
        ,"microsoft.billing/billingaccounts/invoicesections": { "SingularDisplayName": "Microsoft.Billing billing accounts invoice section" }
        ,"microsoft.billing/billingaccounts/invoicesections/billingsubscriptions": { "SingularDisplayName": "Microsoft.Billing billing accounts invoice sections billing subscription" }
        ,"microsoft.billing/billingaccounts/invoicesections/products": { "SingularDisplayName": "Microsoft.Billing billing accounts invoice sections product" }
        ,"microsoft.billing/billingaccounts/invoicesections/transfers": { "SingularDisplayName": "Microsoft.Billing billing accounts invoice sections transfer" }
        ,"microsoft.billing/billingaccounts/lineofcredit": { "SingularDisplayName": "Microsoft.Billing billing accounts line of credit" }
        ,"microsoft.billing/billingaccounts/paymentmethods": { "SingularDisplayName": "Microsoft.Billing billing accounts payment method" }
        ,"microsoft.billing/billingaccounts/policies": { "SingularDisplayName": "Microsoft.Billing billing accounts policy" }
        ,"microsoft.billing/billingaccounts/products": { "SingularDisplayName": "Microsoft.Billing billing accounts product" }
        ,"microsoft.billing/billingaccounts/reservationorders": { "SingularDisplayName": "Microsoft.Billing billing accounts reservation order" }
        ,"microsoft.billing/billingaccounts/reservationorders/reservations": { "SingularDisplayName": "Microsoft.Billing billing accounts reservation orders reservation" }
        ,"microsoft.billing/billingaccounts/savingsplanorders": { "SingularDisplayName": "Savings plan order" }
        ,"microsoft.billing/billingaccounts/savingsplanorders/savingsplans": { "SingularDisplayName": "Savings plan" }
        ,"microsoft.billing/billingperiods": { "SingularDisplayName": "Microsoft.Billing billing period" }
        ,"microsoft.billing/billingproperty": { "SingularDisplayName": "Microsoft.Billing billing property" }
        ,"microsoft.billing/billingrequests": { "SingularDisplayName": "Microsoft.Billing billing request" }
        ,"microsoft.billing/billingroleassignments": { "SingularDisplayName": "Microsoft.Billing billing role assignment" }
        ,"microsoft.billing/billingroledefinitions": { "SingularDisplayName": "Microsoft.Billing billing role definition" }
        ,"microsoft.billing/enrollmentaccounts": { "SingularDisplayName": "Microsoft.Billing enrollment account" }
        ,"microsoft.billing/paymentmethods": { "SingularDisplayName": "Microsoft.Billing payment method" }
        ,"microsoft.billing/policies": { "SingularDisplayName": "Microsoft.Billing policy" }
        ,"microsoft.billing/promotions": { "SingularDisplayName": "Microsoft.Billing promotion" }
        ,"microsoft.billing/transfers": { "SingularDisplayName": "Microsoft.Billing transfer" }
        ,"microsoft.billingbenefits/incentiveschedules": { "SingularDisplayName": "Incentive Schedule" }
        ,"microsoft.billingbenefits/incentiveschedules/milestones": { "SingularDisplayName": "Milestone" }
        ,"microsoft.billingbenefits/maccs": { "SingularDisplayName": "Microsoft Azure Consumption Commitment" }
        ,"microsoft.billingbenefits/reservationorderaliases": { "SingularDisplayName": "Microsoft.BillingBenefits reservation order aliase" }
        ,"microsoft.billingbenefits/savingsplanorderaliases": { "SingularDisplayName": "Microsoft.BillingBenefits savings plan order aliase" }
        ,"microsoft.billingbenefits/savingsplanorders": { "SingularDisplayName": "Savings plan order" }
        ,"microsoft.billingbenefits/savingsplanorders/savingsplans": { "SingularDisplayName": "Savings plan" }
        ,"microsoft.bing/accounts": { "SingularDisplayName": "Bing Resource" }
        ,"microsoft.cache/redis": { "SingularDisplayName": "Redis cache" }
        ,"microsoft.cache/redisenterprise": { "SingularDisplayName": "Redis Enterprise cluster" }
        ,"microsoft.cache/redisenterprise/databases": { "SingularDisplayName": "Redis Enterprise database" }
        ,"microsoft.capacity/reservationorders": { "SingularDisplayName": "Reservation order" }
        ,"microsoft.capacity/reservationorders/reservations": { "SingularDisplayName": "Reservation" }
        ,"microsoft.cascade/sites": { "SingularDisplayName": "Microsoft.Cascade site" }
        ,"microsoft.cleanroom/microservices": { "SingularDisplayName": "Microsoft.CleanRoom microservice" }
        ,"microsoft.cloud/hubs": { "SingularDisplayName": "FinOps hub" }
        ,"microsoft.clouddeviceplatform/delegatedidentities": { "SingularDisplayName": "Microsoft.CloudDevicePlatform delegated identity" }
        ,"microsoft.cloudhealth/healthmodels": { "SingularDisplayName": "Health Model" }
        ,"microsoft.cloudtest/accounts": { "SingularDisplayName": "CloudTest Account" }
        ,"microsoft.cloudtest/buildcaches": { "SingularDisplayName": "1ES Build Cache" }
        ,"microsoft.cloudtest/hostedpools": { "SingularDisplayName": "1ES Hosted Pool" }
        ,"microsoft.cloudtest/images": { "SingularDisplayName": "1ES Image" }
        ,"microsoft.cloudtest/pools": { "SingularDisplayName": "CloudTest Pool" }
        ,"microsoft.clusterstor/nodes": { "SingularDisplayName": "ClusterStor" }
        ,"microsoft.codesigning/codesigningaccounts": { "SingularDisplayName": "Trusted Signing Account" }
        ,"microsoft.codespaces/plans": { "SingularDisplayName": "Microsoft.Codespaces plan" }
        ,"microsoft.cognitiveservices/accounts": { "SingularDisplayName": "Azure AI services" }
        ,"microsoft.cognitiveservices/commitmentplans": { "SingularDisplayName": "Microsoft.CognitiveServices commitment plan" }
        ,"microsoft.cognitiveservices/commitmentplans/accountassociations": { "SingularDisplayName": "Microsoft.CognitiveServices commitment plans account association" }
        ,"microsoft.communication/communicationservices": { "SingularDisplayName": "Communication Service" }
        ,"microsoft.communication/emailservices": { "SingularDisplayName": "Email Communication Service" }
        ,"microsoft.communication/emailservices/domains": { "SingularDisplayName": "Email Communication Services Domain" }
        ,"microsoft.community/communitytrainings": { "SingularDisplayName": "Community Training" }
        ,"microsoft.compositesolutions/compositesolutiondefinitions": { "SingularDisplayName": "Microsoft.CompositeSolutions composite solution definition" }
        ,"microsoft.compositesolutions/compositesolutions": { "SingularDisplayName": "Microsoft.CompositeSolutions composite solution" }
        ,"microsoft.compute/availabilitysets": { "SingularDisplayName": "Availability set" }
        ,"microsoft.compute/capacityreservationgroups": { "SingularDisplayName": "Capacity Reservation Group" }
        ,"microsoft.compute/capacityreservationgroups/capacityreservations": { "SingularDisplayName": "Capacity reservation" }
        ,"microsoft.compute/capacityreservationgroupscomputehub": { "SingularDisplayName": "Capacity Reservation Group" }
        ,"microsoft.compute/cloudservices": { "SingularDisplayName": "Cloud service (extended support)" }
        ,"microsoft.compute/computefleetinstances": { "SingularDisplayName": "Instance" }
        ,"microsoft.compute/diskaccesses": { "SingularDisplayName": "Disk Access" }
        ,"microsoft.compute/diskencryptionsets": { "SingularDisplayName": "Disk Encryption Set" }
        ,"microsoft.compute/disks": { "SingularDisplayName": "Disk" }
        ,"microsoft.compute/galleries": { "SingularDisplayName": "Azure compute gallery" }
        ,"microsoft.compute/galleries/applications": { "SingularDisplayName": "VM application definition" }
        ,"microsoft.compute/galleries/applications/versions": { "SingularDisplayName": "VM application version" }
        ,"microsoft.compute/galleries/images": { "SingularDisplayName": "VM image definition" }
        ,"microsoft.compute/galleries/images/versions": { "SingularDisplayName": "VM image version" }
        ,"microsoft.compute/galleries/imagescomputehub": { "SingularDisplayName": "VM image definition" }
        ,"microsoft.compute/hostgroups": { "SingularDisplayName": "Host group" }
        ,"microsoft.compute/hostgroups/hosts": { "SingularDisplayName": "Host" }
        ,"microsoft.compute/hostgroupscomputehub": { "SingularDisplayName": "Host group" }
        ,"microsoft.compute/images": { "SingularDisplayName": "Image" }
        ,"microsoft.compute/imagescomputehub": { "SingularDisplayName": "Image" }
        ,"microsoft.compute/locations/communitygalleries/images": { "SingularDisplayName": "Community image" }
        ,"microsoft.compute/locations/communitygalleries/imagescomputehub": { "SingularDisplayName": "Community image" }
        ,"microsoft.compute/proximityplacementgroups": { "SingularDisplayName": "Proximity placement group" }
        ,"microsoft.compute/proximityplacementgroupscomputehub": { "SingularDisplayName": "Proximity placement group" }
        ,"microsoft.compute/restorepointcollections": { "SingularDisplayName": "Restore Point Collection" }
        ,"microsoft.compute/restorepointcollections/restorepoints": { "SingularDisplayName": "Restore Point" }
        ,"microsoft.compute/snapshots": { "SingularDisplayName": "Snapshot" }
        ,"microsoft.compute/sshpublickeys": { "SingularDisplayName": "SSH key" }
        ,"microsoft.compute/standbypoolinstance": { "SingularDisplayName": "Standby pool" }
        ,"microsoft.compute/virtualmachinecomputehub": { "SingularDisplayName": "Virtual machine" }
        ,"microsoft.compute/virtualmachineflexinstances": { "SingularDisplayName": "Instance" }
        ,"microsoft.compute/virtualmachines": { "SingularDisplayName": "Virtual machine" }
        ,"microsoft.compute/virtualmachines/providers/guestconfigurationassignments": { "SingularDisplayName": "Guest Assignment" }
        ,"microsoft.compute/virtualmachinescalesets": { "SingularDisplayName": "Virtual machine scale set" }
        ,"microsoft.compute/virtualmachinescalesets/providers/guestconfigurationassignments": { "SingularDisplayName": "Guest Assignment" }
        ,"microsoft.compute/virtualmachinescalesets/virtualmachines": { "SingularDisplayName": "Virtual machine scale set instance" }
        ,"microsoft.compute/virtualmachinescalesets/virtualmachines/networkinterfaces/ipconfigurations/publicipaddresses": { "SingularDisplayName": "Public IP address" }
        ,"microsoft.computehub/advisorcost": { "SingularDisplayName": "Recommendations" }
        ,"microsoft.computehub/advisoroperationalexcellence": { "SingularDisplayName": "Recommendations" }
        ,"microsoft.computehub/advisorperformance": { "SingularDisplayName": "Recommendations" }
        ,"microsoft.computehub/advisorreliability": { "SingularDisplayName": "Recommendations" }
        ,"microsoft.computehub/advisorsecurity": { "SingularDisplayName": "Recommendations" }
        ,"microsoft.computehub/all": { "SingularDisplayName": "All resources" }
        ,"microsoft.computehub/backup": { "SingularDisplayName": "Backup job" }
        ,"microsoft.computehub/computehubmain": { "SingularDisplayName": "Compute infrastructure" }
        ,"microsoft.computehub/healthevents": { "SingularDisplayName": "Health events" }
        ,"microsoft.computehub/linuxostype": { "SingularDisplayName": "Linux OS" }
        ,"microsoft.computehub/microsoftdefenderfreetrialsubscription": { "SingularDisplayName": "Microsoft defender" }
        ,"microsoft.computehub/microsoftdefenderstandardsubscription": { "SingularDisplayName": "Microsoft defender" }
        ,"microsoft.computehub/outages": { "SingularDisplayName": "Outages" }
        ,"microsoft.computehub/powerstatedeallocated": { "SingularDisplayName": "Power states" }
        ,"microsoft.computehub/powerstaterunning": { "SingularDisplayName": "Power states" }
        ,"microsoft.computehub/powerstatestopped": { "SingularDisplayName": "Power states" }
        ,"microsoft.computehub/provisioningstatefailedresources": { "SingularDisplayName": "Provisioning states" }
        ,"microsoft.computehub/provisioningstatesucceededresources": { "SingularDisplayName": "Provisioning states" }
        ,"microsoft.computehub/windowsostype": { "SingularDisplayName": "Windows OS" }
        ,"microsoft.computeschedule/autoactions": { "SingularDisplayName": "Microsoft.ComputeSchedule auto action" }
        ,"microsoft.computeschedule/autoactions/occurrences": { "SingularDisplayName": "Microsoft.ComputeSchedule auto actions occurrence" }
        ,"microsoft.confidentialledger/ledgers": { "SingularDisplayName": "Confidential Ledger" }
        ,"microsoft.confidentialledger/managedccfs": { "SingularDisplayName": "Managed CCF App" }
        ,"microsoft.confluent/agreements": { "SingularDisplayName": "Microsoft.Confluent agreement" }
        ,"microsoft.confluent/organizations": { "SingularDisplayName": "Confluent organization" }
        ,"microsoft.connectedcache/cachenodes": { "SingularDisplayName": "Connected Cache for ISP (early preview)" }
        ,"microsoft.connectedcache/enterprisecustomers": { "SingularDisplayName": "Connected Cache for Enterprise & Education (early preview)" }
        ,"microsoft.connectedcache/enterprisemcccustomers": { "SingularDisplayName": "Connected Cache for Enterprise & Education" }
        ,"microsoft.connectedcache/enterprisemcccustomers/enterprisemcccachenodes": { "SingularDisplayName": "MCC CacheNode for Enterprise" }
        ,"microsoft.connectedcache/ispcustomers": { "SingularDisplayName": "Connected Cache for ISP" }
        ,"microsoft.connectedcredentials/credentials": { "SingularDisplayName": "Microsoft.ConnectedCredentials credential" }
        ,"microsoft.connectedvehicle/platformaccounts": { "SingularDisplayName": "Microsoft.ConnectedVehicle platform account" }
        ,"microsoft.connectedvmwarevsphere/clusters": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere cluster" }
        ,"microsoft.connectedvmwarevsphere/datastores": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere datastore" }
        ,"microsoft.connectedvmwarevsphere/hosts": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere host" }
        ,"microsoft.connectedvmwarevsphere/resourcepools": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere resource pool" }
        ,"microsoft.connectedvmwarevsphere/vcenters": { "SingularDisplayName": "VMware vCenter" }
        ,"microsoft.connectedvmwarevsphere/virtualmachineinstances": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere virtual machine instance" }
        ,"microsoft.connectedvmwarevsphere/virtualmachineinstances/guestagents": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere virtual machine instances guest agent" }
        ,"microsoft.connectedvmwarevsphere/virtualmachineinstances/hybrididentitymetadata": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere virtual machine instances hybrid identity metadata" }
        ,"microsoft.connectedvmwarevsphere/virtualmachines": { "SingularDisplayName": "VMware + AVS virtual machine" }
        ,"microsoft.connectedvmwarevsphere/virtualmachines/providers/guestconfigurationassignments": { "SingularDisplayName": "Guest Assignment" }
        ,"microsoft.connectedvmwarevsphere/virtualmachinetemplates": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere virtual machine template" }
        ,"microsoft.connectedvmwarevsphere/virtualnetworks": { "SingularDisplayName": "Microsoft.ConnectedVMwarevSphere virtual network" }
        ,"microsoft.consumption/budgets": { "SingularDisplayName": "Microsoft.Consumption budget" }
        ,"microsoft.consumption/credits": { "SingularDisplayName": "Microsoft.Consumption credit" }
        ,"microsoft.consumption/pricesheets": { "SingularDisplayName": "Microsoft.Consumption pricesheet" }
        ,"microsoft.containerinstance/containergroupprofiles": { "SingularDisplayName": "Microsoft.ContainerInstance container group profile" }
        ,"microsoft.containerinstance/containergroupprofiles/revisions": { "SingularDisplayName": "Microsoft.ContainerInstance container group profiles revision" }
        ,"microsoft.containerinstance/containergroups": { "SingularDisplayName": "Container instances" }
        ,"microsoft.containerinstance/ngroups": { "SingularDisplayName": "Microsoft.ContainerInstance ngroup" }
        ,"microsoft.containerregistry/registries": { "SingularDisplayName": "Container registry" }
        ,"microsoft.containerregistry/registries/replications": { "SingularDisplayName": "Container registry replication" }
        ,"microsoft.containerregistry/registries/scopemaps": { "SingularDisplayName": "Container registry scope map" }
        ,"microsoft.containerregistry/registries/tokens": { "SingularDisplayName": "Container registry token" }
        ,"microsoft.containerregistry/registries/webhooks": { "SingularDisplayName": "Container registry webhook" }
        ,"microsoft.containerservice/fleets": { "SingularDisplayName": "Kubernetes fleet manager" }
        ,"microsoft.containerservice/managedclusters": { "SingularDisplayName": "Kubernetes service" }
        ,"microsoft.containerservice/managedclusters/microsoft.kubernetesconfiguration/extensions": { "SingularDisplayName": "Kubernetes service extension" }
        ,"microsoft.containerservice/managedclusters/microsoft.kubernetesconfiguration/fluxconfigurations": { "SingularDisplayName": "GitOps configuration" }
        ,"microsoft.containerservice/managedclusters/microsoft.kubernetesconfiguration/namespaces": { "SingularDisplayName": "Kubernetes namespace" }
        ,"microsoft.containerservice/managedclustersnapshots": { "SingularDisplayName": "Microsoft.ContainerService managedclustersnapshot" }
        ,"microsoft.containerservice/snapshots": { "SingularDisplayName": "Microsoft.ContainerService snapshot" }
        ,"microsoft.containerstorage/pools": { "SingularDisplayName": "Container storage" }
        ,"microsoft.costmanagement/alerts": { "SingularDisplayName": "Microsoft.CostManagement alert" }
        ,"microsoft.costmanagement/budgets": { "SingularDisplayName": "Microsoft.CostManagement budget" }
        ,"microsoft.costmanagement/cloudconnectors": { "SingularDisplayName": "Microsoft.CostManagement cloud connector" }
        ,"microsoft.costmanagement/connectors": { "SingularDisplayName": "Microsoft.CostManagement connector" }
        ,"microsoft.costmanagement/costallocationrules": { "SingularDisplayName": "Microsoft.CostManagement cost allocation rule" }
        ,"microsoft.costmanagement/costdetailsoperationresults": { "SingularDisplayName": "Microsoft.CostManagement cost details operation result" }
        ,"microsoft.costmanagement/exports": { "SingularDisplayName": "Microsoft.CostManagement export" }
        ,"microsoft.costmanagement/externalbillingaccounts": { "SingularDisplayName": "Microsoft.CostManagement external billing account" }
        ,"microsoft.costmanagement/externalsubscriptions": { "SingularDisplayName": "Microsoft.CostManagement external subscription" }
        ,"microsoft.costmanagement/markuprules": { "SingularDisplayName": "Microsoft.CostManagement markup rule" }
        ,"microsoft.costmanagement/operationstatus": { "SingularDisplayName": "Microsoft.CostManagement operation statu" }
        ,"microsoft.costmanagement/reportconfigs": { "SingularDisplayName": "Microsoft.CostManagement reportconfig" }
        ,"microsoft.costmanagement/reports": { "SingularDisplayName": "Microsoft.CostManagement report" }
        ,"microsoft.costmanagement/scheduledactions": { "SingularDisplayName": "Microsoft.CostManagement scheduled action" }
        ,"microsoft.costmanagement/settings": { "SingularDisplayName": "Microsoft.CostManagement setting" }
        ,"microsoft.costmanagement/views": { "SingularDisplayName": "Microsoft.CostManagement view" }
        ,"microsoft.customerlockbox/requests": { "SingularDisplayName": "Microsoft.CustomerLockbox request" }
        ,"microsoft.customerlockbox/tenantoptedin": { "SingularDisplayName": "Microsoft.CustomerLockbox tenant opted in" }
        ,"microsoft.customproviders/associations": { "SingularDisplayName": "Microsoft.CustomProviders association" }
        ,"microsoft.customproviders/resourceproviders": { "SingularDisplayName": "Microsoft.CustomProviders resource provider" }
        ,"microsoft.dashboard/grafana": { "SingularDisplayName": "Azure Managed Grafana" }
        ,"microsoft.dataaccelerator/indexclusters": { "SingularDisplayName": "Microsoft.DataAccelerator index cluster" }
        ,"microsoft.databasefleetmanager/fleets": { "SingularDisplayName": "Database fleet manager" }
        ,"microsoft.databasefleetmanager/fleets/fleetspaces": { "SingularDisplayName": "Fleetspaces" }
        ,"microsoft.databasefleetmanager/fleets/fleetspaces/databases": { "SingularDisplayName": "Fleet Managed Database" }
        ,"microsoft.databasefleetmanager/fleets/tiers": { "SingularDisplayName": "tier" }
        ,"microsoft.databasewatcher/watchers": { "SingularDisplayName": "Database watcher" }
        ,"microsoft.databox/jobs": { "SingularDisplayName": "Azure Data Box" }
        ,"microsoft.databoxedge/databoxedgedevices": { "SingularDisplayName": "Azure Stack Edge / Data Box Gateway" }
        ,"microsoft.databricks/accessconnectors": { "SingularDisplayName": "Access Connector for Azure Databricks" }
        ,"microsoft.databricks/workspaces": { "SingularDisplayName": "Azure Databricks Service" }
        ,"microsoft.datacatalog/catalogs": { "SingularDisplayName": "Data Catalog" }
        ,"microsoft.datacollaboration/workspaces": { "SingularDisplayName": "Project CI" }
        ,"microsoft.datadog/agreements": { "SingularDisplayName": "Microsoft.Datadog agreement" }
        ,"microsoft.datadog/monitors": { "SingularDisplayName": "Datadog" }
        ,"microsoft.datadog/subscriptionstatuses": { "SingularDisplayName": "Microsoft.Datadog subscription statuse" }
        ,"microsoft.datafactory/datafactories": { "SingularDisplayName": "Data factory" }
        ,"microsoft.datafactory/factories": { "SingularDisplayName": "Data factory (V2)" }
        ,"microsoft.datafactory/factories/pipelines": { "SingularDisplayName": "Data Factory pipeline" }
        ,"microsoft.datafactory/factories/triggers": { "SingularDisplayName": "Data Factory trigger" }
        ,"microsoft.datalakeanalytics/accounts": { "SingularDisplayName": "Data Lake Analytics account" }
        ,"microsoft.datalakestore/accounts": { "SingularDisplayName": "Data Lake Storage Gen1" }
        ,"microsoft.datamigration/databasemigrations": { "SingularDisplayName": "Microsoft.DataMigration database migration" }
        ,"microsoft.datamigration/migrationservices": { "SingularDisplayName": "Microsoft.DataMigration migration service" }
        ,"microsoft.datamigration/services": { "SingularDisplayName": "Azure Database Migration Service (classic)" }
        ,"microsoft.datamigration/services/projects": { "SingularDisplayName": "Azure Database Migration Project" }
        ,"microsoft.datamigration/sqlmigrationservices": { "SingularDisplayName": "Azure Database Migration Service" }
        ,"microsoft.dataprotection/backupvaults": { "SingularDisplayName": "Backup vault" }
        ,"microsoft.dataprotection/resourceguards": { "SingularDisplayName": "Resource Guard" }
        ,"microsoft.datareplication/replicationfabrics": { "SingularDisplayName": "Microsoft.DataReplication replication fabric" }
        ,"microsoft.datareplication/replicationfabrics/fabricagents": { "SingularDisplayName": "Microsoft.DataReplication replication fabrics fabric agent" }
        ,"microsoft.datareplication/replicationfabrics/fabricagents/operations": { "SingularDisplayName": "Microsoft.DataReplication replication fabrics fabric agents operation" }
        ,"microsoft.datareplication/replicationfabrics/operations": { "SingularDisplayName": "Microsoft.DataReplication replication fabrics operation" }
        ,"microsoft.datareplication/replicationvaults": { "SingularDisplayName": "Microsoft.DataReplication replication vault" }
        ,"microsoft.datareplication/replicationvaults/alertsettings": { "SingularDisplayName": "Microsoft.DataReplication replication vaults alert setting" }
        ,"microsoft.datareplication/replicationvaults/events": { "SingularDisplayName": "Microsoft.DataReplication replication vaults event" }
        ,"microsoft.datareplication/replicationvaults/jobs": { "SingularDisplayName": "Microsoft.DataReplication replication vaults job" }
        ,"microsoft.datareplication/replicationvaults/jobs/operations": { "SingularDisplayName": "Microsoft.DataReplication replication vaults jobs operation" }
        ,"microsoft.datareplication/replicationvaults/operations": { "SingularDisplayName": "Microsoft.DataReplication replication vaults operation" }
        ,"microsoft.datareplication/replicationvaults/protecteditems": { "SingularDisplayName": "Microsoft.DataReplication replication vaults protected item" }
        ,"microsoft.datareplication/replicationvaults/protecteditems/operations": { "SingularDisplayName": "Microsoft.DataReplication replication vaults protected items operation" }
        ,"microsoft.datareplication/replicationvaults/protecteditems/recoverypoints": { "SingularDisplayName": "Microsoft.DataReplication replication vaults protected items recovery point" }
        ,"microsoft.datareplication/replicationvaults/replicationextensions": { "SingularDisplayName": "Microsoft.DataReplication replication vaults replication extension" }
        ,"microsoft.datareplication/replicationvaults/replicationextensions/operations": { "SingularDisplayName": "Microsoft.DataReplication replication vaults replication extensions operation" }
        ,"microsoft.datareplication/replicationvaults/replicationpolicies": { "SingularDisplayName": "Microsoft.DataReplication replication vaults replication policy" }
        ,"microsoft.datareplication/replicationvaults/replicationpolicies/operations": { "SingularDisplayName": "Microsoft.DataReplication replication vaults replication policies operation" }
        ,"microsoft.datashare/accounts": { "SingularDisplayName": "Data Share" }
        ,"microsoft.dbformariadb/servers": { "SingularDisplayName": "Azure Database for MariaDB server" }
        ,"microsoft.dbformysql/flexibleservers": { "SingularDisplayName": "Azure Database for MySQL flexible server" }
        ,"microsoft.dbformysql/servers": { "SingularDisplayName": "MySQL server" }
        ,"microsoft.dbforpostgresql/flexibleservers": { "SingularDisplayName": "Azure Database for PostgreSQL - Flexible Server" }
        ,"microsoft.dbforpostgresql/servergroupsv2": { "SingularDisplayName": "Azure Cosmos DB for PostgreSQL Cluster" }
        ,"microsoft.dbforpostgresql/servers": { "SingularDisplayName": "PostgreSQL server" }
        ,"microsoft.delegateSingularDisplayNameetwork/controller": { "SingularDisplayName": "Microsoft.DelegateSingularDisplayNameetwork controller" }
        ,"microsoft.delegateSingularDisplayNameetwork/delegatedsubnets": { "SingularDisplayName": "Microsoft.DelegateSingularDisplayNameetwork delegated subnet" }
        ,"microsoft.delegateSingularDisplayNameetwork/orchestrators": { "SingularDisplayName": "Microsoft.DelegateSingularDisplayNameetwork orchestrator" }
        ,"microsoft.dependencymap/maps": { "SingularDisplayName": "Microsoft.DependencyMap map" }
        ,"microsoft.dependencymap/maps/discoverysources": { "SingularDisplayName": "Microsoft.DependencyMap maps discovery source" }
        ,"microsoft.deploymentmanager/artifactsources": { "SingularDisplayName": "Microsoft.DeploymentManager artifact source" }
        ,"microsoft.deploymentmanager/rollouts": { "SingularDisplayName": "Rollout" }
        ,"microsoft.deploymentmanager/servicetopologies": { "SingularDisplayName": "Microsoft.DeploymentManager service topology" }
        ,"microsoft.deploymentmanager/servicetopologies/services": { "SingularDisplayName": "Microsoft.DeploymentManager service topologies service" }
        ,"microsoft.deploymentmanager/servicetopologies/services/serviceunits": { "SingularDisplayName": "Microsoft.DeploymentManager service topologies services service unit" }
        ,"microsoft.deploymentmanager/steps": { "SingularDisplayName": "Microsoft.DeploymentManager step" }
        ,"microsoft.desktopvirtualization/appattachpackages": { "SingularDisplayName": "App attach package" }
        ,"microsoft.desktopvirtualization/applicationgroups": { "SingularDisplayName": "Application group" }
        ,"microsoft.desktopvirtualization/hostpools": { "SingularDisplayName": "Host pool" }
        ,"microsoft.desktopvirtualization/scalingplans": { "SingularDisplayName": "Scaling plan" }
        ,"microsoft.desktopvirtualization/workspaces": { "SingularDisplayName": "Workspace" }
        ,"microsoft.devai/instances": { "SingularDisplayName": "Microsoft.DevAI instance" }
        ,"microsoft.devai/instances/experiments": { "SingularDisplayName": "Microsoft.DevAI instances experiment" }
        ,"microsoft.devai/instances/sandboxes": { "SingularDisplayName": "Microsoft.DevAI instances sandbox" }
        ,"microsoft.devai/instances/sandboxes/experiments": { "SingularDisplayName": "Microsoft.DevAI instances sandboxes experiment" }
        ,"microsoft.devcenter/devcenters": { "SingularDisplayName": "Dev center" }
        ,"microsoft.devcenter/devcenters/devboxdefinitions": { "SingularDisplayName": "Dev Box definition" }
        ,"microsoft.devcenter/networkconnections": { "SingularDisplayName": "Network connection" }
        ,"microsoft.devcenter/plans": { "SingularDisplayName": "Dev center plan" }
        ,"microsoft.devcenter/projects": { "SingularDisplayName": "Project" }
        ,"microsoft.devcenter/projects/pools": { "SingularDisplayName": "Pool" }
        ,"microsoft.developmentwindows365/developmentcloudpcdelegatedmsis": { "SingularDisplayName": "Microsoft.DevelopmentWindows365 development cloud pc delegated msi" }
        ,"microsoft.devhub/iacprofiles": { "SingularDisplayName": "Infrastructure as Code Automation" }
        ,"microsoft.devhub/workflows": { "SingularDisplayName": "Microsoft.DevHub workflow" }
        ,"microsoft.deviceonboarding/onboardingservices": { "SingularDisplayName": "Microsoft.DeviceOnboarding onboarding service" }
        ,"microsoft.deviceonboarding/onboardingservices/policies": { "SingularDisplayName": "Microsoft.DeviceOnboarding onboarding services policy" }
        ,"microsoft.deviceregistry/assetendpointprofiles": { "SingularDisplayName": "Microsoft.DeviceRegistry asset endpoint profile" }
        ,"microsoft.deviceregistry/assets": { "SingularDisplayName": "IoT Asset" }
        ,"microsoft.deviceregistry/billingcontainers": { "SingularDisplayName": "Microsoft.DeviceRegistry billing container" }
        ,"microsoft.deviceregistry/devices": { "SingularDisplayName": "IoT Device" }
        ,"microsoft.deviceregistry/discoveredassetendpointprofiles": { "SingularDisplayName": "Microsoft.DeviceRegistry discovered asset endpoint profile" }
        ,"microsoft.deviceregistry/discoveredassets": { "SingularDisplayName": "Microsoft.DeviceRegistry discovered asset" }
        ,"microsoft.deviceregistry/schemaregistries": { "SingularDisplayName": "Microsoft.DeviceRegistry schema registry" }
        ,"microsoft.deviceregistry/schemaregistries/schemas": { "SingularDisplayName": "Microsoft.DeviceRegistry schema registries schema" }
        ,"microsoft.deviceregistry/schemaregistries/schemas/schemaversions": { "SingularDisplayName": "Microsoft.DeviceRegistry schema registries schemas schema version" }
        ,"microsoft.devices/iothubs": { "SingularDisplayName": "IoT hub" }
        ,"microsoft.devices/provisioningservices": { "SingularDisplayName": "Azure IoT Hub Device Provisioning Service (DPS)" }
        ,"microsoft.deviceupdate/accounts": { "SingularDisplayName": "Device Update for IoT Hub" }
        ,"microsoft.deviceupdate/updateaccounts": { "SingularDisplayName": "Device Update Account" }
        ,"microsoft.deviceupdate/updateaccounts/activedeployments": { "SingularDisplayName": "Device Update Active Deployment" }
        ,"microsoft.deviceupdate/updateaccounts/agents": { "SingularDisplayName": "Device Update Agent" }
        ,"microsoft.deviceupdate/updateaccounts/deployments": { "SingularDisplayName": "Device Update Deployment" }
        ,"microsoft.deviceupdate/updateaccounts/deviceclasses": { "SingularDisplayName": "Device Update Device Class" }
        ,"microsoft.deviceupdate/updateaccounts/updates": { "SingularDisplayName": "Device Update" }
        ,"microsoft.devops/pipelines": { "SingularDisplayName": "Microsoft.DevOps pipeline" }
        ,"microsoft.devopsinfrastructure/pools": { "SingularDisplayName": "Managed DevOps Pool" }
        ,"microsoft.devspaces/controllers": { "SingularDisplayName": "Microsoft.DevSpaces controller" }
        ,"microsoft.devtestlab/labs": { "SingularDisplayName": "DevTest lab" }
        ,"microsoft.devtestlab/labs/virtualmachines": { "SingularDisplayName": "DevTest Lab virtual machine" }
        ,"microsoft.devtestlab/schedules": { "SingularDisplayName": "Microsoft.DevTestLab schedule" }
        ,"microsoft.devtunnels/tunnelplans": { "SingularDisplayName": "Dev Tunnels Domain" }
        ,"microsoft.diagnostics/apollo": { "SingularDisplayName": "Microsoft.Diagnostics apollo" }
        ,"microsoft.digitaltwins/digitaltwinsinstances": { "SingularDisplayName": "Azure Digital Twins" }
        ,"microsoft.documentdb/cassandraclusters": { "SingularDisplayName": "Azure Managed Instance for Apache Cassandra" }
        ,"microsoft.documentdb/databaseaccounts": { "SingularDisplayName": "Cosmos DB account" }
        ,"microsoft.documentdb/mongoclusters": { "SingularDisplayName": "Azure Cosmos DB for MongoDB (vCore)" }
        ,"microsoft.documentdb/throughputpools": { "SingularDisplayName": "Microsoft.DocumentDB throughput pool" }
        ,"microsoft.documentdb/throughputpools/throughputpoolaccounts": { "SingularDisplayName": "Microsoft.DocumentDB throughput pools throughput pool account" }
        ,"microsoft.domainregistration/domains": { "SingularDisplayName": "App Service Domain" }
        ,"microsoft.domainregistration/topleveldomains": { "SingularDisplayName": "Microsoft.DomainRegistration top level domain" }
        ,"microsoft.durabletask/namespaces": { "SingularDisplayName": "Durable Task Scheduler" }
        ,"microsoft.durabletask/namespaces/taskhubs": { "SingularDisplayName": "Task Hub" }
        ,"microsoft.dynamics365fraudprotection/instances": { "SingularDisplayName": "Microsoft.Dynamics365FraudProtection instance" }
        ,"microsoft.elastic/monitors": { "SingularDisplayName": "Elastic" }
        ,"microsoft.elasticsan/elasticsans": { "SingularDisplayName": "Elastic SAN" }
        ,"microsoft.energydataplatform/energyservices": { "SingularDisplayName": "Microsoft.EnergyDataPlatform energy service" }
        ,"microsoft.enterpriseknowledgegraph/services": { "SingularDisplayName": "Microsoft.EnterpriseKnowledgeGraph service" }
        ,"microsoft.enterprisesupport/enterprisesupports": { "SingularDisplayName": "Microsoft.EnterpriseSupport enterprise support" }
        ,"microsoft.eventgrid/domains": { "SingularDisplayName": "Event Grid Domain" }
        ,"microsoft.eventgrid/domains/topics": { "SingularDisplayName": "Event Grid Domain Topic" }
        ,"microsoft.eventgrid/eventsubscriptions": { "SingularDisplayName": "Microsoft.EventGrid event subscription" }
        ,"microsoft.eventgrid/extensiontopics": { "SingularDisplayName": "Event Grid extension topic" }
        ,"microsoft.eventgrid/namespaces": { "SingularDisplayName": "Event Grid Namespace" }
        ,"microsoft.eventgrid/namespaces/topics": { "SingularDisplayName": "Event Grid Namespace Topic" }
        ,"microsoft.eventgrid/namespaces/topics/eventsubscriptions": { "SingularDisplayName": "Event Subscription" }
        ,"microsoft.eventgrid/namespaces/topicspaces": { "SingularDisplayName": "Event Grid Topic Space" }
        ,"microsoft.eventgrid/partnerconfigurations": { "SingularDisplayName": "Event Grid Partner Configuration" }
        ,"microsoft.eventgrid/partnerdestinations": { "SingularDisplayName": "Event Grid Partner Destination" }
        ,"microsoft.eventgrid/partnernamespaces": { "SingularDisplayName": "Event Grid Partner Namespace" }
        ,"microsoft.eventgrid/partnernamespaces/channels": { "SingularDisplayName": "Event Grid Channel" }
        ,"microsoft.eventgrid/partnerregistrations": { "SingularDisplayName": "Event Grid Partner Registration" }
        ,"microsoft.eventgrid/partnertopics": { "SingularDisplayName": "Event Grid Partner Topic" }
        ,"microsoft.eventgrid/systemtopics": { "SingularDisplayName": "Event Grid System Topic" }
        ,"microsoft.eventgrid/systemtopics/eventsubscriptions": { "SingularDisplayName": "Event Grid Subscriptions" }
        ,"microsoft.eventgrid/topics": { "SingularDisplayName": "Event Grid Topic" }
        ,"microsoft.eventgrid/topictypes": { "SingularDisplayName": "Microsoft.EventGrid topic type" }
        ,"microsoft.eventgrid/verifiedpartners": { "SingularDisplayName": "Microsoft.EventGrid verified partner" }
        ,"microsoft.eventhub/clusters": { "SingularDisplayName": "Event Hubs Cluster" }
        ,"microsoft.eventhub/namespaces": { "SingularDisplayName": "Event Hubs namespace" }
        ,"microsoft.eventhub/namespaces/disasterrecoveryconfigs": { "SingularDisplayName": "Event Hubs Geo-DR Alias" }
        ,"microsoft.eventhub/namespaces/eventhubs": { "SingularDisplayName": "Event Hubs Instance" }
        ,"microsoft.eventhub/namespaces/providers/diagnosticsettings": { "SingularDisplayName": "Diagnostic settings" }
        ,"microsoft.eventhub/namespaces/schemagroups": { "SingularDisplayName": "Schema Group" }
        ,"microsoft.experimentation/experimentworkspaces": { "SingularDisplayName": "Experiment Workspace" }
        ,"microsoft.extendedlocation/customlocations": { "SingularDisplayName": "Custom location" }
        ,"microsoft.fabric/capacities": { "SingularDisplayName": "Fabric Capacity" }
        ,"microsoft.fabric/privatelinkservicesforfabric": { "SingularDisplayName": "Microsoft.Fabric private link services for fabric" }
        ,"microsoft.fabric/privatelinkservicesforfabric/operationresults": { "SingularDisplayName": "Microsoft.Fabric private link services for fabric operation result" }
        ,"microsoft.fabric/privatelinkservicesforfabric/privateendpointconnections": { "SingularDisplayName": "Microsoft.Fabric private link services for fabric private endpoint connection" }
        ,"microsoft.fabric/privatelinkservicesforfabric/privatelinkresources": { "SingularDisplayName": "Microsoft.Fabric private link services for fabric private link resource" }
        ,"microsoft.fairfieldgardens/deviceprovisioningstates": { "SingularDisplayName": "Microsoft.FairfieldGardens device provisioning state" }
        ,"microsoft.fairfieldgardens/provisioningresources": { "SingularDisplayName": "Fairfield Gardens" }
        ,"microsoft.fairfieldgardens/provisioningresources/provisioningpolicies": { "SingularDisplayName": "Provisioning policy" }
        ,"microsoft.falcon/namespaces": { "SingularDisplayName": "Microsoft.Falcon namespace" }
        ,"microsoft.features/featureprovidernamespaces/featureconfigurations": { "SingularDisplayName": "Preview features" }
        ,"microsoft.fileshares/fileshares": { "SingularDisplayName": "File share" }
        ,"microsoft.fluidrelay/fluidrelayservers": { "SingularDisplayName": "Fluid Relay" }
        ,"microsoft.footprintmonitoring/profiles": { "SingularDisplayName": "Microsoft.FootprintMonitoring profile" }
        ,"microsoft.footprintmonitoring/profiles/experiments": { "SingularDisplayName": "Microsoft.FootprintMonitoring profiles experiment" }
        ,"microsoft.footprintmonitoring/profiles/measurementendpoints": { "SingularDisplayName": "Microsoft.FootprintMonitoring profiles measurement endpoint" }
        ,"microsoft.footprintmonitoring/profiles/measurementendpoints/conditions": { "SingularDisplayName": "Microsoft.FootprintMonitoring profiles measurement endpoints condition" }
        ,"microsoft.gallery/myareas/galleryitems": { "SingularDisplayName": "Template" }
        ,"microsoft.genomics/accounts": { "SingularDisplayName": "Genomics account" }
        ,"microsoft.graph/azureadapplication": { "SingularDisplayName": "Microsoft.Graph Azure ad application" }
        ,"microsoft.graph/azureadapplicationprototype": { "SingularDisplayName": "Microsoft.Graph Azure ad application prototype" }
        ,"microsoft.graphservices/accounts": { "SingularDisplayName": "Metered API Account" }
        ,"microsoft.guestconfiguration/guestconfigurationassignments": { "SingularDisplayName": "Microsoft.GuestConfiguration guest configuration assignment" }
        ,"microsoft.guestconfiguration/guestconfigurationassignments/reports": { "SingularDisplayName": "Microsoft.GuestConfiguration guest configuration assignments report" }
        ,"microsoft.hanaonazure/hanainstances": { "SingularDisplayName": "SAP HANA on Azure" }
        ,"microsoft.hanaonazure/sapmonitors": { "SingularDisplayName": "Azure Monitor for SAP Solutions (classic)" }
        ,"microsoft.hardware/orders": { "SingularDisplayName": "Microsoft.Hardware order" }
        ,"microsoft.hardwaresecuritymodules/cloudhsmclusters": { "SingularDisplayName": "Azure Cloud HSM" }
        ,"microsoft.hdinsight/clusterpools": { "SingularDisplayName": "Azure HDInsight on AKS cluster pool" }
        ,"microsoft.hdinsight/clusterpools/clusters": { "SingularDisplayName": "Azure HDInsight on AKS cluster" }
        ,"microsoft.hdinsight/clusters": { "SingularDisplayName": "HDInsight cluster" }
        ,"microsoft.healthbot/healthbots": { "SingularDisplayName": "Healthcare agent service" }
        ,"microsoft.healthcareapis/services": { "SingularDisplayName": "Azure API for FHIR" }
        ,"microsoft.healthcareapis/workspaces": { "SingularDisplayName": "Health Data Services workspace" }
        ,"microsoft.healthcareapis/workspaces/dicomservices": { "SingularDisplayName": "DICOM service" }
        ,"microsoft.healthcareapis/workspaces/fhirservices": { "SingularDisplayName": "FHIR service" }
        ,"microsoft.healthcareapis/workspaces/iotconnectors": { "SingularDisplayName": "MedTech service" }
        ,"microsoft.healthdataaiservices/deidservices": { "SingularDisplayName": "De-identification Service" }
        ,"microsoft.healthmodel/healthmodels": { "SingularDisplayName": "Health Model" }
        ,"microsoft.help/diagnostics": { "SingularDisplayName": "Microsoft.Help diagnostic" }
        ,"microsoft.help/selfhelp": { "SingularDisplayName": "Microsoft.Help self help" }
        ,"microsoft.help/simplifiedsolutions": { "SingularDisplayName": "Microsoft.Help simplified solution" }
        ,"microsoft.help/solutions": { "SingularDisplayName": "Microsoft.Help solution" }
        ,"microsoft.help/troubleshooters": { "SingularDisplayName": "Microsoft.Help troubleshooter" }
        ,"microsoft.importexport/jobs": { "SingularDisplayName": "Microsoft.ImportExport job" }
        ,"microsoft.insights/actiongroups": { "SingularDisplayName": "Action group" }
        ,"microsoft.insights/activitylogalerts": { "SingularDisplayName": "Activity log alert rule" }
        ,"microsoft.insights/alertrules": { "SingularDisplayName": "Microsoft.Insights alertrule" }
        ,"microsoft.insights/alertrules/incidents": { "SingularDisplayName": "Microsoft.insights alertrules incident" }
        ,"microsoft.insights/autoscalesettings": { "SingularDisplayName": "Microsoft.Insights autoscalesetting" }
        ,"microsoft.insights/components": { "SingularDisplayName": "Application Insights app" }
        ,"microsoft.insights/datacollectionendpoints": { "SingularDisplayName": "Data collection endpoint" }
        ,"microsoft.insights/datacollectionruleassociations": { "SingularDisplayName": "Microsoft.Insights data collection rule association" }
        ,"microsoft.insights/datacollectionrules": { "SingularDisplayName": "Data collection rule" }
        ,"microsoft.insights/diagnosticsettings": { "SingularDisplayName": "Diagnostic settings" }
        ,"microsoft.insights/diagnosticsettingscategories": { "SingularDisplayName": "Microsoft.Insights diagnostic settings category" }
        ,"microsoft.insights/guestdiagnosticsettings": { "SingularDisplayName": "Microsoft.insights guest diagnostic setting" }
        ,"microsoft.insights/guestdiagnosticsettingsassociation": { "SingularDisplayName": "Microsoft.insights guest diagnostic settings association" }
        ,"microsoft.insights/logprofiles": { "SingularDisplayName": "Microsoft.Insights logprofile" }
        ,"microsoft.insights/metricalerts": { "SingularDisplayName": "Metric alert rule" }
        ,"microsoft.insights/notificationstatus": { "SingularDisplayName": "Microsoft.Insights notification statu" }
        ,"microsoft.insights/privatelinkscopeoperationstatuses": { "SingularDisplayName": "Microsoft.insights private link scope operation statuse" }
        ,"microsoft.insights/privatelinkscopes": { "SingularDisplayName": "Azure Monitor Private Link Scope" }
        ,"microsoft.insights/scheduledqueryrules": { "SingularDisplayName": "Log search alert rule" }
        ,"microsoft.insights/tenantactiongroups": { "SingularDisplayName": "Microsoft.Insights tenant action group" }
        ,"microsoft.insights/tenantactiongroups/notificationstatus": { "SingularDisplayName": "Microsoft.Insights tenant action groups notification statu" }
        ,"microsoft.insights/vminsightsonboardingstatuses": { "SingularDisplayName": "Microsoft.Insights VM insights onboarding statuse" }
        ,"microsoft.insights/webtests": { "SingularDisplayName": "Application Insights availability test" }
        ,"microsoft.insights/workbooks": { "SingularDisplayName": "Azure Workbook" }
        ,"microsoft.insights/workbooktemplates": { "SingularDisplayName": "Azure Workbook Template" }
        ,"microsoft.integrationspaces/spaces": { "SingularDisplayName": "Integration Environment" }
        ,"microsoft.intelligentitdigitaltwin/digitaltwins": { "SingularDisplayName": "Microsoft.IntelligentITDigitalTwin digital twin" }
        ,"microsoft.intelligentitdigitaltwin/digitaltwins/assets": { "SingularDisplayName": "Microsoft.IntelligentITDigitalTwin digital twins asset" }
        ,"microsoft.intelligentitdigitaltwin/digitaltwins/executionplans": { "SingularDisplayName": "Microsoft.IntelligentITDigitalTwin digital twins execution plan" }
        ,"microsoft.intelligentitdigitaltwin/digitaltwins/testplans": { "SingularDisplayName": "Microsoft.IntelligentITDigitalTwin digital twins test plan" }
        ,"microsoft.intelligentitdigitaltwin/digitaltwins/tests": { "SingularDisplayName": "Microsoft.IntelligentITDigitalTwin digital twins test" }
        ,"microsoft.inventory/subscriptioninternalproperties": { "SingularDisplayName": "Microsoft.Inventory subscription internal property" }
        ,"microsoft.keyvault/managedhsms": { "SingularDisplayName": "Azure Key Vault Managed HSM" }
        ,"microsoft.keyvault/vaults": { "SingularDisplayName": "Key vault" }
        ,"microsoft.kubernetes/connectedclusters": { "SingularDisplayName": "kubernetes 1 - Azure Arc" }
        ,"microsoft.kubernetes/connectedclusters/microsoft.kubernetesconfiguration/extensions": { "SingularDisplayName": "Kubernetes - Azure Arc extension" }
        ,"microsoft.kubernetes/connectedclusters/microsoft.kubernetesconfiguration/fluxconfigurations": { "SingularDisplayName": "GitOps configuration" }
        ,"microsoft.kubernetes/connectedclusters/microsoft.kubernetesconfiguration/namespaces": { "SingularDisplayName": "Kubernetes - Azure Arc namespace" }
        ,"microsoft.kubernetesconfiguration/extensions": { "SingularDisplayName": "Kubernetes service extension" }
        ,"microsoft.kubernetesconfiguration/extensiontypes": { "SingularDisplayName": "Microsoft.KubernetesConfiguration extension type" }
        ,"microsoft.kubernetesconfiguration/extensiontypes/versions": { "SingularDisplayName": "Microsoft.KubernetesConfiguration extension types version" }
        ,"microsoft.kubernetesconfiguration/fluxconfigurations": { "SingularDisplayName": "Microsoft.KubernetesConfiguration flux configuration" }
        ,"microsoft.kubernetesconfiguration/fluxconfigurations/operations": { "SingularDisplayName": "Microsoft.KubernetesConfiguration flux configurations operation" }
        ,"microsoft.kubernetesconfiguration/privatelinkscopes": { "SingularDisplayName": "Microsoft.KubernetesConfiguration private link scope" }
        ,"microsoft.kubernetesconfiguration/privatelinkscopes/privateendpointconnections": { "SingularDisplayName": "Microsoft.KubernetesConfiguration private link scopes private endpoint connection" }
        ,"microsoft.kubernetesconfiguration/privatelinkscopes/privatelinkresources": { "SingularDisplayName": "Microsoft.KubernetesConfiguration private link scopes private link resource" }
        ,"microsoft.kubernetesconfiguration/sourcecontrolconfigurations": { "SingularDisplayName": "Microsoft.KubernetesConfiguration source control configuration" }
        ,"microsoft.kubernetesruntime/bgppeers": { "SingularDisplayName": "Microsoft.KubernetesRuntime bgp peer" }
        ,"microsoft.kubernetesruntime/loadbalancers": { "SingularDisplayName": "Arc Load Balancer" }
        ,"microsoft.kubernetesruntime/services": { "SingularDisplayName": "Microsoft.KubernetesRuntime service" }
        ,"microsoft.kubernetesruntime/storageclasses": { "SingularDisplayName": "Microsoft.KubernetesRuntime storage class" }
        ,"microsoft.kusto/clusters": { "SingularDisplayName": "Azure Data Explorer Cluster" }
        ,"microsoft.kusto/clusters/databases": { "SingularDisplayName": "Azure Data Explorer Database" }
        ,"microsoft.logic/businessprocesses": { "SingularDisplayName": "Business Process" }
        ,"microsoft.logic/integrationaccounts": { "SingularDisplayName": "Logic app integration account" }
        ,"microsoft.logic/integrationserviceenvironments": { "SingularDisplayName": "Integration Service Environment" }
        ,"microsoft.logic/integrationserviceenvironments/managedapis": { "SingularDisplayName": "Managed Connector" }
        ,"microsoft.logic/workflows": { "SingularDisplayName": "Logic app" }
        ,"microsoft.logz/monitors": { "SingularDisplayName": "Logz.io" }
        ,"microsoft.logz/monitors/accounts": { "SingularDisplayName": "Logz sub account" }
        ,"microsoft.m365/m365resources": { "SingularDisplayName": "Microsoft.M365 m365 resource" }
        ,"microsoft.m365consumptionservices/services": { "SingularDisplayName": "Microsoft.M365ConsumptionServices service" }
        ,"microsoft.machinelearning/commitmentplans": { "SingularDisplayName": "Microsoft.MachineLearning commitment plan" }
        ,"microsoft.machinelearning/commitmentplans/commitmentassociations": { "SingularDisplayName": "Microsoft.MachineLearning commitment plans commitment association" }
        ,"microsoft.machinelearning/webservices": { "SingularDisplayName": "Microsoft.MachineLearning web service" }
        ,"microsoft.machinelearning/workspaces": { "SingularDisplayName": "Microsoft.MachineLearning workspace" }
        ,"microsoft.machinelearningexperimentation/accounts": { "SingularDisplayName": "Microsoft.MachineLearningExperimentation account" }
        ,"microsoft.machinelearningexperimentation/accounts/workspaces": { "SingularDisplayName": "Microsoft.MachineLearningExperimentation accounts workspace" }
        ,"microsoft.machinelearningexperimentation/accounts/workspaces/projects": { "SingularDisplayName": "Microsoft.MachineLearningExperimentation accounts workspaces project" }
        ,"microsoft.machinelearningservices/aistudio": { "SingularDisplayName": "Azure AI Studio" }
        ,"microsoft.machinelearningservices/registries": { "SingularDisplayName": "Azure Machine Learning registry" }
        ,"microsoft.machinelearningservices/workspaces": { "SingularDisplayName": "Azure Machine Learning workspace" }
        ,"microsoft.machinelearningservices/workspaces/onlineendpoints": { "SingularDisplayName": "Machine learning online endpoint" }
        ,"microsoft.machinelearningservices/workspaces/onlineendpoints/deployments": { "SingularDisplayName": "Machine learning online deployment" }
        ,"microsoft.maintenance/configurationassignments": { "SingularDisplayName": "Microsoft.Maintenance configuration assignment" }
        ,"microsoft.maintenance/maintenanceconfigurations": { "SingularDisplayName": "Maintenance Configuration" }
        ,"microsoft.maintenance/publicmaintenanceconfigurations": { "SingularDisplayName": "Microsoft.Maintenance public maintenance configuration" }
        ,"microsoft.managedidentity/identities": { "SingularDisplayName": "Microsoft.ManagedIdentity identity" }
        ,"microsoft.managedidentity/userassignedidentities": { "SingularDisplayName": "Managed Identity" }
        ,"microsoft.manageSingularDisplayNameetwork/manageSingularDisplayNameetworks": { "SingularDisplayName": "Microsoft.ManageSingularDisplayNameetwork managed network" }
        ,"microsoft.manageSingularDisplayNameetwork/manageSingularDisplayNameetworks/manageSingularDisplayNameetworkgroups": { "SingularDisplayName": "Microsoft.ManageSingularDisplayNameetwork managed networks managed network group" }
        ,"microsoft.manageSingularDisplayNameetwork/manageSingularDisplayNameetworks/manageSingularDisplayNameetworkpeeringpolicies": { "SingularDisplayName": "Microsoft.ManageSingularDisplayNameetwork managed networks managed network peering policy" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/accesscontrollists": { "SingularDisplayName": "Access Control List (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/internetgatewayrules": { "SingularDisplayName": "Internet Gateway Rule (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/internetgateways": { "SingularDisplayName": "Internet Gateway (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/ipcommunities": { "SingularDisplayName": "IP Community (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/ipextendedcommunities": { "SingularDisplayName": "IP Extended Community (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/ipprefixes": { "SingularDisplayName": "IP Prefix (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/l2isolationdomains": { "SingularDisplayName": "Layer 2 Isolation Domain (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/l3isolationdomains": { "SingularDisplayName": "Layer 3 Isolation Domain (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/l3isolationdomains/externalnetworks": { "SingularDisplayName": "External Network (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/l3isolationdomains/internalnetworks": { "SingularDisplayName": "Internal Network (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/neighborgroups": { "SingularDisplayName": "Neighbor Group (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkdevices": { "SingularDisplayName": "Network Device (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkdevices/networkinterfaces": { "SingularDisplayName": "Network Interface (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkfabriccontrollers": { "SingularDisplayName": "Network Fabric Controller (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkfabrics": { "SingularDisplayName": "Network Fabric (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkfabrics/networktonetworkinterconnects": { "SingularDisplayName": "Network to Network Interconnect (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkfabricskus": { "SingularDisplayName": "Network Fabric SKU (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkpacketbrokers": { "SingularDisplayName": "Network Packet Broker (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networkracks": { "SingularDisplayName": "Network Rack (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networktaprules": { "SingularDisplayName": "Network Tap Rule (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/networktaps": { "SingularDisplayName": "Network Tap (Operator Nexus)" }
        ,"microsoft.manageSingularDisplayNameetworkfabric/routepolicies": { "SingularDisplayName": "Route Policy (Operator Nexus)" }
        ,"microsoft.managedservices/marketplaceregistrationdefinitions": { "SingularDisplayName": "Microsoft.ManagedServices marketplace registration definition" }
        ,"microsoft.managedservices/registrationassignments": { "SingularDisplayName": "Microsoft.ManagedServices registration assignment" }
        ,"microsoft.managedservices/registrationdefinitions": { "SingularDisplayName": "Azure Lighthouse" }
        ,"microsoft.management/managementgroups": { "SingularDisplayName": "Microsoft.Management management group" }
        ,"microsoft.management/managementgroups/microsoft.resources/deploymentstacks": { "SingularDisplayName": "Deployment stack" }
        ,"microsoft.management/managementgroups/providers/privatelinkassociations": { "SingularDisplayName": "Application Gateway" }
        ,"microsoft.management/managementgroups/providers/templatespecs": { "SingularDisplayName": "Template spec" }
        ,"microsoft.management/managementgroups/settings": { "SingularDisplayName": "Microsoft.Management management groups setting" }
        ,"microsoft.management/managementgroups/subscriptions": { "SingularDisplayName": "Microsoft.Management management groups subscription" }
        ,"microsoft.managementpartner/partners": { "SingularDisplayName": "Microsoft.ManagementPartner partner" }
        ,"microsoft.manufacturingplatform/manufacturingdataservices": { "SingularDisplayName": "Manufacturing Data Solutions" }
        ,"microsoft.maps/accounts": { "SingularDisplayName": "Azure Maps Account" }
        ,"microsoft.maps/accounts/creators": { "SingularDisplayName": "Azure Maps Creator Resource" }
        ,"microsoft.marketplace/privatestores": { "SingularDisplayName": "Microsoft.Marketplace private store" }
        ,"microsoft.marketplace/privatestores/adminrequestapprovals": { "SingularDisplayName": "Microsoft.Marketplace private stores admin request approval" }
        ,"microsoft.marketplace/privatestores/collections": { "SingularDisplayName": "Microsoft.Marketplace private stores collection" }
        ,"microsoft.marketplace/privatestores/collections/offers": { "SingularDisplayName": "Microsoft.Marketplace private stores collections offer" }
        ,"microsoft.marketplace/privatestores/offers": { "SingularDisplayName": "Microsoft.Marketplace private stores offer" }
        ,"microsoft.marketplace/privatestores/requestapprovals": { "SingularDisplayName": "Microsoft.Marketplace private stores request approval" }
        ,"microsoft.media/mediaservices": { "SingularDisplayName": "Media service" }
        ,"microsoft.media/mediaservices/liveevents": { "SingularDisplayName": "Live event" }
        ,"microsoft.media/mediaservices/streamingendpoints": { "SingularDisplayName": "Streaming Endpoint" }
        ,"microsoft.mission/catalogs": { "SingularDisplayName": "Catalog" }
        ,"microsoft.mission/communities": { "SingularDisplayName": "Community" }
        ,"microsoft.mission/communities/communityendpoints": { "SingularDisplayName": "Community endpoint" }
        ,"microsoft.mission/communities/transithubs": { "SingularDisplayName": "Transit hub" }
        ,"microsoft.mission/enclaveconnections": { "SingularDisplayName": "Enclave connection" }
        ,"microsoft.mission/externalconnections": { "SingularDisplayName": "Microsoft.Mission external connection" }
        ,"microsoft.mission/internalconnections": { "SingularDisplayName": "Microsoft.Mission internal connection" }
        ,"microsoft.mission/virtualenclaves": { "SingularDisplayName": "Enclave" }
        ,"microsoft.mission/virtualenclaves/enclaveendpoints": { "SingularDisplayName": "Enclave endpoint" }
        ,"microsoft.mission/virtualenclaves/endpoints": { "SingularDisplayName": "Endpoint" }
        ,"microsoft.mission/virtualenclaves/workloads": { "SingularDisplayName": "Workload" }
        ,"microsoft.monitor/accounts": { "SingularDisplayName": "Azure Monitor workspace" }
        ,"microsoft.monitor/investigations": { "SingularDisplayName": "Microsoft.Monitor investigation" }
        ,"microsoft.monitor/pipelinegroups": { "SingularDisplayName": "Azure Monitor pipeline" }
        ,"microsoft.mysqldiscovery/mysqlsites": { "SingularDisplayName": "Microsoft.MySQLDiscovery my sqlsite" }
        ,"microsoft.mysqldiscovery/mysqlsites/errorsummaries": { "SingularDisplayName": "Microsoft.MySQLDiscovery my sqlsites error summary" }
        ,"microsoft.mysqldiscovery/mysqlsites/mysqlservers": { "SingularDisplayName": "Microsoft.MySQLDiscovery my sqlsites my sqlserver" }
        ,"microsoft.mysqldiscovery/mysqlsites/summaries": { "SingularDisplayName": "Microsoft.MySQLDiscovery my sqlsites summary" }
        ,"microsoft.netapp/netappaccounts": { "SingularDisplayName": "NetApp account" }
        ,"microsoft.netapp/netappaccounts/backupvaults": { "SingularDisplayName": "Backup vault" }
        ,"microsoft.netapp/netappaccounts/capacitypools": { "SingularDisplayName": "Capacity pool" }
        ,"microsoft.netapp/netappaccounts/capacitypools/volumes": { "SingularDisplayName": "Volume" }
        ,"microsoft.netapp/netappaccounts/capacitypools/volumes/snapshots": { "SingularDisplayName": "Snapshot" }
        ,"microsoft.netapp/netappaccounts/capacitypools/volumes/volumequotarules": { "SingularDisplayName": "User and group quota" }
        ,"microsoft.netapp/netappaccounts/snapshotpolicies": { "SingularDisplayName": "Snapshot policy" }
        ,"microsoft.netapp/netappaccounts/volumegroups": { "SingularDisplayName": "VolumeGroup" }
        ,"microsoft.network/applicationgatewayavailablessloptions": { "SingularDisplayName": "Microsoft.Network application gateway available ssl option" }
        ,"microsoft.network/applicationgatewayavailablessloptions/predefinedpolicies": { "SingularDisplayName": "Microsoft.Network application gateway available ssl options predefined policy" }
        ,"microsoft.network/applicationgateways": { "SingularDisplayName": "Application gateway" }
        ,"microsoft.network/applicationgatewaywebapplicationfirewallpolicies": { "SingularDisplayName": "Application Gateway WAF policy" }
        ,"microsoft.network/applicationsecuritygroups": { "SingularDisplayName": "Application security group" }
        ,"microsoft.network/azurefirewalls": { "SingularDisplayName": "Firewall" }
        ,"microsoft.network/azurewebcategories": { "SingularDisplayName": "Microsoft.Network Azure web category" }
        ,"microsoft.network/bastionhosts": { "SingularDisplayName": "Bastion" }
        ,"microsoft.network/cloudserviceslots": { "SingularDisplayName": "Microsoft.Network cloud service slot" }
        ,"microsoft.network/connections": { "SingularDisplayName": "Connection" }
        ,"microsoft.network/customipprefixes": { "SingularDisplayName": "Custom IP Prefix" }
        ,"microsoft.network/ddoscustompolicies": { "SingularDisplayName": "Microsoft.Network DDoS custom policy" }
        ,"microsoft.network/ddosprotectionplans": { "SingularDisplayName": "DDoS protection plan" }
        ,"microsoft.network/SingularDisplayNamesforwardingrulesets": { "SingularDisplayName": "SingularDisplayNameS forwarding ruleset" }
        ,"microsoft.network/SingularDisplayNamesresolverdomainlists": { "SingularDisplayName": "SingularDisplayNameS Domain List" }
        ,"microsoft.network/SingularDisplayNamesresolverpolicies": { "SingularDisplayName": "SingularDisplayNameS Security Policy" }
        ,"microsoft.network/SingularDisplayNamesresolvers": { "SingularDisplayName": "SingularDisplayNameS private resolver" }
        ,"microsoft.network/SingularDisplayNameszones": { "SingularDisplayName": "SingularDisplayNameS zone" }
        ,"microsoft.network/dscpconfigurations": { "SingularDisplayName": "Microsoft.Network DSCP configuration" }
        ,"microsoft.network/expressroutecircuits": { "SingularDisplayName": "ExpressRoute circuit" }
        ,"microsoft.network/expressroutecrossconnections": { "SingularDisplayName": "Microsoft.Network express route cross connection" }
        ,"microsoft.network/expressroutecrossconnections/peerings": { "SingularDisplayName": "Microsoft.Network express route cross connections peering" }
        ,"microsoft.network/expressroutegateways": { "SingularDisplayName": "ExpressRoute Gateway" }
        ,"microsoft.network/expressroutegateways/expressrouteconnections": { "SingularDisplayName": "Microsoft.Network express route gateways express route connection" }
        ,"microsoft.network/expressrouteports": { "SingularDisplayName": "ExpressRoute Direct" }
        ,"microsoft.network/expressrouteportslocations": { "SingularDisplayName": "Microsoft.Network express route ports location" }
        ,"microsoft.network/firewallpolicies": { "SingularDisplayName": "Firewall Policy" }
        ,"microsoft.network/frontdoors": { "SingularDisplayName": "Front Door and CSingularDisplayName profiles" }
        ,"microsoft.network/frontdoorwebapplicationfirewallpolicies": { "SingularDisplayName": "Front Door WAF policy" }
        ,"microsoft.network/ipallocations": { "SingularDisplayName": "Microsoft.Network IP allocation" }
        ,"microsoft.network/ipgroups": { "SingularDisplayName": "IP Group" }
        ,"microsoft.network/loadbalancers": { "SingularDisplayName": "Load balancer" }
        ,"microsoft.network/localnetworkgateways": { "SingularDisplayName": "Local network gateway" }
        ,"microsoft.network/natgateways": { "SingularDisplayName": "NAT gateway" }
        ,"microsoft.network/networkexperimentprofiles": { "SingularDisplayName": "Microsoft.Network network experiment profile" }
        ,"microsoft.network/networkexperimentprofiles/experiments": { "SingularDisplayName": "Microsoft.Network network experiment profiles experiment" }
        ,"microsoft.network/networkinterfaces": { "SingularDisplayName": "Network interface" }
        ,"microsoft.network/networkmanagerconnections": { "SingularDisplayName": "Microsoft.Network network manager connection" }
        ,"microsoft.network/networkmanagers": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/connectivityconfigurations": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/ipampools": { "SingularDisplayName": "IP address pool" }
        ,"microsoft.network/networkmanagers/networkgroups": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/routingconfigurations": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/securityadminconfigurations": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/securityuserconfigurations": { "SingularDisplayName": "Network manager" }
        ,"microsoft.network/networkmanagers/verifierworkspaces": { "SingularDisplayName": "Verifier Workspace" }
        ,"microsoft.network/networkprofiles": { "SingularDisplayName": "Microsoft.Network network profile" }
        ,"microsoft.network/networksecuritygroups": { "SingularDisplayName": "Network security group" }
        ,"microsoft.network/networksecurityperimeters": { "SingularDisplayName": "Network Security Perimeter" }
        ,"microsoft.network/networksecurityperimeters/profiles": { "SingularDisplayName": "Network Security Perimeter" }
        ,"microsoft.network/networkverifiers": { "SingularDisplayName": "Virtual Network Verifier" }
        ,"microsoft.network/networkvirtualappliances": { "SingularDisplayName": "Microsoft.Network network virtual appliance" }
        ,"microsoft.network/networkwatchers": { "SingularDisplayName": "Network Watcher" }
        ,"microsoft.network/networkwatchers/flowlogs": { "SingularDisplayName": "Flow log" }
        ,"microsoft.network/p2svpngateways": { "SingularDisplayName": "Microsoft.Network P2S VPN gateway" }
        ,"microsoft.network/privateSingularDisplayNameszones": { "SingularDisplayName": "Private SingularDisplayNameS zone" }
        ,"microsoft.network/privateendpoints": { "SingularDisplayName": "Private endpoint" }
        ,"microsoft.network/privatelinkservices": { "SingularDisplayName": "Private link service" }
        ,"microsoft.network/publicipaddresses": { "SingularDisplayName": "Public IP address" }
        ,"microsoft.network/publicipprefixes": { "SingularDisplayName": "Public IP Prefix" }
        ,"microsoft.network/routefilters": { "SingularDisplayName": "Route filter" }
        ,"microsoft.network/routetables": { "SingularDisplayName": "Route table" }
        ,"microsoft.network/securitypartnerproviders": { "SingularDisplayName": "Microsoft.Network security partner provider" }
        ,"microsoft.network/serviceendpointpolicies": { "SingularDisplayName": "Service endpoint policy" }
        ,"microsoft.network/trafficmanagergeographichierarchies": { "SingularDisplayName": "Microsoft.Network traffic manager geographic hierarchy" }
        ,"microsoft.network/trafficmanagerprofiles": { "SingularDisplayName": "Traffic Manager profile" }
        ,"microsoft.network/trafficmanagerusermetricskeys": { "SingularDisplayName": "Microsoft.Network traffic manager user metrics key" }
        ,"microsoft.network/virtualhubs": { "SingularDisplayName": "Microsoft.Network/virtualHub" }
        ,"microsoft.network/virtualnetworkgateways": { "SingularDisplayName": "Virtual network gateway" }
        ,"microsoft.network/virtualnetworks": { "SingularDisplayName": "Virtual network" }
        ,"microsoft.network/virtualnetworktaps": { "SingularDisplayName": "Virtual Network Terminal Access Point" }
        ,"microsoft.network/virtualrouters": { "SingularDisplayName": "Microsoft.Network virtual router" }
        ,"microsoft.network/virtualrouters/peerings": { "SingularDisplayName": "Microsoft.Network virtual routers peering" }
        ,"microsoft.network/virtualwans": { "SingularDisplayName": "Virtual WAN" }
        ,"microsoft.network/vpngateways": { "SingularDisplayName": "VPN Gateway" }
        ,"microsoft.network/vpngateways/vpnconnections": { "SingularDisplayName": "Microsoft.Network VPN gateways VPN connection" }
        ,"microsoft.network/vpngateways/vpnconnections/vpnlinkconnections": { "SingularDisplayName": "Microsoft.Network VPN gateways VPN connections VPN link connection" }
        ,"microsoft.network/vpnserverconfigurations": { "SingularDisplayName": "Microsoft.Network VPN server configuration" }
        ,"microsoft.network/vpnsites": { "SingularDisplayName": "Microsoft.Network VPN site" }
        ,"microsoft.network/vpnsites/vpnsitelinks": { "SingularDisplayName": "Microsoft.Network VPN sites VPN site link" }
        ,"microsoft.networkanalytics/dataconnectors": { "SingularDisplayName": "AIOps - Data Connector" }
        ,"microsoft.networkanalytics/datalakehouses": { "SingularDisplayName": "AIOps - Data LakeHouse" }
        ,"microsoft.networkanalytics/dataproducts": { "SingularDisplayName": "Azure Operator Insights ? Data Product" }
        ,"microsoft.networkanalytics/dataproducts/datatypes": { "SingularDisplayName": "Data Type" }
        ,"microsoft.networkanalytics/dataproductscatalogs": { "SingularDisplayName": "Microsoft.NetworkAnalytics data products catalog" }
        ,"microsoft.networkanalytics/metricsingestionendpoints": { "SingularDisplayName": "Microsoft.NetworkAnalytics metrics ingestion endpoint" }
        ,"microsoft.networkanalytics/networkanalyticsproducts": { "SingularDisplayName": "Microsoft.NetworkAnalytics network analytics product" }
        ,"microsoft.networkcloud/baremetalmachines": { "SingularDisplayName": "Bare Metal Machine (Operator Nexus)" }
        ,"microsoft.networkcloud/cloudservicesnetworks": { "SingularDisplayName": "Cloud Services Network (Operator Nexus)" }
        ,"microsoft.networkcloud/clustermanagers": { "SingularDisplayName": "Cluster Manager (Operator Nexus)" }
        ,"microsoft.networkcloud/clusters": { "SingularDisplayName": "Cluster (Operator Nexus)" }
        ,"microsoft.networkcloud/clusters/baremetalmachinekeysets": { "SingularDisplayName": "Cluster Bare Metal Machine Key Set (Operator Nexus)" }
        ,"microsoft.networkcloud/clusters/bmckeysets": { "SingularDisplayName": "Cluster Baseboard Management Controller Key Set (Operator Nexus)" }
        ,"microsoft.networkcloud/clusters/metricsconfigurations": { "SingularDisplayName": "Cluster Metrics Configuration (Operator Nexus)" }
        ,"microsoft.networkcloud/edgeclustermachineskus": { "SingularDisplayName": "Microsoft.NetworkCloud edge cluster machine SKU" }
        ,"microsoft.networkcloud/edgeclusterruntimeversions": { "SingularDisplayName": "Microsoft.NetworkCloud edge cluster runtime version" }
        ,"microsoft.networkcloud/edgeclusters": { "SingularDisplayName": "Microsoft.NetworkCloud edge cluster" }
        ,"microsoft.networkcloud/edgeclusters/nodes": { "SingularDisplayName": "Microsoft.NetworkCloud edge clusters node" }
        ,"microsoft.networkcloud/edgeclusterskus": { "SingularDisplayName": "Microsoft.NetworkCloud edge cluster SKU" }
        ,"microsoft.networkcloud/kubernetesclusters": { "SingularDisplayName": "Kubernetes Cluster (Operator Nexus)" }
        ,"microsoft.networkcloud/kubernetesclusters/agentpools": { "SingularDisplayName": "Agent Pool (Operator Nexus)" }
        ,"microsoft.networkcloud/l2networks": { "SingularDisplayName": "Layer 2 Network (Operator Nexus)" }
        ,"microsoft.networkcloud/l3networks": { "SingularDisplayName": "Layer 3 Network (Operator Nexus)" }
        ,"microsoft.networkcloud/racks": { "SingularDisplayName": "Compute Rack (Operator Nexus)" }
        ,"microsoft.networkcloud/rackskus": { "SingularDisplayName": "Microsoft.NetworkCloud rack SKU" }
        ,"microsoft.networkcloud/registrationhubs": { "SingularDisplayName": "Microsoft.NetworkCloud registration hub" }
        ,"microsoft.networkcloud/registrationhubs/images": { "SingularDisplayName": "Microsoft.NetworkCloud registration hubs image" }
        ,"microsoft.networkcloud/registrationhubs/machines": { "SingularDisplayName": "Microsoft.NetworkCloud registration hubs machine" }
        ,"microsoft.networkcloud/storageappliances": { "SingularDisplayName": "Storage Appliance (Operator Nexus)" }
        ,"microsoft.networkcloud/trunkeSingularDisplayNameetworks": { "SingularDisplayName": "Trunked Network (Operator Nexus)" }
        ,"microsoft.networkcloud/virtualmachines": { "SingularDisplayName": "Virtual Machine (Operator Nexus)" }
        ,"microsoft.networkcloud/virtualmachines/consoles": { "SingularDisplayName": "Virtual Machine Console (Operator Nexus)" }
        ,"microsoft.networkcloud/volumes": { "SingularDisplayName": "Volume (Operator Nexus)" }
        ,"microsoft.networkfunction/azuretrafficcollectors": { "SingularDisplayName": "ExpressRoute traffic collector" }
        ,"microsoft.networkfunction/meshvpns": { "SingularDisplayName": "Mesh VPN" }
        ,"microsoft.nexusidentity/identitycontrollers": { "SingularDisplayName": "Microsoft.NexusIdentity identity controller" }
        ,"microsoft.nexusidentity/identitysets": { "SingularDisplayName": "Microsoft.NexusIdentity identity set" }
        ,"microsoft.notebooks/notebookproxies": { "SingularDisplayName": "Microsoft.Notebooks notebook proxy" }
        ,"microsoft.notificationhubs/namespaces": { "SingularDisplayName": "Notification Hub Namespace" }
        ,"microsoft.notificationhubs/namespaces/notificationhubs": { "SingularDisplayName": "Notification Hub" }
        ,"microsoft.objectstore/osnamespaces": { "SingularDisplayName": "Microsoft.ObjectStore os namespace" }
        ,"microsoft.openenergyplatform/energyservices": { "SingularDisplayName": "Azure Data Manager for Energy" }
        ,"microsoft.openlogisticsplatform/workspaces": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspace" }
        ,"microsoft.openlogisticsplatform/workspaces/applicationregistrations": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspaces application registration" }
        ,"microsoft.openlogisticsplatform/workspaces/applications": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspaces application" }
        ,"microsoft.openlogisticsplatform/workspaces/eventgridfilters": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspaces event grid filter" }
        ,"microsoft.openlogisticsplatform/workspaces/shares": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspaces share" }
        ,"microsoft.openlogisticsplatform/workspaces/sharesubscriptions": { "SingularDisplayName": "Microsoft.OpenLogisticsPlatform workspaces share subscription" }
        ,"microsoft.operationalinsights/clusters": { "SingularDisplayName": "Log Analytics dedicated cluster" }
        ,"microsoft.operationalinsights/querypacks": { "SingularDisplayName": "Log Analytics query pack" }
        ,"microsoft.operationalinsights/workspaces": { "SingularDisplayName": "Log Analytics workspace" }
        ,"microsoft.operationsmanagement/managementassociations": { "SingularDisplayName": "Microsoft.OperationsManagement management association" }
        ,"microsoft.operationsmanagement/solutions": { "SingularDisplayName": "Solution" }
        ,"microsoft.operatorvoicemail/operatorvoicemailinstances": { "SingularDisplayName": "Microsoft.OperatorVoicemail operator voicemail instance" }
        ,"microsoft.oraclediscovery/oraclesites": { "SingularDisplayName": "Microsoft.OracleDiscovery oracle site" }
        ,"microsoft.oraclediscovery/oraclesites/errorsummaries": { "SingularDisplayName": "Microsoft.OracleDiscovery oracle sites error summary" }
        ,"microsoft.oraclediscovery/oraclesites/oracledatabases": { "SingularDisplayName": "Microsoft.OracleDiscovery oracle sites oracle database" }
        ,"microsoft.oraclediscovery/oraclesites/oracleservers": { "SingularDisplayName": "Microsoft.OracleDiscovery oracle sites oracle server" }
        ,"microsoft.oraclediscovery/oraclesites/summaries": { "SingularDisplayName": "Microsoft.OracleDiscovery oracle sites summary" }
        ,"microsoft.orbital/cloudaccessrouters": { "SingularDisplayName": "Cloud Access Router" }
        ,"microsoft.orbital/contactprofiles": { "SingularDisplayName": "Contact Profile" }
        ,"microsoft.orbital/edgesites": { "SingularDisplayName": "Edge Site" }
        ,"microsoft.orbital/geocatalogs": { "SingularDisplayName": "GeoCatalog" }
        ,"microsoft.orbital/globalcommunicationssites": { "SingularDisplayName": "Microsoft.Orbital global communications site" }
        ,"microsoft.orbital/groundstations": { "SingularDisplayName": "Ground Station" }
        ,"microsoft.orbital/l2connections": { "SingularDisplayName": "L2 Connection" }
        ,"microsoft.orbital/sdwancontrollers": { "SingularDisplayName": "SDWAN Controller" }
        ,"microsoft.orbital/spacecrafts": { "SingularDisplayName": "Spacecraft" }
        ,"microsoft.orbital/spacecrafts/contacts": { "SingularDisplayName": "Contact" }
        ,"microsoft.orbital/terminals": { "SingularDisplayName": "Cloud Access Terminal" }
        ,"microsoft.partnermanagedconsumerrecurrence/recurrences": { "SingularDisplayName": "Microsoft.PartnerManagedConsumerRecurrence recurrence" }
        ,"microsoft.partnermanagedconsumerrecurrence/recurrences/operationresult": { "SingularDisplayName": "Microsoft.PartnerManagedConsumerRecurrence recurrences operation result" }
        ,"microsoft.peering/peerasns": { "SingularDisplayName": "Microsoft.Peering peer asn" }
        ,"microsoft.peering/peerings": { "SingularDisplayName": "Peering" }
        ,"microsoft.peering/peerings/registeredasns": { "SingularDisplayName": "Registered ASN" }
        ,"microsoft.peering/peerings/registeredprefixes": { "SingularDisplayName": "Registered prefix" }
        ,"microsoft.peering/peeringservices": { "SingularDisplayName": "Peering Service" }
        ,"microsoft.peering/peeringservices/prefixes": { "SingularDisplayName": "Peering Service Prefix" }
        ,"microsoft.pki/pkis": { "SingularDisplayName": "Microsoft.Pki PKI" }
        ,"microsoft.pki/pkis/certificateauthorities": { "SingularDisplayName": "Microsoft.Pki pkis certificate authority" }
        ,"microsoft.pki/pkis/enrollmentpolicies": { "SingularDisplayName": "Microsoft.Pki pkis enrollment policy" }
        ,"microsoft.policyinsights/attestations": { "SingularDisplayName": "Microsoft.PolicyInsights attestation" }
        ,"microsoft.policyinsights/policymetadata": { "SingularDisplayName": "Microsoft.PolicyInsights policy metadata" }
        ,"microsoft.policyinsights/remediations": { "SingularDisplayName": "Microsoft.PolicyInsights remediation" }
        ,"microsoft.portal/consoles": { "SingularDisplayName": "Microsoft.Portal console" }
        ,"microsoft.portal/dashboards": { "SingularDisplayName": "Shared dashboard" }
        ,"microsoft.portal/tenantconfigurations": { "SingularDisplayName": "Microsoft.Portal tenant configuration" }
        ,"microsoft.portal/usersettings": { "SingularDisplayName": "Microsoft.Portal user setting" }
        ,"microsoft.portal/virtual-privatedashboards": { "SingularDisplayName": "Private dashboard" }
        ,"microsoft.portalservices/copilotsettings": { "SingularDisplayName": "Microsoft.PortalServices copilot setting" }
        ,"microsoft.portalservices/dashboards": { "SingularDisplayName": "Shared dashboard" }
        ,"microsoft.portalservices/extensions": { "SingularDisplayName": "Portal Extension" }
        ,"microsoft.portalservices/extensions/deployments": { "SingularDisplayName": "Extension Deployment" }
        ,"microsoft.portalservices/extensions/slots": { "SingularDisplayName": "Extension Slot" }
        ,"microsoft.portalservices/extensions/versions": { "SingularDisplayName": "Extension Version" }
        ,"microsoft.powerbi/privatelinkservicesforpowerbi": { "SingularDisplayName": "Microsoft.PowerBI private link services for power bi" }
        ,"microsoft.powerbi/privatelinkservicesforpowerbi/privateendpointconnections": { "SingularDisplayName": "Microsoft.PowerBI private link services for power bi private endpoint connection" }
        ,"microsoft.powerbi/privatelinkservicesforpowerbi/privatelinkresources": { "SingularDisplayName": "Microsoft.PowerBI private link services for power bi private link resource" }
        ,"microsoft.powerbi/workspacecollections": { "SingularDisplayName": "Microsoft.PowerBI workspace collection" }
        ,"microsoft.powerbidedicated/autoscalevcores": { "SingularDisplayName": "Microsoft.PowerBIDedicated auto scale vcore" }
        ,"microsoft.powerbidedicated/capacities": { "SingularDisplayName": "Power BI Embedded" }
        ,"microsoft.powerplatform/accounts": { "SingularDisplayName": "Microsoft.PowerPlatform account" }
        ,"microsoft.professionalservice/resources": { "SingularDisplayName": "Professional Service" }
        ,"microsoft.programmableconnectivity/gateways": { "SingularDisplayName": "APC Gateway" }
        ,"microsoft.programmableconnectivity/operatorapiconnections": { "SingularDisplayName": "APC Operator API Connection" }
        ,"microsoft.programmableconnectivity/operatorapiplans": { "SingularDisplayName": "APC Operator API Plan" }
        ,"microsoft.providerhub/providerregistrations": { "SingularDisplayName": "Resource Provider as a Service" }
        ,"microsoft.providerhub/providerregistrations/customrollouts": { "SingularDisplayName": "Rollout" }
        ,"microsoft.providerhub/providerregistrations/defaultrollouts": { "SingularDisplayName": "Rollout" }
        ,"microsoft.providerhub/providerregistrations/resourcetyperegistrations": { "SingularDisplayName": "Resource Type" }
        ,"microsoft.providerhub/providerregistrations/resourcetyperegistrations/resourcetyperegistrations": { "SingularDisplayName": "Resource Type" }
        ,"microsoft.providerhubdevtest/regionalstresstests": { "SingularDisplayName": "Microsoft.ProviderHubDevTest regional stresstest" }
        ,"microsoft.providerhubdevtest/stresstests": { "SingularDisplayName": "Microsoft.ProviderHubDevTest stresstest" }
        ,"microsoft.purview/accounts": { "SingularDisplayName": "Microsoft Purview account" }
        ,"microsoft.quantum/workspaces": { "SingularDisplayName": "Quantum Workspace" }
        ,"microsoft.quota/groupquotas": { "SingularDisplayName": "Microsoft.Quota group quota" }
        ,"microsoft.quota/groupquotas/groupquotarequests": { "SingularDisplayName": "Microsoft.Quota group quotas group quota request" }
        ,"microsoft.quota/groupquotas/quotaallocationrequests": { "SingularDisplayName": "Microsoft.Quota group quotas quota allocation request" }
        ,"microsoft.quota/groupquotas/quotaallocations": { "SingularDisplayName": "Microsoft.Quota group quotas quota allocation" }
        ,"microsoft.quota/groupquotas/subscriptionrequests": { "SingularDisplayName": "Microsoft.Quota group quotas subscription request" }
        ,"microsoft.quota/groupquotas/subscriptions": { "SingularDisplayName": "Microsoft.Quota group quotas subscription" }
        ,"microsoft.quota/quotarequests": { "SingularDisplayName": "Microsoft.Quota quota request" }
        ,"microsoft.quota/quotas": { "SingularDisplayName": "Microsoft.Quota quota" }
        ,"microsoft.quota/usages": { "SingularDisplayName": "Microsoft.Quota usage" }
        ,"microsoft.recommendationsservice/accounts": { "SingularDisplayName": "Intelligent Recommendations Account" }
        ,"microsoft.recommendationsservice/accounts/modeling": { "SingularDisplayName": "Modeling" }
        ,"microsoft.recommendationsservice/accounts/serviceendpoints": { "SingularDisplayName": "Service Endpoint" }
        ,"microsoft.recoveryservices/replicationeligibilityresults": { "SingularDisplayName": "Microsoft.RecoveryServices replication eligibility result" }
        ,"microsoft.recoveryservices/vaults": { "SingularDisplayName": "Recovery Services vault" }
        ,"microsoft.recoveryservices/vaults/backupfabrics/protectioncontainers/protecteditems": { "SingularDisplayName": "Backup Item" }
        ,"microsoft.recoveryservicesbvtd/vaults": { "SingularDisplayName": "Recovery Services BVTD" }
        ,"microsoft.recoveryservicesbvtd2/vaults": { "SingularDisplayName": "Recovery Services BVTD2" }
        ,"microsoft.recoveryservicesintd/vaults": { "SingularDisplayName": "Recovery Services INTD" }
        ,"microsoft.recoveryservicesintd2/vaults": { "SingularDisplayName": "Recovery Services INTD2" }
        ,"microsoft.redhatopenshift/openshiftclusters": { "SingularDisplayName": "Azure Red Hat OpenShift cluster" }
        ,"microsoft.relay/namespaces": { "SingularDisplayName": "Relay" }
        ,"microsoft.relay/namespaces/hybridconnections": { "SingularDisplayName": "Hybrid connection" }
        ,"microsoft.relay/namespaces/wcfrelays": { "SingularDisplayName": "WCF relay" }
        ,"microsoft.resilience/resiliencestates": { "SingularDisplayName": "Microsoft.Resilience resilience state" }
        ,"microsoft.resourceconnector/appliances": { "SingularDisplayName": "Resource bridge" }
        ,"microsoft.resourcegraph/queries": { "SingularDisplayName": "Resource Graph query" }
        ,"microsoft.resourcehealth/availabilitystatuses": { "SingularDisplayName": "Microsoft.ResourceHealth availability statuse" }
        ,"microsoft.resourcehealth/childavailabilitystatuses": { "SingularDisplayName": "Microsoft.ResourceHealth child availability statuse" }
        ,"microsoft.resourcehealth/emergingissues": { "SingularDisplayName": "Microsoft.ResourceHealth emerging issue" }
        ,"microsoft.resourcehealth/events": { "SingularDisplayName": "Microsoft.ResourceHealth event" }
        ,"microsoft.resourcehealth/events/impactedresources": { "SingularDisplayName": "Microsoft.ResourceHealth events impacted resource" }
        ,"microsoft.resourcehealth/metadata": { "SingularDisplayName": "Microsoft.ResourceHealth metadata" }
        ,"microsoft.resources/builtintemplatespecs": { "SingularDisplayName": "Built-in template spec" }
        ,"microsoft.resources/changes": { "SingularDisplayName": "Microsoft.Resources change" }
        ,"microsoft.resources/databoundaries": { "SingularDisplayName": "Microsoft.Resources data boundary" }
        ,"microsoft.resources/deletedresources": { "SingularDisplayName": "Recycle Bin" }
        ,"microsoft.resources/deployments": { "SingularDisplayName": "Microsoft.Resources deployment" }
        ,"microsoft.resources/deployments/operations": { "SingularDisplayName": "Microsoft.Resources deployments operation" }
        ,"microsoft.resources/deploymentscripts": { "SingularDisplayName": "Deployment Script" }
        ,"microsoft.resources/deploymentstacks": { "SingularDisplayName": "Deployment stack" }
        ,"microsoft.resources/mobobrokers": { "SingularDisplayName": "Microsoft.Resources mobo broker" }
        ,"microsoft.resources/resourcechange": { "SingularDisplayName": "Change Analysis" }
        ,"microsoft.resources/resourcechanges": { "SingularDisplayName": "Resource change" }
        ,"microsoft.resources/resourcegraphvisualizer": { "SingularDisplayName": "Resource Graph Visualizer" }
        ,"microsoft.resources/resourcegroups": { "SingularDisplayName": "Microsoft.Resources resource group" }
        ,"microsoft.resources/resources": { "SingularDisplayName": "Resource" }
        ,"microsoft.resources/snapshots": { "SingularDisplayName": "Microsoft.Resources snapshot" }
        ,"microsoft.resources/subscriptions": { "SingularDisplayName": "Subscription" }
        ,"microsoft.resources/subscriptions/resourcegroups": { "SingularDisplayName": "Resource group" }
        ,"microsoft.resources/tags": { "SingularDisplayName": "Microsoft.Resources tag" }
        ,"microsoft.resources/templatespecs": { "SingularDisplayName": "Template spec" }
        ,"microsoft.saas/applications": { "SingularDisplayName": "Software as a Service (classic)" }
        ,"microsoft.saas/resources": { "SingularDisplayName": "SaaS" }
        ,"microsoft.saas/saasresources": { "SingularDisplayName": "SaaS (classic)" }
        ,"microsoft.saashub/cloudservices/hidden": { "SingularDisplayName": "Microsoft SaaS" }
        ,"microsoft.salescopilot/conversationintelligencerecordingaccounts": { "SingularDisplayName": "Microsoft.SalesCopilot conversation intelligence recording account" }
        ,"microsoft.samplepartner/organizations": { "SingularDisplayName": "Sample Partner Resource" }
        ,"microsoft.scheduler/jobcollections": { "SingularDisplayName": "Scheduler job collection" }
        ,"microsoft.scheduler/jobcollections/jobs": { "SingularDisplayName": "Scheduler job" }
        ,"microsoft.scom/managedinstances": { "SingularDisplayName": "SCOM managed instance" }
        ,"microsoft.scvmm/availabilitysets": { "SingularDisplayName": "Microsoft.ScVmm availability set" }
        ,"microsoft.scvmm/clouds": { "SingularDisplayName": "Microsoft.ScVmm cloud" }
        ,"microsoft.scvmm/virtualmachineinstances": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instance" }
        ,"microsoft.scvmm/virtualmachineinstances/guestagents": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instances guest agent" }
        ,"microsoft.scvmm/virtualmachineinstances/hybrididentitymetadata": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instances hybrid identity metadata" }
        ,"microsoft.scvmm/virtualmachines": { "SingularDisplayName": "SCVMM virtual machine - Azure Arc" }
        ,"microsoft.scvmm/virtualmachinetemplates": { "SingularDisplayName": "Microsoft.ScVmm virtual machine template" }
        ,"microsoft.scvmm/virtualnetworks": { "SingularDisplayName": "Microsoft.ScVmm virtual network" }
        ,"microsoft.scvmm/vmmservers": { "SingularDisplayName": "SCVMM management server" }
        ,"microsoft.search/searchservices": { "SingularDisplayName": "Search service" }
        ,"microsoft.secretmanagementsampleprovider/forecasts": { "SingularDisplayName": "Microsoft.SecretManagementSampleProvider forecast" }
        ,"microsoft.secretsynccontroller/azurekeyvaultsecretproviderclasses": { "SingularDisplayName": "Microsoft.SecretSyncController Azure key vault secret provider class" }
        ,"microsoft.secretsynccontroller/secretsyncs": { "SingularDisplayName": "Microsoft.SecretSyncController secret sync" }
        ,"microsoft.security/adaptivenetworkhardenings": { "SingularDisplayName": "Microsoft.Security adaptive network hardening" }
        ,"microsoft.security/advancedthreatprotectionsettings": { "SingularDisplayName": "Microsoft.Security advanced threat protection setting" }
        ,"microsoft.security/alertssuppressionrules": { "SingularDisplayName": "Microsoft.Security alerts suppression rule" }
        ,"microsoft.security/apicollections": { "SingularDisplayName": "Microsoft.Security API collection" }
        ,"microsoft.security/applications": { "SingularDisplayName": "Microsoft.Security application" }
        ,"microsoft.security/assessmentmetadata": { "SingularDisplayName": "Microsoft.Security assessment metadata" }
        ,"microsoft.security/assessments": { "SingularDisplayName": "Microsoft.Security assessment" }
        ,"microsoft.security/assessments/governanceassignments": { "SingularDisplayName": "Microsoft.Security assessments governance assignment" }
        ,"microsoft.security/assessments/subassessments": { "SingularDisplayName": "Microsoft.Security assessments sub assessment" }
        ,"microsoft.security/assignments": { "SingularDisplayName": "Microsoft.Security assignment" }
        ,"microsoft.security/automations": { "SingularDisplayName": "Microsoft.Security automation" }
        ,"microsoft.security/autoprovisioningsettings": { "SingularDisplayName": "Microsoft.Security auto provisioning setting" }
        ,"microsoft.security/complianceresults": { "SingularDisplayName": "Microsoft.Security compliance result" }
        ,"microsoft.security/compliances": { "SingularDisplayName": "Microsoft.Security compliance" }
        ,"microsoft.security/connectors": { "SingularDisplayName": "Microsoft.Security connector" }
        ,"microsoft.security/customassessmentautomations": { "SingularDisplayName": "Microsoft.Security custom assessment automation" }
        ,"microsoft.security/defenderforstoragesettings": { "SingularDisplayName": "Microsoft.Security defender for storage setting" }
        ,"microsoft.security/defenderforstoragesettings/malwarescans": { "SingularDisplayName": "Microsoft.Security defender for storage settings malware scan" }
        ,"microsoft.security/devicesecuritygroups": { "SingularDisplayName": "Microsoft.Security device security group" }
        ,"microsoft.security/governancerules": { "SingularDisplayName": "Microsoft.Security governance rule" }
        ,"microsoft.security/governancerules/operationresults": { "SingularDisplayName": "Microsoft.Security governance rules operation result" }
        ,"microsoft.security/healthreports": { "SingularDisplayName": "Microsoft.Security health report" }
        ,"microsoft.security/informationprotectionpolicies": { "SingularDisplayName": "Microsoft.Security information protection policy" }
        ,"microsoft.security/iotsecuritysolutions": { "SingularDisplayName": "Microsoft.Security IoT security solution" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics model" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels/aggregatedalerts": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics models aggregated alert" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels/aggregatedrecommendations": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics models aggregated recommendation" }
        ,"microsoft.security/iotsecuritysolutions/iotalerts": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT alert" }
        ,"microsoft.security/iotsecuritysolutions/iotalerttypes": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT alert type" }
        ,"microsoft.security/iotsecuritysolutions/iotrecommendations": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT recommendation" }
        ,"microsoft.security/iotsecuritysolutions/iotrecommendationtypes": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT recommendation type" }
        ,"microsoft.security/locations/alerts": { "SingularDisplayName": "Security Alert" }
        ,"microsoft.security/mdeonboardings": { "SingularDisplayName": "Microsoft.Security mde onboarding" }
        ,"microsoft.security/pricings": { "SingularDisplayName": "Defender for Cloud" }
        ,"microsoft.security/pricings/securityoperators": { "SingularDisplayName": "Microsoft.Security pricings security operator" }
        ,"microsoft.security/regulatorycompliancestandards": { "SingularDisplayName": "Microsoft.Security regulatory compliance standard" }
        ,"microsoft.security/regulatorycompliancestandards/regulatorycompliancecontrols": { "SingularDisplayName": "Microsoft.Security regulatory compliance standards regulatory compliance control" }
        ,"microsoft.security/regulatorycompliancestandards/regulatorycompliancecontrols/regulatorycomplianceassessments": { "SingularDisplayName": "Microsoft.Security regulatory compliance standards regulatory compliance controls regulatory compliance assessment" }
        ,"microsoft.security/securescores": { "SingularDisplayName": "Microsoft.Security secure score" }
        ,"microsoft.security/securityconnectors": { "SingularDisplayName": "Microsoft.Security security connector" }
        ,"microsoft.security/securityconnectors/devops": { "SingularDisplayName": "Microsoft.Security security connectors devop" }
        ,"microsoft.security/securitycontacts": { "SingularDisplayName": "Microsoft.Security security contact" }
        ,"microsoft.security/sensitivitysettings": { "SingularDisplayName": "Microsoft.Security sensitivity setting" }
        ,"microsoft.security/servervulnerabilityassessments": { "SingularDisplayName": "Microsoft.Security server vulnerability assessment" }
        ,"microsoft.security/servervulnerabilityassessmentssettings": { "SingularDisplayName": "Microsoft.Security server vulnerability assessments setting" }
        ,"microsoft.security/settings": { "SingularDisplayName": "Microsoft.Security setting" }
        ,"microsoft.security/standards": { "SingularDisplayName": "Microsoft.Security standard" }
        ,"microsoft.security/workspacesettings": { "SingularDisplayName": "Microsoft.Security workspace setting" }
        ,"microsoft.securitycopilot/capacities": { "SingularDisplayName": "Microsoft Security Copilot compute capacity" }
        ,"microsoft.securitydetonation/chambers": { "SingularDisplayName": "Security Detonation Chamber" }
        ,"microsoft.securityinsightsarg/sentinel": { "SingularDisplayName": "Microsoft Sentinel" }
        ,"microsoft.serialconsole/consoleservices": { "SingularDisplayName": "Microsoft.SerialConsole console service" }
        ,"microsoft.serialconsole/serialports": { "SingularDisplayName": "Microsoft.SerialConsole serial port" }
        ,"microsoft.servicebus/namespaces": { "SingularDisplayName": "Service Bus namespace" }
        ,"microsoft.servicebus/namespaces/disasterrecoveryconfigs": { "SingularDisplayName": "Service Bus Geo-DR Alias" }
        ,"microsoft.servicebus/namespaces/queues": { "SingularDisplayName": "Service Bus queue" }
        ,"microsoft.servicebus/namespaces/topics": { "SingularDisplayName": "Service Bus topic" }
        ,"microsoft.servicebus/namespaces/topics/subscriptions": { "SingularDisplayName": "Service Bus Subscription" }
        ,"microsoft.servicefabric/clusters": { "SingularDisplayName": "Service Fabric cluster" }
        ,"microsoft.servicefabric/managedclusters": { "SingularDisplayName": "Service Fabric managed cluster" }
        ,"microsoft.servicefabricmesh/applications": { "SingularDisplayName": "Microsoft.ServiceFabricMesh application" }
        ,"microsoft.servicefabricmesh/applications/services": { "SingularDisplayName": "Microsoft.ServiceFabricMesh applications service" }
        ,"microsoft.servicefabricmesh/applications/services/replicas": { "SingularDisplayName": "Microsoft.ServiceFabricMesh applications services replica" }
        ,"microsoft.servicefabricmesh/gateways": { "SingularDisplayName": "Microsoft.ServiceFabricMesh gateway" }
        ,"microsoft.servicefabricmesh/networks": { "SingularDisplayName": "Microsoft.ServiceFabricMesh network" }
        ,"microsoft.servicefabricmesh/secrets": { "SingularDisplayName": "Microsoft.ServiceFabricMesh secret" }
        ,"microsoft.servicefabricmesh/secrets/values": { "SingularDisplayName": "Microsoft.ServiceFabricMesh secrets value" }
        ,"microsoft.servicefabricmesh/volumes": { "SingularDisplayName": "Microsoft.ServiceFabricMesh volume" }
        ,"microsoft.servicelinker/dryruns": { "SingularDisplayName": "Microsoft.ServiceLinker dryrun" }
        ,"microsoft.servicelinker/linkers": { "SingularDisplayName": "Microsoft.ServiceLinker linker" }
        ,"microsoft.servicenetworking/trafficcontrollers": { "SingularDisplayName": "Application Gateway for Containers" }
        ,"microsoft.serviceshub/connectors": { "SingularDisplayName": "Services Hub Connector" }
        ,"microsoft.signalrservice/signalr": { "SingularDisplayName": "SignalR" }
        ,"microsoft.signalrservice/signalr/replicas": { "SingularDisplayName": "SignalR Replica" }
        ,"microsoft.signalrservice/webpubsub": { "SingularDisplayName": "Web PubSub Service" }
        ,"microsoft.signalrservice/webpubsub/replicas": { "SingularDisplayName": "Web PubSub Service Replica" }
        ,"microsoft.skytap/billingnodes": { "SingularDisplayName": "Microsoft.Skytap billing node" }
        ,"microsoft.skytap/interfaces": { "SingularDisplayName": "Microsoft.Skytap interface" }
        ,"microsoft.skytap/nodes": { "SingularDisplayName": "Microsoft.Skytap node" }
        ,"microsoft.softwareplan/hybridusebenefits": { "SingularDisplayName": "Microsoft.SoftwarePlan hybrid use benefit" }
        ,"microsoft.solutions/applicationdefinitions": { "SingularDisplayName": "Service catalog managed application definition" }
        ,"microsoft.solutions/applications": { "SingularDisplayName": "Managed application" }
        ,"microsoft.solutions/jitrequests": { "SingularDisplayName": "Microsoft.Solutions JIT request" }
        ,"microsoft.sovereign/landingzoneaccounts": { "SingularDisplayName": "Landing zone accounts" }
        ,"microsoft.sovereign/landingzoneaccounts/landingzoneconfigurations": { "SingularDisplayName": "Landing Zone Configuration" }
        ,"microsoft.sovereign/landingzoneaccounts/landingzoneregistrations": { "SingularDisplayName": "Landing Zone Registration" }
        ,"microsoft.sovereign/landingzoneconfigurations": { "SingularDisplayName": "Landing Zone Configuration" }
        ,"microsoft.sovereign/landingzoneregistrations": { "SingularDisplayName": "Landing Zone Registration" }
        ,"microsoft.sovereign/transparencylogs": { "SingularDisplayName": "Transparency log" }
        ,"microsoft.sql/azuresql": { "SingularDisplayName": "Azure SQL resource" }
        ,"microsoft.sql/instancepools": { "SingularDisplayName": "Instance pool" }
        ,"microsoft.sql/managedinstances": { "SingularDisplayName": "SQL managed instance" }
        ,"microsoft.sql/managedinstances/databases": { "SingularDisplayName": "Managed database" }
        ,"microsoft.sql/servers": { "SingularDisplayName": "SQL server" }
        ,"microsoft.sql/servers/databases": { "SingularDisplayName": "SQL database" }
        ,"microsoft.sql/servers/elasticpools": { "SingularDisplayName": "SQL elastic pool" }
        ,"microsoft.sql/servers/jobagents": { "SingularDisplayName": "Elastic Job agent" }
        ,"microsoft.sql/virtualclusters": { "SingularDisplayName": "Virtual cluster" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachinegroups": { "SingularDisplayName": "Microsoft.SqlVirtualMachine sql virtual machine group" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachinegroups/availabilitygrouplisteners": { "SingularDisplayName": "Microsoft.SqlVirtualMachine sql virtual machine groups availability group listener" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachines": { "SingularDisplayName": "SQL virtual machine" }
        ,"microsoft.standbypool/standbycontainergrouppools": { "SingularDisplayName": "Microsoft.StandbyPool standby container group pool" }
        ,"microsoft.standbypool/standbycontainergrouppools/runtimeviews": { "SingularDisplayName": "Microsoft.StandbyPool standby container group pools runtime view" }
        ,"microsoft.standbypool/standbyvirtualmachinepools": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pool" }
        ,"microsoft.standbypool/standbyvirtualmachinepools/runtimeviews": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pools runtime view" }
        ,"microsoft.standbypool/standbyvirtualmachinepools/standbyvirtualmachines": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pools standby virtual machine" }
        ,"microsoft.storage/storageaccounts": { "SingularDisplayName": "Storage account" }
        ,"microsoft.storageactions/storagetasks": { "SingularDisplayName": "Storage task - Azure Storage Actions" }
        ,"microsoft.storagecache/amlfilesystems": { "SingularDisplayName": "Azure Managed Lustre" }
        ,"microsoft.storagecache/caches": { "SingularDisplayName": "HPC cache" }
        ,"microsoft.storageinsights/storagecollectionrules": { "SingularDisplayName": "Microsoft.StorageInsights storage collection rule" }
        ,"microsoft.storagemover/storagemovers": { "SingularDisplayName": "Storage mover" }
        ,"microsoft.storagepool/diskpools": { "SingularDisplayName": "Microsoft.StoragePool disk pool" }
        ,"microsoft.storagepool/diskpools/iscsitargets": { "SingularDisplayName": "Microsoft.StoragePool disk pools iscsi target" }
        ,"microsoft.storagesync/storagesyncservices": { "SingularDisplayName": "Storage Sync Service" }
        ,"microsoft.storagetasks/storagetasks": { "SingularDisplayName": "Microsoft.StorageTasks storage task" }
        ,"microsoft.storsimple/managers": { "SingularDisplayName": "StorSimple device manager" }
        ,"microsoft.storsimple/managers/accesscontrolrecords": { "SingularDisplayName": "Microsoft.StorSimple managers access control record" }
        ,"microsoft.storsimple/managers/bandwidthsettings": { "SingularDisplayName": "Microsoft.StorSimple managers bandwidth setting" }
        ,"microsoft.storsimple/managers/certificates": { "SingularDisplayName": "Microsoft.StorSimple managers certificate" }
        ,"microsoft.storsimple/managers/devices": { "SingularDisplayName": "Microsoft.StorSimple managers device" }
        ,"microsoft.storsimple/managers/devices/alertsettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices alert setting" }
        ,"microsoft.storsimple/managers/devices/backuppolicies": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup policy" }
        ,"microsoft.storsimple/managers/devices/backuppolicies/schedules": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup policies schedule" }
        ,"microsoft.storsimple/managers/devices/backupschedulegroups": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup schedule group" }
        ,"microsoft.storsimple/managers/devices/chapsettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices chap setting" }
        ,"microsoft.storsimple/managers/devices/fileservers": { "SingularDisplayName": "Microsoft.StorSimple managers devices fileserver" }
        ,"microsoft.storsimple/managers/devices/fileservers/shares": { "SingularDisplayName": "Microsoft.StorSimple managers devices fileservers share" }
        ,"microsoft.storsimple/managers/devices/iscsiservers": { "SingularDisplayName": "Microsoft.StorSimple managers devices iscsiserver" }
        ,"microsoft.storsimple/managers/devices/iscsiservers/disks": { "SingularDisplayName": "Microsoft.StorSimple managers devices iscsiservers disk" }
        ,"microsoft.storsimple/managers/devices/jobs": { "SingularDisplayName": "Microsoft.StorSimple managers devices job" }
        ,"microsoft.storsimple/managers/devices/networksettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices network setting" }
        ,"microsoft.storsimple/managers/devices/securitysettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices security setting" }
        ,"microsoft.storsimple/managers/devices/timesettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices time setting" }
        ,"microsoft.storsimple/managers/devices/updatesummary": { "SingularDisplayName": "Microsoft.StorSimple managers devices update summary" }
        ,"microsoft.storsimple/managers/devices/volumecontainers": { "SingularDisplayName": "Microsoft.StorSimple managers devices volume container" }
        ,"microsoft.storsimple/managers/devices/volumecontainers/volumes": { "SingularDisplayName": "Microsoft.StorSimple managers devices volume containers volume" }
        ,"microsoft.storsimple/managers/encryptionsettings": { "SingularDisplayName": "Microsoft.StorSimple managers encryption setting" }
        ,"microsoft.storsimple/managers/extendedinformation": { "SingularDisplayName": "Microsoft.StorSimple managers extended information" }
        ,"microsoft.storsimple/managers/storageaccountcredentials": { "SingularDisplayName": "Microsoft.StorSimple managers storage account credential" }
        ,"microsoft.storsimple/managers/storagedomains": { "SingularDisplayName": "Microsoft.StorSimple managers storage domain" }
        ,"microsoft.streamanalytics/clusters": { "SingularDisplayName": "Stream Analytics cluster" }
        ,"microsoft.streamanalytics/streamingjobs": { "SingularDisplayName": "Stream Analytics job" }
        ,"microsoft.subscription/aliases": { "SingularDisplayName": "Microsoft.Subscription aliase" }
        ,"microsoft.subscription/changetenantrequest": { "SingularDisplayName": "Microsoft.Subscription change tenant request" }
        ,"microsoft.subscription/policies": { "SingularDisplayName": "Microsoft.Subscription policy" }
        ,"microsoft.subscription/subscriptiondefinitions": { "SingularDisplayName": "Microsoft.Subscription subscription definition" }
        ,"microsoft.subscription/subscriptionoperations": { "SingularDisplayName": "Microsoft.Subscription subscription operation" }
        ,"microsoft.support/fileworkspaces": { "SingularDisplayName": "Microsoft.Support file workspace" }
        ,"microsoft.support/fileworkspaces/files": { "SingularDisplayName": "Microsoft.Support file workspaces file" }
        ,"microsoft.support/services": { "SingularDisplayName": "Microsoft.Support service" }
        ,"microsoft.support/services/problemclassifications": { "SingularDisplayName": "Microsoft.Support services problem classification" }
        ,"microsoft.support/supporttickets": { "SingularDisplayName": "Support Request" }
        ,"microsoft.sustainabilityservices/calculations": { "SingularDisplayName": "Microsoft.SustainabilityServices calculation" }
        ,"microsoft.symphony/instances": { "SingularDisplayName": "Microsoft.Symphony instance" }
        ,"microsoft.symphony/solutions": { "SingularDisplayName": "Microsoft.Symphony solution" }
        ,"microsoft.symphony/targets": { "SingularDisplayName": "Microsoft.Symphony target" }
        ,"microsoft.synapse/privatelinkhubs": { "SingularDisplayName": "Synapse private link hub" }
        ,"microsoft.synapse/workspaces": { "SingularDisplayName": "Synapse workspace" }
        ,"microsoft.synapse/workspaces/bigdatapools": { "SingularDisplayName": "Apache Spark pool" }
        ,"microsoft.synapse/workspaces/kustopools": { "SingularDisplayName": "Data Explorer pool" }
        ,"microsoft.synapse/workspaces/kustopools/databases": { "SingularDisplayName": "Data Explorer Database" }
        ,"microsoft.synapse/workspaces/scopepools": { "SingularDisplayName": "SCOPE pool" }
        ,"microsoft.synapse/workspaces/sqlpools": { "SingularDisplayName": "Dedicated SQL pool" }
        ,"microsoft.syntex/accounts": { "SingularDisplayName": "Microsoft.Syntex account" }
        ,"microsoft.syntex/documentprocessors": { "SingularDisplayName": "Microsoft.Syntex document processor" }
        ,"microsoft.test/healthdataaiservices": { "SingularDisplayName": "Azure Health Data and AI Services" }
        ,"microsoft.timeseriesinsights/environments": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environment" }
        ,"microsoft.timeseriesinsights/environments/accesspolicies": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments access policy" }
        ,"microsoft.timeseriesinsights/environments/eventsources": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments event source" }
        ,"microsoft.timeseriesinsights/environments/referencedatasets": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments reference data set" }
        ,"microsoft.toolchainorchestrator/activations": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator activation" }
        ,"microsoft.toolchainorchestrator/campaigns": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator campaign" }
        ,"microsoft.toolchainorchestrator/campaigns/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator campaigns version" }
        ,"microsoft.toolchainorchestrator/catalogs": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator catalog" }
        ,"microsoft.toolchainorchestrator/catalogs/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator catalogs version" }
        ,"microsoft.toolchainorchestrator/instances": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator instance" }
        ,"microsoft.toolchainorchestrator/instances/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator instances version" }
        ,"microsoft.toolchainorchestrator/solutions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator solution" }
        ,"microsoft.toolchainorchestrator/solutions/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator solutions version" }
        ,"microsoft.toolchainorchestrator/targets": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator target" }
        ,"microsoft.toolchainorchestrator/targets/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator targets version" }
        ,"microsoft.usagebilling/accounts": { "SingularDisplayName": "Microsoft.UsageBilling account" }
        ,"microsoft.usagebilling/accounts/dataexports": { "SingularDisplayName": "Microsoft.UsageBilling accounts data export" }
        ,"microsoft.usagebilling/accounts/inputs": { "SingularDisplayName": "Microsoft.UsageBilling accounts input" }
        ,"microsoft.usagebilling/accounts/metricexports": { "SingularDisplayName": "Microsoft.UsageBilling accounts metric export" }
        ,"microsoft.usagebilling/accounts/pav2outputs": { "SingularDisplayName": "Microsoft.UsageBilling accounts pav2output" }
        ,"microsoft.usagebilling/accounts/pipelines": { "SingularDisplayName": "Microsoft.UsageBilling accounts pipeline" }
        ,"microsoft.usagebilling/accounts/pipelines/outputselectors": { "SingularDisplayName": "Microsoft.UsageBilling accounts pipelines output selector" }
        ,"microsoft.verifiedid/authorities": { "SingularDisplayName": "Microsoft.VerifiedId authority" }
        ,"microsoft.videoindexer/accounts": { "SingularDisplayName": "Azure AI Video Indexer" }
        ,"microsoft.virtualmachineimages/imagetemplates": { "SingularDisplayName": "Image template" }
        ,"microsoft.visualstudio/account": { "SingularDisplayName": "Azure DevOps organization" }
        ,"microsoft.vmware/resourcepools": { "SingularDisplayName": "Microsoft.VMware resource pool" }
        ,"microsoft.vmware/vcenters": { "SingularDisplayName": "Microsoft.VMware vcenter" }
        ,"microsoft.vmware/vcenters/inventoryitems": { "SingularDisplayName": "Microsoft.VMware vcenters inventory item" }
        ,"microsoft.vmware/virtualmachines": { "SingularDisplayName": "Microsoft.VMware virtual machine" }
        ,"microsoft.vmware/virtualmachinetemplates": { "SingularDisplayName": "Microsoft.VMware virtual machine template" }
        ,"microsoft.vmware/virtualnetworks": { "SingularDisplayName": "Microsoft.VMware virtual network" }
        ,"microsoft.vmwarecloudsimple/dedicatedclouSingularDisplayNameodes": { "SingularDisplayName": "Microsoft.VMwareCloudSimple dedicated cloud node" }
        ,"microsoft.vmwarecloudsimple/dedicatedcloudservices": { "SingularDisplayName": "Microsoft.VMwareCloudSimple dedicated cloud service" }
        ,"microsoft.vmwarecloudsimple/virtualmachines": { "SingularDisplayName": "Microsoft.VMwareCloudSimple virtual machine" }
        ,"microsoft.vnfmanager/devices": { "SingularDisplayName": "Microsoft.VnfManager device" }
        ,"microsoft.vnfmanager/vendors": { "SingularDisplayName": "Microsoft.VnfManager vendor" }
        ,"microsoft.vnfmanager/vendors/skus": { "SingularDisplayName": "Microsoft.VnfManager vendors SKU" }
        ,"microsoft.vnfmanager/vnfs": { "SingularDisplayName": "Microsoft.VnfManager vnf" }
        ,"microsoft.voiceservices/communicationsgateways": { "SingularDisplayName": "Communications Gateway" }
        ,"microsoft.voiceservices/communicationsgateways/testlines": { "SingularDisplayName": "Communications Gateway Test Line" }
        ,"microsoft.vsonline/accounts": { "SingularDisplayName": "Microsoft.VSOnline account" }
        ,"microsoft.vsonline/plans": { "SingularDisplayName": "Visual Studio Online Plan" }
        ,"microsoft.web/certificates": { "SingularDisplayName": "Microsoft.Web certificate" }
        ,"microsoft.web/connectiongateways": { "SingularDisplayName": "App Service on-premises data gateway" }
        ,"microsoft.web/connections": { "SingularDisplayName": "App Service API connection" }
        ,"microsoft.web/containerapps": { "SingularDisplayName": "Microsoft.Web container app" }
        ,"microsoft.web/containerapps/revisions": { "SingularDisplayName": "Microsoft.Web container apps revision" }
        ,"microsoft.web/customapis": { "SingularDisplayName": "Logic apps custom connector" }
        ,"microsoft.web/deletedsites": { "SingularDisplayName": "Microsoft.Web deleted site" }
        ,"microsoft.web/hostingenvironments": { "SingularDisplayName": "App Service Environment" }
        ,"microsoft.web/ishostingenvironmentnameavailable": { "SingularDisplayName": "Microsoft.Web ishostingenvironmentnameavailable" }
        ,"microsoft.web/kubeenvironments": { "SingularDisplayName": "App Service Kubernetes Environment" }
        ,"microsoft.web/publishingusers": { "SingularDisplayName": "Microsoft.Web publishing user" }
        ,"microsoft.web/serverfarms": { "SingularDisplayName": "App Service plan" }
        ,"microsoft.web/sites": { "SingularDisplayName": "App Service web app" }
        ,"microsoft.web/sites/slots": { "SingularDisplayName": "App Service deployment slot" }
        ,"microsoft.web/sourcecontrols": { "SingularDisplayName": "Microsoft.Web sourcecontrol" }
        ,"microsoft.web/staticsites": { "SingularDisplayName": "Static Web App" }
    })[tolower(id)]
}
