# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

<#
    .SYNOPSIS
    Generates the query-catalog.md knowledge file from KQL source files.

    .DESCRIPTION
    Reads all .kql files from src/queries/catalog, includes the full file content
    (comments and query), replaces Costs() with Costs_v1_2(), and writes a combined
    markdown file to the Copilot Studio knowledge folder.

    .EXAMPLE
    ./Build-QueryCatalog

    Generates query-catalog.md from all KQL files in the catalog.

    .LINK
    https://github.com/microsoft/finops-toolkit/blob/dev/src/scripts/README.md
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$queriesDir = "$PSScriptRoot/../queries/catalog"
$outputFile = "$PSScriptRoot/../templates/finops-hub-copilot-studio/knowledge/query-catalog.md"

# Queries that require cross-database references or special setup
$excludeFiles = @('costs-enriched-base')

if (-not (Test-Path $queriesDir))
{
    Write-Error "Queries directory not found: $queriesDir"
    return
}

Write-Host "Building query catalog..."

# Start with the header
$output = @"
<!-- This file is auto-generated by Build-QueryCatalog.ps1. Do not edit manually. -->

# FinOps Hub KQL query catalog

This document contains ready-to-use KQL query patterns for common FinOps analysis tasks. Use these as templates when answering cost questions. Always execute queries via the Kusto MCP tool — never answer from this document alone.

All queries use the ``Costs_v1_2()`` function unless noted otherwise.
"@

# Process each KQL file
$kqlFiles = Get-ChildItem "$queriesDir/*.kql" -ErrorAction SilentlyContinue `
    | Where-Object { $excludeFiles -notcontains $_.BaseName } `
    | Sort-Object Name
if (-not $kqlFiles -or $kqlFiles.Count -eq 0)
{
    Write-Warning "No .kql files found in $queriesDir"
    return
}
Write-Verbose "Found $($kqlFiles.Count) KQL file(s) to process"

foreach ($file in $kqlFiles)
{
    Write-Verbose "  Processing: $($file.Name)"
    $content = (Get-Content $file.FullName -Raw).TrimEnd()

    # Extract the title from the filename (e.g., "monthly-cost-trend" -> "Monthly cost trend")
    $title = ($file.BaseName -replace '-', ' ')
    $title = $title.Substring(0, 1).ToUpper() + $title.Substring(1)

    # Replace Costs() with Costs_v1_2()
    $content = $content -replace '\bCosts\(\)', 'Costs_v1_2()'

    # Guard against triple backticks in KQL content breaking the markdown code fence
    if ($content -match '``````')
    {
        Write-Warning "Skipping $($file.Name): contains triple backticks that would break markdown"
        continue
    }

    # Build the section
    $output += "`n`n## $title`n`n``````kusto`n$content`n``````"
}

# Write output
$outputDir = Split-Path $outputFile -Parent
if (-not (Test-Path $outputDir))
{
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$output += "`n"
$output | Out-File $outputFile -Encoding utf8 -NoNewline
Write-Host "  Generated: $outputFile"
Write-Host ""
