# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

<#
    .SYNOPSIS
    Generates PowerShell command reference docs for the Microsoft Learn documentation site.

    .DESCRIPTION
    The Build-Documentation command generates one reference page per public PowerShell command
    under docs-mslearn/toolkit/powershell/{category}/{command-name-lowercase}.md by parsing each
    command's comment-based help. It imports the FinOpsToolkit module, uses Get-Help -Full to read
    parameters, examples, and syntax, and regex-scans the raw source for ".OUTPUTS" and
    ".PARAMETERSET" markers, since PowerShell's native help XML does not expose return-value
    schemas or friendly parameter set names.

    Only the command pages are generated. Category index pages (for example,
    cost/cost-management-commands.md) and the top-level powershell-commands.md are hand-maintained
    and are not regenerated by this script.

    .PARAMETER Command
    Optional. PowerShell command to generate documentation for. Default = * (all).

    .PARAMETER NewDate
    Optional. Date to stamp in ms.date for brand-new doc pages, in MM/dd/yyyy format. Default = today.
    Existing pages keep their current ms.date; a CI workflow updates it when body content changes.

    .EXAMPLE
    ./Build-Documentation

    ### Generate documentation
    Generates documentation for all public commands.

    .EXAMPLE
    ./Build-Documentation -Command Get-FinOpsHub

    ### Generate documentation for a single command
    Generates documentation for the Get-FinOpsHub command only.

    .LINK
    https://github.com/microsoft/finops-toolkit/blob/dev/src/scripts/README.md#-build-documentation
#>
[CmdletBinding()]
param
(
    [string]
    $Command = '*',

    [string]
    $NewDate = (Get-Date -Format 'MM/dd/yyyy')
)

$ErrorActionPreference = 'Stop'

$srcDir = "$PSScriptRoot/../powershell"
$docsDir = "$PSScriptRoot/../../docs-mslearn/toolkit/powershell"

# Map a command noun to its docs-mslearn category folder and "Give feedback" featureName prefix.
# Mirrors the grouping used in powershell-commands.md and the individual category index pages.
function Get-CommandCategory([string] $CommandName)
{
    $noun = $CommandName -replace '^[A-Za-z]+-FinOps', ''

    if ($noun -eq 'ServicePrincipal' -or $noun.StartsWith('Cost'))
    {
        return @{ Folder = 'cost'; FeaturePrefix = 'CostManagement' }
    }
    elseif ($noun.StartsWith('Hub'))
    {
        return @{ Folder = 'hubs'; FeaturePrefix = 'Hubs' }
    }
    elseif (@('PricingUnit', 'Region', 'ResourceType', 'Service') -contains $noun)
    {
        return @{ Folder = 'data'; FeaturePrefix = 'OpenData' }
    }
    else
    {
        return @{ Folder = 'toolkit'; FeaturePrefix = 'Toolkit' }
    }
}

# Renders a GitHub-flavored markdown table with prettier-style column padding so re-generating
# unchanged content doesn't produce formatting-only diffs.
function Format-MarkdownTable([string[]] $Headers, [string[][]] $Rows)
{
    $widths = @()
    for ($i = 0; $i -lt $Headers.Count; $i++)
    {
        $cellLengths = @($Rows | ForEach-Object { $_[$i].Length })
        $widths += [Math]::Max($Headers[$i].Length, ((@($cellLengths) + 0) | Measure-Object -Maximum).Maximum)
    }

    $headerCells = @()
    for ($i = 0; $i -lt $Headers.Count; $i++) { $headerCells += $Headers[$i].PadRight($widths[$i]) }

    $lines = @()
    $lines += '| ' + ($headerCells -join ' | ') + ' |'
    $lines += '| ' + ((0..($Headers.Count - 1) | ForEach-Object { '-' * $widths[$_] }) -join ' | ') + ' |'
    foreach ($row in $Rows)
    {
        $lines += '| ' + ((0..($Headers.Count - 1) | ForEach-Object { $row[$_].PadRight($widths[$_]) }) -join ' | ') + ' |'
    }
    return $lines
}

# Import the module so Get-Help resolves the same way it would for an installed module (importing
# the module -- rather than dot-sourcing a single file -- picks up private function dependencies).
Import-Module "$srcDir/FinOpsToolkit.psm1" -Force -ErrorAction Stop

# Map .NET type names from Get-Help to the PowerShell type aliases used in the hand-written docs
# (for example, "String" -> "string", "Int32" -> "int").
$typeAliasMap = @{
    'String'   = 'string'
    'Int32'    = 'int'
    'Int64'    = 'long'
    'Boolean'  = 'bool'
    'Double'   = 'double'
    'Object'   = 'object'
    'Hashtable' = 'hashtable'
    'SwitchParameter' = 'switch'
    'DateTime' = 'datetime'
}
function Get-FriendlyTypeName([string] $TypeName)
{
    # Get-Help renders Nullable[T] as "Nullable`1" -- unwrap to the friendly name of T.
    if ($TypeName -match '^Nullable``?1$') { $TypeName = 'Boolean' }
    if ($typeAliasMap.ContainsKey($TypeName)) { return $typeAliasMap[$TypeName] }
    return $TypeName
}

Write-Host 'Generating PowerShell command documentation...'

Get-ChildItem -Path "$srcDir/Public/$Command.ps1" | ForEach-Object {
    $file = $_
    $commandName = $file.BaseName

    Write-Host "- $commandName"

    $category = Get-CommandCategory -CommandName $commandName
    $folder = $category.Folder
    $featurePrefix = $category.FeaturePrefix
    $outFile = "$docsDir/$folder/$($commandName.ToLowerInvariant()).md"
    $isNewFile = -not (Test-Path $outFile)

    $help = Get-Help $commandName -Full
    $rawText = Get-Content $file.FullName
    $rawTextJoined = $rawText -join "`n"

    # Collect file contents via string builder for perf
    $sb = [System.Text.StringBuilder]::new()
    function append([string] $Text)
    {
        [void]$sb.AppendLine($Text)
    }

    # ------------------------------------------------------------------
    # Front matter
    # ------------------------------------------------------------------
    if ($isNewFile)
    {
        $msDate = $NewDate
        $author = 'flanakin'
        $msAuthor = 'micflan'
        $msReviewer = 'micflan'
    }
    else
    {
        $existing = Get-Content $outFile -Raw
        $msDate = if ($existing -match '(?m)^ms\.date:\s*(.+)$') { $Matches[1].Trim() } else { $NewDate }
        $author = if ($existing -match '(?m)^author:\s*(.+)$') { $Matches[1].Trim() } else { 'flanakin' }
        $msAuthor = if ($existing -match '(?m)^ms\.author:\s*(.+)$') { $Matches[1].Trim() } else { 'micflan' }
        $msReviewer = if ($existing -match '(?m)^ms\.reviewer:\s*(.+)$') { $Matches[1].Trim() } else { $msAuthor }
    }

    $synopsis = ($help.Synopsis | Out-String).Trim().TrimEnd('.')
    # Convert the synopsis's leading 3rd-person verb to imperative for the meta description,
    # e.g. "Gets a list of..." -> "Get a list of...".
    $synopsisImperative = [regex]::Replace($synopsis, '^(\w+?)s\b', '$1')

    # The meta description is often a hand-curated paraphrase rather than a mechanical function of
    # the synopsis, so preserve it verbatim from the existing file. New pages get a synthesized
    # description built from the synopsis.
    if (-not $isNewFile -and $existing -match '(?m)^description:\s*(.+)$')
    {
        $description = $Matches[1].Trim()
    }
    else
    {
        $description = "$synopsisImperative using the $commandName command in the FinOpsToolkit module."
    }

    append '---'
    append "title: $commandName command"
    append "description: $description"
    append "author: $author"
    append "ms.author: $msAuthor"
    append "ms.date: $msDate"
    append 'ms.topic: reference'
    append 'ms.service: finops'
    append 'ms.subservice: finops-toolkit'
    append "ms.reviewer: $msReviewer"
    append "#customer intent: As a FinOps user, I want to understand how to use the $commandName command in the FinOpsToolkit module."
    append '---'
    append ''
    append "# $commandName command"
    append ''

    # ------------------------------------------------------------------
    # Description + API version note
    # ------------------------------------------------------------------
    $descText = (($help.Description.Text | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join "`n`n").Trim()

    # Split off a leading "This command was/has been tested with the following API versions"
    # paragraph (including its bullet list) so it renders as its own paragraph, matching the
    # existing hand-written docs.
    $apiVersionBlock = $null
    $bodyDescText = $descText
    if ($descText -match '(?ms)^(This command (?:was|has been) tested with the following API versions:\r?\n(?:- .+\r?\n?)+)')
    {
        $apiVersionBlock = $Matches[1].Trim()
        $apiVersionBlock = $apiVersionBlock -replace 'has been tested', 'was tested'
        # Insert a blank line between the header and the bullet list to match the hand-written docs.
        $apiVersionBlock = $apiVersionBlock -replace '(API versions:)\r?\n', "`$1`n`n"
        $bodyDescText = $descText.Replace($Matches[1], '').Trim()
    }

    if (-not $bodyDescText)
    {
        $synopsisLowerFirst = [regex]::Replace($synopsisImperative, '^[A-Z]', { param($m) $m.Value.ToLowerInvariant() })
        $bodyDescText = "The **$commandName** command $synopsisLowerFirst."
    }
    elseif ($bodyDescText -notmatch [regex]::Escape("**$commandName**"))
    {
        $lines = $bodyDescText -split "`n"
        # Bold only the first standalone mention of the command name, in the opening sentence.
        $pattern = [regex]"(?<!\*\*)\b$([regex]::Escape($commandName))\b(?!\*\*)"
        $firstMatch = $pattern.Match($lines[0])
        if ($firstMatch.Success)
        {
            $lines[0] = $lines[0].Substring(0, $firstMatch.Index) + "**$commandName**" + $lines[0].Substring($firstMatch.Index + $firstMatch.Length)
        }
        $bodyDescText = ($lines -join "`n")
    }

    append $bodyDescText
    append ''

    if ($apiVersionBlock)
    {
        append $apiVersionBlock
        append ''
    }
    elseif (-not $isNewFile -and $existing -match '(?ms)^#\s.*?\r?\n(.*?)## Syntax' -and $Matches[1] -match '(?m)^(> \[!NOTE\]\r?\n(?:> .*\r?\n?)+)')
    {
        # A "> [!NOTE]" callout directly under the intro description (no API-version block in
        # between, and before the Syntax section) is hand-written and can't be derived from
        # source -- preserve it verbatim.
        append $Matches[1].TrimEnd("`r", "`n")
        append ''
    }

    append '<br>'
    append ''

    # ------------------------------------------------------------------
    # Syntax
    # ------------------------------------------------------------------
    append '## Syntax'
    append ''

    $paramSets = $rawText | Select-String -Pattern '#\s*\.PARAMETERSET\s+(.*)$' | ForEach-Object { $_.Matches.Groups[1].Value.Trim() }
    $hasConfirm = ($help.Parameters.Parameter | Where-Object { $_.Name -eq 'Confirm' -and (($_.Description.Text -join '')).Length -gt 0 }).Count -gt 0
    $hasCmdletBinding = $rawTextJoined -match '\[CmdletBinding\('

    $syntaxItems = @($help.Syntax.SyntaxItem)
    $paramSetIndex = 0
    foreach ($syntaxItem in $syntaxItems)
    {
        append '```powershell'
        if ($syntaxItems.Count -gt 1 -and $paramSets.Length -gt $paramSetIndex)
        {
            append "# $($paramSets[$paramSetIndex])"
        }
        $paramSetIndex++

        $paramLines = @()
        $syntaxItem.Parameter | Where-Object { $_.Name -ne 'Confirm' -or $hasConfirm } | ForEach-Object {
            $p = $_
            $piece = ''
            if ($p.Required -ne $true) { $piece += '[' }
            if ($p.Position -ne 'named') { $piece += '[' }
            $piece += "‑$($p.Name)"
            if ($p.Position -ne 'named') { $piece += ']' }
            if ($p.ParameterValue) { $piece += " <$(Get-FriendlyTypeName $p.ParameterValue)>" }
            if ($p.Required -ne $true) { $piece += ']' }
            $paramLines += $piece
        }
        if ($hasCmdletBinding)
        {
            $paramLines += '[<CommonParameters>]'
        }

        if ($paramLines.Count -gt 0)
        {
            append "$commandName ``"
            for ($i = 0; $i -lt $paramLines.Count; $i++)
            {
                $suffix = if ($i -lt $paramLines.Count - 1) { ' `' } else { '' }
                append "    $($paramLines[$i])$suffix"
            }
        }
        else
        {
            append $commandName
        }
        append '```'
        append ''
    }
    append '<br>'
    append ''

    # ------------------------------------------------------------------
    # Parameters
    # ------------------------------------------------------------------
    $paramRows = @()
    $help.Parameters.Parameter | Where-Object { $_.Name -ne 'Confirm' -or $hasConfirm } | ForEach-Object {
        $p = $_
        $desc = (($p.Description.Text | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join ' ').Trim()
        if ($p.Name -eq 'WhatIf' -and [string]::IsNullOrWhiteSpace($desc))
        {
            $desc = 'Optional. Shows what would happen if the command runs without actually running it.'
        }
        # A multi-line PARAMETER description (e.g. a bullet list of scope ID formats) must not
        # contain a raw newline inside a markdown table cell -- join lines with <br> instead.
        $desc = ($desc -split "`r?`n" | ForEach-Object { $_.Trim() }) -join '<br>'
        # Escape a standalone "*" used as a wildcard-default placeholder (e.g. "Default = * (all)")
        # so markdown doesn't parse it as emphasis -- but leave a "*" fused inside a word/token
        # (e.g. "*_raw", "*_final_v*") alone, since that's a glob fragment, not emphasis markup.
        $desc = [regex]::Replace($desc, '(?<![\\\w])\*(?![\w])', '\*')
        $paramRows += , @("``‑$($p.Name)``", $desc)
    }

    append '## Parameters'
    append ''
    (Format-MarkdownTable -Headers @('Name', 'Description') -Rows $paramRows) | ForEach-Object { append $_ }
    append ''

    # A "> [!NOTE]" callout directly under the parameter table (e.g. a SKU-availability caveat)
    # is hand-written and can't be derived from source -- preserve it verbatim when present.
    if (-not $isNewFile -and $existing -match '(?m)^\| `‑[^\r\n]+\r?\n\r?\n(> \[!NOTE\]\r?\n(?:> .*\r?\n?)+)')
    {
        append $Matches[1].TrimEnd("`r", "`n")
        append ''
    }

    append '<br>'
    append ''

    # ------------------------------------------------------------------
    # Return value (parsed from ".OUTPUTS" markers in the raw source)
    # ------------------------------------------------------------------
    $outputBlocks = @()
    $currentPrefix = $null
    $currentType = $null
    $currentLines = @()
    foreach ($line in $rawText)
    {
        if ($line -match '^(\s*#\s*)\.OUTPUTS\s+(\S+)\s*$')
        {
            if ($currentType) { $outputBlocks += @{ Type = $currentType; Lines = $currentLines } }
            $currentPrefix = $Matches[1]
            $currentType = $Matches[2]
            $currentLines = @()
        }
        elseif ($currentPrefix -and $line -match '^\s*#\s?(\|.*\|)\s*$')
        {
            $currentLines += $Matches[1]
        }
        elseif ($currentType -and $currentLines.Count -gt 0)
        {
            $outputBlocks += @{ Type = $currentType; Lines = $currentLines }
            $currentPrefix = $null
            $currentType = $null
            $currentLines = @()
        }
    }
    if ($currentType -and $currentLines.Count -gt 0)
    {
        $outputBlocks += @{ Type = $currentType; Lines = $currentLines }
    }

    # Root type first: a block is "nested" if some other block's rows reference its type name
    # (for example, FinOpsCostExport lists a RunHistory column of type FinOpsCostExportRunHistory[]).
    # Nested types are documented after the root type they belong to, regardless of source order.
    if ($outputBlocks.Count -gt 1)
    {
        $allLines = ($outputBlocks | ForEach-Object { $_.Lines }) -join "`n"
        $outputBlocks = @($outputBlocks | Sort-Object -Property @{
                Expression = { if ($allLines -match [regex]::Escape($_.Type) + '\[\]') { 1 } else { 0 } }
            }, @{ Expression = { $outputBlocks.IndexOf($_) } })
    }

    if ($outputBlocks.Count -gt 0)
    {
        append '## Return value'
        append ''
        foreach ($block in $outputBlocks)
        {
            append "### $($block.Type) object"
            append ''
            $block.Lines | ForEach-Object { append $_ }
            append ''
        }
        append '<br>'
        append ''
    }

    # ------------------------------------------------------------------
    # Examples
    # ------------------------------------------------------------------
    append '## Examples'
    append ''

    # The one-line intro under "## Examples" ("The following example(s) demonstrate...") is a
    # hand-written paraphrase of what the examples cover, not mechanically derived from source.
    # Preserve it verbatim from the existing file; new pages get a generic intro line.
    if (-not $isNewFile -and $existing -match '(?m)^(The following examples? demonstrates? .+)$')
    {
        append $Matches[1].Trim()
        append ''
    }

    $help.Examples.Example | ForEach-Object {
        $example = $_
        $remarksText = (($example.Remarks.Text | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }) -join "`n").Trim()
        $descText = $remarksText
        $title = $null

        if ($remarksText -match '(?s)^###\s+(.+?)\r?\n(.*)$')
        {
            $title = "### $($Matches[1].Trim())"
            $descText = $Matches[2].Trim()
        }
        else
        {
            $fallback = ($example.Title -replace '-+', '').Trim() -replace '^EXAMPLE\s*(\d*)\s*', 'Example $1'
            $title = "### $($fallback.Trim())"
        }

        append $title
        append ''
        append '```powershell'
        append ($example.Code.Trim())
        append '```'
        append ''
        if ($descText)
        {
            append $descText
            append ''
        }
    }
    append '<br>'
    append ''

    # ------------------------------------------------------------------
    # Give feedback + related content
    # ------------------------------------------------------------------
    append '## Give feedback'
    append ''
    append "Let us know how we're doing with a quick review. We use these reviews to improve and expand FinOps tools and resources."
    append ''
    # The featureName suffix used in the feedback survey link is a hand-picked short label per
    # command (for example, "Hubs.InitDeployment", not "Hubs.InitializeHubDeployment"), so it
    # can't be reliably derived from the command name. Preserve it from the existing file; only
    # synthesize one for brand-new pages that have never had a featureName before.
    if (-not $isNewFile -and $existing -match 'featureName/([A-Za-z.]+)\)')
    {
        $featureName = $Matches[1]
    }
    else
    {
        $noun = $commandName -replace '^[A-Za-z]+-FinOps', ''
        $verb = ($commandName -split '-')[0]
        $featureName = "$featurePrefix.$verb$noun"
    }
    append '<!-- prettier-ignore-start -->'
    append '> [!div class="nextstepaction"]'
    append "> [Give feedback](https://portal.azure.com/#view/HubsExtension/InProductFeedbackBlade/extensionName/FinOpsToolkit/cesQuestion/How%20easy%20or%20hard%20is%20it%20to%20use%20the%20FinOps%20toolkit%20PowerShell%20module%3F/cvaQuestion/How%20valuable%20are%20the%20FinOps%20toolkit%20PowerShell%20module%3F/surveyId/FTK/bladeName/PowerShell/featureName/$featureName)"
    append '<!-- prettier-ignore-end -->'
    append ''
    append "If you're looking for something specific, vote for an existing or create a new idea. Share ideas with others to get more votes. We focus on ideas with the most votes."
    append ''
    append '<!-- prettier-ignore-start -->'
    append '> [!div class="nextstepaction"]'
    append '> [Vote on or suggest ideas](https://github.com/microsoft/finops-toolkit/issues?q=is%3Aissue%20is%3Aopen%20label%3A%22Tool%3A%20PowerShell%22%20sort%3A"reactions-%2B1-desc")'
    append '<!-- prettier-ignore-end -->'
    append ''
    append '<br>'
    append ''
    # "Related content" (products vs. solutions, and which links are included) is hand-curated
    # per command and can't be derived from the source .ps1. Preserve it verbatim from the
    # existing file; new pages get the standard solutions-only boilerplate.
    if (-not $isNewFile -and $existing -match '(?s)(## Related content\r?\n.*)$')
    {
        $relatedContent = $Matches[1].TrimEnd("`r", "`n")
        $relatedContent -split "`r?`n" | ForEach-Object { append $_ }
    }
    else
    {
        append '## Related content'
        append ''
        append 'Related solutions:'
        append ''
        append '- [FinOps toolkit Power BI reports](../../power-bi/reports.md)'
        append '- [FinOps hubs](../../hubs/finops-hubs-overview.md)'
        append ''
        append '<br>'
    }

    $content = $sb.ToString().TrimEnd("`r", "`n") + "`n"
    [System.IO.File]::WriteAllText($outFile, $content, [System.Text.UTF8Encoding]::new($false))
    $sb.Clear() | Out-Null
}

Write-Host 'Done.'
