// Query: Analyzes reservation usage and savings by month.
// Query ID: 377e3693-0738-45d7-97d9-4b6e71ec5b36
// Description: Analyzes reservation usage and savings by month.
// Used Variables: `CostsByMonth`

CostsByMonth
| summarize
    ReservationUsage = sum(ReservationUsage),
    ReservationSavings = sum(ReservationSavings)
    by BillingPeriodStart = startofmonth(BillingPeriodStart)
| order by BillingPeriodStart asc
