#!/usr/bin/env python3
"""Build a deck-outline.md table from scenes.json.

The output format matches the 7-cell table that release-deck/build.py expects,
so this skill's output can be consumed by either:
  - This skill's own build_pptx.py
  - The hand-tuned release-deck/build.py

7 cells per row: num | stage | title | content | notes | layout | screens

- num: scene id (1, 2, 3, ...)
- stage: doc slug (used for the chyron / cluster label)
- title: scene heading
- content: scene's content bullets (HTML <br/>-separated)
- notes: speaker notes = the normalized TTS transcript (HTML <br/>-separated)
- layout: 'kind=BULLETS' / 'kind=TITLE' / 'kind=TABLE' / 'kind=CODE'
- screens: 'None' (this skill doesn't auto-attach assets — that's a downstream concern)

The notes cell is THE SOURCE OF TRUTH for narration. It carries the same content
as transcripts/scene_NN.txt with <br/> instead of <break> tags so it renders in
PowerPoint speaker notes.
"""
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))
from normalize_text import normalize  # type: ignore


def to_html_br(text: str) -> str:
    """Convert paragraph breaks to <br/><br/> and line breaks within a paragraph to <br/>.

    PowerPoint speaker notes treat <br/> as a soft break; release-deck/build.py
    splits on '<br/>' to populate paragraphs.
    """
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    out = []
    for p in paragraphs:
        # Within a paragraph, fold soft newlines to spaces
        p = re.sub(r"\n+", " ", p).strip()
        out.append(p)
    return "<br/><br/>".join(out)


def extract_content_bullets(scene: dict) -> str:
    """Extract bullet-list content from the scene's raw markdown for the slide body.

    Returns '<br/>'-separated bullet items (without the '- ' prefix), or a single
    summary sentence if the scene has no bullets.
    """
    raw = scene["raw_markdown"]
    # Find bullet lines
    bullet_lines = re.findall(r"^\s*-\s+(.+)$", raw, flags=re.MULTILINE)
    if bullet_lines:
        # Clean each bullet: strip markdown link syntax, bold, italic, breaks
        cleaned = []
        for line in bullet_lines:
            line = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", line)
            line = re.sub(r"\*\*([^*]+)\*\*", r"\1", line)
            line = re.sub(r"\*([^*]+)\*", r"\1", line)
            line = re.sub(r"_([^_\n]+)_", r"\1", line)
            line = re.sub(r"<br\s*/?>", " — ", line)
            line = re.sub(r"`([^`]+)`", r"\1", line)
            line = re.sub(r"\s+", " ", line).strip()
            cleaned.append(f"\u2022 {line}")
        return "<br/>".join(cleaned)
    # No bullets — use first sentence of cleaned text as the content
    text = scene["text"].strip()
    first_sentence = re.split(r"(?<=[.!?])\s+", text, maxsplit=1)[0] if text else ""
    return f"\u2022 {first_sentence}" if first_sentence else "(visual only)"


def build_outline(scenes_data: dict, doc_slug: str) -> str:
    """Render the deck-outline.md content as a markdown document with a 7-cell table."""
    h1 = scenes_data["h1"]
    lines = []
    lines.append(f"# {h1} — narrated deck outline")
    lines.append("")
    lines.append(
        f"Generated by `narrated-deck` skill from `{scenes_data['doc_path']}`. "
        "Edit this table by hand to override scene titles, content, layouts, or assets, "
        "then rebuild slides with `build_pptx.py --outline <this-file>`."
    )
    lines.append("")
    lines.append("| num | stage | title | content | notes | layout | screens |")
    lines.append("|---|---|---|---|---|---|---|")
    for scene in scenes_data["scenes"]:
        scene_id = scene["id"]
        heading = scene["heading"]
        if heading == "Intro":
            heading = h1  # use the doc title as the title slide heading
        content = extract_content_bullets(scene)
        # Notes = normalized TTS narration with <br/> formatting
        if scene.get("narration_only", False):
            notes = "(slide-only \u2014 no narration)"
        else:
            normalized = normalize(scene["text"], with_breaks=False)
            notes = to_html_br(normalized)
        layout = f"kind={scene['layout']}"
        screens = "None"
        # Escape any literal pipes in cell content (rare but possible in code identifiers)
        def esc(s: str) -> str:
            return s.replace("|", "\\|")
        cells = [
            str(scene_id),
            doc_slug,
            esc(heading),
            esc(content),
            esc(notes),
            esc(layout),
            esc(screens),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def main():
    args = sys.argv[1:]
    if "--out" not in args:
        print("Usage: build_outline.py --out <path> --slug <doc-slug> [--scenes <path>]", file=sys.stderr)
        sys.exit(2)
    out_path = Path(args[args.index("--out") + 1])
    doc_slug = args[args.index("--slug") + 1] if "--slug" in args else "doc"
    if "--scenes" in args:
        scenes_data = json.loads(Path(args[args.index("--scenes") + 1]).read_text())
    else:
        scenes_data = json.loads(sys.stdin.read())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_outline(scenes_data, doc_slug), encoding="utf-8")
    print(out_path)


if __name__ == "__main__":
    main()
