/// Instance size flexibility data from FinOps toolkit open data, sourced from the Azure Reservations Catalogs API. Loaded from the latest toolkit release assets.
table InstanceSizeFlexibility
	lineageTag: 04a435c4-9138-4c1f-ad59-dd939cd8e139

	column x_CommitmentDiscountFlexGroup
		dataType: string
		lineageTag: 57d1a022-b990-443e-ac76-39099da91d22
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountFlexGroup

		annotation SummarizationSetBy = Automatic

	column x_SkuType
		dataType: string
		lineageTag: 528c532f-6dfe-4e64-82d0-577334078041
		summarizeBy: none
		sourceColumn: x_SkuType

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountFlexRatio
		dataType: double
		lineageTag: 8b5d50bb-801f-4161-ad86-25d089cf77fb
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountFlexRatio

		annotation SummarizationSetBy = Automatic

	partition InstanceSizeFlexibility = m
		mode: import
		queryGroup: 'Open data'
		source =
				let
				    Source = Csv.Document(Web.Contents("https://github.com/microsoft/finops-toolkit/releases/latest/download/InstanceSizeFlexibility.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstanceSizeFlexibilityGroup", type text}, {"ArmSkuName", type text}, {"Ratio", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ArmSkuName", "x_SkuType"}, {"InstanceSizeFlexibilityGroup", "x_CommitmentDiscountFlexGroup"}, {"Ratio", "x_CommitmentDiscountFlexRatio"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

