table PolicyDefinitions
	lineageTag: f9b1ee3e-756a-4801-a1b7-8891089488b5

	column id
		dataType: string
		lineageTag: 46cb1c87-971b-4b73-8539-c8c078bd18ca
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: bf4ef11f-bed9-4e29-8e43-f6c38a5d03f6
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: bf32972c-95e7-45c7-84d9-f810d7a7dee2
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: bdfe912b-9357-4694-8b47-27bb9e00233c
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: b759ef82-769a-4d22-ba72-7026308a0253
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 87086657-6a1a-46af-a139-7fe17e53d65c
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: b0cdf0de-447d-4a23-bc84-e8565ed78113
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 236f6213-3b9c-4295-b96a-4753ad7b74cc
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 12d3c9ac-6782-478e-8f62-54320e884cb4
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: b55b303b-7744-42c6-885a-59746ca3ca8e
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 8924364c-a942-45c9-a08c-e76fbd218fdd
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.displayName'
		dataType: string
		lineageTag: e700b640-6123-4a99-8676-6aaea51eb7fd
		summarizeBy: none
		sourceColumn: properties.displayName

		annotation SummarizationSetBy = Automatic

	column 'properties.policyType'
		dataType: string
		lineageTag: bc7778b3-3623-4ade-99cd-31be98763e9a
		summarizeBy: none
		sourceColumn: properties.policyType

		annotation SummarizationSetBy = Automatic

	column 'properties.description'
		dataType: string
		lineageTag: 89f20b51-f79b-4245-aaea-ff9f63034a9b
		summarizeBy: none
		sourceColumn: properties.description

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata'
		dataType: string
		lineageTag: f7e10fc6-e600-48ba-a2ff-f4a59a7c6834
		summarizeBy: none
		sourceColumn: properties.metadata

		annotation SummarizationSetBy = Automatic

	column 'properties.version'
		dataType: string
		lineageTag: f9d87ff0-0edb-40ed-bbb4-111e671a3f9d
		summarizeBy: none
		sourceColumn: properties.version

		annotation SummarizationSetBy = Automatic

	column 'properties.parameters'
		dataType: string
		lineageTag: 2e39c73b-bf6f-42ac-88a1-5c07d64b669c
		summarizeBy: none
		sourceColumn: properties.parameters

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitions'
		dataType: string
		lineageTag: 7f2d1054-9685-4e15-be8e-4e0edd0ccd79
		summarizeBy: none
		sourceColumn: properties.policyDefinitions

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionGroups'
		dataType: string
		lineageTag: 0431ef47-bb3a-42d2-8335-8fa146c48589
		summarizeBy: none
		sourceColumn: properties.policyDefinitionGroups

		annotation SummarizationSetBy = Automatic

	column 'properties.versions'
		dataType: string
		lineageTag: 40ce3f95-5acf-4f83-acfe-da2b3c9a34e9
		summarizeBy: none
		sourceColumn: properties.versions

		annotation SummarizationSetBy = Automatic

	column 'properties.oldVersions'
		dataType: string
		lineageTag: 9ece9465-e2b0-4ef3-96ce-9aec3473e18b
		summarizeBy: none
		sourceColumn: properties.oldVersions

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 2b53eb0c-7c26-41a0-acc5-e22b57b77596
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 387cf40a-1459-48d6-a78f-fa93ecc1d6df
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 3b474b78-99a0-4205-9fce-e1064e998bc8
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: c07117a5-6915-4a7c-982b-45e76a9be26d
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition PolicyDefinitions = m
		mode: import
		queryGroup: 'Resource Graph'
		source =
				let
				  Source = AzureResourceGraph.Query(
				    "policyResources
				    | where type =~'Microsoft.Authorization/PolicySetDefinitions' or type =~'Microsoft.Authorization/PolicyDefinitions'
				  " & ftk_DemoFilter(), "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"displayName", "policyType", "description", "metadata", "version", "parameters", "policyDefinitions", "policyDefinitionGroups", "versions", "oldVersions"}, {"properties.displayName", "properties.policyType", "properties.description", "properties.metadata", "properties.version", "properties.parameters", "properties.policyDefinitions", "properties.policyDefinitionGroups", "properties.versions", "properties.oldVersions"})
				in
				  #"Expanded properties"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

