table PricingUnits
	lineageTag: d66ce6f9-eeff-48b4-8b10-825ead39a54d

	column UnitOfMeasure
		dataType: string
		lineageTag: 8d4d2d26-9798-492c-b612-ac08db8a2dcb
		summarizeBy: none
		sourceColumn: UnitOfMeasure

		annotation SummarizationSetBy = Automatic

	column PricingBlockSize
		dataType: double
		lineageTag: d723d459-dd23-42bd-8fea-0a25e63f5649
		summarizeBy: sum
		sourceColumn: PricingBlockSize

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DistinctUnits
		dataType: string
		lineageTag: 3eeebc9e-5288-49d8-a217-81eb4263623a
		summarizeBy: none
		sourceColumn: DistinctUnits

		annotation SummarizationSetBy = Automatic

	partition PricingUnits = m
		mode: import
		queryGroup: 'Open data'
		source =
				let
				  Source = Csv.Document(Web.Contents("https://github.com/microsoft/finops-toolkit/releases/latest/download/PricingUnits.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  Remove = Table.RemoveColumns(PromoteHeaders, {"AccountTypes"}),
				  Types = Table.TransformColumnTypes(Remove, {
				    {"UnitOfMeasure",    type text},
				    {"PricingBlockSize", type number},
				    {"DistinctUnits",    type text}
				  }),
				  RemoveBlanks = Table.SelectRows(Types, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				  RemoveBlanks

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

