table TagCosts
	lineageTag: 0742a7c6-dcde-4bf1-8d77-b7e436e02f7e

	column BilledCost
		dataType: double
		sourceProviderType: decimal
		lineageTag: 6f987797-b607-4765-ab26-8798db1369a4
		summarizeBy: sum
		sourceColumn: BilledCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BillingCurrency
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 40299619-ac8b-4797-85be-8ceec559e790
		summarizeBy: none
		sourceColumn: BillingCurrency

		annotation SummarizationSetBy = Automatic

	column ChargePeriodEnd
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: fbf91a3f-bfeb-49aa-86bd-75845f91c608
		summarizeBy: none
		sourceColumn: ChargePeriodEnd

		annotation SummarizationSetBy = Automatic

	column ChargePeriodStart
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 0c315936-76be-44d8-a4da-60b220583caa
		summarizeBy: none
		sourceColumn: ChargePeriodStart

		annotation SummarizationSetBy = Automatic

	column ContractedCost
		dataType: double
		sourceProviderType: decimal
		lineageTag: b795125b-b6d7-456b-83b4-bcbbb2181796
		summarizeBy: sum
		sourceColumn: ContractedCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveCost
		dataType: double
		sourceProviderType: decimal
		lineageTag: 632a582d-0967-474f-b50e-f8fca5f13021
		summarizeBy: sum
		sourceColumn: EffectiveCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListCost
		dataType: double
		sourceProviderType: decimal
		lineageTag: 9b73283f-1df2-427b-b111-0daedc54cc23
		summarizeBy: sum
		sourceColumn: ListCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_ChargePeriodMonth
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 98481498-95b0-45b6-8111-a2c9403f7f19
		summarizeBy: none
		sourceColumn: x_ChargePeriodMonth

		annotation SummarizationSetBy = Automatic

	column x_CostCategories
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: f77884cc-ffcb-4523-b1ac-0a388f8ed561
		summarizeBy: none
		sourceColumn: x_CostCategories

		annotation SummarizationSetBy = Automatic

	column x_CostCenter
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 1e537be6-2eed-4da0-801a-c5c989876cb6
		summarizeBy: none
		sourceColumn: x_CostCenter

		annotation SummarizationSetBy = Automatic

	column x_ReportingDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 82b6efa6-27e2-43a0-b13f-d3e05a988672
		summarizeBy: none
		sourceColumn: x_ReportingDate

		annotation SummarizationSetBy = Automatic

	column tag_Untagged
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: 0ce4d294-1fbd-4e74-829c-d765b292d84f
		summarizeBy: none
		sourceColumn: tag_Untagged

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 1415dd3c-df67-489f-9a38-07542362cd6a
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column tag_Application
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0fd9854a-aef8-48e4-978b-07d529f5a596
		summarizeBy: none
		sourceColumn: tag_Application

		annotation SummarizationSetBy = Automatic

	column tag_CostCenter
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: e25b618c-631a-47ca-9d6a-2f5301ac0028
		summarizeBy: none
		sourceColumn: tag_CostCenter

		annotation SummarizationSetBy = Automatic

	column tag_Department
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 46abdaa1-b6ea-4e58-9c53-f7e0b7b5fcc6
		summarizeBy: none
		sourceColumn: tag_Department

		annotation SummarizationSetBy = Automatic

	column tag_Env
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 5519b78a-a2f7-4460-8bb5-764cbbc1097a
		summarizeBy: none
		sourceColumn: tag_Env

		annotation SummarizationSetBy = Automatic

	column tag_Owner
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c88b9003-5a17-4185-a453-9e4c37b81e02
		summarizeBy: none
		sourceColumn: tag_Owner

		annotation SummarizationSetBy = Automatic

	column tag_Project
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 28f4d3a4-56e2-4714-a9dd-1b19626a68a0
		summarizeBy: none
		sourceColumn: tag_Project

		annotation SummarizationSetBy = Automatic

	column tag_Service
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0cc5d9b2-13c9-4f37-972e-1220fa7138c2
		summarizeBy: none
		sourceColumn: tag_Service

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a097e2ca-d435-47ad-9ddf-8861802d1769
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition TagCosts = m
		mode: directQuery
		queryGroup: 'Data Explorer'
		source =
				let
				    // Customize the following settings to tune how tags are handled
				
				        // Set the tags you want to promote as 'tag_*' columns in this array
				        PromotedTags = {"Application", "BusinessUnit", "CostCenter", "Department", "Division", "Env", "Owner", "Product", "Project", "Purpose", "Service"},
				
				        // This option matches tag keys that may have different case (e.g., 'env' and 'ENV')
				        Handle_mixed_case_tags = true,
				
				        // This option removes any unwanted spaces before or after the tag key
				        Trim_spaces_from_tags = true,
				
				    // Init report parameters
				    lookback = Text.From(if #"Number of Months" = "" or #"Number of Months" = null then 999 else #"Number of Months"),
				    promotedTagsObject = "dynamic(['" & Text.Combine(PromotedTags, "', '") & "'])",
				    Source = AzureDataExplorer.Contents(#"Cluster URL", "Hub", "
				
				    let checktag = (key: string) {
				        let tagColumn = print tag = promotedTags | mv-expand tag | where tag == key or (caseInsensitive and tag =~ key) | project tag = strcat('tag_', tag);
				        iff(toscalar(tagColumn | count) > 0, toscalar(tagColumn | limit 1), '')
				    };
				    Costs_v1_0
				    | where ChargePeriodStart >= monthsago(" & lookback & ")
				    | extend x_ChargePeriodMonth = startofmonth(ChargePeriodStart)
				    | extend x_ReportingDate = " & (if #"Default Granularity" = "Monthly" then "x_ChargePeriodMonth" else "startofday(ChargePeriodStart)") & "
				    //
				    | extend Tags = tostring(Tags)
				    | summarize
				        BilledCost = sum(BilledCost),
				        ChargePeriodEnd = max(ChargePeriodEnd),
				        ChargePeriodStart = min(ChargePeriodStart),
				        ContractedCost = sum(ContractedCost),
				        EffectiveCost = sum(EffectiveCost),
				        ListCost = sum(ListCost)
				        by
				            BillingCurrency,
				            // CommitmentDiscountCategory,
				            // CommitmentDiscountId,
				            // CommitmentDiscountName,
				            // CommitmentDiscountType,
				            RegionName,
				            Tags,
				            x_ChargePeriodMonth,
				            x_CostCategories = tostring(x_CostCategories),
				            x_CostCenter,
				            x_ReportingDate,
				            tag_Untagged = isempty(Tags) or Tags == '{}'
				    //
				    // Extract tags
				    | extend tmp_Tags = parse_json(Tags)
				    | mv-apply tmp_Tags on (
				        extend TagName = tostring(bag_keys(tmp_Tags)[0])
				        | extend cleanTagName = " & (if Trim_spaces_from_tags then "trim(' ', TagName)" else "TagName") & "
				        | where cleanTagName in (" & promotedTagsObject & ")" & (if Handle_mixed_case_tags then " or cleanTagName in~ (" & promotedTagsObject & ")" else "") & "
				        | extend tagColumn = strcat('tag_', " & promotedTagsObject & "[array_index_of(parse_json(tolower(" & promotedTagsObject & ")), tolower(cleanTagName))])
				        | where isnotempty(tagColumn)
				        | summarize tmp_Tags = make_bag(bag_pack(tagColumn, tostring(tmp_Tags[TagName])))
				    )
				    | evaluate bag_unpack(tmp_Tags)
				    | extend tag_Untagged = isempty(Tags) or tostring(Tags) == '{}'
				    //
				    // | extend x_CommitmentDiscountSavings = ContractedCost - EffectiveCost
				    // | extend x_NegotiatedDiscountSavings = ListCost - ContractedCost
				    // | extend x_TotalSavings = ListCost - EffectiveCost
				
				    ", [MaxRows=null, MaxSize=1073741824, NoTruncate=false, AdditionalSetStatements=null, ClientRequestIdPrefix="ftk-PowerBI-TagCosts"]),
				
				    // Sort columns alphabetically
				    Output = Table.ReorderColumns(Source, List.Sort(Table.ColumnNames(Source)))
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

