table AdvisorRecommendations
	lineageTag: a76a7ba9-b6b5-4140-9739-344b958bfc9f

	column id
		dataType: string
		lineageTag: de03600f-0938-479c-9668-1386cd8fd8cc
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b82b2171-5f91-421e-9052-b72ae63ed3c3
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: cfcd06c0-8643-4070-a8d7-99b52aec15dc
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 1c1af2b8-219f-43e0-8592-5d29cf9643b5
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: dcc211d0-e8f4-40b8-a6d6-de6e9a40fc68
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: f3836cb3-377c-4207-963b-bb1530e31c58
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: d7eeaa34-78c9-4ee9-8196-28155e05bab5
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: eff05517-d757-40ef-84ad-a9c2285bd926
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 10ab154c-3f52-439e-8698-ee38e7b592fe
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 107904ab-daf2-43d6-a764-fe491b840dc4
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 0ce894ab-6bb5-4135-85cc-7cd57c1ae987
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.recommendationTypeId'
		dataType: string
		lineageTag: b5215814-f868-4a8c-8c85-719e04a93cdd
		summarizeBy: none
		sourceColumn: properties.recommendationTypeId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ObservationPeriodStartDate'
		dataType: dateTime
		formatString: General Date
		lineageTag: ab4f38d6-4047-479b-9f9b-e410f75ddc7e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ObservationPeriodStartDate

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ObservationPeriodEndDate'
		dataType: dateTime
		formatString: General Date
		lineageTag: 56c63f3b-8ddd-4c48-a1d4-ebd95bb7c077
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ObservationPeriodEndDate

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.annualSavingsAmount'
		dataType: double
		lineageTag: 19b8e57a-5d4c-47c6-b339-244398d3280f
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.annualSavingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.HasRecommendation'
		dataType: string
		lineageTag: 43a90524-510a-48a1-a41b-67275ab5a220
		summarizeBy: none
		sourceColumn: properties.extendedProperties.HasRecommendation

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsCurrency'
		dataType: string
		lineageTag: 17b12b2b-14c2-4a12-90d0-1faa1b3a192b
		summarizeBy: none
		sourceColumn: properties.extendedProperties.savingsCurrency

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.IsInReplication'
		dataType: string
		lineageTag: dbfe3e6c-c999-447a-bc1b-c7fe0e506013
		summarizeBy: none
		sourceColumn: properties.extendedProperties.IsInReplication

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Recommended_DTU'
		dataType: string
		lineageTag: a7158037-adc3-42fb-a6ee-234086f5dc36
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Recommended_DTU

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Recommended_SKU'
		dataType: string
		lineageTag: 73678d68-9152-45dc-b63b-c84bec6430c3
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Recommended_SKU

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ResourceGroup'
		dataType: string
		lineageTag: b96cc7fb-e6a6-456c-b1a7-62a7f1faf6f2
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ResourceGroup

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsAmount'
		dataType: double
		lineageTag: fe066f63-af23-441a-b614-df90e7b459c2
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.savingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.DatabaseSize'
		dataType: string
		lineageTag: 291bcdda-5321-4bb3-8900-62cb86a30af8
		summarizeBy: none
		sourceColumn: properties.extendedProperties.DatabaseSize

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.DatabaseName'
		dataType: string
		lineageTag: 282b6040-b89c-4139-95bf-c914e6a07138
		summarizeBy: none
		sourceColumn: properties.extendedProperties.DatabaseName

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ServerName'
		dataType: string
		lineageTag: 64d82cc4-f542-4ee4-9cdd-f0ce960d97a4
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ServerName

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Region'
		dataType: string
		lineageTag: a804462d-34e5-498d-ae01-0ba78750329e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Region

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.lookbackPeriod'
		dataType: string
		lineageTag: e0579f64-a229-40fd-b0d2-6a6c7baf8052
		summarizeBy: none
		sourceColumn: properties.extendedProperties.lookbackPeriod

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.subId'
		dataType: string
		lineageTag: b2ca600b-c8f6-42db-9edc-97ca64a5429e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.subId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.scope'
		dataType: string
		lineageTag: 32e4dd3a-74a6-4e20-9005-55bfbcd3ac7e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.scope

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.term'
		dataType: string
		lineageTag: 12b6fe8e-9c25-4287-8db1-23279ec5616e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.term

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.sku'
		dataType: string
		lineageTag: 9a56ac74-a4e4-44b0-b879-9d0d696aa06a
		summarizeBy: none
		sourceColumn: properties.extendedProperties.sku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.commitment'
		dataType: string
		lineageTag: c63f1307-bbd6-48c1-807f-9b5dcd0ad9cf
		summarizeBy: none
		sourceColumn: properties.extendedProperties.commitment

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.currentSku'
		dataType: string
		lineageTag: 9ac388a6-51eb-4bec-aa68-5c13b7fe5c9b
		summarizeBy: none
		sourceColumn: properties.extendedProperties.currentSku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.targetSku'
		dataType: string
		lineageTag: 1ebb5230-bc88-4be3-8e7f-7ce06fbecce4
		summarizeBy: none
		sourceColumn: properties.extendedProperties.targetSku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.recommendationMessage'
		dataType: string
		lineageTag: e0744324-2c7b-43b4-bc4d-bce14a18a0e2
		summarizeBy: none
		sourceColumn: properties.extendedProperties.recommendationMessage

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.solution'
		dataType: string
		lineageTag: 9c791663-17ff-42a2-9648-ef4b12b2671e
		summarizeBy: none
		sourceColumn: properties.shortDescription.solution

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.problem'
		dataType: string
		lineageTag: 5c657cce-2d94-4eec-b526-7d20c72bec54
		summarizeBy: none
		sourceColumn: properties.shortDescription.problem

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.resourceId'
		dataType: string
		lineageTag: 395d38f4-d4f6-4d30-94a2-ec3244abfed2
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.resourceId

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.singular'
		dataType: string
		lineageTag: 58f9df6d-d682-4bf8-9273-d141f30c4743
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.singular

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.plural'
		dataType: string
		lineageTag: 86f40b1b-56c8-4b29-9ac2-7b2cbb6f9f19
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.plural

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.action'
		dataType: string
		lineageTag: 1cdc271b-78aa-45e9-b85c-89684dddf18c
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.action

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.source'
		dataType: string
		lineageTag: c83167c4-f804-4568-8894-a9ffd8d0fdd9
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.source

		annotation SummarizationSetBy = Automatic

	column 'properties.suppressionIds'
		dataType: string
		lineageTag: 8761bfa3-8cb3-4d24-984e-c0cb3482a2a0
		summarizeBy: none
		sourceColumn: properties.suppressionIds

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedField'
		dataType: string
		lineageTag: 26285858-61f3-4efd-8201-9f79d3f877cd
		summarizeBy: none
		sourceColumn: properties.impactedField

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedValue'
		dataType: string
		lineageTag: 62951291-b70a-47eb-bbfd-74e781fef07e
		summarizeBy: none
		sourceColumn: properties.impactedValue

		annotation SummarizationSetBy = Automatic

	column 'properties.lastUpdated'
		dataType: dateTime
		formatString: General Date
		lineageTag: d3bf7cce-83bc-4589-a2da-ece0e146e1d3
		summarizeBy: none
		sourceColumn: properties.lastUpdated

		annotation SummarizationSetBy = Automatic

	column 'properties.category'
		dataType: string
		lineageTag: d4071f11-546e-49cc-9131-675482ae0927
		summarizeBy: none
		sourceColumn: properties.category

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata'
		dataType: string
		lineageTag: 9888db80-3867-4fe4-8600-661836e054a1
		summarizeBy: none
		sourceColumn: properties.metadata

		annotation SummarizationSetBy = Automatic

	column 'properties.impact'
		dataType: string
		lineageTag: 62f29742-9472-4678-b789-5da41abf1051
		summarizeBy: none
		sourceColumn: properties.impact
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 45dddaff-88d5-4b1f-95b5-9b5267308a26
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 5d0af29e-7135-432f-895f-94e3cb470aac
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 1462e1f4-bbb1-4ae1-9f0c-50f39881a2d6
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 866ddc18-dc53-4171-97bb-fb0cbc8cc19d
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 4d8ca85e-f35a-4e71-866b-188c3de4f284
		summarizeBy: sum
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition AdvisorRecommendations = m
		mode: import
		queryGroup: 'Resource Graph'
		source = ```
				let
				  Source = AzureResourceGraph.Query("
				    advisorresources 
				    | where type == 'microsoft.advisor/recommendations'
				    | where properties['category'] == 'Cost'
				  " & ftk_DemoFilter(), "Tenant", null, null, [resultTruncated = true]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"recommendationTypeId", "extendedProperties", "shortDescription", "resourceMetadata", "suppressionIds", "impactedField", "impactedValue", "lastUpdated", "category", "metadata", "impact"}, {"properties.recommendationTypeId", "properties.extendedProperties", "properties.shortDescription", "properties.resourceMetadata", "properties.suppressionIds", "properties.impactedField", "properties.impactedValue", "properties.lastUpdated", "properties.category", "properties.metadata", "properties.impact"}),
				  #"Expanded properties.extendedProperties" = Table.ExpandRecordColumn(#"Expanded properties", "properties.extendedProperties", {"ObservationPeriodStartDate", "ObservationPeriodEndDate", "annualSavingsAmount", "HasRecommendation", "savingsCurrency", "IsInReplication", "Recommended_DTU", "Recommended_SKU", "ResourceGroup", "savingsAmount", "DatabaseSize", "DatabaseName", "ServerName", "Region", "lookbackPeriod", "subId", "scope", "term", "sku", "commitment", "currentSku", "targetSku", "recommendationMessage"}, {"properties.extendedProperties.ObservationPeriodStartDate", "properties.extendedProperties.ObservationPeriodEndDate", "properties.extendedProperties.annualSavingsAmount", "properties.extendedProperties.HasRecommendation", "properties.extendedProperties.savingsCurrency", "properties.extendedProperties.IsInReplication", "properties.extendedProperties.Recommended_DTU", "properties.extendedProperties.Recommended_SKU", "properties.extendedProperties.ResourceGroup", "properties.extendedProperties.savingsAmount", "properties.extendedProperties.DatabaseSize", "properties.extendedProperties.DatabaseName", "properties.extendedProperties.ServerName", "properties.extendedProperties.Region", "properties.extendedProperties.lookbackPeriod", "properties.extendedProperties.subId", "properties.extendedProperties.scope", "properties.extendedProperties.term", "properties.extendedProperties.sku", "properties.extendedProperties.commitment", "properties.extendedProperties.currentSku", "properties.extendedProperties.targetSku", "properties.extendedProperties.recommendationMessage"}),
				  #"Changed column type 2" = Table.TransformColumnTypes(#"Expanded properties.extendedProperties", {{"properties.extendedProperties.annualSavingsAmount", type number}}, "en-US"),
				  #"Replaced errors" = Table.ReplaceErrorValues(#"Changed column type 2", {{"properties.extendedProperties.annualSavingsAmount", null}}),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Replaced errors", {{"properties.extendedProperties.savingsAmount", type number}}, "en-US"),
				  #"Replaced errors 1" = Table.ReplaceErrorValues(#"Changed column type 1", {{"properties.extendedProperties.savingsAmount", null}}),
				  #"Expanded properties.shortDescription" = Table.ExpandRecordColumn(#"Replaced errors 1", "properties.shortDescription", {"solution", "problem"}, {"properties.shortDescription.solution", "properties.shortDescription.problem"}),
				  #"Expanded properties.resourceMetadata" = Table.ExpandRecordColumn(#"Expanded properties.shortDescription", "properties.resourceMetadata", {"resourceId", "singular", "plural", "action", "source"}, {"properties.resourceMetadata.resourceId", "properties.resourceMetadata.singular", "properties.resourceMetadata.plural", "properties.resourceMetadata.action", "properties.resourceMetadata.source"}),
				  #"Replaced value" = Table.ReplaceValue(#"Expanded properties.resourceMetadata", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.savingsAmount"}),
				  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.annualSavingsAmount"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Replaced value 1", {{"properties.extendedProperties.ObservationPeriodStartDate", type datetimezone}, {"properties.extendedProperties.ObservationPeriodEndDate", type datetimezone}, {"properties.lastUpdated", type datetimezone}}),
				  #"Inserted conditional column" = Table.AddColumn(#"Changed column type", "SortOrder", each if [properties.impact] = "High" then 1 else if [properties.impact] = "Medium" then 2 else if [properties.impact] = "Low" then 3 else ""),
				  #"Changed column type 3" = Table.TransformColumnTypes(#"Inserted conditional column", {{"SortOrder", Int64.Type}})
				in
				  #"Changed column type 3"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

