table Disks
	lineageTag: ca0025b1-6be2-4a29-af32-30ef5f20fe5f

	column id
		dataType: string
		lineageTag: deeae826-f875-4504-8131-757498d8759a
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a5fefea2-4fe5-484f-aed7-3d13f6323531
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: a311742d-a3f5-4432-b707-8dcd17c7d279
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 956716b4-925c-4fd7-966e-a3e3d8a8a4ce
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 4c524547-d15c-4cfd-a1b6-eed57b7f75a1
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: e2c9aac1-398d-407d-b62f-43596f401420
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: d2ec8b97-974d-4273-ab54-a99d67396140
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: bddb0cc5-51dd-4fd2-9bcf-16f5e4f9f18a
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: c25abab2-269e-4428-9632-f00ff63cf033
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column 'sku.name'
		dataType: string
		lineageTag: f1132ac0-604d-47d1-9b06-74db3b2d443c
		summarizeBy: none
		sourceColumn: sku.name

		annotation SummarizationSetBy = Automatic

	column 'sku.tier'
		dataType: string
		lineageTag: e9b4cfc4-81eb-4d94-bc14-ff38f90cbd8b
		summarizeBy: none
		sourceColumn: sku.tier

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: a48ec8c3-8134-47be-83e4-42c24554add2
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: e0422dd9-490b-46ea-bba7-58623656ad8d
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.publicNetworkAccess'
		dataType: string
		lineageTag: e66bb3fa-7deb-49fc-9be6-130494ad2e20
		summarizeBy: none
		sourceColumn: properties.publicNetworkAccess

		annotation SummarizationSetBy = Automatic

	column 'properties.encryption'
		dataType: string
		lineageTag: 4b8960fb-6583-473c-bd60-9575871b4e94
		summarizeBy: none
		sourceColumn: properties.encryption

		annotation SummarizationSetBy = Automatic

	column 'properties.networkAccessPolicy'
		dataType: string
		lineageTag: 5c055ec0-604c-49f1-99fa-d87cff2131d4
		summarizeBy: none
		sourceColumn: properties.networkAccessPolicy

		annotation SummarizationSetBy = Automatic

	column 'properties.timeCreated'
		dataType: string
		lineageTag: cf636967-ce8c-4922-a10a-a8ce6349380c
		summarizeBy: none
		sourceColumn: properties.timeCreated

		annotation SummarizationSetBy = Automatic

	column 'properties.diskSizeGB'
		dataType: double
		lineageTag: 12ec3d0b-32dc-41a7-9b06-8adc11f4ead9
		summarizeBy: sum
		sourceColumn: properties.diskSizeGB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.hyperVGeneration'
		dataType: string
		lineageTag: 846d8ace-16fa-4fc8-83b0-d77ff75b9e60
		summarizeBy: none
		sourceColumn: properties.hyperVGeneration

		annotation SummarizationSetBy = Automatic

	column 'properties.diskSizeBytes'
		dataType: double
		lineageTag: 69588c16-e1f7-4423-a050-147e83823716
		summarizeBy: sum
		sourceColumn: properties.diskSizeBytes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.creationData.createOption'
		dataType: string
		lineageTag: 967b33c4-a659-4e78-a76b-63edba801366
		summarizeBy: none
		sourceColumn: properties.creationData.createOption

		annotation SummarizationSetBy = Automatic

	column 'properties.creationData.imageReference.id'
		dataType: string
		lineageTag: 819ebb4b-c380-49d6-9b18-59d807d2ea91
		summarizeBy: none
		sourceColumn: properties.creationData.imageReference.id

		annotation SummarizationSetBy = Automatic

	column 'properties.osType'
		dataType: string
		lineageTag: 666c7b76-3df6-4cfb-b908-f81d7ffecdf8
		summarizeBy: none
		sourceColumn: properties.osType

		annotation SummarizationSetBy = Automatic

	column 'properties.LastOwnershipUpdateTime'
		dataType: string
		lineageTag: fcef111b-7b03-4329-a762-37ed1fbdf4ff
		summarizeBy: none
		sourceColumn: properties.LastOwnershipUpdateTime

		annotation SummarizationSetBy = Automatic

	column 'properties.diskState'
		dataType: string
		lineageTag: 515cbaa6-df64-484c-aef0-0e3804620405
		summarizeBy: none
		sourceColumn: properties.diskState

		annotation SummarizationSetBy = Automatic

	column 'properties.uniqueId'
		dataType: string
		lineageTag: 3ac2b374-3003-48ff-8fa4-f7d98991ac05
		summarizeBy: none
		sourceColumn: properties.uniqueId

		annotation SummarizationSetBy = Automatic

	column 'properties.diskMBpsReadWrite'
		dataType: double
		lineageTag: 2f95f7e9-da97-4689-87e0-84b3903aff7d
		summarizeBy: sum
		sourceColumn: properties.diskMBpsReadWrite

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.diskIOPSReadWrite'
		dataType: double
		lineageTag: 490d018d-7a97-4546-ac90-157d803c424f
		summarizeBy: sum
		sourceColumn: properties.diskIOPSReadWrite

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.tier'
		dataType: string
		lineageTag: 9cdaeebc-4e7e-4795-9026-53f5cdc4a43e
		summarizeBy: none
		sourceColumn: properties.tier

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 72b832d7-5eb6-4a58-9b2b-d135d659d231
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 032ff0cb-1cc0-48b6-a95d-d835578f742f
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 96b63e5f-b360-4135-b384-cf4a4f0c0e88
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: dc3f509c-ea2b-4c19-9085-2c6167e21d62
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column diskType
		dataType: string
		lineageTag: efab8b0e-646d-4b4a-93c6-8196f1379fec
		summarizeBy: none
		sourceColumn: diskType

		annotation SummarizationSetBy = Automatic

	column parentVM
		dataType: string
		lineageTag: 8abc188f-2c52-4db8-967f-5447de969f33
		summarizeBy: none
		sourceColumn: parentVM

		annotation SummarizationSetBy = Automatic

	partition Disks = m
		mode: import
		queryGroup: 'Resource Graph'
		source =
				let
				  Source = AzureResourceGraph.Query("
				    Resources
				    | where type =~ 'microsoft.compute/disks'
				  ", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "publicNetworkAccess", "encryption", "networkAccessPolicy", "timeCreated", "diskSizeGB", "hyperVGeneration", "diskSizeBytes", "creationData", "osType", "LastOwnershipUpdateTime", "diskState", "uniqueId", "diskMBpsReadWrite", "diskIOPSReadWrite", "tier"}, {"properties.provisioningState", "properties.publicNetworkAccess", "properties.encryption", "properties.networkAccessPolicy", "properties.timeCreated", "properties.diskSizeGB", "properties.hyperVGeneration", "properties.diskSizeBytes", "properties.creationData", "properties.osType", "properties.LastOwnershipUpdateTime", "properties.diskState", "properties.uniqueId", "properties.diskMBpsReadWrite", "properties.diskIOPSReadWrite", "properties.tier"}),
				  #"Expanded sku" = Table.ExpandRecordColumn(#"Expanded properties", "sku", {"name", "tier"}, {"sku.name", "sku.tier"}),
				  #"Expanded properties.creationData" = Table.ExpandRecordColumn(#"Expanded sku", "properties.creationData", {"createOption", "imageReference"}, {"properties.creationData.createOption", "properties.creationData.imageReference"}),
				  #"Expanded properties.creationData.imageReference" = Table.ExpandRecordColumn(#"Expanded properties.creationData", "properties.creationData.imageReference", {"id"}, {"properties.creationData.imageReference.id"}),
				  #"Expanded zones" = Table.ExpandListColumn(#"Expanded properties.creationData.imageReference", "zones"),
				  #"Inserted conditional column" = Table.AddColumn(#"Expanded zones", "diskType", each if [properties.osType] = null then "Data Disk" else "OS Disk"),
				  #"Changed column type" = Table.TransformColumnTypes(#"Inserted conditional column", {{"properties.diskSizeGB", type number}, {"properties.diskSizeBytes", type number}, {"properties.diskMBpsReadWrite", type number}, {"properties.diskIOPSReadWrite", type number}}),
				  #"Duplicated column" = Table.DuplicateColumn(#"Changed column type", "managedBy", "managedBy - Copy"),
				  #"Extracted text after delimiter" = Table.TransformColumns(#"Duplicated column", {{"managedBy - Copy", each Text.AfterDelimiter(Text.From(_), "/", {0, RelativePosition.FromEnd}), type text}}),
				  #"Renamed columns" = Table.RenameColumns(#"Extracted text after delimiter", {{"managedBy - Copy", "parentVM"}})
				in
				  #"Renamed columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

