table HubIngestion
	lineageTag: 78fe6c31-4536-4a91-952c-0d612defc0e2

	measure IngestionMonths = FORMAT(MIN([Month]), "Mmm yyyy") & IF(MIN([Month])=MAX([Month]), "", "-" & FORMAT(MAX([Month]), "Mmm yyyy"))
		lineageTag: 2c089fa3-ed10-4b1c-91ea-b05560dce5f4

	column StorageAccount
		dataType: string
		lineageTag: 53913106-87fc-45b9-89c1-cabac2e58fcc
		summarizeBy: none
		sourceColumn: StorageAccount

		annotation SummarizationSetBy = Automatic

	column Container
		dataType: string
		lineageTag: d301301a-661a-4506-bd34-455deede08f8
		summarizeBy: none
		sourceColumn: Container

		annotation SummarizationSetBy = Automatic

	column Scope
		dataType: string
		lineageTag: 05ccb0e1-cb89-4517-ad98-dcd3c932459a
		summarizeBy: none
		sourceColumn: Scope

		annotation SummarizationSetBy = Automatic

	column Dataset
		dataType: string
		lineageTag: d03019e7-0ae4-4f53-823f-7adbdd966213
		summarizeBy: none
		sourceColumn: Dataset

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Mmm yyyy
		lineageTag: 370fa4c3-3fac-4188-821c-e790cf702e5a
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 8fec1225-20ef-4ce3-9c0e-58c5857898b7
			defaultHierarchy: LocalDateTable_41efb852-a77d-41a4-8d93-fa1942f528a3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column FileType
		dataType: string
		lineageTag: 75be167a-a612-46c8-a5c9-7c195bfa04d6
		summarizeBy: none
		sourceColumn: FileType

		annotation SummarizationSetBy = Automatic

	column Files
		dataType: int64
		formatString: 0
		lineageTag: 92ab0acc-cdfb-4891-a0af-f91add494ac2
		summarizeBy: sum
		sourceColumn: Files

		annotation SummarizationSetBy = Automatic

	column SizeInGB
		dataType: int64
		formatString: 0
		lineageTag: 866745ce-0b06-47c7-ae00-afb8a410adb9
		summarizeBy: sum
		sourceColumn: SizeInGB

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: e3fecfbb-5910-41ca-9e30-af8b2a6487cf
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 0b911ae4-f354-4a70-a9a2-63bc92f7b26c
			defaultHierarchy: LocalDateTable_c7280346-3e7b-4b97-8f9a-9eece9b5d3ed.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Updated
		dataType: dateTime
		formatString: Mmm d hh:nn
		lineageTag: 2f9bb0e3-6a1b-495d-84b4-eb53debbfd09
		summarizeBy: none
		sourceColumn: Updated

		variation Variation
			isDefault
			relationship: 440308a8-6879-464d-a8b1-79f3a3a71c69
			defaultHierarchy: LocalDateTable_1cba35dd-c086-4d23-8329-b3c1c5cbdc70.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Accessed
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ac52edc-af6e-454a-a27e-472b1e1f39f8
		summarizeBy: none
		sourceColumn: Accessed

		variation Variation
			isDefault
			relationship: a3808251-3896-4682-8e9d-524755e4ca18
			defaultHierarchy: LocalDateTable_7e252193-4a78-4d83-a440-30c8768441b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FolderPath
		dataType: string
		lineageTag: 493d4b4d-0112-4627-ad51-4b3b422e0922
		summarizeBy: none
		sourceColumn: FolderPath

		annotation SummarizationSetBy = Automatic

	partition HubIngestion = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source = ```
				let
				    ADLS = AzureStorage.DataLake(#"Storage URL"),
				    RenameColumns = Table.RenameColumns(ADLS, {{"Date accessed", "DateAccessed"}, {"Date modified", "DateModified"}, {"Date created", "DateCreated"}, {"Folder Path", "FolderPath"}, {"Name", "FileName"}}),
				    FileSize  = Table.AddColumn(RenameColumns, "FileSizeInGB", each 1.0 * [Attributes][Size] / 1000000000, type number),
				    Storage   = Table.AddColumn(FileSize, "StorageAccount", each Text.SplitAny([FolderPath], "/."){2}),
				    Container = Table.AddColumn(Storage, "Container", each Text.Split([FolderPath], "/"){3}),
				    MonthStr  = Table.AddColumn(Container, "MonthStr", each List.Last(List.RemoveLastN(Text.Split(Text.Trim([FolderPath], "/"), "/"), 1))),
				    _toMonth  = (s) => Date.FromText(Text.Range(s, 0, 4) & "-" & Text.Range(s, 4, 2) & "-01"),
				    // TODO: If we use UTC, it shows up as the previous month -- DateTime.Date(DateTime.FromText(Text.Range(s, 0, 4) & "-" & Text.Range(s, 4, 2) & "-01T00:00:00Z")),
				    Month     = Table.AddColumn(MonthStr, "Month", each if [MonthStr] <> null then _toMonth([MonthStr]) else null, type date),
				    Scope     = Table.AddColumn(Month, "Scope", each Text.Split(Text.Split([FolderPath], "/" & [Container]){1}, "/" & [MonthStr]){0}),
				    FileType  = Table.AddColumn(Scope, "FileType", each if [Extension] = ".parquet" then "Parquet" else "Unknown"),
				    Dataset   = Table.AddColumn(FileType, "Dataset", each List.Last(Text.Split(Text.Trim([FolderPath], "/"), "/"))),
				    GroupBy   = Table.Group(Dataset, {
				        "StorageAccount", "Container", "Scope", "Dataset", "Month", "FileType", "FolderPath"
				    }, {
				        {"Files", each Table.RowCount(_), Int64.Type},
				        {"SizeInGB", each List.Sum([FileSizeInGB]), Int64.Type},
				        {"Created", each List.Min([DateCreated]), type nullable datetime}, 
				        {"Updated", each List.Max([DateModified]), type nullable datetime}, 
				        {"Accessed", each List.Max([DateAccessed]), type nullable datetime}
				    }),
				    _columns = {"Scope", "StorageAccount", "Container", "Dataset", "Month", "FileType", "Files", "SizeInGB", "FolderPath", "Created", "Updated", "Accessed"},
				    RemoveColumns  = Table.SelectColumns(GroupBy, _columns),
				    ReorderColumns = Table.ReorderColumns(RemoveColumns, _columns)
				in
				    ReorderColumns
				```

	annotation PBI_ResultType = Table

