table InstanceSizeFlexibility
	lineageTag: 04a435c4-9138-4c1f-ad59-dd939cd8e139

	column InstanceSizeFlexibilityGroup
		dataType: string
		lineageTag: 57d1a022-b990-443e-ac76-39099da91d22
		summarizeBy: none
		sourceColumn: InstanceSizeFlexibilityGroup

		annotation SummarizationSetBy = Automatic

	column ResourceLocation
		dataType: string
		lineageTag: 0048e9dd-f968-48b6-b249-8809062ee9c1
		summarizeBy: none
		sourceColumn: ResourceLocation

		annotation SummarizationSetBy = Automatic

	column ArmSkuName
		dataType: string
		lineageTag: 528c532f-6dfe-4e64-82d0-577334078041
		summarizeBy: none
		sourceColumn: ArmSkuName

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: int64
		formatString: 0
		lineageTag: 8b5d50bb-801f-4161-ad86-25d089cf77fb
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

	column ComboMeter
		dataType: string
		lineageTag: 3e71b355-f940-4cb4-89b9-5128567265d2
		summarizeBy: none
		sourceColumn: ComboMeter

		annotation SummarizationSetBy = Automatic

	column HardwareMeter
		dataType: string
		lineageTag: 00534664-6f13-4eca-9d9b-2a23cc470ecf
		summarizeBy: none
		sourceColumn: HardwareMeter

		annotation SummarizationSetBy = Automatic

	column SoftwareMeter
		dataType: string
		lineageTag: 0f3af934-f3a3-4834-9191-21297b52076b
		summarizeBy: none
		sourceColumn: SoftwareMeter

		annotation SummarizationSetBy = Automatic

	column CompositeKey
		dataType: string
		lineageTag: 9cfd70d1-ca7f-44a4-ba5d-dfb34f11f7b6
		summarizeBy: none
		sourceColumn: CompositeKey

		annotation SummarizationSetBy = Automatic

	column NormalizedSKU
		dataType: string
		lineageTag: f4e375e3-cff8-41af-9c9b-45b6ac3becc3
		summarizeBy: none
		sourceColumn: NormalizedSKU

		annotation SummarizationSetBy = Automatic

	column NormalizedSizeKey = [NormalizedSKU] & [HardwareMeter]
		dataType: string
		lineageTag: d1db9f39-1d52-4cd1-950f-8089a14f760a
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition InstanceSizeFlexibility = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				    Source = Csv.Document(AzureStorage.BlobContents("https://ccmstorageprod.blob.core.windows.net/costmanagementconnector-data/AutofitComboMeterData.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstanceSizeFlexibilityGroup", type text}, {"ResourceLocation", type text}, {"ArmSkuName", type text}, {"Ratio", Int64.Type}, {"ComboMeter", type text}, {"HardwareMeter", type text}, {"SoftwareMeter", type text}, {"CompositeKey", type text}, {"NormalizedSKU", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

