table NetworkSecurityGroups
	lineageTag: 7d98f967-9180-4a4f-958a-89256520af0f

	column id
		dataType: string
		lineageTag: f482c1e4-d36d-47dd-ab46-ab41d9e651ae
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: dbe15cec-f5b3-4c38-8688-b1dc486c42d9
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 5f4b1e88-2765-4e77-adb4-cfc36d46993a
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 72c91362-41b8-4bc4-8c8a-203ed8678806
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 54ccea47-564a-482a-811a-a087edbe78c6
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 8043bb49-8a98-4a22-85be-655e135f6f79
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 1099ad85-7cc4-4dd6-9a20-ee04cf0187db
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 0e6a56c5-6e87-498a-ba54-d0eee60d4494
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: b6c809eb-78b5-4c85-9126-92c3b404242d
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: d97c5705-4579-4d8d-be6a-17261fd6ff0e
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: b8c418c7-6526-4106-8541-8c529b94f33d
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: b4e66de6-ba0d-4078-bd7e-87213dec6eda
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.networkInterfaces.id'
		dataType: string
		lineageTag: 33cd5c1b-ee11-458d-a063-818ec4700e1d
		summarizeBy: none
		sourceColumn: properties.networkInterfaces.id

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceGuid'
		dataType: string
		lineageTag: eff5cb67-bada-4826-adc8-4b2a10f81ddc
		summarizeBy: none
		sourceColumn: properties.resourceGuid

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.type'
		dataType: string
		lineageTag: 72f0586e-5f20-4340-b1f0-0a6788c7d9af
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.type

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.provisioningState'
		dataType: string
		lineageTag: 7c397dfc-8cd7-4f6c-a3ff-ba4d6b617c07
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationAddressPrefixes'
		dataType: string
		lineageTag: bda54d1f-ebc9-424b-9f35-026e5052a58d
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationAddressPrefix'
		dataType: string
		lineageTag: 2a1eb696-b4aa-4845-a0ab-e38ff0215daa
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationPortRanges'
		dataType: string
		lineageTag: d9bd3cb8-52bf-432c-986c-f1effc6ead24
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationPortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourceAddressPrefixes'
		dataType: string
		lineageTag: 25aa2af0-e874-43ef-b4e7-d0040823c2dd
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourceAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourceAddressPrefix'
		dataType: string
		lineageTag: c6043291-1f1e-4f55-9145-c6e0fc5979d6
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourceAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationPortRange'
		dataType: string
		lineageTag: 2f3abc03-b7ce-4456-ba56-ec3f0762d66e
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationPortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourcePortRanges'
		dataType: string
		lineageTag: 5dc73886-cc90-428b-9292-58fdb58462c2
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourcePortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourcePortRange'
		dataType: string
		lineageTag: bedee4f3-50c2-401a-86e0-64a11439bd2e
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourcePortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.description'
		dataType: string
		lineageTag: 068ca36f-9c39-4a51-8b36-49aa4169d3b7
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.description

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.protocol'
		dataType: string
		lineageTag: 6bf0d34b-2f94-4860-9448-7b350c06f5d1
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.protocol

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.direction'
		dataType: string
		lineageTag: d8b55cc2-7c7c-40be-aa57-5b2efa2f1776
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.direction

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.priority'
		dataType: string
		lineageTag: fcf33bb9-0778-4def-b144-b2d434bd90f1
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.priority

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.access'
		dataType: string
		lineageTag: 0c3063b5-8072-49ed-bd74-bf05e71e10d7
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.access

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.name'
		dataType: string
		lineageTag: b82db288-f47f-4ca8-aa36-b6ab1a0b319c
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.name

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.id'
		dataType: string
		lineageTag: af8174c6-8ecf-4518-9b6a-0fb3af10ac14
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.id

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.etag'
		dataType: string
		lineageTag: 607c416f-3d80-4c02-b85a-0bf2339171ca
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.etag

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.type'
		dataType: string
		lineageTag: 26144edf-1720-4f17-94ba-75d6b2172f84
		summarizeBy: none
		sourceColumn: properties.securityRules.type

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.provisioningState'
		dataType: string
		lineageTag: 44472d08-f5b3-4186-9adf-513876707543
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationAddressPrefixes'
		dataType: string
		lineageTag: 9d8984ff-b1c4-4c62-8600-72e43104b272
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationAddressPrefix'
		dataType: string
		lineageTag: 2f249b57-c790-4687-82a1-d805f75f3f83
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationPortRanges'
		dataType: string
		lineageTag: d72520c2-0cfd-4e13-b112-3ba4cd8c3b70
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationPortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourceAddressPrefixes'
		dataType: string
		lineageTag: 0c6fa3a9-0b54-4905-a9d8-7004272f0f13
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourceAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourceAddressPrefix'
		dataType: string
		lineageTag: 04bad4dd-667f-4ff3-bde1-ad99b1b40d31
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourceAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationPortRange'
		dataType: string
		lineageTag: b2ca87a4-a342-493b-8a4e-8ae9b48755d0
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationPortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourcePortRanges'
		dataType: string
		lineageTag: 9d5c381e-80ea-4201-b9cd-1f2b579dfe17
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourcePortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourcePortRange'
		dataType: string
		lineageTag: 77d6b680-9a1e-4e7f-8af8-13278f52c156
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourcePortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.protocol'
		dataType: string
		lineageTag: 398c4c53-0c7b-4f52-a06a-e798d9df7416
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.protocol

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.direction'
		dataType: string
		lineageTag: 399c736a-57aa-4c0e-8892-865e1cef7484
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.direction

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.priority'
		dataType: string
		lineageTag: 437e410b-fa04-49ee-b33e-00abf7a5435d
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.priority

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.access'
		dataType: string
		lineageTag: 5033a598-4e4b-4394-9085-3affe314aa9a
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.access

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.name'
		dataType: string
		lineageTag: 4c100028-a36b-4531-84fc-6b39ea2e005d
		summarizeBy: none
		sourceColumn: properties.securityRules.name

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.id'
		dataType: string
		lineageTag: 710fb1a1-0b44-45c5-8e6b-e55ef2788b53
		summarizeBy: none
		sourceColumn: properties.securityRules.id

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.etag'
		dataType: string
		lineageTag: 723e6af4-22cf-4bb1-8b33-43f96becb7c4
		summarizeBy: none
		sourceColumn: properties.securityRules.etag

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 3a4b6011-036a-43b2-b00a-0dde8213c493
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 2850f8aa-e401-404a-accb-70ea7e7f411d
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 6bc69d6e-9632-4bd0-b190-3ce481d89224
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: b339f020-364d-4510-b227-7715a48353fa
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column isWarning = ```
			IF('NetworkSecurityGroups'[properties.securityRules.properties.access]="Allow",
			        SWITCH(
			            'NetworkSecurityGroups'[properties.securityRules.properties.destinationPortRange],
			            "80", "True",
			            "22", "True",
			            "3389", "True",
			            "False"
			    ), "False" 
			)
			```
		dataType: string
		lineageTag: 5fb590a3-057d-487e-af26-3e6686be93fe
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition NetworkSecurityGroups = m
		mode: import
		queryGroup: 'Resource Graph'
		source =
				let
				  Source = AzureResourceGraph.Query("
				    Resources
				    | where type =~ 'microsoft.network/networksecuritygroups'
				  " & ftk_DemoFilter(), "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "networkInterfaces", "resourceGuid", "defaultSecurityRules", "securityRules"}, {"properties.provisioningState", "properties.networkInterfaces", "properties.resourceGuid", "properties.defaultSecurityRules", "properties.securityRules"}),
				  #"Expanded properties.networkInterfaces" = Table.ExpandListColumn(#"Expanded properties", "properties.networkInterfaces"),
				  #"Expanded properties.networkInterfaces 1" = Table.ExpandRecordColumn(#"Expanded properties.networkInterfaces", "properties.networkInterfaces", {"id"}, {"properties.networkInterfaces.id"}),
				  #"Expanded properties.defaultSecurityRules" = Table.ExpandListColumn(#"Expanded properties.networkInterfaces 1", "properties.defaultSecurityRules"),
				  #"Expanded properties.defaultSecurityRules 1" = Table.ExpandRecordColumn(#"Expanded properties.defaultSecurityRules", "properties.defaultSecurityRules", {"type", "properties", "name", "id", "etag"}, {"properties.defaultSecurityRules.type", "properties.defaultSecurityRules.properties", "properties.defaultSecurityRules.name", "properties.defaultSecurityRules.id", "properties.defaultSecurityRules.etag"}),
				  #"Expanded properties.defaultSecurityRules.properties" = Table.ExpandRecordColumn(#"Expanded properties.defaultSecurityRules 1", "properties.defaultSecurityRules.properties", {"provisioningState", "destinationAddressPrefixes", "destinationAddressPrefix", "destinationPortRanges", "sourceAddressPrefixes", "sourceAddressPrefix", "destinationPortRange", "sourcePortRanges", "sourcePortRange", "description", "protocol", "direction", "priority", "access"}, {"properties.defaultSecurityRules.properties.provisioningState", "properties.defaultSecurityRules.properties.destinationAddressPrefixes", "properties.defaultSecurityRules.properties.destinationAddressPrefix", "properties.defaultSecurityRules.properties.destinationPortRanges", "properties.defaultSecurityRules.properties.sourceAddressPrefixes", "properties.defaultSecurityRules.properties.sourceAddressPrefix", "properties.defaultSecurityRules.properties.destinationPortRange", "properties.defaultSecurityRules.properties.sourcePortRanges", "properties.defaultSecurityRules.properties.sourcePortRange", "properties.defaultSecurityRules.properties.description", "properties.defaultSecurityRules.properties.protocol", "properties.defaultSecurityRules.properties.direction", "properties.defaultSecurityRules.properties.priority", "properties.defaultSecurityRules.properties.access"}),
				  #"Expanded properties.defaultSecurityRules.properties.destinationAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties", "properties.defaultSecurityRules.properties.destinationAddressPrefixes"),
				  #"Expanded properties.defaultSecurityRules.properties.destinationPortRanges" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.destinationAddressPrefixes", "properties.defaultSecurityRules.properties.destinationPortRanges"),
				  #"Expanded properties.defaultSecurityRules.properties.sourceAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.destinationPortRanges", "properties.defaultSecurityRules.properties.sourceAddressPrefixes"),
				  #"Expanded properties.defaultSecurityRules.properties.sourcePortRanges" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.sourceAddressPrefixes", "properties.defaultSecurityRules.properties.sourcePortRanges"),
				  #"Expanded properties.securityRules" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.sourcePortRanges", "properties.securityRules"),
				  #"Expanded properties.securityRules 1" = Table.ExpandRecordColumn(#"Expanded properties.securityRules", "properties.securityRules", {"type", "properties", "name", "id", "etag"}, {"properties.securityRules.type", "properties.securityRules.properties", "properties.securityRules.name", "properties.securityRules.id", "properties.securityRules.etag"}),
				  #"Expanded properties.securityRules.properties" = Table.ExpandRecordColumn(#"Expanded properties.securityRules 1", "properties.securityRules.properties", {"provisioningState", "destinationAddressPrefixes", "destinationAddressPrefix", "destinationPortRanges", "sourceAddressPrefixes", "sourceAddressPrefix", "destinationPortRange", "sourcePortRanges", "sourcePortRange", "protocol", "direction", "priority", "access"}, {"properties.securityRules.properties.provisioningState", "properties.securityRules.properties.destinationAddressPrefixes", "properties.securityRules.properties.destinationAddressPrefix", "properties.securityRules.properties.destinationPortRanges", "properties.securityRules.properties.sourceAddressPrefixes", "properties.securityRules.properties.sourceAddressPrefix", "properties.securityRules.properties.destinationPortRange", "properties.securityRules.properties.sourcePortRanges", "properties.securityRules.properties.sourcePortRange", "properties.securityRules.properties.protocol", "properties.securityRules.properties.direction", "properties.securityRules.properties.priority", "properties.securityRules.properties.access"}),
				  #"Expanded properties.securityRules.properties.destinationAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties", "properties.securityRules.properties.destinationAddressPrefixes"),
				  #"Expanded properties.securityRules.properties.destinationPortRanges" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.destinationAddressPrefixes", "properties.securityRules.properties.destinationPortRanges"),
				  #"Expanded properties.securityRules.properties.sourceAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.destinationPortRanges", "properties.securityRules.properties.sourceAddressPrefixes"),
				  #"Expanded properties.securityRules.properties.sourcePortRanges" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.sourceAddressPrefixes", "properties.securityRules.properties.sourcePortRanges")
				in
				  #"Expanded properties.securityRules.properties.sourcePortRanges"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

