/// Cost and usage (FOCUS) data from Cost Management exports.
/// 
/// Data version = 1.0-preview(v1)
/// Learn more @ https://aka.ms/finops/hubs
table ReservationDetails
	lineageTag: 4f9c5acb-e811-40c7-9d01-347392d90bfd

	column ChargePeriodStart
		dataType: dateTime
		formatString: General Date
		lineageTag: 6735c9ae-5fe6-462b-8a61-0d1df0a8e8ca
		summarizeBy: none
		sourceColumn: ChargePeriodStart

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountCategory
		dataType: string
		lineageTag: 616bbebe-0356-4a54-965c-209e8c5f1938
		summarizeBy: none
		sourceColumn: CommitmentDiscountCategory

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountId
		dataType: string
		lineageTag: e53acdf0-6bca-43d9-a407-1d2a961d3505
		summarizeBy: none
		sourceColumn: CommitmentDiscountId

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountType
		dataType: string
		lineageTag: f4a2d942-7e64-43fe-a723-cef8363539c6
		summarizeBy: none
		sourceColumn: CommitmentDiscountType

		annotation SummarizationSetBy = Automatic

	column ConsumedQuantity
		dataType: double
		lineageTag: a6d3d740-52cc-4673-b33b-d6cb116b93c9
		summarizeBy: sum
		sourceColumn: ConsumedQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ResourceId
		dataType: string
		lineageTag: c1350c07-1c3e-4e45-a106-ae2bc5ba1fd7
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column ResourceName
		dataType: string
		lineageTag: b9d04ea6-bd9f-48b5-b827-f2c62598c978
		summarizeBy: none
		sourceColumn: ResourceName

		annotation SummarizationSetBy = Automatic

	column x_AccountType
		dataType: string
		lineageTag: 3f409722-0af4-47a6-b4c0-9c7baf2cda1c
		summarizeBy: none
		sourceColumn: x_AccountType

		annotation SummarizationSetBy = Automatic

	column x_CommittedQuantity
		dataType: double
		lineageTag: 28190ab6-e6b7-465a-a8a4-cfa4c089d1e1
		summarizeBy: sum
		sourceColumn: x_CommittedQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CommittedQuantityTotal
		dataType: double
		lineageTag: 33d615e9-16a4-4218-92fd-20d9528711a4
		summarizeBy: sum
		sourceColumn: x_CommittedQuantityTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_DatasetType
		dataType: string
		lineageTag: 01cb61ad-a48a-4044-9af1-c31d189545ea
		summarizeBy: none
		sourceColumn: x_DatasetType

		annotation SummarizationSetBy = Automatic

	column x_DatasetVersion
		dataType: string
		lineageTag: ce527d2a-3d33-4eba-828a-6906caafbcba
		summarizeBy: none
		sourceColumn: x_DatasetVersion

		annotation SummarizationSetBy = Automatic

	column x_IncrementalRefreshDate
		dataType: string
		lineageTag: 7631c2d6-b330-42de-8588-967752ced645
		summarizeBy: none
		sourceColumn: x_IncrementalRefreshDate

		annotation SummarizationSetBy = Automatic

	column x_InstanceFlexibilityGroup
		dataType: string
		lineageTag: 20d5233f-4bf7-4b03-b90f-70a9898c4bce
		summarizeBy: none
		sourceColumn: x_InstanceFlexibilityGroup

		annotation SummarizationSetBy = Automatic

	column x_InstanceFlexibilityRatio
		dataType: double
		lineageTag: ed6e9d02-72e7-47b2-ba64-4df46ec71566
		summarizeBy: sum
		sourceColumn: x_InstanceFlexibilityRatio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_SkuName
		dataType: string
		lineageTag: 2360c6ed-ba22-45ac-afa2-7212c380a8e2
		summarizeBy: none
		sourceColumn: x_SkuName

		annotation SummarizationSetBy = Automatic

	column x_SkuOrderId
		dataType: string
		lineageTag: 8c59ab78-c210-41f8-95a9-81591348d749
		summarizeBy: none
		sourceColumn: x_SkuOrderId

		annotation SummarizationSetBy = Automatic

	partition ReservationDetails = m
		mode: import
		queryGroup: Storage
		source = ```
				let
				    // Get the data
				    RawData = ftk_Storage("reservationdetails"),
				
				    FixTypes = Table.TransformColumnTypes(
				        Table.ReplaceValue(Table.ReplaceValue(RawData, 
				            // Clear "NA" values
				            "NA", null, Replacer.ReplaceValue, {"InstanceFlexibilityGroup", "SkuName"}),
				            // Use fully-qulified resrvation ID
				            each [ReservationId], each if Text.StartsWith([ReservationId], "/") then [ReservationId] else "/providers/Microsoft.Capacity/resrvationOrders/" & [ReservationOrderId] & "/resrvationOrders/" & [ReservationId], Replacer.ReplaceValue, {"ReservationId"}),
				        {
				            // Dates
				            {"UsageDate",                type datetime},
				            // Numbers
				            {"InstanceFlexibilityRatio", type number},
				            {"ReservedHours",            type number},
				            {"TotalReservedQuantity",    type number},
				            {"UsedHours",                type number}
				        }
				    ),
				
				    Rename = Table.RenameColumns(FixTypes, {
				        { "InstanceFlexibilityGroup", "x_InstanceFlexibilityGroup" },
				        { "InstanceFlexibilityRatio", "x_InstanceFlexibilityRatio" },
				        { "InstanceId",               "ResourceId" },
				        { "Kind",                     "CommitmentDiscountType" },
				        { "ReservationId",            "CommitmentDiscountId" },
				        { "ReservationOrderId",       "x_SkuOrderId" },
				        { "ReservedHours",            "x_CommittedQuantity" },
				        { "SkuName",                  "x_SkuName" },
				        { "TotalReservedQuantity",    "x_CommittedQuantityTotal" },
				        { "UsageDate",                "ChargePeriodStart" },
				        { "UsedHours",                "ConsumedQuantity" }
				    }, MissingField.Ignore),
				    Add = Table.AddColumn(Table.AddColumn(Rename,
				        "ResourceName",               each if [ResourceId] <> null then ftk_ParseResourceName([ResourceId]) else null),
				        "CommitmentDiscountCategory", each "Usage"),
				        
				    // Sort columns alphabetically
				    Output = Table.ReorderColumns(Add, List.Sort(Table.ColumnNames(Add)))
				in
				    Output
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

