table Resources
	lineageTag: ec447c64-6e55-41d8-a5ea-a43adab5dc79

	column id
		dataType: string
		lineageTag: f2fe893c-5928-43aa-ad1f-b56b552c0e9f
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 1bdfa520-9413-4134-88de-d9b01fae9770
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: f7306763-dc3d-4aed-8237-8643a0609e2c
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 8f0794a6-19ac-4b05-8dee-7d7a19648cc2
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: ec12e42d-a7db-4b86-931e-0a5c135084c8
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 8f241632-6530-4e51-b27e-7b7ff6cb13ee
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 7d74d9e0-c4ff-478c-a548-8a23d16eb327
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: e4e0cd67-cb43-426a-b339-49110fbb9386
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 141f2061-f795-412e-91d7-8d8320255709
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column 'sku.name'
		dataType: string
		lineageTag: 5b3a78b6-0bcc-41a4-9031-72d0954b6a20
		summarizeBy: none
		sourceColumn: sku.name

		annotation SummarizationSetBy = Automatic

	column 'sku.tier'
		dataType: string
		lineageTag: 14414c55-72e8-4d02-abe4-d5e540cb70e7
		summarizeBy: none
		sourceColumn: sku.tier

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: c222026e-b9c4-4137-872a-d47d16b9c687
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column provisioningState
		dataType: string
		lineageTag: bdae7404-05e2-4633-931b-bcaaaf1118b4
		summarizeBy: none
		sourceColumn: provisioningState

		annotation SummarizationSetBy = Automatic

	column privateEndpointConnections
		dataType: string
		lineageTag: 591481b4-5573-44c2-8565-2d8d0bcb9545
		summarizeBy: none
		sourceColumn: privateEndpointConnections

		annotation SummarizationSetBy = Automatic

	column encryption
		dataType: string
		lineageTag: d07f85c5-81b8-4436-9823-3e7ca3f45a91
		summarizeBy: none
		sourceColumn: encryption

		annotation SummarizationSetBy = Automatic

	column creationTime
		dataType: string
		lineageTag: e23ab9bd-b7c9-42f5-b9e2-f4cb152769df
		summarizeBy: none
		sourceColumn: creationTime

		annotation SummarizationSetBy = Automatic

	column supportsHttpsTrafficOnly
		dataType: string
		lineageTag: 7ea5fb91-f3c4-4ff6-aa1f-a1d21e4ceace
		summarizeBy: none
		sourceColumn: supportsHttpsTrafficOnly

		annotation SummarizationSetBy = Automatic

	column allowBlobPublicAccess
		dataType: string
		lineageTag: 9f62c910-5d82-4bf7-abd8-898128727bf0
		summarizeBy: none
		sourceColumn: allowBlobPublicAccess

		annotation SummarizationSetBy = Automatic

	column minimumTlsVersion
		dataType: string
		lineageTag: 2222bc49-a5f3-4d5e-8ea6-91f3623e6b87
		summarizeBy: none
		sourceColumn: minimumTlsVersion

		annotation SummarizationSetBy = Automatic

	column primaryEndpoints
		dataType: string
		lineageTag: 8c14172c-90d4-4988-bc6a-d1a901b9353b
		summarizeBy: none
		sourceColumn: primaryEndpoints

		annotation SummarizationSetBy = Automatic

	column keyCreationTime
		dataType: string
		lineageTag: 9e84d8f5-4184-426d-8074-01962d351568
		summarizeBy: none
		sourceColumn: keyCreationTime

		annotation SummarizationSetBy = Automatic

	column primaryLocation
		dataType: string
		lineageTag: 799d5f2a-6909-44a2-85ec-0fee794e9f32
		summarizeBy: none
		sourceColumn: primaryLocation

		annotation SummarizationSetBy = Automatic

	column statusOfPrimary
		dataType: string
		lineageTag: 74fd04cb-863b-4405-aa39-ffc7729a7ed2
		summarizeBy: none
		sourceColumn: statusOfPrimary

		annotation SummarizationSetBy = Automatic

	column networkAcls
		dataType: string
		lineageTag: 3239e69d-a30f-44ff-948f-e717c68cd3d1
		summarizeBy: none
		sourceColumn: networkAcls

		annotation SummarizationSetBy = Automatic

	column allowCrossTenantReplication
		dataType: string
		lineageTag: d0ac6d80-6fee-48f8-ba9f-bd17f4f3632d
		summarizeBy: none
		sourceColumn: allowCrossTenantReplication

		annotation SummarizationSetBy = Automatic

	column allowSharedKeyAccess
		dataType: string
		lineageTag: 4525b8cf-8c02-4c8f-9f47-d52904bd4a2c
		summarizeBy: none
		sourceColumn: allowSharedKeyAccess

		annotation SummarizationSetBy = Automatic

	column accessTier
		dataType: string
		lineageTag: c7710043-6993-4bbb-8cb8-fe2d4fe99a0b
		summarizeBy: none
		sourceColumn: accessTier

		annotation SummarizationSetBy = Automatic

	column isHnsEnabled
		dataType: string
		lineageTag: fe38ab5a-f459-43df-afd2-279d79acc04b
		summarizeBy: none
		sourceColumn: isHnsEnabled

		annotation SummarizationSetBy = Automatic

	column isBlueShiftAccount
		dataType: string
		lineageTag: dabdceb1-fa09-40cc-befc-5e66f5feceab
		summarizeBy: none
		sourceColumn: isBlueShiftAccount

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 13d268dd-c5da-4683-bff4-c2469e828078
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: e00e53ed-8071-4665-8f4c-5b359ec05219
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: c71fdf86-ee23-43a5-9e86-4de61d8c5442
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 6aa596ff-5a0e-4783-8ec7-aa20056594ae
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition Resources = m
		mode: import
		queryGroup: 'Resource Graph'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "privateEndpointConnections", "encryption", "creationTime", "supportsHttpsTrafficOnly", "allowBlobPublicAccess", "minimumTlsVersion", "primaryEndpoints", "keyCreationTime", "primaryLocation", "statusOfPrimary", "networkAcls", "allowCrossTenantReplication", "allowSharedKeyAccess", "accessTier", "isHnsEnabled", "isBlueShiftAccount"}, {"provisioningState", "privateEndpointConnections", "encryption", "creationTime", "supportsHttpsTrafficOnly", "allowBlobPublicAccess", "minimumTlsVersion", "primaryEndpoints", "keyCreationTime", "primaryLocation", "statusOfPrimary", "networkAcls", "allowCrossTenantReplication", "allowSharedKeyAccess", "accessTier", "isHnsEnabled", "isBlueShiftAccount"}),
				  #"Expanded sku" = Table.ExpandRecordColumn(#"Expanded properties", "sku", {"name", "tier"}, {"sku.name", "sku.tier"})
				in
				  #"Expanded sku"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

