// Azure AI Foundry platform metrics for the FinOps hub dashboard.

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { buildFoundryPriceCatalogQuery, readBoundedBody } from "./kusto.mjs";

const execFileAsync = promisify(execFile);
const ARM_RESOURCE = "https://management.azure.com/";
const METRICS_RESOURCE = "https://metrics.monitor.azure.com/";
const LOGS_RESOURCE = "https://api.loganalytics.io";
const RESOURCE_GRAPH_API = "2022-10-01";
const COGNITIVE_SERVICES_API = "2024-10-01";
const METRICS_API = "2023-10-01";
const TOKEN_REFRESH_SKEW_MS = 2 * 60 * 1000;
const TOKEN_TIMEOUT_MS = 15000;
const TOKEN_MAX_BUFFER = 1024 * 1024;
const MAX_ACCOUNTS = 500;
const MAX_AGENT_DISCOVERY_RESOURCES = 1000;
const MAX_ARM_BATCH_REQUESTS = 20;
const MAX_BATCH_RESOURCES = 50;
const MAX_LOG_QUERY_WORKSPACES = 100;
const MAX_SERIES_PER_RESOURCE = 500;
const MAX_RESPONSE_BYTES = 16 * 1024 * 1024;
const AZURE_REQUEST_CONCURRENCY = 8;
const AGENT_CACHE_TTL_MS = 30 * 1000;
const agentCacheByLoader = new WeakMap();
const foundryCacheByLoader = new WeakMap();

export const FOUNDRY_PRESETS = Object.freeze({
  "24h": { durationMs: 24 * 60 * 60 * 1000, interval: "PT15M", label: "24 hours" },
  "7d": { durationMs: 7 * 24 * 60 * 60 * 1000, interval: "PT1H", label: "7 days" },
  "30d": { durationMs: 30 * 24 * 60 * 60 * 1000, interval: "PT6H", label: "30 days" },
  "93d": { durationMs: 93 * 24 * 60 * 60 * 1000, interval: "P1D", label: "93 days" },
});

export const FOUNDRY_PANEL_CONTRACT = Object.freeze([
  {
    id: 13,
    title: "Estimated Cost",
    type: "stat",
    gridPos: { h: 4, w: 24, x: 0, y: 0 },
    unit: "currency",
    description: "Estimated input and output token cost by model. Rates come from eligible FinOps Hub Prices() rows.",
  },
  {
    id: 11,
    title: "Input Tokens (total)",
    type: "stat",
    gridPos: { h: 5, w: 24, x: 0, y: 4 },
    unit: "short",
    description: "Number of prompt tokens processed by model deployment.",
  },
  {
    id: 12,
    title: "Output Tokens (total)",
    type: "stat",
    gridPos: { h: 5, w: 24, x: 0, y: 9 },
    unit: "short",
    description: "Number of tokens generated by model deployment.",
  },
  {
    id: 2,
    title: "Model Requests",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 0, y: 14 },
    unit: "short",
    style: "bars",
    fillOpacity: 60,
    description: "Number of model inference requests by deployment.",
  },
  {
    id: 16,
    title: "Non-200 Model Requests (Throttling & Errors)",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 12, y: 14 },
    unit: "short",
    style: "bars",
    fillOpacity: 80,
    description: "Model requests that did not return HTTP 200, split by status code.",
  },
  {
    id: 7,
    title: "Average Latency (Time to Last Byte)",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 0, y: 24 },
    unit: "ms",
    style: "lines",
    fillOpacity: 21,
    description: "Average time to receive the last byte of a model response.",
  },
  {
    id: 17,
    title: "Tokens per Second (OpenAI models)",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 12, y: 24 },
    unit: "short",
    style: "lines",
    fillOpacity: 10,
    description: "Average generation throughput by Azure OpenAI deployment.",
  },
  {
    id: 4,
    title: "Input Tokens",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 0, y: 34 },
    unit: "short",
    style: "bars",
    fillOpacity: 60,
    description: "Prompt tokens processed by model deployment over time.",
  },
  {
    id: 5,
    title: "Output Tokens",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 12, y: 34 },
    unit: "short",
    style: "bars",
    fillOpacity: 60,
    description: "Tokens generated by model deployment over time.",
  },
  {
    id: 8,
    title: "Total Tokens",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 0, y: 44 },
    unit: "short",
    style: "bars",
    fillOpacity: 60,
    description: "Inference tokens processed by model deployment over time.",
  },
  {
    id: 14,
    title: "Token Cache Match Rate (OpenAI models)",
    type: "timeseries",
    gridPos: { h: 10, w: 12, x: 12, y: 44 },
    unit: "percent",
    style: "lines",
    fillOpacity: 21,
    description: "Percentage of prompt tokens that matched the Azure OpenAI prompt cache.",
  },
]);

export const AGENT_PANEL_CONTRACT = Object.freeze([
  { id: "summary", title: "Summary statistics", type: "stats" },
  { id: "tokens", title: "Token consumption over time", type: "timeseries", unit: "short" },
  { id: "cost", title: "Daily estimated run cost", type: "timeseries", unit: "currency" },
  { id: "cache", title: "Cache behavior", type: "stats", unit: "percent" },
  { id: "finish", title: "Chat finish reasons", type: "table" },
  { id: "model-latency", title: "Model latency", type: "table", unit: "ms" },
  { id: "tools", title: "Tool usage leaderboard", type: "table" },
  { id: "response", title: "Agent response trends", type: "timeseries", unit: "ms" },
  { id: "success", title: "Success, errors, and throughput", type: "timeseries" },
  { id: "performance", title: "Agent performance", type: "table" },
  { id: "runs", title: "Recent runs", type: "table" },
  { id: "errors", title: "Recent errors", type: "table" },
]);

const METRIC_GROUPS = Object.freeze([
  {
    id: "foundry",
    metricNames: [
      "InputTokens",
      "OutputTokens",
      "TotalTokens",
      "ModelRequests",
      "TimeToLastByte",
      "AzureOpenAITTLTInMS",
      "AzureOpenAITokenPerSecond",
      "AzureOpenAIContextTokensCacheMatchRate",
    ],
    aggregation: "Total,Average",
    filter: "ModelDeploymentName eq '*' and ModelName eq '*' and ModelVersion eq '*' and StatusCode eq '*'",
  },
]);

const tokenCache = new Map();

export function normalizeAzureTenantId(value) {
  const tenantId = String(value ?? "").trim().toLowerCase();
  if (!tenantId) throw new Error("Tenant ID is required for AI Foundry discovery and monitoring.");
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(tenantId)) {
    throw new Error("Tenant ID must be a valid Microsoft Entra tenant GUID.");
  }
  return tenantId;
}

export function azureMonitorTokenArgs(resource, tenantId) {
  if (![ARM_RESOURCE, METRICS_RESOURCE, LOGS_RESOURCE].includes(resource)) {
    throw new Error("Unsupported Azure token resource.");
  }
  return [
    "account", "get-access-token",
    "--resource", resource,
    "--tenant", normalizeAzureTenantId(tenantId),
    "--output", "json",
  ];
}

function parseTokenExpiry(payload) {
  const raw = payload.expires_on ?? payload.expiresOn;
  if (typeof raw === "number" || /^\d+$/.test(String(raw ?? ""))) {
    const seconds = Number(raw);
    if (Number.isFinite(seconds)) return seconds * 1000;
  }
  const parsed = Date.parse(String(raw ?? ""));
  return Number.isFinite(parsed) ? parsed : Date.now() + 5 * 60 * 1000;
}

async function getAzureCliToken(resource, tenantId, options = {}) {
  const normalizedTenant = normalizeAzureTenantId(tenantId);
  const key = `${normalizedTenant}|${resource}`;
  const cached = tokenCache.get(key);
  if (cached && cached.expiresAt - TOKEN_REFRESH_SKEW_MS > Date.now()) return cached.token;

  const run = options.execFileFn || execFileAsync;
  let stdout;
  try {
    ({ stdout } = await run("az", azureMonitorTokenArgs(resource, normalizedTenant), {
      timeout: TOKEN_TIMEOUT_MS,
      maxBuffer: TOKEN_MAX_BUFFER,
    }));
  } catch (error) {
    throw new Error(`Azure CLI could not acquire an Azure Monitor token for tenant ${normalizedTenant}: ${error.message}`);
  }

  let payload;
  try {
    payload = JSON.parse(stdout);
  } catch {
    throw new Error("Azure CLI returned invalid token JSON.");
  }
  const token = payload.accessToken ?? payload.access_token;
  if (typeof token !== "string" || !token) throw new Error("Azure CLI returned no access token.");
  tokenCache.set(key, { token, expiresAt: parseTokenExpiry(payload) });
  return token;
}

function azureErrorMessages(error, messages = []) {
  if (!error || typeof error !== "object") return messages;
  if (error.message) messages.push(error.message);
  for (const detail of error.details || []) azureErrorMessages(detail, messages);
  return azureErrorMessages(error.innererror, messages);
}

async function fetchJson(url, init, context, options = {}) {
  const fetchFn = options.fetchFn || fetch;
  const response = await fetchFn(url, init);
  const text = await readBoundedBody(response, options.maxResponseBytes || MAX_RESPONSE_BYTES);
  let payload;
  try {
    payload = text ? JSON.parse(text) : {};
  } catch {
    throw new Error(`${context} returned invalid JSON.`);
  }
  if (!response.ok) {
    const detail = [
      ...azureErrorMessages(payload?.error),
      payload?.message,
    ].filter(Boolean).filter((item, index, items) => items.indexOf(item) === index).join(" ")
      || `${response.status} ${response.statusText}`;
    throw new Error(`${context} failed: ${detail}`);
  }
  return payload;
}

export async function listFoundryAccounts(tenantId, options = {}) {
  const token = await getAzureCliToken(ARM_RESOURCE, tenantId, options);
  const payload = await fetchJson(
    `https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=${RESOURCE_GRAPH_API}`,
    {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        query: `Resources
| where type =~ 'microsoft.cognitiveservices/accounts'
| where kind in~ ('OpenAI', 'AIServices')
| project id, name, resourceGroup, subscriptionId, location=tolower(location), kind, sku=tostring(sku.name)
| order by name asc
| take ${MAX_ACCOUNTS}`,
        options: { resultFormat: "objectArray" },
      }),
    },
    "Azure Resource Graph account discovery",
    options
  );
  const rows = Array.isArray(payload.data) ? payload.data : [];
  return rows.map((row) => ({
    id: normalizeResourceId(row.id),
    name: String(row.name || ""),
    resourceGroup: String(row.resourceGroup || ""),
    subscriptionId: String(row.subscriptionId || "").toLowerCase(),
    location: String(row.location || "").toLowerCase(),
    kind: String(row.kind || ""),
    sku: String(row.sku || ""),
  })).filter((row) =>
    row.id && row.name && row.subscriptionId && /^[a-z0-9-]+$/.test(row.location)
  );
}

export async function listMonitorWorkspaces(tenantId, options = {}) {
  const token = await getAzureCliToken(ARM_RESOURCE, tenantId, options);
  const payload = await fetchJson(
    `https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=${RESOURCE_GRAPH_API}`,
    {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        query: `Resources
| where type =~ 'microsoft.operationalinsights/workspaces'
| project id, name, resourceGroup, subscriptionId, location=tolower(location), customerId=tostring(properties.customerId)
| order by subscriptionId asc, resourceGroup asc, name asc`,
        options: { resultFormat: "objectArray" },
      }),
    },
    "Azure Resource Graph workspace discovery",
    options
  );
  const workspaces = new Map();
  for (const row of Array.isArray(payload.data) ? payload.data : []) {
    const id = String(row.id || "").trim().replace(/\/+$/, "");
    if (!/^\/subscriptions\/[^/]+\/resourceGroups\/[^/]+\/providers\/microsoft\.operationalinsights\/workspaces\/[^/]+$/i.test(id)) {
      continue;
    }
    const key = id.toLowerCase();
    if (workspaces.has(key)) continue;
    const parts = id.split("/");
    workspaces.set(key, {
      id,
      name: String(row.name || parts.at(-1) || ""),
      resourceGroup: String(row.resourceGroup || parts[4] || ""),
      subscriptionId: String(row.subscriptionId || parts[2] || "").toLowerCase(),
      location: String(row.location || "").toLowerCase(),
      customerId: String(row.customerId || "").toLowerCase(),
    });
  }
  return [...workspaces.values()];
}

export async function listAgentResources(tenantId, options = {}) {
  const token = await getAzureCliToken(ARM_RESOURCE, tenantId, options);
  const payload = await fetchJson(
    `https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=${RESOURCE_GRAPH_API}`,
    {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        query: `Resources
| where type in~ (
    'microsoft.cognitiveservices/accounts',
    'microsoft.cognitiveservices/accounts/deployments',
    'microsoft.cognitiveservices/accounts/projects',
    'microsoft.insights/components',
    'microsoft.operationalinsights/workspaces')
| extend ResourceKind=case(
    type =~ 'microsoft.cognitiveservices/accounts', 'account',
    type =~ 'microsoft.cognitiveservices/accounts/deployments', 'deployment',
    type =~ 'microsoft.cognitiveservices/accounts/projects', 'project',
    type =~ 'microsoft.insights/components', 'application-insights',
    'workspace')
| project
    ResourceKind,
    id,
    name,
    resourceGroup,
    subscriptionId,
    location=tolower(location),
    kind,
    sku=tostring(sku.name),
    customerId=tostring(properties.customerId),
    workspaceResourceId=tostring(properties.WorkspaceResourceId),
    modelName=tostring(properties.model.name),
    modelVersion=tostring(properties.model.version),
    modelFormat=tostring(properties.model.format),
    provisioningState=tostring(properties.provisioningState)
| order by ResourceKind asc, id asc
| take ${MAX_AGENT_DISCOVERY_RESOURCES}`,
        options: { resultFormat: "objectArray", $top: MAX_AGENT_DISCOVERY_RESOURCES },
      }),
    },
    "Azure Resource Graph agent discovery",
    options
  );
  const accounts = [];
  const applicationInsights = [];
  const projects = [];
  const workspaces = [];
  const deploymentsByAccount = new Map();
  for (const row of Array.isArray(payload.data) ? payload.data : []) {
    const kind = String(row.ResourceKind || "").toLowerCase();
    const id = String(row.id || "").trim().replace(/\/+$/, "");
    if (kind === "application-insights") {
      applicationInsights.push({
        id: id.toLowerCase(),
        workspaceResourceId: String(row.workspaceResourceId || "").trim().replace(/\/+$/, "").toLowerCase(),
      });
      continue;
    }
    if (kind === "project") {
      projects.push({ id, name: String(row.name || id.split("/").at(-1) || "") });
      continue;
    }
    if (kind === "account") {
      const accountId = normalizeResourceId(id);
      const account = {
        id: accountId,
        name: String(row.name || ""),
        resourceGroup: String(row.resourceGroup || ""),
        subscriptionId: String(row.subscriptionId || "").toLowerCase(),
        location: String(row.location || "").toLowerCase(),
        kind: String(row.kind || ""),
        sku: String(row.sku || ""),
      };
      if (account.id && account.name && account.subscriptionId && /^[a-z0-9-]+$/.test(account.location)) {
        accounts.push(account);
        deploymentsByAccount.set(account.id.toLowerCase(), []);
      }
      continue;
    }
    if (kind === "workspace") {
      if (!/^\/subscriptions\/[^/]+\/resourceGroups\/[^/]+\/providers\/microsoft\.operationalinsights\/workspaces\/[^/]+$/i.test(id)) {
        continue;
      }
      workspaces.push({
        id,
        name: String(row.name || id.split("/").at(-1) || ""),
        resourceGroup: String(row.resourceGroup || ""),
        subscriptionId: String(row.subscriptionId || "").toLowerCase(),
        location: String(row.location || "").toLowerCase(),
        customerId: String(row.customerId || "").toLowerCase(),
      });
      continue;
    }
    const marker = id.toLowerCase().lastIndexOf("/deployments/");
    if (kind !== "deployment" || marker < 0) continue;
    const accountId = id.slice(0, marker).toLowerCase();
    const deployments = deploymentsByAccount.get(accountId);
    if (!deployments) continue;
    const name = String(row.name || id.slice(marker + "/deployments/".length)).split("/").at(-1);
    if (!name) continue;
    deployments.push({
      name,
      skuName: String(row.sku || ""),
      modelName: String(row.modelName || ""),
      modelVersion: String(row.modelVersion || ""),
      modelFormat: String(row.modelFormat || ""),
      provisioningState: String(row.provisioningState || ""),
    });
  }
  const connectionDiscovery = await listFoundryProjectApplicationInsights(projects, token, options);
  const linkedWorkspaceIds = new Set(applicationInsights
    .filter((component) => connectionDiscovery.resourceIds.has(component.id))
    .map((component) => component.workspaceResourceId)
    .filter(Boolean));
  return {
    accounts,
    diagnostics: connectionDiscovery.diagnostics,
    deploymentsByAccount,
    workspaces: [...new Map(workspaces
      .filter((workspace) => linkedWorkspaceIds.has(workspace.id.toLowerCase()))
      .map((workspace) => [workspace.id.toLowerCase(), workspace])).values()],
  };
}

async function listFoundryProjectApplicationInsights(projects, token, options) {
  const resourceIds = new Set();
  const diagnostics = [];
  const batches = chunked(projects, MAX_ARM_BATCH_REQUESTS);
  await mapWithConcurrency(batches, async (batch) => {
    const payload = await fetchJson(
      "https://management.azure.com/batch?api-version=2020-06-01",
      {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          requests: batch.map((project) => ({
            httpMethod: "GET",
            relativeUrl: `${project.id}/connections?category=AppInsights&api-version=2025-06-01`,
          })),
        }),
      },
      "Microsoft Foundry project connection discovery",
      options
    );
    batch.forEach((project, index) => {
      const response = payload.responses?.[index];
      if (!response || response.httpStatusCode < 200 || response.httpStatusCode >= 300) {
        diagnostics.push({
          stage: "connection-discovery",
          status: "unavailable",
          resourceId: project.id,
          resourceName: project.name,
          message: response?.content?.error?.message || "Azure Resource Manager did not return project connections.",
        });
        return;
      }
      for (const connection of response.content?.value || []) {
        const target = String(connection.properties?.target || connection.properties?.metadata?.ResourceId || "")
          .trim().replace(/\/+$/, "").toLowerCase();
        if (String(connection.properties?.category || "").toLowerCase() === "appinsights" &&
          /^\/subscriptions\/[^/]+\/resourcegroups\/[^/]+\/providers\/microsoft\.insights\/components\/[^/]+$/.test(target)) {
          resourceIds.add(target);
        }
      }
    });
  }, Math.min(8, batches.length));
  return { resourceIds, diagnostics };
}

export async function listFoundryDeployments(account, tenantId, options = {}) {
  const token = await getAzureCliToken(ARM_RESOURCE, tenantId, options);
  const payload = await fetchJson(
    `https://management.azure.com${account.id}/deployments?api-version=${COGNITIVE_SERVICES_API}`,
    {
      method: "GET",
      headers: { Authorization: `Bearer ${token}`, Accept: "application/json" },
    },
    `AI Foundry deployment discovery for ${account.name}`,
    options
  );
  return (payload.value || []).slice(0, MAX_ACCOUNTS).map((deployment) => ({
    name: String(deployment.name || ""),
    skuName: String(deployment.sku?.name || ""),
    modelName: String(deployment.properties?.model?.name || ""),
    modelVersion: String(deployment.properties?.model?.version || ""),
    modelFormat: String(deployment.properties?.model?.format || ""),
    provisioningState: String(deployment.properties?.provisioningState || ""),
  })).filter((deployment) => deployment.name);
}

export async function listFoundryDeploymentsBatch(accounts, tenantId, options = {}) {
  const deploymentsByAccount = new Map(accounts.map((account) => [account.id.toLowerCase(), []]));
  const diagnostics = [];
  if (!accounts.length) return { deploymentsByAccount, diagnostics };
  const token = await getAzureCliToken(ARM_RESOURCE, tenantId, options);
  const batches = chunked(accounts, MAX_ARM_BATCH_REQUESTS);
  await mapWithConcurrency(batches, async (batch) => {
    const payload = await fetchJson(
      "https://management.azure.com/batch?api-version=2020-06-01",
      {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          requests: batch.map((account) => ({
            httpMethod: "GET",
            relativeUrl: `${account.id}/deployments?api-version=${COGNITIVE_SERVICES_API}`,
          })),
        }),
      },
      "AI Foundry deployment batch discovery",
      options
    );
    const responses = Array.isArray(payload.responses) ? payload.responses : [];
    batch.forEach((account, index) => {
      const response = responses[index];
      if (!response || response.httpStatusCode < 200 || response.httpStatusCode >= 300) {
        diagnostics.push({
          stage: "deployment-discovery",
          status: "unavailable",
          resourceId: account.id,
          resourceName: account.name,
          message: response?.content?.error?.message || "Azure Resource Manager did not return deployment metadata.",
        });
        return;
      }
      deploymentsByAccount.set(
        account.id.toLowerCase(),
        (response.content?.value || []).slice(0, MAX_ACCOUNTS).map((deployment) => ({
          name: String(deployment.name || ""),
          skuName: String(deployment.sku?.name || ""),
          modelName: String(deployment.properties?.model?.name || ""),
          modelVersion: String(deployment.properties?.model?.version || ""),
          modelFormat: String(deployment.properties?.model?.format || ""),
          provisioningState: String(deployment.properties?.provisioningState || ""),
        })).filter((deployment) => deployment.name)
      );
    });
  }, Math.min(8, batches.length));
  return { deploymentsByAccount, diagnostics };
}

function normalizeResourceId(resourceId) {
  const value = String(resourceId || "").trim().replace(/\/+$/, "");
  return /^\/subscriptions\/[^/]+\/resourceGroups\/[^/]+\/providers\/microsoft\.cognitiveservices\/accounts\/[^/]+$/i.test(value)
    ? value
    : null;
}

function idsEqual(left, right) {
  return String(left || "").replace(/\/+$/, "").toLowerCase()
    === String(right || "").replace(/\/+$/, "").toLowerCase();
}

async function mapWithConcurrency(items, worker, concurrency = AZURE_REQUEST_CONCURRENCY) {
  const results = new Array(items.length);
  let cursor = 0;
  async function run() {
    while (cursor < items.length) {
      const index = cursor++;
      results[index] = await worker(items[index], index);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, run));
  return results;
}

function foundryMetricWindow(preset, options = {}) {
  const config = FOUNDRY_PRESETS[preset];
  if (!config) throw new Error(`Unknown AI Foundry time preset '${preset}'.`);
  const endDate = options.now ? new Date(options.now) : new Date();
  if (!Number.isFinite(endDate.getTime())) throw new Error("AI Foundry query end time is invalid.");
  return {
    preset,
    label: config.label,
    start: new Date(endDate.getTime() - config.durationMs).toISOString(),
    end: endDate.toISOString(),
    interval: config.interval,
  };
}

function agentNumber(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : 0;
}

function foundryConnectionKey(connection, database) {
  const cluster = typeof connection === "string"
    ? connection
    : connection?.clusterUri || connection?.endpoint || connection?.cluster || "";
  return `${String(cluster).trim().toLowerCase()}|${String(database || "").trim().toLowerCase()}`;
}

function agentsCache(loader) {
  let cache = agentCacheByLoader.get(loader);
  if (!cache) {
    cache = new Map();
    agentCacheByLoader.set(loader, cache);
  }
  return cache;
}

function foundryCache(loader) {
  let cache = foundryCacheByLoader.get(loader);
  if (!cache) {
    cache = new Map();
    foundryCacheByLoader.set(loader, cache);
  }
  return cache;
}

function agentTelemetryDeclarations(options, baseExpression) {
  const start = new Date(options.start);
  const end = new Date(options.end);
  if (!Number.isFinite(start.getTime()) || !Number.isFinite(end.getTime()) || start >= end) {
    throw new Error("Agent telemetry requires a valid start and end time.");
  }
  const bucket = end.getTime() - start.getTime() <= 24 * 60 * 60 * 1000
    ? "15m"
    : end.getTime() - start.getTime() <= 7 * 24 * 60 * 60 * 1000
      ? "1h"
      : end.getTime() - start.getTime() <= 30 * 24 * 60 * 60 * 1000 ? "6h" : "1d";
  return `let StartTime = datetime(${start.toISOString()});
let EndTime = datetime(${end.toISOString()});
let Bucket = ${bucket};
let Base = materialize(
${baseExpression}
| where TimeGenerated >= datetime(${start.toISOString()}) and TimeGenerated < datetime(${end.toISOString()})
| extend
    SpanName = tostring(column_ifexists('Name', '')),
    SpanProperties = column_ifexists('Properties', dynamic({})),
    SpanSuccess = tobool(column_ifexists('Success', true)),
    SpanDurationMs = todouble(column_ifexists('DurationMs', 0.0))
| extend
    OperationName = tostring(SpanProperties['gen_ai.operation.name']),
    AgentName = tostring(SpanProperties['gen_ai.agent.name']),
    AgentId = tostring(SpanProperties['gen_ai.agent.id']),
    FoundryProjectId = tostring(SpanProperties['microsoft.foundry.project.id']),
    InputTokens = tolong(SpanProperties['gen_ai.usage.input_tokens']),
    CachedInputTokens = tolong(SpanProperties['gen_ai.usage.cache_read.input_tokens']),
    OutputTokens = tolong(SpanProperties['gen_ai.usage.output_tokens']),
    RequestModel = tostring(SpanProperties['gen_ai.request.model']),
    ResponseModel = tostring(SpanProperties['gen_ai.response.model']),
    FinishReason = tostring(SpanProperties['gen_ai.response.finish_reasons']),
    ToolName = tostring(SpanProperties['gen_ai.tool.name']),
    ErrorType = tostring(SpanProperties['error.type'])
| extend
    AgentKey = iff(isnotempty(AgentId), AgentId, AgentName),
    Model = iff(isnotempty(ResponseModel), ResponseModel, RequestModel)
| project
    SourceTable, TimeGenerated, OperationId, SpanName, SpanSuccess, SpanDurationMs,
    OperationName, AgentName, AgentId, FoundryProjectId, InputTokens, CachedInputTokens,
    OutputTokens, Model, FinishReason, ToolName, ErrorType, AgentKey
);
let AgentIdentities = Base
| where isnotempty(AgentKey) and isnotempty(FoundryProjectId)
| project TimeGenerated, OperationId, AgentKey, AgentName, AgentId, FoundryProjectId;
let TraceIdentities = AgentIdentities
| summarize
    TraceAgentCount=dcount(strcat(AgentKey, '|', FoundryProjectId)),
    TraceAgentKey=take_any(AgentKey),
    TraceAgentName=take_any(AgentName),
    TraceAgentId=take_any(AgentId),
    TraceFoundryProjectId=take_any(FoundryProjectId)
    by OperationId;
let AgentInvocations = Base
| where SourceTable endswith 'AppDependencies'
| where SpanName contains 'invoke_agent' or OperationName =~ 'invoke_agent'
| where isnotempty(AgentKey) and isnotempty(FoundryProjectId)
| project
    TimeGenerated, OperationId, AgentKey, AgentName, AgentId, FoundryProjectId,
    DurationMs=SpanDurationMs, Success=SpanSuccess, ErrorType;
let ChatSpans = Base
| where OperationName =~ 'chat'
| lookup kind=leftouter TraceIdentities on OperationId
| extend
    AssignedAgentKey=iff(isnotempty(AgentKey), AgentKey, iff(TraceAgentCount == 1, TraceAgentKey, '')),
    AssignedAgentName=iff(isnotempty(AgentKey), AgentName, iff(TraceAgentCount == 1, TraceAgentName, '')),
    AssignedAgentId=iff(isnotempty(AgentKey), AgentId, iff(TraceAgentCount == 1, TraceAgentId, '')),
    AssignedFoundryProjectId=iff(isnotempty(FoundryProjectId), FoundryProjectId, iff(TraceAgentCount == 1, TraceFoundryProjectId, ''))
| where isnotempty(AssignedAgentKey) and isnotempty(AssignedFoundryProjectId)
| project
    TimeGenerated, OperationId, AgentKey=AssignedAgentKey, AgentName=AssignedAgentName,
    AgentId=AssignedAgentId, FoundryProjectId=AssignedFoundryProjectId,
    Model, InputTokens=max_of(0, InputTokens), CachedInputTokens=max_of(0, CachedInputTokens),
    OutputTokens=max_of(0, OutputTokens), DurationMs=SpanDurationMs, FinishReason;
let ToolSpans = Base
| where OperationName =~ 'execute_tool'
| lookup kind=leftouter TraceIdentities on OperationId
| extend
    AssignedAgentKey=iff(isnotempty(AgentKey), AgentKey, iff(TraceAgentCount == 1, TraceAgentKey, '')),
    AssignedAgentName=iff(isnotempty(AgentKey), AgentName, iff(TraceAgentCount == 1, TraceAgentName, '')),
    AssignedAgentId=iff(isnotempty(AgentKey), AgentId, iff(TraceAgentCount == 1, TraceAgentId, '')),
    AssignedFoundryProjectId=iff(isnotempty(FoundryProjectId), FoundryProjectId, iff(TraceAgentCount == 1, TraceFoundryProjectId, ''))
| where isnotempty(AssignedAgentKey) and isnotempty(AssignedFoundryProjectId)
| project
    TimeGenerated, OperationId, AgentKey=AssignedAgentKey, AgentName=AssignedAgentName,
    AgentId=AssignedAgentId, FoundryProjectId=AssignedFoundryProjectId,
    ToolName, DurationMs=SpanDurationMs, Success=SpanSuccess, ErrorType;
let Activity = AgentIdentities
| summarize
    ActivityEvents=count(),
    LastSeen=max(TimeGenerated)
    by AgentKey, AgentName, AgentId, FoundryProjectId;
let InvocationSummary = AgentInvocations
| summarize
    Operations=count(),
    Successes=countif(Success != false and isempty(ErrorType)),
    Errors=countif(Success == false or isnotempty(ErrorType)),
    TotalDurationMs=sum(DurationMs),
    AverageLatencyMs=avg(DurationMs),
    P95LatencyMs=percentile(DurationMs, 95)
    by AgentKey, FoundryProjectId;
let ChatSummary = ChatSpans
| summarize
    InputTokens=sum(InputTokens),
    CachedInputTokens=sum(CachedInputTokens),
    OutputTokens=sum(OutputTokens)
    by AgentKey, FoundryProjectId;
let AgentSummary = Activity
| lookup kind=leftouter InvocationSummary on AgentKey, FoundryProjectId
| lookup kind=leftouter ChatSummary on AgentKey, FoundryProjectId
| project
    RowType='AgentSummary', AgentKey, AgentName, AgentId, FoundryProjectId, ActivityEvents,
    Operations=coalesce(Operations, 0), Successes=coalesce(Successes, 0), Errors=coalesce(Errors, 0),
    TotalDurationMs=coalesce(TotalDurationMs, 0.0), AverageLatencyMs=coalesce(AverageLatencyMs, 0.0),
    P95LatencyMs=coalesce(P95LatencyMs, 0.0), LastSeen,
    InputTokens=coalesce(InputTokens, 0), CachedInputTokens=coalesce(CachedInputTokens, 0),
    OutputTokens=coalesce(OutputTokens, 0);
let InvocationBuckets = AgentInvocations
| summarize
    Operations=count(), Successes=countif(Success != false and isempty(ErrorType)),
    Errors=countif(Success == false or isnotempty(ErrorType)),
    AverageLatencyMs=avg(DurationMs), P95LatencyMs=percentile(DurationMs, 95)
    by BucketStart=bin(TimeGenerated, Bucket), AgentKey, AgentName, AgentId, FoundryProjectId
| extend RowType='TimeBucket';
let TokenBuckets = ChatSpans
| summarize
    InputTokens=sum(InputTokens), CachedInputTokens=sum(CachedInputTokens),
    OutputTokens=sum(OutputTokens), AverageLatencyMs=avg(DurationMs), P95LatencyMs=percentile(DurationMs, 95)
    by BucketStart=bin(TimeGenerated, Bucket), AgentKey, AgentName, AgentId, FoundryProjectId, Model
| extend RowType='TokenBucket';
let ModelUsage = ChatSpans
| summarize
    Chats=count(), InputTokens=sum(InputTokens), CachedInputTokens=sum(CachedInputTokens),
    OutputTokens=sum(OutputTokens), AverageLatencyMs=avg(DurationMs), P95LatencyMs=percentile(DurationMs, 95),
    LastSeen=max(TimeGenerated)
    by AgentKey, AgentName, AgentId, FoundryProjectId, Model
| extend RowType='ModelUsage';
let FinishReasons = ChatSpans
| extend FinishReason=iff(isempty(FinishReason), '(not reported)', FinishReason)
| summarize Count=count() by AgentKey, AgentName, AgentId, FoundryProjectId, FinishReason
| extend RowType='FinishReason';
let Tools = ToolSpans
| extend ToolName=iff(isempty(ToolName), '(not reported)', ToolName)
| summarize Calls=count(), Errors=countif(Success == false or isnotempty(ErrorType)), AverageLatencyMs=avg(DurationMs)
    by AgentKey, AgentName, AgentId, FoundryProjectId, ToolName
| extend RowType='Tool';
let RunModels = ChatSpans
| summarize
    InputTokens=sum(InputTokens), CachedInputTokens=sum(CachedInputTokens), OutputTokens=sum(OutputTokens)
    by OperationId, AgentKey, FoundryProjectId, Model;
let RecentRuns = AgentInvocations
| join kind=leftouter RunModels on OperationId, AgentKey, FoundryProjectId
| project
    RowType='Run', Timestamp=TimeGenerated, TraceId=OperationId, AgentKey, AgentName, AgentId,
    FoundryProjectId, Model, InputTokens, CachedInputTokens, OutputTokens, DurationMs, Success, ErrorType
| top 100 by Timestamp desc;
let RecentErrors = AgentInvocations
| where Success == false or isnotempty(ErrorType)
| project
    RowType='Error', Timestamp=TimeGenerated, TraceId=OperationId, AgentKey, AgentName, AgentId,
    FoundryProjectId, DurationMs, ErrorType
| top 20 by Timestamp desc;`;
}

const AGENT_TELEMETRY_ROWS = `union
    AgentSummary,
    InvocationBuckets,
    TokenBuckets,
    ModelUsage,
    FinishReasons,
    Tools,
    RecentRuns,
    RecentErrors`;

export function buildAgentTelemetryQuery(options = {}) {
  return `${agentTelemetryDeclarations(
    options,
    "union isfuzzy=true withsource=SourceTable AppDependencies, AppTraces"
  )}
${AGENT_TELEMETRY_ROWS}`;
}

function monitorWorkspaceEntity(workspace) {
  const id = String(workspace?.id || "").trim().replace(/\/+$/, "");
  const name = String(workspace?.name || "").trim();
  if (!/^\/subscriptions\/[^/]+\/resourceGroups\/[^/]+\/providers\/microsoft\.operationalinsights\/workspaces\/[^/]+$/i.test(id)) {
    throw new Error("Agent activity requires valid Log Analytics workspace resource IDs.");
  }
  if (!name || name.length > 63 || !/^[A-Za-z0-9-]+$/.test(name)) {
    throw new Error("Agent activity requires valid Log Analytics workspace names.");
  }
  return `cluster(${JSON.stringify(`https://adx.monitor.azure.com${id}`)}).database(${JSON.stringify(name)})`;
}

export function buildAgentDatasetQuery(discovery, options = {}) {
  const workspaces = discovery?.workspaces || [];
  const accounts = discovery?.accounts || [];
  const deploymentsByAccount = discovery?.deploymentsByAccount || new Map();
  const start = new Date(options.start);
  const end = new Date(options.end);
  if (!Number.isFinite(start.getTime()) || !Number.isFinite(end.getTime()) || start >= end) {
    throw new Error("Agent dataset requires a valid start and end time.");
  }
  const baseExpression = workspaces.length
    ? `macro-expand kind=inner isfuzzy=true MonitorWorkspaces as W
(
    union isfuzzy=true withsource=SourceTable W.AppDependencies, W.AppTraces
)`
    : "datatable(TimeGenerated:datetime, OperationId:string, SourceTable:string)[]";
  const workspaceDeclaration = workspaces.length
    ? `let MonitorWorkspaces = entity_group [
    ${workspaces.map(monitorWorkspaceEntity).join(",\n    ")}
];`
    : "";
  const subscriptionIds = [...new Set(accounts.map((account) => account.subscriptionId).filter(Boolean))];
  const models = [...new Set(accounts.flatMap((account) =>
    (deploymentsByAccount.get(account.id.toLowerCase()) || []).map((deployment) => deployment.modelName)
  ).filter(Boolean))];
  const duration = end.getTime() - start.getTime();
  const costStart = new Date(start.getTime() - duration);
  const priceQuery = buildFoundryPriceCatalogQuery(subscriptionIds, {
    ...options,
    costSource: "CostRows",
    includeCached: true,
    resultName: "PriceRows",
    models,
  });
  return `set query_results_cache_max_age = time(30s);
set best_effort=true;
${workspaceDeclaration}
${agentTelemetryDeclarations(options, baseExpression)}
let AgentRows = ${AGENT_TELEMETRY_ROWS};
let CostStart = datetime(${costStart.toISOString()});
let CostRows = materialize(
    Costs()
    | where ChargePeriodStart >= ago(400d)
);
let BilledCostRows = CostRows
| where ChargePeriodStart >= CostStart and ChargePeriodStart < EndTime
| where x_SkuMeterSubcategory has 'Agent'
| extend AgentResourceId=tolower(ResourceId)
| summarize
    EffectiveCost=sum(EffectiveCost),
    BilledCost=sum(BilledCost),
    ConsumedQuantity=sum(ConsumedQuantity),
    Meter=take_any(x_SkuMeterSubcategory)
    by AgentResourceId, BillingCurrency
| extend RowType='BilledCost';
${priceQuery}
union AgentRows, BilledCostRows, (PriceRows | extend RowType='Price')`;
}

function splitAgentDataset(rows) {
  const telemetryRows = rows.filter((row) => row.RowType !== "Price" && row.RowType !== "BilledCost");
  const billedCosts = rows.filter((row) => row.RowType === "BilledCost");
  const priceRows = rows.filter((row) => row.RowType === "Price");
  const pricesBySubscription = new Map();
  for (const row of priceRows) {
    const subscriptionId = String(row.SubAccountId || "").trim().toLowerCase();
    if (!subscriptionId) continue;
    const prices = pricesBySubscription.get(subscriptionId) || [];
    prices.push(row);
    pricesBySubscription.set(subscriptionId, prices);
  }
  return {
    rows: telemetryRows,
    billedCosts,
    pricesBySubscription,
    pricing: {
      status: priceRows.length ? "available" : "empty",
      errors: [],
      candidateRows: priceRows.length,
      subscriptionsQueried: pricesBySubscription.size,
    },
  };
}

async function loadAgentsShared(connection, database, tenantId, preset, runQueryFn, options = {}) {
  if (typeof runQueryFn !== "function") throw new Error("Agent activity requires a Kusto query runner.");
  const discovery = await listAgentResources(tenantId, options);
  const window = foundryMetricWindow(preset, options);
  const queryOptions = { ...options, start: window.start, end: window.end };
  const resultRows = await runQueryFn(
    connection,
    database,
    buildAgentDatasetQuery(discovery, queryOptions),
    { allowPartialResults: true, maxResponseBytes: MAX_RESPONSE_BYTES }
  );
  const dataset = splitAgentDataset(resultRows);
  const telemetryAccountIds = new Set(dataset.rows
    .map((row) => foundryProjectAccount(row.FoundryProjectId, discovery.accounts)?.id.toLowerCase())
    .filter(Boolean));
  const telemetryAccounts = discovery.accounts.filter((account) =>
    telemetryAccountIds.has(account.id.toLowerCase())
  );
  const deploymentDiscovery = await listFoundryDeploymentsBatch(telemetryAccounts, tenantId, options);
  const deploymentsByAccount = new Map(discovery.accounts.map((account) => {
    const accountId = account.id.toLowerCase();
    const deployments = deploymentDiscovery.deploymentsByAccount.get(accountId) || [];
    return [
      accountId,
      deployments.length ? deployments : discovery.deploymentsByAccount.get(accountId) || [],
    ];
  }));
  return {
    ...dataset,
    accounts: discovery.accounts,
    diagnostics: [
      ...(discovery.diagnostics || []),
      ...(deploymentDiscovery.diagnostics || []),
      ...(resultRows.queryWarnings || []).map((message) => ({
        stage: "workspace-query",
        status: "partial",
        message,
      })),
    ],
    deploymentsByAccount,
    workspaceCount: discovery.workspaces.length,
    window,
  };
}

function getCachedAgentsShared(connection, database, tenantId, preset, runQueryFn, options = {}) {
  const loader = runQueryFn;
  const ttlMs = Math.max(0, Number(options.agentCacheTtlMs ?? AGENT_CACHE_TTL_MS));
  const cache = agentsCache(loader);
  const key = `${tenantId}|${foundryConnectionKey(connection, database)}|${preset}`;
  const now = Date.now();
  const cached = cache.get(key);
  if (!options.bypassAgentCache && cached && (cached.pending || cached.expiresAt > now)) {
    return cached.promise;
  }

  const entry = { pending: true, expiresAt: Number.POSITIVE_INFINITY, promise: null };
  entry.promise = loadAgentsShared(connection, database, tenantId, preset, runQueryFn, options)
    .then((result) => {
      entry.pending = false;
      entry.expiresAt = Date.now() + ttlMs;
      return result;
    })
    .catch((error) => {
      cache.delete(key);
      throw error;
    });
  cache.set(key, entry);
  return entry.promise;
}

function metricBatchUrl(account, group, window) {
  const params = new URLSearchParams({
    starttime: window.start,
    endtime: window.end,
    interval: window.interval,
    metricnamespace: "Microsoft.CognitiveServices/accounts",
    metricnames: group.metricNames.join(","),
    aggregation: group.aggregation,
    top: String(MAX_SERIES_PER_RESOURCE),
    filter: group.filter,
    validateDimensions: "false",
    "api-version": METRICS_API,
  });
  return `https://${account.location}.metrics.monitor.azure.com/subscriptions/${account.subscriptionId}/metrics:getBatch?${params}`;
}

function chunked(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

export async function queryFoundryMetrics(accounts, preset = "7d", options = {}) {
  const accountList = Array.isArray(accounts) ? accounts : [accounts];
  const window = foundryMetricWindow(preset, options);
  if (!accountList.length) return { window, payloads: [], diagnostics: [] };
  const token = await getAzureCliToken(METRICS_RESOURCE, options.tenantId, options);
  const groups = new Map();
  for (const account of accountList) {
    const key = `${account.subscriptionId.toLowerCase()}|${account.location.toLowerCase()}`;
    const group = groups.get(key) || [];
    group.push(account);
    groups.set(key, group);
  }

  const requests = [];
  for (const accountsInRegion of groups.values()) {
    for (const accountBatch of chunked(accountsInRegion, MAX_BATCH_RESOURCES)) {
      for (const metricGroup of METRIC_GROUPS) requests.push({ accountBatch, metricGroup });
    }
  }
  const responses = await mapWithConcurrency(requests, async ({ accountBatch, metricGroup }) => {
    const resourceIds = accountBatch.map((account) => account.id);
    try {
      return {
        group: metricGroup.id,
        resourceIds,
        payload: await fetchJson(
          metricBatchUrl(accountBatch[0], metricGroup, window),
          {
            method: "POST",
            headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
            body: JSON.stringify({ resourceids: resourceIds }),
          },
          `Azure Monitor ${metricGroup.id} metrics`,
          options
        ),
      };
    } catch (error) {
      return { group: metricGroup.id, resourceIds, error: error.message };
    }
  }, Math.min(32, requests.length));

  return {
    window,
    payloads: responses.filter((response) => response.payload),
    diagnostics: responses.filter((response) => response.error).map((response) => ({
      stage: "platform-metrics",
      status: "unavailable",
      resourceIds: response.resourceIds,
      message: response.error,
    })),
  };
}

function metadataMap(values) {
  const output = {};
  for (const item of values || []) {
    const name = item?.name?.value ?? item?.name?.localizedValue;
    if (name) output[String(name).toLowerCase()] = String(item.value ?? "");
  }
  return output;
}

export function flattenMetricBatch(payloads) {
  const rows = [];
  const diagnostics = [];
  for (const item of payloads || []) {
    for (const resource of item?.payload?.values || []) {
      const resourceId = normalizeResourceId(resource?.resourceid || resource?.resourceId)
        || (item.resourceIds?.length === 1 ? normalizeResourceId(item.resourceIds[0]) : null);
      for (const metric of resource?.value || []) {
        const metricName = String(metric?.name?.value || "");
        if (metric.errorCode && metric.errorCode !== "Success") {
          diagnostics.push({
            stage: "platform-metrics",
            status: "unavailable",
            group: item.group,
            resourceId,
            metric: metricName,
            code: metric.errorCode,
            message: metric.errorMessage || "Azure Monitor did not return this metric.",
          });
          continue;
        }
        for (const series of metric.timeseries || []) {
          const metadata = metadataMap(series.metadatavalues);
          for (const point of series.data || []) {
            const value = Number(point.total ?? point.average);
            if (!point.timeStamp || !Number.isFinite(value)) continue;
            const group = item.group === "foundry"
              ? ["InputTokens", "OutputTokens", "TotalTokens"].includes(metricName) ? "tokens"
                : metricName === "ModelRequests" ? "requests"
                  : ["TimeToLastByte", "AzureOpenAITTLTInMS"].includes(metricName) ? "latency"
                    : metricName === "AzureOpenAITokenPerSecond" ? "throughput"
                      : metricName === "AzureOpenAIContextTokensCacheMatchRate" ? "cache"
                        : "unknown"
              : item.group;
            rows.push({
              group,
              resourceId,
              metric: metricName,
              timestamp: point.timeStamp,
              value,
              deployment: metadata.modeldeploymentname || "(unknown deployment)",
              modelName: metadata.modelname || "",
              modelVersion: metadata.modelversion || "",
              statusCode: metadata.statuscode || "",
            });
          }
        }
      }
    }
  }
  return { rows, diagnostics };
}

function inferFoundryDeployments(rows, accounts) {
  const accountIds = new Set(accounts.map((account) => account.id.toLowerCase()));
  const maps = new Map(accounts.map((account) => [account.id.toLowerCase(), new Map()]));
  for (const row of rows || []) {
    const accountId = String(row.resourceId || "").toLowerCase();
    const deploymentName = String(row.deployment || "").trim();
    if (!accountIds.has(accountId) || !deploymentName || deploymentName === "(unknown deployment)") continue;
    const deployments = maps.get(accountId);
    const key = deploymentName.toLowerCase();
    const current = deployments.get(key) || {
      name: deploymentName,
      skuName: "",
      modelName: "",
      modelVersion: "",
      modelFormat: "OpenAI",
      provisioningState: "",
    };
    current.modelName ||= String(row.modelName || "");
    current.modelVersion ||= String(row.modelVersion || "");
    deployments.set(key, current);
  }
  return new Map([...maps].map(([accountId, deployments]) => [accountId, [...deployments.values()]]));
}

function normalizeText(value) {
  return String(value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function priceDirection(row) {
  const text = normalizeText(`${row.Direction || ""} ${row.x_SkuMeterName || ""} ${row.SkuMeter || ""} ${row.x_SkuDescription || ""}`);
  if (text.includes("input") || /\bprompt\b/.test(text)) return "Input";
  if (text.includes("output") || /\b(completion|outp|opt)\b/.test(text)) return "Output";
  return null;
}

function specializedPrice(row) {
  const text = normalizeText(`${row.Variant || ""} ${row.x_SkuMeterName || ""} ${row.SkuMeter || ""} ${row.x_SkuDescription || ""}`);
  return /\b(batch|cached|cache|cd|wr|pp|priority|longco|longcontext|fine tuned|finetuned|training|context|audio|image|video)\b/.test(text);
}

function specializedCachedPrice(row) {
  const text = normalizeText(`${row.x_SkuMeterName || ""} ${row.SkuMeter || ""} ${row.x_SkuDescription || ""}`);
  return /\b(batch|wr|write|pp|priority|longco|longcontext|fine tuned|finetuned|training|audio|image|video)\b/.test(text);
}

function deploymentPriceIdentity(deployment) {
  const sku = normalizeText(deployment?.skuName).replaceAll(" ", "");
  if (!sku) return { supported: true, variant: "Standard", priceScope: null };
  if (sku.includes("provisioned")) {
    return { supported: false, reason: `Deployment SKU ${deployment.skuName} is capacity-priced, not token-priced.` };
  }
  const variant = sku.includes("batch") ? "Batch" : "Standard";
  const priceScope = sku.includes("global") ? "Global" : sku.includes("datazone") ? "DataZone" : "Regional";
  return { supported: true, variant, priceScope };
}

function priceVariant(row) {
  const variant = normalizeText(row.Variant || "");
  if (variant === "batch") return "Batch";
  if (variant === "cached" || variant === "cache") return "Cached";
  if (variant === "standard") return "Standard";
  return null;
}

const PRICE_DESCRIPTOR_TERMS = new Set([
  "audio", "batch", "cache", "cached", "cd", "completion", "datazone", "dz",
  "gl", "global", "image", "inp", "input", "longco", "longcontext", "opt",
  "outp", "output", "pp", "priority", "prompt", "regional", "shortco", "std",
  "standard", "text", "tokens", "video", "wr",
]);

function contiguousTermsIndex(words, terms) {
  for (let index = 0; index <= words.length - terms.length; index++) {
    if (terms.every((term, offset) => words[index + offset] === term)) return index;
  }
  return -1;
}

function priceMatchesModel(row, model, version) {
  const words = normalizeText(`${row.ModelText || ""} ${row.x_SkuMeterName || ""} ${row.SkuMeter || ""} ${row.x_SkuDescription || ""}`).split(" ").filter(Boolean);
  const normalizedModel = normalizeText(model).split(" ").filter(Boolean);
  const variants = [normalizedModel];
  if (normalizedModel[0] === "gpt" && normalizedModel.length > 1) variants.push(normalizedModel.slice(1));
  const versionTerms = normalizeText(version).split(" ").filter(Boolean);

  for (const terms of variants) {
    const index = contiguousTermsIndex(words, terms);
    if (index < 0) continue;
    let nextIndex = index + terms.length;
    const hasVersion = versionTerms.length &&
      versionTerms.every((term, offset) => words[nextIndex + offset] === term);
    if (hasVersion) nextIndex += versionTerms.length;
    else if (/^20\d{2}$/.test(words[nextIndex] || "")) continue;
    const next = words[nextIndex];
    if (!next || PRICE_DESCRIPTOR_TERMS.has(next) || /^\d+m$/.test(next)) return true;
  }
  return false;
}

function prepareFoundryPriceCandidates(model, version, direction, region, prices, deployment) {
  if (!normalizeText(model)) return { error: { status: "unmatched", reason: "Deployment metadata has no model name." } };
  const deploymentIdentity = deploymentPriceIdentity(deployment);
  if (!deploymentIdentity) {
    return { error: { status: "unmatched", reason: "No Azure deployment SKU metadata is available for this metric series." } };
  }
  if (!deploymentIdentity.supported) return { error: { status: "unmatched", reason: deploymentIdentity.reason } };
  const cachedInput = direction === "Cached input" || direction === "Cached";
  const expectedDirection = cachedInput ? "Input" : direction;
  const expectedVariant = cachedInput ? "Cached" : deploymentIdentity.variant;

  let candidates = (prices || []).filter((row) => {
    const variant = priceVariant(row);
    if (priceDirection(row) !== expectedDirection || variant !== expectedVariant) return false;
    if (variant === "Standard" && specializedPrice(row)) return false;
    if (cachedInput && specializedCachedPrice(row)) return false;
    const priceScope = String(row.PriceScope || "");
    if (deploymentIdentity.priceScope && priceScope !== deploymentIdentity.priceScope) return false;
    const priceRegion = String(row.PriceRegionId || "").toLowerCase();
    if (priceRegion && priceRegion !== "global" &&
      priceRegion !== String(region || "").toLowerCase()) return false;
    return priceMatchesModel(row, model, version);
  });
  if (!candidates.length) {
    return {
      error: {
        status: "unmatched",
        reason: `No ${expectedVariant.toLowerCase()} ${String(direction).toLowerCase()} token rate matched ${model} ${version}${deploymentIdentity.priceScope ? ` for ${deploymentIdentity.priceScope.toLowerCase()} pricing` : ""}.`,
      },
    };
  }

  candidates = candidates.filter((row) =>
    Number(row.x_PricingBlockSize) > 0 &&
    row.SelectedUnitPrice !== null &&
    row.SelectedUnitPrice !== undefined &&
    Number.isFinite(Number(row.SelectedUnitPrice))
  );
  if (!candidates.length) {
    return { error: { status: "unmatched", reason: "Matching rates have no explicit pricing block size or usable unit price." } };
  }

  const exactScopeCandidates = candidates.filter((row) => {
    if (row.ScopeMatch !== true && row.ScopeMatch !== 1) return false;
    const scopeCurrency = String(row.ScopeCurrency || "");
    const pricingCurrency = String(row.PricingCurrency || row.BillingCurrency || "");
    return scopeCurrency && pricingCurrency && scopeCurrency.toLowerCase() === pricingCurrency.toLowerCase();
  });
  if (!exactScopeCandidates.length) {
    return { error: { status: "unmatched", reason: "No rate matched the subscription's current billing account and currency." } };
  }
  return { candidates: exactScopeCandidates };
}

function resolveFoundryPrice(prepared, usageTimestamp) {
  if (prepared.error) return prepared.error;
  const usageTime = Date.parse(String(usageTimestamp || ""));
  if (!Number.isFinite(usageTime)) {
    return { status: "unmatched", reason: "Metric series has no valid usage timestamp." };
  }
  const active = prepared.candidates.filter((row) => {
    const effectiveStart = Date.parse(String(row.x_EffectivePeriodStart || ""));
    const effectiveEnd = row.x_EffectivePeriodEnd ? Date.parse(String(row.x_EffectivePeriodEnd)) : Infinity;
    return Number.isFinite(effectiveStart) && usageTime >= effectiveStart &&
      (effectiveEnd === Infinity || Number.isFinite(effectiveEnd) && usageTime < effectiveEnd);
  });
  const usageDate = new Date(usageTime);
  const usageMonthStart = Date.UTC(usageDate.getUTCFullYear(), usageDate.getUTCMonth(), 1);
  const previousMonth = active.length
    ? []
    : prepared.candidates.filter((row) =>
      Date.parse(String(row.x_EffectivePeriodEnd || "")) === usageMonthStart
    );
  const eligible = active.length ? active : previousMonth;
  if (!eligible.length) {
    return {
      status: "unmatched",
      reason: "No matching Hub rate was effective at the metric timestamp or in the previous monthly price sheet.",
    };
  }

  const rateBasis = active.length ? "active" : "previous-month";
  const normalized = eligible.map((row) => ({
    unitPricePerToken: Number(row.SelectedUnitPrice) / Number(row.x_PricingBlockSize),
    currency: String(row.PricingCurrency || row.BillingCurrency || ""),
    source: String(row.PriceSource || ""),
    billingAccountId: String(row.BillingAccountId || ""),
    meter: String(row.x_SkuMeterName || row.SkuMeter || ""),
    blockSize: Number(row.x_PricingBlockSize),
    rateBasis,
    rateEffectiveStart: row.x_EffectivePeriodStart || null,
    rateEffectiveEnd: row.x_EffectivePeriodEnd || null,
  }));
  const signatures = new Set(normalized.map((row) => `${row.currency}|${row.unitPricePerToken}`));
  if (signatures.size !== 1) {
    return { status: "ambiguous", reason: `${normalized.length} eligible Hub rates disagree on currency or unit price.` };
  }
  return {
    status: "matched",
    ...normalized[0],
    scope: "billing-scope",
    reason: rateBasis === "previous-month"
      ? "The current monthly price sheet is not available. This estimate uses the previous month's rate."
      : null,
  };
}

export function matchFoundryPrice(model, version, direction, region, prices, deployment, usageTimestamp) {
  return resolveFoundryPrice(
    prepareFoundryPriceCandidates(model, version, direction, region, prices, deployment),
    usageTimestamp
  );
}

function seriesStats(points, aggregation) {
  const values = points.map((point) => point.Value);
  const total = values.reduce((sum, value) => sum + value, 0);
  return {
    Total: total,
    Mean: values.length ? total / values.length : 0,
    Max: values.length ? Math.max(...values) : 0,
    Last: values.at(-1) || 0,
    Aggregation: aggregation,
  };
}

function buildSeries(rows, keyFn, nameFn, aggregation) {
  const groups = new Map();
  for (const row of rows) {
    const key = keyFn(row);
    const current = groups.get(key) || { Name: nameFn(row), Buckets: new Map() };
    const bucket = current.Buckets.get(row.timestamp) || {
      sum: 0,
      count: 0,
      estimatedCost: 0,
      estimatedTokens: 0,
      currencies: new Set(),
      hasEstimatedCost: false,
    };
    bucket.sum += row.value;
    bucket.count++;
    if (row.EstimatedCost != null && Number.isFinite(Number(row.EstimatedCost))) {
      bucket.estimatedCost += Number(row.EstimatedCost);
      bucket.estimatedTokens += Number(row.EstimatedTokens || 0);
      if (row.Currency) bucket.currencies.add(row.Currency);
      bucket.hasEstimatedCost = true;
    }
    current.Buckets.set(row.timestamp, bucket);
    groups.set(key, current);
  }
  return [...groups.values()].map((series) => {
    const Points = [...series.Buckets].map(([Bucket, bucket]) => {
      const point = {
        Bucket,
        Value: aggregation === "Average" ? bucket.sum / bucket.count : bucket.sum,
      };
      if (bucket.hasEstimatedCost) {
        point.Cost = bucket.currencies.size === 1 ? bucket.estimatedCost : null;
        point.Currency = bucket.currencies.size === 1 ? [...bucket.currencies][0] : null;
        point.PriceCoverage = bucket.sum > 0
          ? Math.min(1, bucket.estimatedTokens / bucket.sum)
          : 0;
      }
      return point;
    }).sort((left, right) => left.Bucket.localeCompare(right.Bucket));
    return { Name: series.Name, Points, Stats: seriesStats(Points, aggregation) };
  }).sort((left, right) => right.Stats.Total - left.Stats.Total);
}

function mergePriceStatus(current, incoming) {
  if (current === "ambiguous" || incoming === "ambiguous") return "ambiguous";
  if (current === "unmatched" || incoming === "unmatched") return "unmatched";
  return "matched";
}

export function summarizeFoundryMetrics(flattened, accounts, deploymentsByAccount, pricesBySubscription) {
  const rows = flattened.rows || [];
  const accountMap = new Map(accounts.map((account) => [account.id.toLowerCase(), account]));
  const includeAccountName = accounts.length > 1;
  const deploymentMaps = new Map([...deploymentsByAccount].map(([accountId, deployments]) => [
    accountId.toLowerCase(),
    new Map(deployments.map((deployment) => [deployment.name.toLowerCase(), deployment])),
  ]));
  const enriched = rows.map((row) => {
    const account = accountMap.get(String(row.resourceId || "").toLowerCase())
      || (accounts.length === 1 ? accounts[0] : null);
    const deployment = account
      ? deploymentMaps.get(account.id.toLowerCase())?.get(row.deployment.toLowerCase()) || null
      : null;
    const deploymentLabel = row.deployment || "(unknown deployment)";
    return {
      ...row,
      account,
      deploymentMetadata: deployment,
      seriesName: includeAccountName && account
        ? `${account.name} / ${deploymentLabel}`
        : deploymentLabel,
    };
  });

  const tokenRows = enriched.filter((row) =>
    row.group === "tokens" && ["InputTokens", "OutputTokens", "TotalTokens"].includes(row.metric)
  );
  const requestRows = enriched.filter((row) => row.group === "requests" && row.metric === "ModelRequests");
  const requestErrorRows = enriched.filter((row) =>
    row.metric === "ModelRequests" && (
      row.group === "request-errors"
      || row.group === "requests" && row.statusCode && row.statusCode !== "200"
    )
  );

  const tokenTotals = new Map();
  const tokenCostBuckets = new Map();
  const costByModel = new Map();
  let estimatedTokens = 0;
  let previousMonthEstimatedTokens = 0;
  let estimatedCostTotal = 0;
  const estimatedCurrencies = new Set();

  for (const row of tokenRows) {
    if (!["InputTokens", "OutputTokens"].includes(row.metric)) continue;
    const direction = row.metric === "InputTokens" ? "Input" : "Output";
    const accountId = row.account?.id?.toLowerCase() || "";
    const totalKey = `${accountId}\u001f${row.deployment}\u001f${row.metric}`;
    const currentTotal = tokenTotals.get(totalKey) || {
      Name: row.seriesName,
      AccountId: row.account?.id || null,
      Deployment: row.deployment,
      Metric: row.metric,
      Value: 0,
      EstimatedCost: 0,
      EstimatedTokens: 0,
      PreviousMonthEstimatedTokens: 0,
      Currencies: new Set(),
      PriceStatus: "matched",
      PriceReason: null,
    };
    currentTotal.Value += row.value;

    const deployment = row.deploymentMetadata;
    const modelName = deployment?.modelName || row.deployment;
    const modelKey = normalizeText(modelName) || row.deployment.toLowerCase();
    const modelCost = costByModel.get(modelKey) || {
      Model: modelName,
      EstimatedCost: 0,
      EstimatedTokens: 0,
      PreviousMonthEstimatedTokens: 0,
      Currencies: new Set(),
      PriceStatus: "matched",
      PriceReason: null,
    };
    const prices = row.account
      ? (pricesBySubscription.get(row.account.subscriptionId.toLowerCase()) || []).filter((price) =>
        !price.AccountResourceId || idsEqual(price.AccountResourceId, row.account.id)
      )
      : [];
    const price = deployment && row.account
      ? matchFoundryPrice(
        deployment.modelName,
        deployment.modelVersion,
        direction,
        row.account.location,
        prices,
        deployment,
        row.timestamp
      )
      : {
        status: "unmatched",
        reason: row.account
          ? `No Azure deployment metadata matched '${row.deployment}'.`
          : "Azure Monitor did not identify the source account.",
      };
    modelCost.PriceStatus = mergePriceStatus(modelCost.PriceStatus, price.status);
    modelCost.PriceReason ||= price.reason || null;
    currentTotal.PriceStatus = mergePriceStatus(currentTotal.PriceStatus, price.status);
    currentTotal.PriceReason ||= price.reason || null;
    row.EstimatedCost = null;
    row.EstimatedTokens = 0;
    row.Currency = null;
    row.PriceStatus = price.status;
    row.PriceReason = price.reason || null;
    if (price.status === "matched") {
      const cost = row.value * price.unitPricePerToken;
      modelCost.EstimatedCost += cost;
      modelCost.EstimatedTokens += row.value;
      modelCost.Currencies.add(price.currency);
      estimatedCostTotal += cost;
      estimatedTokens += row.value;
      estimatedCurrencies.add(price.currency);
      currentTotal.EstimatedCost += cost;
      currentTotal.EstimatedTokens += row.value;
      currentTotal.Currencies.add(price.currency);
      row.EstimatedCost = cost;
      row.EstimatedTokens = row.value;
      row.Currency = price.currency;
      const costBucketKey = `${accountId}\u001f${row.deployment}\u001f${row.timestamp}`;
      const costBucket = tokenCostBuckets.get(costBucketKey) || {
        EstimatedCost: 0,
        EstimatedTokens: 0,
        PreviousMonthEstimatedTokens: 0,
        Currencies: new Set(),
      };
      costBucket.EstimatedCost += cost;
      costBucket.EstimatedTokens += row.value;
      costBucket.Currencies.add(price.currency);
      if (price.rateBasis === "previous-month") {
        modelCost.PreviousMonthEstimatedTokens += row.value;
        previousMonthEstimatedTokens += row.value;
        currentTotal.PreviousMonthEstimatedTokens += row.value;
        costBucket.PreviousMonthEstimatedTokens += row.value;
      }
      tokenCostBuckets.set(costBucketKey, costBucket);
    }
    tokenTotals.set(totalKey, currentTotal);
    costByModel.set(modelKey, modelCost);
  }

  for (const row of tokenRows.filter((item) => item.metric === "TotalTokens")) {
    const accountId = row.account?.id?.toLowerCase() || "";
    const costBucket = tokenCostBuckets.get(`${accountId}\u001f${row.deployment}\u001f${row.timestamp}`);
    row.EstimatedCost = costBucket?.Currencies.size === 1 ? costBucket.EstimatedCost : null;
    row.EstimatedTokens = costBucket?.Currencies.size === 1 ? costBucket.EstimatedTokens : 0;
    row.Currency = costBucket?.Currencies.size === 1 ? [...costBucket.Currencies][0] : null;
    row.PriceCoverage = row.value > 0 ? Math.min(1, row.EstimatedTokens / row.value) : 0;
  }

  const finalizedTokenTotals = [...tokenTotals.values()].map((row) => {
    const currencyConflict = row.Currencies.size > 1;
    return {
      Name: row.Name,
      AccountId: row.AccountId,
      Deployment: row.Deployment,
      Metric: row.Metric,
      Value: row.Value,
      EstimatedCost: row.EstimatedTokens > 0 && !currencyConflict ? row.EstimatedCost : null,
      EstimatedTokens: currencyConflict ? 0 : row.EstimatedTokens,
      PreviousMonthEstimatedTokens: currencyConflict ? 0 : row.PreviousMonthEstimatedTokens,
      PriceCoverage: row.Value > 0 && !currencyConflict ? row.EstimatedTokens / row.Value : 0,
      Currency: row.Currencies.size === 1 ? [...row.Currencies][0] : null,
      PriceStatus: currencyConflict ? "ambiguous" : row.PriceStatus,
      PriceReason: currencyConflict ? "Eligible rates use multiple currencies." : row.PriceReason,
    };
  });

  const costs = [...costByModel.values()].map((row) => ({
    Model: row.Model,
    EstimatedCost: row.Currencies.size === 1 && row.EstimatedTokens > 0 ? row.EstimatedCost : null,
    EstimatedTokens: row.Currencies.size === 1 ? row.EstimatedTokens : 0,
    PreviousMonthEstimatedTokens: row.Currencies.size === 1 ? row.PreviousMonthEstimatedTokens : 0,
    Currency: row.Currencies.size === 1 ? [...row.Currencies][0] : null,
    PriceStatus: row.Currencies.size > 1 ? "ambiguous" : row.PriceStatus,
    PriceReason: row.Currencies.size > 1
      ? "Eligible rates use multiple currencies."
      : row.PriceReason,
  })).filter((row) => row.EstimatedCost != null)
    .sort((left, right) => right.EstimatedCost - left.EstimatedCost);

  const inputTotal = tokenRows
    .filter((row) => row.metric === "InputTokens")
    .reduce((sum, row) => sum + row.value, 0);
  const outputTotal = tokenRows
    .filter((row) => row.metric === "OutputTokens")
    .reduce((sum, row) => sum + row.value, 0);
  const totalTokens = tokenRows
    .filter((row) => row.metric === "TotalTokens")
    .reduce((sum, row) => sum + row.value, 0);
  const totalRequests = requestRows.reduce((sum, row) => sum + row.value, 0);
  const totalErrors = requestErrorRows.reduce((sum, row) => sum + row.value, 0);
  const inputEstimatedCost = finalizedTokenTotals
    .filter((row) => row.Metric === "InputTokens" && row.EstimatedCost != null)
    .reduce((sum, row) => sum + row.EstimatedCost, 0);
  const outputEstimatedCost = finalizedTokenTotals
    .filter((row) => row.Metric === "OutputTokens" && row.EstimatedCost != null)
    .reduce((sum, row) => sum + row.EstimatedCost, 0);
  const accountIdsWithData = new Set(enriched.map((row) => row.account?.id).filter(Boolean));
  const deploymentSeriesKey = (row) =>
    `${row.account?.id || ""}\u001f${row.deployment}\u001f${row.metric}`;
  const deploymentSeriesName = (row) => row.seriesName;

  return {
    summary: {
      InputTokens: inputTotal,
      OutputTokens: outputTotal,
      TotalTokens: totalTokens,
      Requests: totalRequests,
      Errors: totalErrors,
      ErrorRate: totalRequests > 0 ? totalErrors / totalRequests : 0,
      EstimatedCost: estimatedCurrencies.size === 1 && estimatedTokens > 0 ? estimatedCostTotal : null,
      InputEstimatedCost: estimatedCurrencies.size === 1 && estimatedTokens > 0 ? inputEstimatedCost : null,
      OutputEstimatedCost: estimatedCurrencies.size === 1 && estimatedTokens > 0 ? outputEstimatedCost : null,
      EstimatedTokens: estimatedCurrencies.size === 1 ? estimatedTokens : 0,
      PreviousMonthEstimatedTokens: estimatedCurrencies.size === 1 ? previousMonthEstimatedTokens : 0,
      PriceCoverage: inputTotal + outputTotal > 0 ? estimatedTokens / (inputTotal + outputTotal) : 0,
      PreviousMonthPriceCoverage: estimatedTokens > 0 ? previousMonthEstimatedTokens / estimatedTokens : 0,
      Currency: estimatedCurrencies.size === 1 ? [...estimatedCurrencies][0] : null,
      AccountCount: accounts.length,
      AccountsWithData: accountIdsWithData.size,
    },
    stats: {
      costs,
      inputTokens: finalizedTokenTotals
        .filter((row) => row.Metric === "InputTokens")
        .sort((left, right) => right.Value - left.Value),
      outputTokens: finalizedTokenTotals
        .filter((row) => row.Metric === "OutputTokens")
        .sort((left, right) => right.Value - left.Value),
    },
    charts: {
      modelRequests: buildSeries(requestRows, deploymentSeriesKey, deploymentSeriesName, "Total"),
      requestErrors: buildSeries(
        requestErrorRows,
        (row) => row.statusCode || "(unknown status)",
        (row) => row.statusCode || "(unknown status)",
        "Total"
      ),
      latency: buildSeries(
        enriched.filter((row) => row.group === "latency"),
        deploymentSeriesKey,
        (row) => `${row.seriesName} · ${row.metric === "TimeToLastByte" ? "Time to last byte" : "Azure OpenAI TTLT"}`,
        "Average"
      ),
      tokensPerSecond: buildSeries(
        enriched.filter((row) => row.group === "throughput"),
        deploymentSeriesKey,
        deploymentSeriesName,
        "Average"
      ),
      inputTokens: buildSeries(
        tokenRows.filter((row) => row.metric === "InputTokens"),
        deploymentSeriesKey,
        deploymentSeriesName,
        "Total"
      ),
      outputTokens: buildSeries(
        tokenRows.filter((row) => row.metric === "OutputTokens"),
        deploymentSeriesKey,
        deploymentSeriesName,
        "Total"
      ),
      totalTokens: buildSeries(
        tokenRows.filter((row) => row.metric === "TotalTokens"),
        deploymentSeriesKey,
        deploymentSeriesName,
        "Total"
      ),
      cacheMatchRate: buildSeries(
        enriched.filter((row) => row.group === "cache"),
        deploymentSeriesKey,
        deploymentSeriesName,
        "Average"
      ),
    },
    diagnostics: [...(flattened.diagnostics || [])],
  };
}

async function loadFoundryPricing(
  connection,
  database,
  accounts,
  deploymentsByAccount,
  window,
  getPrices,
  options,
  diagnostics
) {
  const pricesBySubscription = new Map();
  const errors = [];
  if (typeof getPrices !== "function") {
    return { pricesBySubscription, errors, status: "unavailable", candidateRows: 0 };
  }
  const activeAccounts = accounts.filter((account) =>
    (deploymentsByAccount.get(account.id.toLowerCase()) || []).length
  );
  const subscriptionIds = [...new Set(activeAccounts.map((account) => account.subscriptionId.toLowerCase()))];
  const models = [...new Set(activeAccounts
    .flatMap((account) => deploymentsByAccount.get(account.id.toLowerCase()) || [])
    .map((deployment) => deployment.modelName)
    .filter(Boolean))];
  if (!subscriptionIds.length) {
    return { pricesBySubscription, errors, status: "empty", candidateRows: 0 };
  }
  let rows = [];
  try {
    rows = await getPrices(connection, database, subscriptionIds, {
      ...options,
      maxResponseBytes: MAX_RESPONSE_BYTES,
      start: window.start,
      end: window.end,
      models,
      regions: [...new Set(activeAccounts.map((account) => account.location).filter(Boolean))],
    });
  } catch (error) {
    const diagnostic = {
      stage: "pricing",
      status: "unavailable",
      message: error.message,
    };
    errors.push(diagnostic);
    diagnostics.push(diagnostic);
  }
  for (const subscriptionId of subscriptionIds) {
    const uniqueRows = new Map();
    for (const row of rows.filter((item) =>
      String(item.SubAccountId || "").toLowerCase() === subscriptionId
    )) {
      const key = [
        row.SubAccountId,
        row.BillingAccountId,
        row.x_BillingAccountId,
        row.x_BillingProfileId,
        row.x_SkuMeterId || row.SkuMeter || row.ModelText,
        row.Direction,
        row.Variant,
        row.PriceScope,
        row.x_EffectivePeriodStart,
        row.x_EffectivePeriodEnd,
        row.PricingCurrency || row.BillingCurrency,
        row.SelectedUnitPrice,
        row.x_PricingBlockSize,
      ].map((value) => String(value ?? "").toLowerCase()).join("\u001f");
      uniqueRows.set(key, row);
    }
    pricesBySubscription.set(subscriptionId, [...uniqueRows.values()]);
  }
  const candidateRows = [...pricesBySubscription.values()].reduce((sum, rows) => sum + rows.length, 0);
  return {
    pricesBySubscription,
    errors,
    candidateRows,
    status: errors.length
      ? candidateRows > 0 ? "partial" : "unavailable"
      : candidateRows > 0 ? "available" : "empty",
  };
}

function foundryProjectAccount(projectId, accounts) {
  const normalizedProject = String(projectId || "").trim().replace(/\/+$/, "").toLowerCase();
  if (!normalizedProject) return null;
  return accounts.find((account) =>
    normalizedProject.startsWith(`${String(account.id).toLowerCase()}/projects/`)
  ) || null;
}

function agentIdentity(row) {
  return String(row.AgentKey || row.AgentId || row.AgentName || "").trim();
}

function mergeAgentAggregateRows(rows, rowType, dimensions, numericFields) {
  const merged = new Map();
  for (const row of rows.filter((item) => item.RowType === rowType)) {
    const key = dimensions.map((field) => String(row[field] ?? "").toLowerCase()).join("\u001f");
    const current = merged.get(key) || {
      ...row,
      ...Object.fromEntries(numericFields.map((field) => [field, 0])),
    };
    for (const field of numericFields) {
      current[field] = agentNumber(current[field]) + agentNumber(row[field]);
    }
    merged.set(key, current);
  }
  return [...merged.values()];
}

function mergeAgentSummaries(rows) {
  const merged = new Map();
  for (const row of rows.filter((item) => item.RowType === "AgentSummary")) {
    const key = `${agentIdentity(row).toLowerCase()}\u001f${String(row.FoundryProjectId || "").toLowerCase()}`;
    const current = merged.get(key) || {
      ...row,
      ActivityEvents: 0,
      Operations: 0,
      Successes: 0,
      Errors: 0,
      TotalDurationMs: 0,
      InputTokens: 0,
      CachedInputTokens: 0,
      OutputTokens: 0,
      P95LatencyMs: 0,
    };
    for (const field of [
      "ActivityEvents", "Operations", "Successes", "Errors", "TotalDurationMs",
      "InputTokens", "CachedInputTokens", "OutputTokens",
    ]) current[field] += agentNumber(row[field]);
    current.P95LatencyMs = Math.max(current.P95LatencyMs, agentNumber(row.P95LatencyMs));
    if (new Date(row.LastSeen || 0) > new Date(current.LastSeen || 0)) current.LastSeen = row.LastSeen;
    merged.set(key, current);
  }
  return [...merged.values()].map((row) => ({
    ...row,
    AverageLatencyMs: row.Operations > 0 ? row.TotalDurationMs / row.Operations : 0,
  }));
}

function decorateAgentRows(rows, accounts) {
  return rows.map((row) => {
    const account = foundryProjectAccount(row.FoundryProjectId, accounts);
    return {
      ...row,
      AccountId: account?.id || null,
      AgentType: "Microsoft Foundry agent",
    };
  });
}

function findAgentDeployment(row, account, deploymentsByAccount) {
  if (!account) return {
    deployment: null,
    reason: row.FoundryProjectId
      ? "The Foundry project ID did not match an accessible Cognitive Services account."
      : "The agent telemetry did not report a Microsoft Foundry project ID.",
  };
  const model = String(row.Model || "").trim();
  if (!model) return { deployment: null, reason: "The chat span did not report a request or response model." };
  const deployments = deploymentsByAccount.get(account.id.toLowerCase()) || [];
  const matches = deployments.filter((deployment) => [
    deployment.name,
    deployment.modelName,
    deployment.modelName && deployment.modelVersion
      ? `${deployment.modelName}-${deployment.modelVersion}`
      : null,
  ].some((candidate) => candidate && idsEqual(candidate, model)));
  if (matches.length === 1) return { deployment: matches[0], reason: null };
  if (matches.length > 1) {
    return { deployment: null, reason: `Model '${model}' matched more than one deployment or model version.` };
  }
  return { deployment: null, reason: `No Azure deployment metadata matched model '${model}'.` };
}

export function priceAgentTokenUsage(
  row,
  accounts,
  deploymentsByAccount,
  pricesBySubscription,
  usageTimestamp
) {
  const account = accounts.find((item) => idsEqual(item.id, row.AccountId))
    || foundryProjectAccount(row.FoundryProjectId, accounts);
  const { deployment, reason } = findAgentDeployment(row, account, deploymentsByAccount);
  const input = Math.max(0, agentNumber(row.InputTokens));
  const cached = Math.max(0, agentNumber(row.CachedInputTokens));
  const output = Math.max(0, agentNumber(row.OutputTokens));
  const uncached = Math.max(0, input - cached);
  const total = uncached + cached + output;
  if (total === 0) {
    return {
      EstimatedCost: 0,
      EstimatedTokens: 0,
      PriceCoverage: 1,
      PriceStatus: "not-applicable",
      Currency: null,
      UncachedInputTokens: 0,
      UncachedInputCost: 0,
      CachedInputCost: 0,
      OutputCost: 0,
      PreviousMonthEstimatedTokens: 0,
      PriceComponents: [],
    };
  }
  if (!deployment || !account) {
    return {
      EstimatedCost: null,
      EstimatedTokens: 0,
      PriceCoverage: 0,
      PriceStatus: "unmatched",
      PriceReason: reason,
      Currency: null,
      UncachedInputTokens: uncached,
      UncachedInputCost: null,
      CachedInputCost: null,
      OutputCost: null,
      PreviousMonthEstimatedTokens: 0,
      PriceComponents: [],
    };
  }
  const prices = pricesBySubscription.get(account.subscriptionId.toLowerCase()) || [];
  const timestamp = usageTimestamp || row.LastSeen || row.BucketStart || row.Timestamp;
  const definitions = [
    { name: "Uncached input", direction: "Input", tokens: uncached },
    { name: "Cached input", direction: "Cached input", tokens: cached },
    { name: "Output", direction: "Output", tokens: output },
  ];
  const components = definitions.filter((item) => item.tokens > 0).map((item) => {
    const price = matchFoundryPrice(
      deployment.modelName,
      deployment.modelVersion,
      item.direction,
      account.location,
      prices,
      deployment,
      timestamp
    );
    return {
      Component: item.name,
      Tokens: item.tokens,
      ...price,
      Cost: price.status === "matched" ? item.tokens * price.unitPricePerToken : null,
    };
  });
  const matched = components.filter((item) => item.status === "matched");
  const currencies = new Set(matched.map((item) => item.currency));
  const matchedTokens = matched.reduce((sum, item) => sum + item.Tokens, 0);
  const previousMonthTokens = matched
    .filter((item) => item.rateBasis === "previous-month")
    .reduce((sum, item) => sum + item.Tokens, 0);
  const conflictingCurrency = currencies.size > 1;
  const partial = matchedTokens > 0 && matchedTokens < total;
  const componentCost = (name, tokens) => {
    if (tokens === 0) return 0;
    const component = components.find((item) => item.Component === name);
    return !conflictingCurrency && component?.status === "matched" ? component.Cost : null;
  };
  return {
    EstimatedCost: matched.length && !conflictingCurrency
      ? matched.reduce((sum, item) => sum + item.Cost, 0)
      : null,
    EstimatedTokens: conflictingCurrency ? 0 : matchedTokens,
    PriceCoverage: conflictingCurrency ? 0 : matchedTokens / total,
    PriceStatus: conflictingCurrency ? "ambiguous" : partial ? "partial"
      : matchedTokens === total ? "matched"
        : components.some((item) => item.status === "ambiguous") ? "ambiguous" : "unmatched",
    PriceReason: conflictingCurrency
      ? "Eligible token components use multiple currencies."
      : components.find((item) => item.status !== "matched")?.reason || null,
    Currency: currencies.size === 1 ? [...currencies][0] : null,
    UncachedInputTokens: uncached,
    UncachedInputCost: componentCost("Uncached input", uncached),
    CachedInputCost: componentCost("Cached input", cached),
    OutputCost: componentCost("Output", output),
    PreviousMonthEstimatedTokens: conflictingCurrency ? 0 : previousMonthTokens,
    PriceComponents: components,
  };
}

function authoritativeAgentCosts(agentId, billedCosts) {
  const normalizedId = String(agentId || "").trim().replace(/\/+$/, "").toLowerCase();
  const isArmId = /^\/subscriptions\/[^/]+\/resourcegroups\/[^/]+\/providers\/[^/]+\/[^/]+\/[^/]+$/i.test(normalizedId);
  const rows = isArmId
    ? billedCosts.filter((row) => idsEqual(row.AgentResourceId, normalizedId))
    : [];
  return {
    BilledCostStatus: rows.length
      ? "Exact Costs() match"
      : isArmId ? "No exact Costs() match" : "Not an ARM resource identity",
    AuthoritativeCosts: rows.map((row) => ({
      Meter: row.Meter || null,
      ConsumedQuantity: agentNumber(row.ConsumedQuantity),
      EffectiveCost: agentNumber(row.EffectiveCost),
      BilledCost: agentNumber(row.BilledCost),
      BillingCurrency: String(row.BillingCurrency || ""),
    })),
  };
}

function summarizeAgentsPayload(
  shared,
  accounts,
  selectedAccountId,
  deploymentsByAccount,
  pricesBySubscription,
  diagnostics
) {
  const decorated = decorateAgentRows(shared.rows, accounts);
  const scoped = selectedAccountId
    ? decorated.filter((row) => idsEqual(row.AccountId, selectedAccountId))
    : decorated;
  const agentRows = mergeAgentSummaries(scoped);
  const modelUsageRows = mergeAgentAggregateRows(
    scoped,
    "ModelUsage",
    ["AgentKey", "FoundryProjectId", "Model"],
    ["Chats", "InputTokens", "CachedInputTokens", "OutputTokens"]
  );
  const pricedUsage = modelUsageRows.map((row) => ({
    ...row,
    ...priceAgentTokenUsage(row, accounts, deploymentsByAccount, pricesBySubscription, row.LastSeen || shared.window.end),
  }));
  const usageByAgent = new Map();
  for (const row of pricedUsage) {
    const key = `${agentIdentity(row).toLowerCase()}\u001f${String(row.FoundryProjectId || "").toLowerCase()}`;
    const current = usageByAgent.get(key) || {
      EstimatedCost: 0,
      EstimatedTokens: 0,
      TotalTokens: 0,
      PreviousMonthEstimatedTokens: 0,
      Currencies: new Set(),
      Statuses: new Set(),
      UncachedInputCost: 0,
      CachedInputCost: 0,
      OutputCost: 0,
      HasUncachedInputCost: false,
      HasCachedInputCost: false,
      HasOutputCost: false,
    };
    if (row.EstimatedCost != null) current.EstimatedCost += row.EstimatedCost;
    current.EstimatedTokens += row.EstimatedTokens;
    current.TotalTokens += Math.max(0, agentNumber(row.InputTokens) - agentNumber(row.CachedInputTokens))
      + agentNumber(row.CachedInputTokens) + agentNumber(row.OutputTokens);
    current.PreviousMonthEstimatedTokens += row.PreviousMonthEstimatedTokens;
    if (row.Currency) current.Currencies.add(row.Currency);
    current.Statuses.add(row.PriceStatus);
    for (const field of ["UncachedInputCost", "CachedInputCost", "OutputCost"]) {
      if (row[field] != null) {
        current[field] += row[field];
        current[`Has${field}`] = true;
      }
    }
    usageByAgent.set(key, current);
  }
  const agents = agentRows.map((row) => {
    const key = `${agentIdentity(row).toLowerCase()}\u001f${String(row.FoundryProjectId || "").toLowerCase()}`;
    const usage = usageByAgent.get(key);
    const currencyConflict = usage?.Currencies.size > 1;
    return {
      ...row,
      EstimatedCost: usage && !currencyConflict && usage.EstimatedTokens > 0 ? usage.EstimatedCost : null,
      EstimatedTokens: usage && !currencyConflict ? usage.EstimatedTokens : 0,
      PriceCoverage: usage?.TotalTokens > 0 && !currencyConflict ? usage.EstimatedTokens / usage.TotalTokens : 0,
      PriceStatus: currencyConflict ? "ambiguous"
        : !usage ? "not-applicable"
          : usage.Statuses.has("unmatched") || usage.Statuses.has("ambiguous") || usage.Statuses.has("partial")
            ? usage.EstimatedTokens > 0 ? "partial" : "unmatched"
            : "matched",
      Currency: usage?.Currencies.size === 1 ? [...usage.Currencies][0] : null,
      UncachedInputTokens: Math.max(0, agentNumber(row.InputTokens) - agentNumber(row.CachedInputTokens)),
      UncachedInputCost: usage?.HasUncachedInputCost && !currencyConflict ? usage.UncachedInputCost : null,
      CachedInputCost: usage?.HasCachedInputCost && !currencyConflict ? usage.CachedInputCost : null,
      OutputCost: usage?.HasOutputCost && !currencyConflict ? usage.OutputCost : null,
      ...authoritativeAgentCosts(row.AgentId || row.AgentKey, shared.billedCosts),
    };
  }).sort((left, right) => right.Operations - left.Operations || left.AgentName.localeCompare(right.AgentName));

  const tokenBuckets = mergeAgentAggregateRows(
    scoped,
    "TokenBucket",
    ["BucketStart", "AgentKey", "FoundryProjectId", "Model"],
    ["InputTokens", "CachedInputTokens", "OutputTokens"]
  ).map((row) => ({
    ...row,
    ...priceAgentTokenUsage(row, accounts, deploymentsByAccount, pricesBySubscription, row.BucketStart),
  }));
  const timeBuckets = mergeAgentAggregateRows(
    scoped,
    "TimeBucket",
    ["BucketStart", "AgentKey", "FoundryProjectId"],
    ["Operations", "Successes", "Errors"]
  );
  const finishReasons = mergeAgentAggregateRows(
    scoped,
    "FinishReason",
    ["AgentKey", "FoundryProjectId", "FinishReason"],
    ["Count"]
  ).sort((left, right) => right.Count - left.Count);
  const tools = mergeAgentAggregateRows(
    scoped,
    "Tool",
    ["AgentKey", "FoundryProjectId", "ToolName"],
    ["Calls", "Errors"]
  ).sort((left, right) => right.Calls - left.Calls);
  const recentRuns = scoped.filter((row) => row.RowType === "Run")
    .map((row) => ({
      ...row,
      ...priceAgentTokenUsage(row, accounts, deploymentsByAccount, pricesBySubscription, row.Timestamp),
    }))
    .sort((left, right) => String(right.Timestamp).localeCompare(String(left.Timestamp)))
    .slice(0, 100);
  const recentErrors = scoped.filter((row) => row.RowType === "Error")
    .sort((left, right) => String(right.Timestamp).localeCompare(String(left.Timestamp)))
    .slice(0, 20);
  const inputTokens = agents.reduce((sum, row) => sum + agentNumber(row.InputTokens), 0);
  const cachedInputTokens = agents.reduce((sum, row) => sum + agentNumber(row.CachedInputTokens), 0);
  const outputTokens = agents.reduce((sum, row) => sum + agentNumber(row.OutputTokens), 0);
  const operations = agents.reduce((sum, row) => sum + agentNumber(row.Operations), 0);
  const successes = agents.reduce((sum, row) => sum + agentNumber(row.Successes), 0);
  const duration = agents.reduce((sum, row) => sum + agentNumber(row.TotalDurationMs), 0);
  const estimatedTokens = agents.reduce((sum, row) => sum + agentNumber(row.EstimatedTokens), 0);
  const currencies = new Set(agents.map((row) => row.Currency).filter(Boolean));
  const estimateCurrency = currencies.size === 1 ? [...currencies][0] : null;
  const estimatedCost = estimateCurrency
    ? agents.filter((row) => row.Currency === estimateCurrency && row.EstimatedCost != null)
      .reduce((sum, row) => sum + row.EstimatedCost, 0)
    : null;
  const estimatedComponentCost = (field) => {
    const values = agents.map((row) => row[field]).filter((value) => value != null);
    return estimateCurrency && values.length ? values.reduce((sum, value) => sum + value, 0) : null;
  };
  const authoritativeCosts = new Map();
  for (const row of agents.flatMap((agent) => agent.AuthoritativeCosts)) {
    const currency = row.BillingCurrency || "Unknown";
    const current = authoritativeCosts.get(currency) || {
      BillingCurrency: currency,
      EffectiveCost: 0,
      BilledCost: 0,
    };
    current.EffectiveCost += row.EffectiveCost;
    current.BilledCost += row.BilledCost;
    authoritativeCosts.set(currency, current);
  }
  const priceableTokens = agents.reduce((sum, row) =>
    sum + Math.max(0, agentNumber(row.InputTokens) - agentNumber(row.CachedInputTokens))
      + agentNumber(row.CachedInputTokens) + agentNumber(row.OutputTokens), 0);
  return {
    summary: {
      AgentCount: agents.length,
      Operations: operations,
      Successes: successes,
      Errors: agents.reduce((sum, row) => sum + agentNumber(row.Errors), 0),
      SuccessRate: operations > 0 ? successes / operations : 0,
      AverageLatencyMs: operations > 0 ? duration / operations : 0,
      InputTokens: inputTokens,
      CachedInputTokens: cachedInputTokens,
      OutputTokens: outputTokens,
      CacheRate: inputTokens > 0 ? cachedInputTokens / inputTokens : 0,
      EstimatedCost: estimatedCost,
      UncachedInputCost: estimatedComponentCost("UncachedInputCost"),
      CachedInputCost: estimatedComponentCost("CachedInputCost"),
      OutputCost: estimatedComponentCost("OutputCost"),
      EstimatedTokens: estimatedTokens,
      PriceCoverage: priceableTokens > 0 && estimateCurrency ? estimatedTokens / priceableTokens : 0,
      Currency: estimateCurrency,
      AuthoritativeCosts: [...authoritativeCosts.values()],
    },
    agents,
    charts: {
      tokens: tokenBuckets,
      estimatedCost: tokenBuckets.filter((row) => row.EstimatedCost != null),
      latency: timeBuckets,
      throughput: timeBuckets,
      success: timeBuckets,
    },
    models: pricedUsage.sort((left, right) =>
      agentNumber(right.InputTokens) + agentNumber(right.OutputTokens)
      - agentNumber(left.InputTokens) - agentNumber(left.OutputTokens)
    ),
    finishReasons,
    tools,
    recentRuns,
    recentErrors,
    diagnostics,
  };
}

export async function getAgentsDashboard({
  connection,
  database,
  tenantId,
  preset = "7d",
  accountId = null,
  runQuery,
  options = {},
}) {
  const normalizedTenant = normalizeAzureTenantId(tenantId);
  const shared = await getCachedAgentsShared(
    connection,
    database,
    normalizedTenant,
    preset,
    runQuery,
    options
  );
  const allAccounts = shared.accounts;
  const diagnostics = [...(shared.diagnostics || [])];
  let selectedAccountId = accountId ? String(accountId) : null;
  if (selectedAccountId && !allAccounts.some((account) => idsEqual(account.id, selectedAccountId))) {
    diagnostics.push({
      stage: "account-selection",
      status: "reset",
      resourceId: selectedAccountId,
      message: "The selected AI Foundry resource is no longer accessible. The view returned to estate scope.",
    });
    selectedAccountId = null;
  }
  const telemetryAccountIds = new Set(shared.rows
    .map((row) => foundryProjectAccount(row.FoundryProjectId, allAccounts)?.id.toLowerCase())
    .filter(Boolean));
  const activeAccounts = allAccounts.filter((account) =>
    selectedAccountId ? idsEqual(account.id, selectedAccountId) : telemetryAccountIds.has(account.id.toLowerCase())
  );
  const deploymentsByAccount = new Map(activeAccounts.map((account) => [
    account.id.toLowerCase(),
    shared.deploymentsByAccount.get(account.id.toLowerCase()) || [],
  ]));
  const data = summarizeAgentsPayload(
    shared,
    allAccounts,
    selectedAccountId,
    deploymentsByAccount,
    shared.pricesBySubscription,
    diagnostics
  );
  return {
    empty: data.summary.AgentCount === 0,
    accounts: allAccounts,
    selectedAccountId,
    window: shared.window,
    panels: AGENT_PANEL_CONTRACT,
    summary: data.summary,
    agents: data.agents,
    charts: data.charts,
    models: data.models,
    finishReasons: data.finishReasons,
    tools: data.tools,
    recentRuns: data.recentRuns,
    recentErrors: data.recentErrors,
    diagnostics: data.diagnostics,
    pricing: shared.pricing,
    workspaceCount: shared.workspaceCount,
    source: {
      operational: "Azure Monitor Logs AppDependencies and AppTraces",
      pricing: "FinOps Hub Prices() trace estimate",
      billedCost: "Exact FinOps Hub Costs() matches for separately billed agent resources",
      estimatedCostAuthoritative: false,
      billedCostAuthoritative: true,
    },
    generatedAt: new Date().toISOString(),
  };
}

async function loadFoundryShared({
  connection,
  database,
  tenantId,
  preset = "7d",
  getPrices,
  options = {},
}) {
  const normalizedTenant = normalizeAzureTenantId(tenantId);
  const accounts = await listFoundryAccounts(normalizedTenant, options);
  const window = foundryMetricWindow(preset, options);
  const diagnostics = [];
  if (!accounts.length) {
    return { accounts, window, diagnostics, flattened: { rows: [], diagnostics: [] },
      deploymentsByAccount: new Map(), pricing: {
        pricesBySubscription: new Map(), errors: [], status: "empty", candidateRows: 0,
      }, generatedAt: new Date().toISOString() };
  }
  const metrics = await queryFoundryMetrics(accounts, preset, {
    ...options,
    tenantId: normalizedTenant,
  });
  diagnostics.push(...metrics.diagnostics);
  const flattened = flattenMetricBatch(metrics.payloads);
  diagnostics.push(...flattened.diagnostics);
  const inferredDeployments = inferFoundryDeployments(flattened.rows, accounts);
  const activeAccountIds = new Set(flattened.rows
    .map((row) => String(row.resourceId || "").toLowerCase())
    .filter(Boolean));
  const activeAccounts = accounts.filter((account) => activeAccountIds.has(account.id.toLowerCase()));
  const [discoveredDeployments, pricing] = await Promise.all([
    listFoundryDeploymentsBatch(activeAccounts, normalizedTenant, options),
    loadFoundryPricing(
      connection,
      database,
      accounts,
      inferredDeployments,
      window,
      getPrices,
      options,
      diagnostics
    ),
  ]);
  diagnostics.push(...discoveredDeployments.diagnostics);
  const deploymentsByAccount = new Map(accounts.map((account) => {
    const accountId = account.id.toLowerCase();
    const deployments = discoveredDeployments.deploymentsByAccount.get(accountId) || [];
    return [accountId, deployments.length ? deployments : inferredDeployments.get(accountId) || []];
  }));
  return {
    accounts,
    window: metrics.window,
    diagnostics,
    flattened,
    deploymentsByAccount,
    pricing,
    generatedAt: new Date().toISOString(),
  };
}

function buildFoundryDashboard(shared, accountId) {
  const allAccounts = shared.accounts;
  let selectedAccountId = accountId ? String(accountId) : null;
  let selectedAccounts = selectedAccountId
    ? allAccounts.filter((account) => idsEqual(account.id, selectedAccountId))
    : allAccounts;
  const diagnostics = [...shared.diagnostics];
  if (selectedAccountId && !selectedAccounts.length) {
    diagnostics.push({
      stage: "account-selection",
      status: "reset",
      resourceId: selectedAccountId,
      message: "The selected AI Foundry resource is no longer accessible. The view returned to estate scope.",
    });
    selectedAccountId = null;
    selectedAccounts = allAccounts;
  }
  const selectedIds = new Set(selectedAccounts.map((account) => account.id.toLowerCase()));
  const flattened = {
    rows: shared.flattened.rows.filter((row) => selectedIds.has(String(row.resourceId || "").toLowerCase())),
    diagnostics,
  };
  const deploymentsByAccount = new Map(
    [...shared.deploymentsByAccount].filter(([accountId]) => selectedIds.has(accountId))
  );
  const data = summarizeFoundryMetrics(
    flattened,
    selectedAccounts,
    deploymentsByAccount,
    shared.pricing.pricesBySubscription
  );
  return {
    empty: !allAccounts.length,
    reason: allAccounts.length ? undefined : "no-resources",
    selectedAccountId,
    window: shared.window,
    accounts: allAccounts,
    panels: FOUNDRY_PANEL_CONTRACT,
    data,
    pricing: {
      status: shared.pricing.status,
      errors: shared.pricing.errors,
      candidateRows: shared.pricing.candidateRows,
      subscriptionsQueried: shared.pricing.pricesBySubscription.size,
    },
    source: {
      operational: "Azure Monitor metrics for Microsoft.CognitiveServices/accounts",
      pricing: "FinOps Hub Prices() estimate",
      billedCost: "FinOps Hub Costs() only",
      authoritativeCost: false,
    },
    generatedAt: shared.generatedAt,
  };
}

function getCachedFoundryShared(input) {
  const { connection, database, tenantId, preset = "7d", getPrices, options = {} } = input;
  const loader = getPrices || queryFoundryMetrics;
  const ttlMs = Math.max(0, Number(options.foundryCacheTtlMs ?? AGENT_CACHE_TTL_MS));
  const cache = foundryCache(loader);
  const key = [
    normalizeAzureTenantId(tenantId),
    foundryConnectionKey(connection, database),
    preset,
  ].join("|");
  const now = Date.now();
  const cached = cache.get(key);
  if (!options.bypassFoundryCache && cached && (cached.pending || cached.expiresAt > now)) {
    return cached.promise;
  }
  const entry = { pending: true, expiresAt: Number.POSITIVE_INFINITY, promise: null };
  entry.promise = loadFoundryShared(input)
    .then((result) => {
      entry.pending = false;
      entry.expiresAt = Date.now() + ttlMs;
      return result;
    })
    .catch((error) => {
      cache.delete(key);
      throw error;
    });
  cache.set(key, entry);
  return entry.promise;
}

export async function getFoundryDashboard(input) {
  return buildFoundryDashboard(await getCachedFoundryShared(input), input.accountId);
}
