table 'Compliance calculation'
	lineageTag: 9b45030f-f270-4b9c-8264-bde9e0fd5fea

	measure Compliance = [Compliant]/([Compliant]+[NonCompliant])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 29f8601e-ce71-4a61-b68a-1f2156fa7579

	measure Compliant = [totalResource]-[NonCompliant]-[Error]
		lineageTag: 64fc79fa-cc90-4fde-beb2-b91897876b57

	measure Error = CALCULATE(COUNTROWS(PolicyStates),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="Error")
		formatString: 0
		lineageTag: 29658b49-19e5-4be8-9167-ed47736603ef

	measure NonCompliant = CALCULATE(DISTINCTCOUNT(PolicyStates[properties.resourceId]),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="NonCompliant")
		formatString: 0
		lineageTag: 02012fa6-cb4e-40ce-b1f1-6f309a674b5f

	measure totalResource = DISTINCTCOUNT(PolicyStates[properties.resourceId])
		formatString: 0
		lineageTag: 01b903ed-7899-418d-b0b2-1b0596b5c997

	measure Unknown = CALCULATE(COUNTROWS(PolicyStates),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="Unknown")
		formatString: 0
		lineageTag: 9becaa14-5807-417b-bd27-11ab94040ea7

	column id
		lineageTag: 35d1b525-0b41-4d94-b4ec-364fa486a1d2
		summarizeBy: none
		isNameInferred
		sourceColumn: PolicyAssignments[id]

		annotation SummarizationSetBy = Automatic

	partition 'Compliance calculation' = calculated
		mode: import
		source = SUMMARIZE(PolicyAssignments,PolicyAssignments[id])

	annotation PBI_Id = af3777b18ad24a32ba4657565bfd5d7e

