/// Instance size flexibility data loaded from a Cost Management storage account. Use anonymous access to connect to this data.
table InstanceSizeFlexibility
	lineageTag: 04a435c4-9138-4c1f-ad59-dd939cd8e139

	column x_CommitmentDiscountFlexGroup
		dataType: string
		lineageTag: 57d1a022-b990-443e-ac76-39099da91d22
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountFlexGroup

		annotation SummarizationSetBy = Automatic

	column RegionId
		dataType: string
		lineageTag: 0048e9dd-f968-48b6-b249-8809062ee9c1
		summarizeBy: none
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column x_SkuType
		dataType: string
		lineageTag: 528c532f-6dfe-4e64-82d0-577334078041
		summarizeBy: none
		sourceColumn: x_SkuType

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountFlexRatio
		dataType: int64
		formatString: 0
		lineageTag: 8b5d50bb-801f-4161-ad86-25d089cf77fb
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountFlexRatio

		annotation SummarizationSetBy = Automatic

	column x_SkuComboMeter
		dataType: string
		lineageTag: 3e71b355-f940-4cb4-89b9-5128567265d2
		summarizeBy: none
		sourceColumn: x_SkuComboMeter

		annotation SummarizationSetBy = Automatic

	column x_SkuHardwareMeter
		dataType: string
		lineageTag: 00534664-6f13-4eca-9d9b-2a23cc470ecf
		summarizeBy: none
		sourceColumn: x_SkuHardwareMeter

		annotation SummarizationSetBy = Automatic

	column x_SkuSoftwareMeter
		dataType: string
		lineageTag: 0f3af934-f3a3-4834-9191-21297b52076b
		summarizeBy: none
		sourceColumn: x_SkuSoftwareMeter

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountKey
		dataType: string
		lineageTag: 9cfd70d1-ca7f-44a4-ba5d-dfb34f11f7b6
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountKey

		annotation SummarizationSetBy = Automatic

	column x_SkuTypeNormalized
		dataType: string
		lineageTag: f4e375e3-cff8-41af-9c9b-45b6ac3becc3
		summarizeBy: none
		sourceColumn: x_SkuTypeNormalized

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountKeyNormalized = [x_SkuTypeNormalized] & [x_SkuHardwareMeter]
		lineageTag: d1db9f39-1d52-4cd1-950f-8089a14f760a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition InstanceSizeFlexibility = m
		mode: import
		queryGroup: 'Open data'
		source =
				let
				    Source = Csv.Document(AzureStorage.BlobContents("https://ccmstorageprod.blob.core.windows.net/costmanagementconnector-data/AutofitComboMeterData.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstanceSizeFlexibilityGroup", type text}, {"ResourceLocation", type text}, {"ArmSkuName", type text}, {"Ratio", Int64.Type}, {"ComboMeter", type text}, {"HardwareMeter", type text}, {"SoftwareMeter", type text}, {"CompositeKey", type text}, {"NormalizedSKU", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ArmSkuName", "x_SkuType"}, {"ComboMeter", "x_SkuComboMeter"}, {"CompositeKey", "x_CommitmentDiscountKey"}, {"HardwareMeter", "x_SkuHardwareMeter"}, {"InstanceSizeFlexibilityGroup", "x_CommitmentDiscountFlexGroup"}, {"NormalizedSKU", "x_SkuTypeNormalized"}, {"ResourceLocation", "RegionId"}, {"SoftwareMeter", "x_SkuSoftwareMeter"}, {"Ratio", "x_CommitmentDiscountFlexRatio"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

