table ManagementGroups
	lineageTag: 0e04ab5f-9838-4180-a7f3-dc1cbcb6f296

	column id
		dataType: string
		lineageTag: 38577e5e-de2d-4ca7-a7bf-0bd1d7760f70
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 0fd21169-a00f-4900-9617-2b610fd5aeeb
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 7caac691-f03c-426f-a945-13fac8d416eb
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 41a1123e-155c-48a8-ae42-be5c2f9a8d39
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: fdcebd93-8ecc-42c1-ad50-b8a9545c2ff4
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: bd352c53-fffc-45b9-9042-ddac5d8cb7b1
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 32c2cdd3-8cfb-467f-b932-bd860cdf5454
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 95c5f3c2-0cf9-40e6-93bf-70c46e61ee16
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: b7f98133-e7a2-4b5c-80b3-f07c76116251
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 8a230b5a-d863-43b3-a713-31badfce6796
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: c405bc3b-7b6b-45c4-93e4-06f0d3eda278
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: c95adf9e-155b-4db2-a6e8-83d630a2892e
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column 'managementGroupAncestorsChain.displayName'
		dataType: string
		lineageTag: 6c8a61d3-6351-4374-b38b-85f967964e05
		summarizeBy: none
		sourceColumn: managementGroupAncestorsChain.displayName

		annotation SummarizationSetBy = Automatic

	column 'managementGroupAncestorsChain.name'
		dataType: string
		lineageTag: 34bc6713-be52-4615-b9d5-dd89193cda7d
		summarizeBy: none
		sourceColumn: managementGroupAncestorsChain.name

		annotation SummarizationSetBy = Automatic

	column updatedTime
		dataType: string
		lineageTag: 7df50bf9-576b-4d14-ac15-b2e380019699
		summarizeBy: none
		sourceColumn: updatedTime

		annotation SummarizationSetBy = Automatic

	column updatedBy
		dataType: string
		lineageTag: 0534e99a-a2a7-444c-88ea-26d6e6a060f5
		summarizeBy: none
		sourceColumn: updatedBy

		annotation SummarizationSetBy = Automatic

	column version
		dataType: string
		lineageTag: 775e305e-38e1-4c55-988b-4f2b8a3b57d6
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column 'parent.displayName'
		dataType: string
		lineageTag: d766d044-4796-4bef-9dbb-5abc1f8a9366
		summarizeBy: none
		sourceColumn: parent.displayName

		annotation SummarizationSetBy = Automatic

	column 'parent.name'
		dataType: string
		lineageTag: 363e53e3-8504-4dd9-bd88-8df6c587a964
		summarizeBy: none
		sourceColumn: parent.name

		annotation SummarizationSetBy = Automatic

	column 'parent.id'
		dataType: string
		lineageTag: ded0c0a5-dc3f-42ff-8ee0-fbaca8fff87e
		summarizeBy: none
		sourceColumn: parent.id

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 9084e19a-6639-447c-b365-671cd2e81486
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 5ffd94bb-922a-4e28-a475-b818e035a90f
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 843d2718-8d1a-41a2-be04-8010408f4f84
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 1536d8ca-3e8b-492f-9ebd-1760fcda0656
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition ManagementGroups = m
		mode: import
		queryGroup: 'Resource Graph'
		source =
				let
				  Source = AzureResourceGraph.Query("
				    resourcecontainers
				    | where type == 'microsoft.management/managementgroups'
				  " & (if ftk_DemoFilter() = "" then "" else "| where name startswith 'Trey'"), "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"displayName", "details"}, {"displayName", "details"}),
				  #"Expanded details" = Table.ExpandRecordColumn(#"Expanded properties", "details", {"managementGroupAncestorsChain", "updatedTime", "updatedBy", "version", "parent"}, {"managementGroupAncestorsChain", "updatedTime", "updatedBy", "version", "parent"}),
				  #"Expanded parent" = Table.ExpandRecordColumn(#"Expanded details", "parent", {"displayName", "name", "id"}, {"parent.displayName", "parent.name", "parent.id"}),
				  #"Expanded managementGroupAncestorsChain" = Table.ExpandListColumn(#"Expanded parent", "managementGroupAncestorsChain"),
				  #"Expanded managementGroupAncestorsChain 1" = Table.ExpandRecordColumn(#"Expanded managementGroupAncestorsChain", "managementGroupAncestorsChain", {"displayName", "name"}, {"managementGroupAncestorsChain.displayName", "managementGroupAncestorsChain.name"})
				in
				  #"Expanded managementGroupAncestorsChain 1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

