/// Cost and usage (FOCUS) data from Cost Management exports.
/// 
/// Data version = 1.0-preview(v1)
/// Learn more @ https://aka.ms/finops/hubs
table ReservationRecomendations
	lineageTag: e2acd751-9829-4624-bb15-d9a1cb22f057

	column ChargePeriodStart
		dataType: dateTime
		formatString: General Date
		lineageTag: b0452121-e940-47c3-8c6e-e3982d4eef46
		summarizeBy: none
		sourceColumn: ChargePeriodStart

		annotation SummarizationSetBy = Automatic

	column ContractedCost
		dataType: double
		lineageTag: f78b1e2b-c53a-405f-8ac7-e3e546644bb9
		summarizeBy: sum
		sourceColumn: ContractedCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveCost
		dataType: double
		lineageTag: 7bb5c5ca-328a-47eb-8f98-407fa05a208a
		summarizeBy: sum
		sourceColumn: EffectiveCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RegionId
		dataType: string
		lineageTag: 97c29472-f16f-43ee-9a8b-0c2fd9ea3708
		summarizeBy: none
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column x_CommitmentCostSavings
		dataType: double
		lineageTag: a485aa3f-b250-47dd-bc10-25ee191fbe2b
		summarizeBy: sum
		sourceColumn: x_CommitmentCostSavings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_IncrementalRefreshDate
		dataType: string
		lineageTag: 0d03437c-a892-4d20-9e24-e1ae25b31e47
		summarizeBy: none
		sourceColumn: x_IncrementalRefreshDate

		annotation SummarizationSetBy = Automatic

	column x_LookbackPeriod
		dataType: string
		lineageTag: 6c100c2c-63f8-408d-af01-3a0f29d8e8f9
		summarizeBy: none
		sourceColumn: x_LookbackPeriod

		annotation SummarizationSetBy = Automatic

	column x_RecommendedQuantity
		dataType: double
		lineageTag: d89a1d79-6b29-44e5-b003-6bad08adcffa
		summarizeBy: sum
		sourceColumn: x_RecommendedQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_RecommendedQuantityNormlized
		dataType: double
		lineageTag: 89705278-04fb-4195-a8b8-939235bcaf31
		summarizeBy: sum
		sourceColumn: x_RecommendedQuantityNormlized

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_SkuDetails
		dataType: string
		lineageTag: 1436758b-70a6-468d-945a-84a0a392ad45
		summarizeBy: none
		sourceColumn: x_SkuDetails

		annotation SummarizationSetBy = Automatic

	column x_SkuMeterId
		dataType: string
		lineageTag: 14a30bac-3352-45af-9908-a8b6753d594d
		summarizeBy: none
		sourceColumn: x_SkuMeterId

		annotation SummarizationSetBy = Automatic

	column x_SkuTerm
		dataType: double
		lineageTag: 1013a5ec-8dd1-41b6-828c-3303f799c754
		summarizeBy: sum
		sourceColumn: x_SkuTerm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_SkuType
		dataType: string
		lineageTag: a4dc7371-c985-4d7f-9dfa-6ba686e3d92e
		summarizeBy: none
		sourceColumn: x_SkuType

		annotation SummarizationSetBy = Automatic

	column x_SkuTypeNormalized
		dataType: string
		lineageTag: e8061aef-7550-481a-b922-0eb51fa5b941
		summarizeBy: none
		sourceColumn: x_SkuTypeNormalized

		annotation SummarizationSetBy = Automatic

	column TermLabel = IF([x_SKuTerm] = 12, "1 year", IF([x_SKuTerm] = 36, "3 year", IF([x_SKuTerm] = 60, "5 year", FORMAT([x_SKuTerm], ""))))
		lineageTag: e04a711d-dd85-44b4-9f88-aff1e84e5499
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountFlexGroup
		dataType: string
		lineageTag: 89935ef7-8197-4c5e-ad5a-4a3caba3dd5f
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountFlexGroup

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountFlexRatio
		dataType: string
		lineageTag: 4ad018db-5f35-4c7a-bb7f-1cd68371c87d
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountFlexRatio

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountKey = CONCATENATE([x_SkuTypeNormalized], [x_SkuMeterId])
		lineageTag: 1bcc33e3-2946-461c-a99d-31f6d228dc80
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountKeyNormalized = [x_SkuTypeNormalized] & [x_SkuMeterId]
		lineageTag: f752702c-e8c3-4687-909d-bad72fd0250d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountResourceType
		dataType: string
		lineageTag: 0c1be146-3120-4a5e-844b-48957c6b547a
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountResourceType

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountScope
		dataType: string
		lineageTag: d4ac4964-0805-4398-bc73-9dd7db4bae61
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountScope

		annotation SummarizationSetBy = Automatic

	column x_BillingAccountAgreement
		dataType: string
		lineageTag: bd791989-03ff-472b-bf5a-835bf1ea6a7d
		summarizeBy: none
		sourceColumn: x_BillingAccountAgreement

		annotation SummarizationSetBy = Automatic

	column x_SourceType
		dataType: string
		lineageTag: 6f87e180-fda9-41a6-817b-320f313162d1
		summarizeBy: none
		sourceColumn: x_SourceType

		annotation SummarizationSetBy = Automatic

	column x_SourceVersion
		dataType: string
		lineageTag: 5b288faa-c9d1-4fc5-a96d-31eacecd5060
		summarizeBy: none
		sourceColumn: x_SourceVersion

		annotation SummarizationSetBy = Automatic

	column RecommendedQuantityNormlized
		dataType: string
		lineageTag: 82c2150a-82ae-444d-b275-0f7b54c94115
		summarizeBy: sum
		sourceColumn: RecommendedQuantityNormlized

		annotation SummarizationSetBy = Automatic

	column TotaCostWithReservedInstances
		dataType: string
		lineageTag: df9cfff5-baa5-453a-b8db-539d5b97c952
		summarizeBy: sum
		sourceColumn: TotaCostWithReservedInstances

		annotation SummarizationSetBy = Automatic

	partition ReservationRecomendations = m
		mode: import
		queryGroup: Storage
		source = ```
				let
				    // Get the data
				    RawData = ftk_Storage("reservationrecommendations"),
				
				    _addMissing = (tbl, col, typ) => if Table.HasColumns(tbl, {col}) then tbl else Table.AddColumn(tbl, col, each null, typ),
				    FixTypes = Table.TransformColumnTypes(
				        Table.ReplaceValue(Table.ReplaceValue(
				            // Create missing columns
				            _addMissing(_addMissing(RawData,
				                "RecommendedQuantityNormalized", type number),
				                "TotalCostWithReservedInstances", type number),
				            // Normalize frequency
				            each [LookBackPeriod], each Text.Replace(Text.Replace([LookBackPeriod], "Last", ""), "Days", " Days"), Replacer.ReplaceValue, {"LookBackPeriod"}),
				            // Fix inconsistent Microsoft term values
				            each [Term], each if [Term] = "P1M" then 1 else if [Term] = "P1Y" then 12 else if [Term] = "P3Y" then 36 else if [Term] = "P5Y" then 60 else Number.FromText([Term]), Replacer.ReplaceValue, {"Term"}),
				        {
				            // Dates
				            {"FirstUsageDate",                 type datetime},
				            // Numbers
				            {"CostWithNoReservedInstances",    type number},
				            {"NetSavings",                     type number},
				            {"RecommendedQuantity",            type number},
				            {"RecommendedQuantityNormalized",  type number},
				            {"Term",                           type number},
				            {"TotalCostWithReservedInstances", type number}
				        }
				    ),
				
				    Rename = Table.RenameColumns(FixTypes, {
				        {"CostWithNoReservedInstances",    "ContractedCost"},
				        {"FirstUsageDate",                 "ChargePeriodStart"},
				        {"InstanceFlexibilityGroup",       "x_CommitmentDiscountFlexGroup"},
				        {"InstanceFlexibilityRatio",       "x_CommitmentDiscountFlexRatio"},
				        {"Location",                       "RegionId"},
				        {"LookBackPeriod",                 "x_LookbackPeriod"},
				        {"MeterId",                        "x_SkuMeterId"},
				        {"NetSavings",                     "x_CommitmentCostSavings"},
				        {"NormalizedSize",                 "x_SkuTypeNormalized"},
				        {"RecommendedQuantity",            "x_RecommendedQuantity"},
				        {"RecommendedQuantityNormalized",  "x_RecommendedQuantityNormlized"},
				        {"ResourceType",                   "x_CommitmentDiscountResourceType"},
				        {"SKU",                            "x_SkuType"},
				        {"Scope",                          "x_CommitmentDiscountScope"},
				        {"SkuProperties",                  "x_SkuDetails"},
				        {"Term",                           "x_SkuTerm"},
				        {"TotalCostWithReservedInstances", "EffectiveCost"}
				    }, MissingField.Ignore),
				        
				    // Sort columns alphabetically
				    Output = Table.ReorderColumns(Rename, List.Sort(Table.ColumnNames(Rename)))
				in
				    Output
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

