# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

function Get-FinOpsServicesData {
    return [PSCustomObject]@(
        [PSCustomObject]@{ ConsumedService = 'Citrix.Services'; ResourceType = 'citrix.services/xenappessentials'; ServiceName = 'Citrix Virtual App Essentials'; ServiceCategory = 'Compute'; PublisherName = 'Citrix'; PublisherType = 'Marketplace'; }
        ,[PSCustomObject]@{ ConsumedService = 'Citrix.Services'; ResourceType = 'citrix.services/xendesktopessentials'; ServiceName = 'Citrix Virtual Desktop Essentials'; ServiceCategory = 'Compute'; PublisherName = 'Citrix'; PublisherType = 'Marketplace'; }
        ,[PSCustomObject]@{ ConsumedService = 'GitHub.Enterprise'; ResourceType = 'github.enterprise/accounts'; ServiceName = 'GitHub Enterprise Cloud'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'GitHub'; ResourceType = 'github/enterpriseaccount'; ServiceName = 'GitHub Enterprise Cloud'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Marketplace'; ResourceType = 'marketplace/account'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MFA'; ResourceType = 'mfa/perauthentication'; ServiceName = 'Microsoft Entra ID'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MFA'; ResourceType = 'mfa/peruser'; ServiceName = 'Microsoft Entra ID'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AAD'; ResourceType = 'microsoft.aad/domainservices'; ServiceName = 'Azure Active Directory Domain Services'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AgFoodPlatform'; ResourceType = 'microsoft.agfoodplatform/farmbeats'; ServiceName = 'Azure Data Manager for Agriculture'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AnalysisServices'; ResourceType = 'microsoft.analysisservices/servers'; ServiceName = 'Azure Analysis Services'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ApiManagement'; ResourceType = 'microsoft.apimanagement/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.apimanagement/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.App'; ResourceType = 'microsoft.app/containerapps'; ServiceName = 'Azure Container Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.App'; ResourceType = 'microsoft.app/managedenvironments'; ServiceName = 'Azure Container Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.appcenter'; ResourceType = 'microsoft.appcenter/accounts'; ServiceName = 'App Center'; ServiceCategory = 'Mobile'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AppConfiguration'; ResourceType = 'microsoft.appconfiguration/configurationstores'; ServiceName = 'App Configuration'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.appconfiguration/configurationstores'; ServiceName = 'App Configuration'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AppPlatform'; ResourceType = 'microsoft.appplatform/spring'; ServiceName = 'Azure Spring Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.automation'; ResourceType = 'microsoft.automation/automationaccounts'; ServiceName = 'Azure Automation'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AutonomousDevelopmentPlatform'; ResourceType = 'microsoft.autonomousdevelopmentplatform/workspaces'; ServiceName = 'Microsoft Autonomous Systems'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.autonomousdevelopmentplatform/workspaces'; ServiceName = 'Microsoft Autonomous Systems'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AVS'; ResourceType = 'microsoft.avs/privateclouds'; ServiceName = 'Azure VMware Solution'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureActiveDirectory'; ResourceType = 'microsoft.azureactivedirectory/b2cdirectories'; ServiceName = 'Azure Active Directory External Identities'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureActiveDirectory'; ResourceType = 'microsoft.azureactivedirectory/guestusages'; ServiceName = 'Azure Active Directory External Identities'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureArcData'; ResourceType = 'microsoft.azurearcdata/postgresinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureArcData'; ResourceType = 'microsoft.azurearcdata/sqlmanagedinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureArcData'; ResourceType = 'microsoft.azurearcdata/sqlserverinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.AzureStackHCI'; ResourceType = 'microsoft.azurestackhci/clusters'; ServiceName = 'Azure Stack HCI'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.BareMetalInfrastructure'; ResourceType = 'microsoft.baremetalinfrastructure/baremetalstorageinstances'; ServiceName = 'BareMetal Infrastructure'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Batch'; ResourceType = 'microsoft.batch/batchaccounts'; ServiceName = 'Batch'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Bing'; ResourceType = 'microsoft.bing/accounts'; ServiceName = 'Microsoft Bing'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.BotService'; ResourceType = 'microsoft.botservice/botservices'; ServiceName = 'Azure AI Bot Service'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Cache'; ResourceType = 'microsoft.cache/redis'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.cache/redis'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Cache'; ResourceType = 'microsoft.cache/redisenterprise'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cdn'; ResourceType = 'microsoft.cdn/cdnwebapplicationfirewallpolicies'; ServiceName = 'Content Delivery Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Cdn'; ResourceType = 'microsoft.cdn/profiles'; ServiceName = 'Content Delivery Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.certificateregistration'; ResourceType = 'microsoft.certificateregistration/certificateorders'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classiccompute'; ResourceType = 'microsoft.classiccompute/domainnames'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classiccompute'; ResourceType = 'microsoft.classiccompute/virtualmachines'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ClassicNetwork'; ResourceType = 'microsoft.classicnetwork/ipv4vip'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ClassicNetwork'; ResourceType = 'microsoft.classicnetwork/publicip'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ClassicNetwork'; ResourceType = 'microsoft.classicnetwork/publicipaddresses'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ClassicStorage'; ResourceType = 'microsoft.classicstorage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.CognitiveServices'; ResourceType = 'microsoft.cognitiveservices/accounts'; ServiceName = 'Azure AI Services'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.communication'; ResourceType = 'microsoft.communication/communicationservices'; ServiceName = 'Azure Communication Services'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.communication/communicationservices'; ServiceName = 'Azure Communication Services'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/capacityreservationgroups'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/cloudservices'; ServiceName = 'Cloud Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/disks'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/galleries'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/hostgroups'; ServiceName = 'Azure Dedicated Host'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/images'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/restorepointcollections'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/sharedvmimages'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Compute'; ResourceType = 'microsoft.compute/snapshots'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/virtualmachines'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/virtualmachinescalesets'; ServiceName = 'Virtual Machine Scale Sets'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ConfidentialLedger'; ResourceType = 'microsoft.confidentialledger/ledgers'; ServiceName = 'Azure Confidential Ledger'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ContainerInstance'; ResourceType = 'microsoft.containerinstance/containergroups'; ServiceName = 'Azure Container Instances'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.containerregistry'; ResourceType = 'microsoft.containerregistry/registries'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.containerregistry/registries'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ContainerService'; ResourceType = 'microsoft.containerservice/containerservices'; ServiceName = 'Azure Container Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ContainerService'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.KubernetesConfiguration'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.DASHBOARD'; ResourceType = 'microsoft.dashboard/grafana'; ServiceName = 'Azure Managed Grafana'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataBox'; ResourceType = 'microsoft.databox/jobs'; ServiceName = 'Azure Data Box'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataBoxEdge'; ResourceType = 'microsoft.databoxedge/databoxedgedevices'; ServiceName = 'Azure Data Box'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Databricks'; ResourceType = 'microsoft.databricks/workspaces'; ServiceName = 'Azure Databricks'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataCatalog'; ResourceType = 'microsoft.datacatalog/catalogs'; ServiceName = 'Data Catalog'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataFactory'; ResourceType = 'microsoft.datafactory/datafactories'; ServiceName = 'Azure Data Factory'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.DATAFACTORY'; ResourceType = 'microsoft.datafactory/factories'; ServiceName = 'Azure Data Factory'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataLakeAnalytics'; ResourceType = 'microsoft.datalakeanalytics/accounts'; ServiceName = 'Azure Data Lake Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataLakeStore'; ResourceType = 'microsoft.datalakestore/accounts'; ServiceName = 'Azure Data Lake Store'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.DATAMIGRATION'; ResourceType = 'microsoft.datamigration/sqlmigrationservices'; ServiceName = 'Azure Database Migration Service'; ServiceCategory = 'Migration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataProtection'; ResourceType = 'microsoft.dataprotection/backupvaults'; ServiceName = 'Azure Backup'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DataShare'; ResourceType = 'microsoft.datashare/accounts'; ServiceName = 'Azure Data Share'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforMariaDB'; ResourceType = 'microsoft.dbformariadb/servers'; ServiceName = 'Azure DB for MariaDB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforMySQL'; ResourceType = 'microsoft.dbformysql/flexibleservers'; ServiceName = 'Azure DB for MySQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforMySQL'; ResourceType = 'microsoft.dbformysql/servers'; ServiceName = 'Azure DB for MySQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforPostgreSQL'; ResourceType = 'microsoft.dbforpostgresql/flexibleservers'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforPostgreSQL'; ResourceType = 'microsoft.dbforpostgresql/servergroupsv2'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DBforPostgreSQL'; ResourceType = 'microsoft.dbforpostgresql/servers'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DesktopVirtualization'; ResourceType = 'microsoft.desktopvirtualization/hostpools'; ServiceName = 'Azure Virtual Desktop'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.devcenter'; ResourceType = 'microsoft.devcenter/projects'; ServiceName = 'Microsoft Dev Box'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.devices'; ResourceType = 'microsoft.devices/iothubs'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.devices/iothubs'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.DEVICES'; ResourceType = 'microsoft.devices/provisioningservices'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DeviceUpdate'; ResourceType = 'microsoft.deviceupdate/accounts'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DigitalTwins'; ResourceType = 'microsoft.digitaltwins/digitaltwinsinstances'; ServiceName = 'Azure Digital Twins'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DocumentDB'; ResourceType = 'microsoft.documentdb/cassandraclusters'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.documentdb'; ResourceType = 'microsoft.documentdb/databaseaccounts'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DocumentDB'; ResourceType = 'microsoft.documentdb/mongocluster'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.DocumentDB'; ResourceType = 'microsoft.documentdb/mongoclusters'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.domainregistration'; ResourceType = 'microsoft.domainregistration/domains'; ServiceName = 'App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Easm'; ResourceType = 'microsoft.easm/workspaces'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EdgeOrder'; ResourceType = 'microsoft.edgeorder/orderitems'; ServiceName = 'Azure Stack Edge'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ElasticSan'; ResourceType = 'microsoft.elasticsan/elasticsans'; ServiceName = 'Azure Elastic SAN'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.eventgrid/domains'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.eventgrid/extensiontopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.eventgrid/namespaces'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.EVENTGRID'; ResourceType = 'microsoft.eventgrid/partnertopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.EVENTGRID'; ResourceType = 'microsoft.eventgrid/systemtopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.eventgrid/topics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventHub'; ResourceType = 'microsoft.eventhub/clusters'; ServiceName = 'Event Hubs'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.eventhub/namespaces'; ServiceName = 'Event Hubs'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventHub'; ResourceType = 'microsoft.eventhub/namespaces'; ServiceName = 'Event Hubs'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Fabric'; ResourceType = 'microsoft.fabric/capacities'; ServiceName = 'Microsoft.Fabric'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.FluidRelay'; ResourceType = 'microsoft.fluidrelay/fluidrelayservers'; ServiceName = 'Azure Fluid Relay'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Genomics'; ResourceType = 'microsoft.genomics/accounts'; ServiceName = 'Microsoft Genomics'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Graph'; ResourceType = 'microsoft.graph/azureadapplications'; ServiceName = 'Microsoft Graph Data Connect'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.GraphServices'; ResourceType = 'microsoft.graphservices/accounts'; ServiceName = 'Microsoft Graph'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HanaOnAzure'; ResourceType = 'microsoft.hanaonazure/hanainstances'; ServiceName = 'SAP on Azure'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HardwareSecurityModules'; ResourceType = 'microsoft.hardwaresecuritymodules/dedicatedhsms'; ServiceName = 'Azure Dedicated HSM'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HDInsight'; ResourceType = 'microsoft.hdinsight/clusters'; ServiceName = 'HDInsight'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HDInsightFairfax'; ResourceType = 'microsoft.hdinsightfairfax/clusters'; ServiceName = 'HDInsight'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HealthBot'; ResourceType = 'microsoft.healthbot/healthbots'; ServiceName = 'Health Bot'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HealthcareApis'; ResourceType = 'microsoft.healthcareapis/services'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.healthcareapis/workspaces'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.HealthcareApis'; ResourceType = 'microsoft.healthcareapis/workspaces'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hybridcompute'; ResourceType = 'microsoft.hybridcompute/machines'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = ''; ResourceType = 'microsoft.hybridnetwork/devices'; ServiceName = 'Azure Network Function Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ImportExport'; ResourceType = 'microsoft.importexport/jobs'; ServiceName = 'Azure Storage'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/actiongroups'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/components'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/metricalerts'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Insights'; ResourceType = 'microsoft.insights/pricings'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/scheduledqueryrules'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.IoTCentral'; ResourceType = 'microsoft.iotcentral/iotapps'; ServiceName = 'Azure IoT Central'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'default'; ResourceType = 'microsoft.iotsecurity/defendersettings'; ServiceName = 'Microsoft Defender for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.IoTSecurity'; ResourceType = 'microsoft.iotsecurity/defendersettings'; ServiceName = 'Microsoft Defender for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.KeyVault'; ResourceType = 'microsoft.keyvault/hsmpools'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.KeyVault'; ResourceType = 'microsoft.keyvault/managedhsms'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.keyvault/vaults'; ServiceName = 'Azure KeyVault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.KEYVAULT'; ResourceType = 'microsoft.keyvault/vaults'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.kubernetes'; ResourceType = 'microsoft.kubernetes/connectedclusters'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Kusto'; ResourceType = 'microsoft.kusto/clusters'; ServiceName = 'Azure Data Explorer'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.labservices'; ResourceType = 'microsoft.labservices/labaccounts'; ServiceName = 'Azure Lab Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.LabServices'; ResourceType = 'microsoft.labservices/labs'; ServiceName = 'Azure Lab Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.loadtestservice'; ResourceType = 'microsoft.loadtestservice/loadtests'; ServiceName = 'Azure Load Testing'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Logic'; ResourceType = 'microsoft.logic/integrationaccounts'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Logic'; ResourceType = 'microsoft.logic/integrationserviceenvironments'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.LOGIC'; ResourceType = 'microsoft.logic/workflows'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MachineLearning'; ResourceType = 'microsoft.machinelearning/commitmentplans'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MachineLearning'; ResourceType = 'microsoft.machinelearning/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.machinelearningservices/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MachineLearningServices'; ResourceType = 'microsoft.machinelearningservices/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.maintenance/maintenanceconfigurations'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.maps/accounts'; ServiceName = 'Azure Maps'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Maps'; ResourceType = 'microsoft.maps/accounts'; ServiceName = 'Azure Maps'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.media/mediaservices'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Media'; ResourceType = 'microsoft.media/mediaservices'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Media'; ResourceType = 'microsoft.media/videoanalyzers'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Migrate'; ResourceType = 'microsoft.migrate/movecollections'; ServiceName = 'Azure Migrate'; ServiceCategory = 'Migration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MixedReality'; ResourceType = 'microsoft.mixedreality/objectanchorsaccounts'; ServiceName = 'Object Anchors'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MixedReality'; ResourceType = 'microsoft.mixedreality/remoterenderingaccounts'; ServiceName = 'Remote Rendering'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MixedReality'; ResourceType = 'microsoft.mixedreality/spatialanchorsaccounts'; ServiceName = 'Spatial Anchors'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.MobileNetwork'; ResourceType = 'microsoft.mobilenetwork/mobilenetworks'; ServiceName = 'Azure Private 5G Core'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mobilenetwork'; ResourceType = 'microsoft.mobilenetwork/packetcorecontrolplanes'; ServiceName = 'Azure Private 5G Core'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.monitor'; ResourceType = 'microsoft.monitor/accounts'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.NetApp'; ResourceType = 'microsoft.netapp/netappaccounts'; ServiceName = 'Azure NetApp Files'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/applicationgateways'; ServiceName = 'Application Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/azurefirewalls'; ServiceName = 'Azure Firewall'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/bastionhosts'; ServiceName = 'Azure Bastion'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/connections'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/ddosprotectionplans'; ServiceName = 'Azure DDoS Protection'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/dnsforwardingrulesets'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/dnsresolvers'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/dnszones'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/expressroutecircuits'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/expressroutegateways'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/expressrouteports'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/firewallpolicies'; ServiceName = 'Azure Firewall Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/frontdoors'; ServiceName = 'Azure Front Door'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/frontdoorwebapplicationfirewallpolicies'; ServiceName = 'Azure Front Door'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = ''; ResourceType = 'microsoft.network/internetanalyzerprofiles'; ServiceName = 'Azure Internet Analyzer'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/loadbalancers'; ServiceName = 'Load Balancer'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/natgateways'; ServiceName = 'Azure NAT Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkinterfaces'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkmanagers'; ServiceName = 'Azure Virtual Network Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networksecuritygroups'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkvirtualappliances'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkwatchers'; ServiceName = 'Network Watcher'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/p2svpngateways'; ServiceName = 'VPN Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/privatednszones'; ServiceName = 'Azure Private Link'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/privateendpoints'; ServiceName = 'Azure Private Link'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/publicipaddresses'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/publicipprefixes'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/trafficmanagerprofiles'; ServiceName = 'Traffic Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/virtualhubs'; ServiceName = 'Virtual WAN'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/virtualnetworkgateways'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/virtualnetworks'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Network'; ResourceType = 'microsoft.network/vpngateways'; ServiceName = 'VPN Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.NetworkAnalytics'; ResourceType = 'microsoft.networkanalytics/dataconnectors'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.NotificationHubs'; ResourceType = 'microsoft.notificationhubs/namespaces'; ServiceName = 'Notification Hubs'; ServiceCategory = 'Mobile'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.nutanix'; ResourceType = 'microsoft.nutanix/nodes'; ServiceName = 'Azure VMWare Solution'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OpenEnergyPlatform'; ResourceType = 'microsoft.openenergyplatform/energyservices'; ServiceName = 'Azure Data manager for Energy'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OperationalInsights'; ResourceType = 'microsoft.operationalinsights/azurefirewall'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OperationalInsights'; ResourceType = 'microsoft.operationalinsights/clusters'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OperationalInsights'; ResourceType = 'microsoft.operationalinsights/networksecuritygroups'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OperationalInsights'; ResourceType = 'microsoft.operationalinsights/p2svpngateways'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.OperationalInsights'; ResourceType = 'microsoft.operationalinsights/virtualnetworkgateways'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/workspaces'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Orbital'; ResourceType = 'microsoft.orbital/spacecrafts'; ServiceName = 'Azure Orbital'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.ORBITAL'; ResourceType = 'microsoft.orbital/terminals'; ServiceName = 'Azure Orbital'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Peering'; ResourceType = 'microsoft.peering/peerings'; ServiceName = 'Azure Peering Service'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.PowerBIDedicated'; ResourceType = 'microsoft.powerbidedicated/autoscalevcores'; ServiceName = 'Power BI Embedded'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.PowerBIDedicated'; ResourceType = 'microsoft.powerbidedicated/capacities'; ServiceName = 'Power BI Embedded'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.PowerPlatform'; ResourceType = 'microsoft.powerplatform/accounts'; ServiceName = 'Power Platform'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Purview'; ResourceType = 'microsoft.purview/accounts'; ServiceName = 'Microsoft Purview'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Quantum'; ResourceType = 'microsoft.quantum/workspaces'; ServiceName = 'Azure Quantum'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.RecoveryServices'; ResourceType = 'microsoft.recoveryservices/vaults'; ServiceName = 'Azure Site Recovery'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Relay'; ResourceType = 'microsoft.relay/namespaces'; ServiceName = 'Azure Relay'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.SaaS'; ResourceType = 'microsoft.saas/resources'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Marketplace'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.SaaS'; ResourceType = 'microsoft.saas/saasresources'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Marketplace'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Search'; ResourceType = 'microsoft.search/searchservices'; ServiceName = 'Azure Cognitive Search'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Security'; ResourceType = 'microsoft.security/mdeservers'; ServiceName = 'Microsoft Defender for Endpoint'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'AppServices'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'ContainerRegistry'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'KubernetesService'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Security'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'VirtualMachines'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Security'; ResourceType = 'microsoft.security/securityconnectors'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.servicebus/namespaces'; ServiceName = 'Service Bus'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.ServiceBus'; ResourceType = 'microsoft.servicebus/namespaces'; ServiceName = 'Service Bus'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.signalrservice/signalr'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.SignalRService'; ResourceType = 'microsoft.signalrservice/signalr'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.SignalRService'; ResourceType = 'microsoft.signalrservice/webpubsub'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.solutions'; ResourceType = 'microsoft.solutions/applications'; ServiceName = 'Azure Managed Applications'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Sql'; ResourceType = 'microsoft.sql/instancepools'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiaeast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiasoutheast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'brazilsouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'canadacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'canadaeast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'centralindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'centralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastasia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastus2'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'francecentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'japaneast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'japanwest'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'koreacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'koreasouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Sql'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'northcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'northeurope'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'southafricanorth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'southcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'southeastasia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'southindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'uaenorth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'uksouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'ukwest'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'westcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'westeurope'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'westindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'westus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'westus2'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Sql'; ResourceType = 'microsoft.sql/managedinstances'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Sql'; ResourceType = 'microsoft.sql/servers'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.storage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.STORAGE'; ResourceType = 'microsoft.storage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StorageCache'; ResourceType = 'microsoft.storagecache/amlfilesystems'; ServiceName = 'Azure HPC Cache'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StorageCache'; ResourceType = 'microsoft.storagecache/caches'; ServiceName = 'Azure HPC Cache'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StorageSync'; ResourceType = 'microsoft.storagesync/storagesyncservices'; ServiceName = 'Azure File Sync'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StorSimple'; ResourceType = 'microsoft.storsimple/managers'; ServiceName = 'Azure StorSimple'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StreamAnalytics'; ResourceType = 'microsoft.streamanalytics/clusters'; ServiceName = 'Azure Stream Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.StreamAnalytics'; ResourceType = 'microsoft.streamanalytics/streamingjobs'; ServiceName = 'Azure Stream Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.SYNAPSE'; ResourceType = 'microsoft.synapse/workspaces'; ServiceName = 'Azure Synapse Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Syntex'; ResourceType = 'microsoft.syntex/accounts'; ServiceName = 'Microsoft Syntex'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Syntex'; ResourceType = 'microsoft.syntex/documentprocessors'; ServiceName = 'Microsoft Syntex'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.TESTBASE'; ResourceType = 'microsoft.testbase/testbaseaccounts'; ServiceName = 'Test Base for Microsoft 365'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.TimeSeriesInsights'; ResourceType = 'microsoft.timeseriesinsights/environments'; ServiceName = 'Azure Time Series Insights'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.VideoIndexer'; ResourceType = 'microsoft.videoindexer/accounts'; ServiceName = 'Azure AI Video Indexer'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.visualstudio'; ResourceType = 'microsoft.visualstudio/organizations'; ServiceName = 'Visual Studio'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.VoiceServices'; ResourceType = 'microsoft.voiceservices/communicationsgateways'; ServiceName = 'Azure Communitcations Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Web.Admin'; ResourceType = 'microsoft.web.admin/role'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'MICROSOFT.WEB'; ResourceType = 'microsoft.web/connections'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Web'; ResourceType = 'microsoft.web/containerapps'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/hostingenvironments'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.web/serverfarms'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/serverfarms'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.EventGrid'; ResourceType = 'microsoft.web/sites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.Web'; ResourceType = 'microsoft.web/sites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/staticsites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'Microsoft.WindowsIoT'; ResourceType = 'microsoft.windowsiot/deviceservices'; ServiceName = 'Windows for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'NGINX.NGINXPLUS'; ResourceType = 'nginx.nginxplus/nginxdeployments'; ServiceName = 'NGINX Plus'; ServiceCategory = 'Networking'; PublisherName = 'NGINX'; PublisherType = 'Marketplace'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/blobs'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/catalogrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/compute'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/egress'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/events'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/executiontimegbs'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/filestorage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/flatfee'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/insightscredits'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/inventoryreadrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/inventorywriterequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/itemstorage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/lobbyrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/matchmakingrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/messages'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/partyconnectivity'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/playstream'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/reads'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/storage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/telemetry'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/totalexecution'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
        ,[PSCustomObject]@{ ConsumedService = 'PlayFabBillingService'; ResourceType = 'playfabbillingservice/writes'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; }
    )
}
