# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

function Get-OpenDataService
{
    param()
    return [PSCustomObject]@(
        [PSCustomObject]@{ ConsumedService = ''; ResourceType = 'microsoft.hybridnetwork/devices'; ServiceName = 'Azure Network Function Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = ''; ResourceType = 'microsoft.network/internetanalyzerprofiles'; ServiceName = 'Azure Internet Analyzer'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'appservices'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiaeast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'australiasoutheast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'brazilsouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'canadacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'canadaeast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'centralindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'centralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'citrix.services'; ResourceType = 'citrix.services/xenappessentials'; ServiceName = 'Citrix Virtual App Essentials'; ServiceCategory = 'Compute'; PublisherName = 'Citrix'; PublisherType = 'Marketplace'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'citrix.services'; ResourceType = 'citrix.services/xendesktopessentials'; ServiceName = 'Citrix Virtual Desktop Essentials'; ServiceCategory = 'Compute'; PublisherName = 'Citrix'; PublisherType = 'Marketplace'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'containerregistry'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'default'; ResourceType = 'microsoft.iotsecurity/defendersettings'; ServiceName = 'Microsoft Defender for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastasia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'eastus2'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'francecentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'github'; ResourceType = 'github/enterpriseaccount'; ServiceName = 'GitHub Enterprise Cloud'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'github.enterprise'; ResourceType = 'github.enterprise/accounts'; ServiceName = 'GitHub Enterprise Cloud'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'japaneast'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'japanwest'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'koreacentral'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'koreasouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'kubernetesservice'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'marketplace'; ResourceType = 'marketplace/account'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'mfa'; ResourceType = 'mfa/perauthentication'; ServiceName = 'Microsoft Entra ID'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'mfa'; ResourceType = 'mfa/peruser'; ServiceName = 'Microsoft Entra ID'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.aad'; ResourceType = 'microsoft.aad/domainservices'; ServiceName = 'Microsoft Entra Domain Services'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.agfoodplatform'; ResourceType = 'microsoft.agfoodplatform/farmbeats'; ServiceName = 'Azure Data Manager for Agriculture'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.analysisservices'; ResourceType = 'microsoft.analysisservices/servers'; ServiceName = 'Azure Analysis Services'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.apicenter'; ResourceType = 'microsoft.apicenter/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.apimanagement'; ResourceType = 'microsoft.apimanagement/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.app'; ResourceType = 'microsoft.app/containerapps'; ServiceName = 'Azure Container Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.app'; ResourceType = 'microsoft.app/managedenvironments'; ServiceName = 'Azure Container Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.app'; ResourceType = 'microsoft.app/jobs'; ServiceName = 'Azure Container Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.appcenter'; ResourceType = 'microsoft.appcenter/accounts'; ServiceName = 'App Center'; ServiceCategory = 'Mobile'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.appconfiguration'; ResourceType = 'microsoft.appconfiguration/configurationstores'; ServiceName = 'App Configuration'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.appplatform'; ResourceType = 'microsoft.appplatform/spring'; ServiceName = 'Azure Spring Apps'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.automation'; ResourceType = 'microsoft.automation/automationaccounts'; ServiceName = 'Azure Automation'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.autonomousdevelopmentplatform'; ResourceType = 'microsoft.autonomousdevelopmentplatform/workspaces'; ServiceName = 'Microsoft Autonomous Systems'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.avs'; ResourceType = 'microsoft.avs/privateclouds'; ServiceName = 'Azure VMware Solution'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azureactivedirectory'; ResourceType = 'microsoft.azureactivedirectory/b2cdirectories'; ServiceName = 'Microsoft Entra External Identities'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azureactivedirectory'; ResourceType = 'microsoft.azureactivedirectory/guestusages'; ServiceName = 'Microsoft Entra External Identities'; ServiceCategory = 'Identity'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azurearcdata'; ResourceType = 'microsoft.azurearcdata/postgresinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azurearcdata'; ResourceType = 'microsoft.azurearcdata/sqlmanagedinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azurearcdata'; ResourceType = 'microsoft.azurearcdata/sqlserverinstances'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azurearcdata'; ResourceType = 'microsoft.azurearcdata/sqlserverlicenses'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azureplaywrightservice'; ResourceType = 'microsoft.azureplaywrightservice/accounts'; ServiceName = 'Playwright Testing'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.azurestackhci'; ResourceType = 'microsoft.azurestackhci/clusters'; ServiceName = 'Azure Stack HCI'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'On-Premises'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.baremetalinfrastructure'; ResourceType = 'microsoft.baremetalinfrastructure/baremetalstorageinstances'; ServiceName = 'BareMetal Infrastructure'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.batch'; ResourceType = 'microsoft.batch/batchaccounts'; ServiceName = 'Batch'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.billingbenefits'; ResourceType = 'Microsoft.BillingBenefits/savingsPlanOrders'; ServiceName = 'Azure Savings Plan for Compute'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.billingbenefits'; ResourceType = 'Microsoft.BillingBenefits/savingsPlanOrders/savingsPlans'; ServiceName = 'Azure Savings Plan for Compute'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.bing'; ResourceType = 'microsoft.bing/accounts'; ServiceName = 'Microsoft Bing'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.botservice'; ResourceType = 'microsoft.botservice/botservices'; ServiceName = 'Azure AI Bot Service'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cache'; ResourceType = 'microsoft.cache/redisenterprise'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cache'; ResourceType = 'microsoft.cache/redis'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.capacity'; ResourceType = 'microsoft.capacity/reservationOrders'; ServiceName = 'Azure Reservations'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.capacity'; ResourceType = 'microsoft.capacity/reservationOrders/reservations'; ServiceName = 'Azure Reservations'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cdn'; ResourceType = 'microsoft.cdn/cdnwebapplicationfirewallpolicies'; ServiceName = 'Content Delivery Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cdn'; ResourceType = 'microsoft.cdn/profiles'; ServiceName = 'Content Delivery Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.certificateregistration'; ResourceType = 'microsoft.certificateregistration/certificateorders'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.chaos'; ResourceType = 'microsoft.chaos/experiments'; ServiceName = 'Azure Chaos Studio'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classiccompute'; ResourceType = 'microsoft.classiccompute/domainnames'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classiccompute'; ResourceType = 'microsoft.classiccompute/virtualmachines'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classicnetwork'; ResourceType = 'microsoft.classicnetwork/ipv4vip'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classicnetwork'; ResourceType = 'microsoft.classicnetwork/publicip'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classicnetwork'; ResourceType = 'microsoft.classicnetwork/publicipaddresses'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.classicstorage'; ResourceType = 'microsoft.classicstorage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.codesigning'; ResourceType = 'microsoft.codesigning/codesigningaccounts'; ServiceName = 'Trusted Signing'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.cognitiveservices'; ResourceType = 'microsoft.cognitiveservices/accounts'; ServiceName = 'Azure AI Services'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.communication'; ResourceType = 'microsoft.communication/communicationservices'; ServiceName = 'Azure Communication Services'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/capacityreservationgroups'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/cloudservices'; ServiceName = 'Cloud Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/disks'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/galleries'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/hostgroups'; ServiceName = 'Azure Dedicated Host'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/images'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/restorepointcollections'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/sharedvmimages'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/snapshots'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/virtualmachines'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.compute'; ResourceType = 'microsoft.compute/virtualmachinescalesets'; ServiceName = 'Virtual Machine Scale Sets'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.confidentialledger'; ResourceType = 'microsoft.confidentialledger/ledgers'; ServiceName = 'Azure Confidential Ledger'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.confidentialledger'; ResourceType = 'microsoft.confidentialledger/managedccfs'; ServiceName = 'Azure Confidential Ledger'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.containerinstance'; ResourceType = 'microsoft.containerinstance/containergroups'; ServiceName = 'Azure Container Instances'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.containerregistry'; ResourceType = 'microsoft.containerregistry/registries'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.containerservice'; ResourceType = 'microsoft.containerservice/containerservices'; ServiceName = 'Azure Container Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.containerservice'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dashboard'; ResourceType = 'microsoft.dashboard/grafana'; ServiceName = 'Azure Managed Grafana'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.databox'; ResourceType = 'microsoft.databox/jobs'; ServiceName = 'Azure Data Box'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.databoxedge'; ResourceType = 'microsoft.databoxedge/databoxedgedevices'; ServiceName = 'Azure Data Box'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.databricks'; ResourceType = 'microsoft.databricks/workspaces'; ServiceName = 'Azure Databricks'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datacatalog'; ResourceType = 'microsoft.datacatalog/catalogs'; ServiceName = 'Data Catalog'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datafactory'; ResourceType = 'microsoft.datafactory/datafactories'; ServiceName = 'Azure Data Factory'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datafactory'; ResourceType = 'microsoft.datafactory/factories'; ServiceName = 'Azure Data Factory'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datalakeanalytics'; ResourceType = 'microsoft.datalakeanalytics/accounts'; ServiceName = 'Azure Data Lake Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datalakestore'; ResourceType = 'microsoft.datalakestore/accounts'; ServiceName = 'Azure Data Lake Store'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datamigration'; ResourceType = 'microsoft.datamigration/sqlmigrationservices'; ServiceName = 'Azure Database Migration Service'; ServiceCategory = 'Migration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dataprotection'; ResourceType = 'microsoft.dataprotection/backupvaults'; ServiceName = 'Azure Backup'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.datashare'; ResourceType = 'microsoft.datashare/accounts'; ServiceName = 'Azure Data Share'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbformariadb'; ResourceType = 'microsoft.dbformariadb/servers'; ServiceName = 'Azure DB for MariaDB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbformysql'; ResourceType = 'microsoft.dbformysql/flexibleservers'; ServiceName = 'Azure DB for MySQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbformysql'; ResourceType = 'microsoft.dbformysql/servers'; ServiceName = 'Azure DB for MySQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbforpostgresql'; ResourceType = 'microsoft.dbforpostgresql/flexibleservers'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbforpostgresql'; ResourceType = 'microsoft.dbforpostgresql/servergroupsv2'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.dbforpostgresql'; ResourceType = 'microsoft.dbforpostgresql/servers'; ServiceName = 'Azure DB for PostgreSQL'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.desktopvirtualization'; ResourceType = 'microsoft.desktopvirtualization/hostpools'; ServiceName = 'Azure Virtual Desktop'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.devcenter'; ResourceType = 'microsoft.devcenter/projects'; ServiceName = 'Microsoft Dev Box'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.devices'; ResourceType = 'microsoft.devices/provisioningservices'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.devices'; ResourceType = 'microsoft.devices/iothubs'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.deviceupdate'; ResourceType = 'microsoft.deviceupdate/accounts'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.digitaltwins'; ResourceType = 'microsoft.digitaltwins/digitaltwinsinstances'; ServiceName = 'Azure Digital Twins'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.documentdb'; ResourceType = 'microsoft.documentdb/cassandraclusters'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.documentdb'; ResourceType = 'microsoft.documentdb/databaseaccounts'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.documentdb'; ResourceType = 'microsoft.documentdb/mongocluster'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.documentdb'; ResourceType = 'microsoft.documentdb/mongoclusters'; ServiceName = 'Cosmos DB'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.domainregistration'; ResourceType = 'microsoft.domainregistration/domains'; ServiceName = 'App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.easm'; ResourceType = 'microsoft.easm/workspaces'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.edgeorder'; ResourceType = 'microsoft.edgeorder/orderitems'; ServiceName = 'Azure Stack Edge'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.elasticsan'; ResourceType = 'microsoft.elasticsan/elasticsans'; ServiceName = 'Azure Elastic SAN'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.apimanagement/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.appconfiguration/configurationstores'; ServiceName = 'App Configuration'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.autonomousdevelopmentplatform/workspaces'; ServiceName = 'Microsoft Autonomous Systems'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.cache/redis'; ServiceName = 'Azure Cache for Redis'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.communication/communicationservices'; ServiceName = 'Azure Communication Services'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.containerregistry/registries'; ServiceName = 'Azure Container Registry'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/domains'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/extensiontopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/namespaces'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/partnertopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/systemtopics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventgrid/topics'; ServiceName = 'Event Grid'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.devices/iothubs'; ServiceName = 'Azure IoT Hub'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.eventhub/namespaces'; ServiceName = 'Event Hubs'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.keyvault/vaults'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.maintenance/maintenanceconfigurations'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.healthcareapis/workspaces'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.machinelearningservices/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.maps/accounts'; ServiceName = 'Azure Maps'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.apicenter/services'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.media/mediaservices'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.servicebus/namespaces'; ServiceName = 'Service Bus'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.signalrservice/signalr'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.storage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.web/serverfarms'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventgrid'; ResourceType = 'microsoft.web/sites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventhub'; ResourceType = 'microsoft.eventhub/namespaces'; ServiceName = 'Event Hubs'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.eventhub'; ResourceType = 'microsoft.eventhub/clusters'; ServiceName = 'Event Hubs'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.fabric'; ResourceType = 'microsoft.fabric/capacities'; ServiceName = 'Microsoft.Fabric'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.fluidrelay'; ResourceType = 'microsoft.fluidrelay/fluidrelayservers'; ServiceName = 'Azure Fluid Relay'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.genomics'; ResourceType = 'microsoft.genomics/accounts'; ServiceName = 'Microsoft Genomics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.graph'; ResourceType = 'microsoft.graph/azureadapplications'; ServiceName = 'Microsoft Graph Data Connect'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.graphservices'; ResourceType = 'microsoft.graphservices/accounts'; ServiceName = 'Microsoft Graph'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hanaonazure'; ResourceType = 'microsoft.hanaonazure/hanainstances'; ServiceName = 'SAP on Azure'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hardwaresecuritymodules'; ResourceType = 'microsoft.hardwaresecuritymodules/dedicatedhsms'; ServiceName = 'Azure Dedicated HSM'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hdinsight'; ResourceType = 'microsoft.hdinsight/clusters'; ServiceName = 'HDInsight'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hdinsight'; ResourceType = 'microsoft.hdinsight/clusterpools'; ServiceName = 'HDInsight'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hdinsightfairfax'; ResourceType = 'microsoft.hdinsightfairfax/clusters'; ServiceName = 'HDInsight'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.healthbot'; ResourceType = 'microsoft.healthbot/healthbots'; ServiceName = 'Health Bot'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.healthcareapis'; ResourceType = 'microsoft.healthcareapis/workspaces'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.healthcareapis'; ResourceType = 'microsoft.healthcareapis/services'; ServiceName = 'Azure Health Data Services'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hybridcompute'; ResourceType = 'microsoft.hybridcompute/machines'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.hybridcompute'; ResourceType = 'microsoft.hybridcompute/licenses'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.importexport'; ResourceType = 'microsoft.importexport/jobs'; ServiceName = 'Azure Storage'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/actiongroups'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/components'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/metricalerts'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/pricings'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.insights'; ResourceType = 'microsoft.insights/scheduledqueryrules'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.iotcentral'; ResourceType = 'microsoft.iotcentral/iotapps'; ServiceName = 'Azure IoT Central'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.iotsecurity'; ResourceType = 'microsoft.iotsecurity/defendersettings'; ServiceName = 'Microsoft Defender for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.keyvault'; ResourceType = 'microsoft.keyvault/hsmpools'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.keyvault'; ResourceType = 'microsoft.keyvault/managedhsms'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.keyvault'; ResourceType = 'microsoft.keyvault/vaults'; ServiceName = 'Key Vault'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.kubernetes'; ResourceType = 'microsoft.kubernetes/connectedclusters'; ServiceName = 'Azure Arc'; ServiceCategory = 'Multicloud'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.kubernetesconfiguration'; ResourceType = 'microsoft.containerservice/managedclusters'; ServiceName = 'Azure Kubernetes Service'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.kusto'; ResourceType = 'microsoft.kusto/clusters'; ServiceName = 'Azure Data Explorer'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.labservices'; ResourceType = 'microsoft.labservices/labaccounts'; ServiceName = 'Azure Lab Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.labservices'; ResourceType = 'microsoft.labservices/labs'; ServiceName = 'Azure Lab Services'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.loadtestservice'; ResourceType = 'microsoft.loadtestservice/loadtests'; ServiceName = 'Azure Load Testing'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.logic'; ResourceType = 'microsoft.logic/integrationaccounts'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.logic'; ResourceType = 'microsoft.logic/integrationserviceenvironments'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.logic'; ResourceType = 'microsoft.logic/workflows'; ServiceName = 'Logic Apps'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.machinelearning'; ResourceType = 'microsoft.machinelearning/commitmentplans'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.machinelearning'; ResourceType = 'microsoft.machinelearning/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.machinelearningservices'; ResourceType = 'microsoft.machinelearningservices/workspaces'; ServiceName = 'Azure Machine Learning'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.maps'; ResourceType = 'microsoft.maps/accounts'; ServiceName = 'Azure Maps'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.media'; ResourceType = 'microsoft.media/mediaservices'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.media'; ResourceType = 'microsoft.media/videoanalyzers'; ServiceName = 'Azure Media Services'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.migrate'; ResourceType = 'microsoft.migrate/movecollections'; ServiceName = 'Azure Migrate'; ServiceCategory = 'Migration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mixedreality'; ResourceType = 'microsoft.mixedreality/objectanchorsaccounts'; ServiceName = 'Object Anchors'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mixedreality'; ResourceType = 'microsoft.mixedreality/remoterenderingaccounts'; ServiceName = 'Remote Rendering'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mixedreality'; ResourceType = 'microsoft.mixedreality/spatialanchorsaccounts'; ServiceName = 'Spatial Anchors'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mobilenetwork'; ResourceType = 'microsoft.mobilenetwork/mobilenetworks'; ServiceName = 'Azure Private 5G Core'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.mobilenetwork'; ResourceType = 'microsoft.mobilenetwork/packetcorecontrolplanes'; ServiceName = 'Azure Private 5G Core'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.modsimworkbench'; ResourceType = 'microsoft.modsimworkbench/workbenches'; ServiceName = 'Azure Modeling and Simulation Workbench'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.monitor'; ResourceType = 'microsoft.monitor/accounts'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.netapp'; ResourceType = 'microsoft.netapp/netappaccounts'; ServiceName = 'Azure NetApp Files'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/applicationgateways'; ServiceName = 'Application Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/azurefirewalls'; ServiceName = 'Azure Firewall'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/bastionhosts'; ServiceName = 'Azure Bastion'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/connections'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/ddosprotectionplans'; ServiceName = 'Azure DDoS Protection'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/dnsforwardingrulesets'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/dnsresolvers'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/dnszones'; ServiceName = 'Azure DNS'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/expressroutecircuits'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/expressroutegateways'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/expressrouteports'; ServiceName = 'Azure ExpressRoute'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/firewallpolicies'; ServiceName = 'Azure Firewall Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/frontdoors'; ServiceName = 'Azure Front Door'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/frontdoorwebapplicationfirewallpolicies'; ServiceName = 'Azure Front Door'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/loadbalancers'; ServiceName = 'Load Balancer'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/natgateways'; ServiceName = 'Azure NAT Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkinterfaces'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkmanagers'; ServiceName = 'Azure Virtual Network Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networksecuritygroups'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkvirtualappliances'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/networkwatchers'; ServiceName = 'Network Watcher'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/p2svpngateways'; ServiceName = 'VPN Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/privatednszones'; ServiceName = 'Azure Private Link'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/privateendpoints'; ServiceName = 'Azure Private Link'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/publicipaddresses'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/publicipprefixes'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/trafficmanagerprofiles'; ServiceName = 'Traffic Manager'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/virtualhubs'; ServiceName = 'Virtual WAN'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/virtualnetworkgateways'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/virtualnetworkgateways/connections'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/virtualnetworks'; ServiceName = 'Virtual Network'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.network'; ResourceType = 'microsoft.network/vpngateways'; ServiceName = 'VPN Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.networkanalytics'; ResourceType = 'microsoft.networkanalytics/dataconnectors'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.networkanalytics'; ResourceType = 'microsoft.networkanalytics/dataproducts'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.notificationhubs'; ResourceType = 'microsoft.notificationhubs/namespaces'; ServiceName = 'Notification Hubs'; ServiceCategory = 'Mobile'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.nutanix'; ResourceType = 'microsoft.nutanix/nodes'; ServiceName = 'Azure VMWare Solution'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.openenergyplatform'; ResourceType = 'microsoft.openenergyplatform/energyservices'; ServiceName = 'Azure Data manager for Energy'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/azurefirewall'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/clusters'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/networksecuritygroups'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/p2svpngateways'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/virtualnetworkgateways'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.operationalinsights'; ResourceType = 'microsoft.operationalinsights/workspaces'; ServiceName = 'Azure Monitor'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.orbital'; ResourceType = 'microsoft.orbital/spacecrafts'; ServiceName = 'Azure Orbital'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.orbital'; ResourceType = 'microsoft.orbital/terminals'; ServiceName = 'Azure Orbital'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.peering'; ResourceType = 'microsoft.peering/peerings'; ServiceName = 'Azure Peering Service'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.powerbidedicated'; ResourceType = 'microsoft.powerbidedicated/autoscalevcores'; ServiceName = 'Power BI Embedded'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.powerbidedicated'; ResourceType = 'microsoft.powerbidedicated/capacities'; ServiceName = 'Power BI Embedded'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.powerplatform'; ResourceType = 'microsoft.powerplatform/accounts'; ServiceName = 'Power Platform'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.purview'; ResourceType = 'microsoft.purview/accounts'; ServiceName = 'Microsoft Purview'; ServiceCategory = 'Management and Governance'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.quantum'; ResourceType = 'microsoft.quantum/workspaces'; ServiceName = 'Azure Quantum'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.recoveryservices'; ResourceType = 'microsoft.recoveryservices/vaults'; ServiceName = 'Azure Site Recovery'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.relay'; ResourceType = 'microsoft.relay/namespaces'; ServiceName = 'Azure Relay'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.saas'; ResourceType = 'microsoft.saas/resources'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Marketplace'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.saas'; ResourceType = 'microsoft.saas/saasresources'; ServiceName = 'Azure Marketplace'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Marketplace'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.search'; ResourceType = 'microsoft.search/searchservices'; ServiceName = 'Azure Cognitive Search'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.security'; ResourceType = 'microsoft.apimanagement/service'; ServiceName = 'API Management'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.security'; ResourceType = 'microsoft.security/mdeservers'; ServiceName = 'Microsoft Defender for Endpoint'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.security'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.security'; ResourceType = 'microsoft.security/securityconnectors'; ServiceName = 'Microsoft Defender for Cloud'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.securitycopilot'; ResourceType = 'microsoft.securitycopilot/capacities'; ServiceName = 'Microsoft Copilot for Security'; ServiceCategory = 'Security'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.servicebus'; ResourceType = 'microsoft.servicebus/namespaces'; ServiceName = 'Service Bus'; ServiceCategory = 'Integration'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.signalrservice'; ResourceType = 'microsoft.signalrservice/signalr'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.signalrservice'; ResourceType = 'microsoft.signalrservice/webpubsub'; ServiceName = 'Azure SignalR Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.solutions'; ResourceType = 'microsoft.solutions/applications'; ServiceName = 'Azure Managed Applications'; ServiceCategory = 'Other'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.sql'; ResourceType = 'microsoft.sql/instancepools'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.sql'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.sql'; ResourceType = 'microsoft.sql/managedinstances'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.sql'; ResourceType = 'microsoft.sql/servers'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.sql'; ResourceType = 'microsoft.sql/servers/databases'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.storage'; ResourceType = 'microsoft.storage/storageaccounts'; ServiceName = 'Storage Accounts'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.storagecache'; ResourceType = 'microsoft.storagecache/amlfilesystems'; ServiceName = 'Azure HPC Cache'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.storagecache'; ResourceType = 'microsoft.storagecache/caches'; ServiceName = 'Azure HPC Cache'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.storagesync'; ResourceType = 'microsoft.storagesync/storagesyncservices'; ServiceName = 'Azure File Sync'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.storsimple'; ResourceType = 'microsoft.storsimple/managers'; ServiceName = 'Azure StorSimple'; ServiceCategory = 'Storage'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Hybrid'; ServiceModel = 'IaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.streamanalytics'; ResourceType = 'microsoft.streamanalytics/clusters'; ServiceName = 'Azure Stream Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.streamanalytics'; ResourceType = 'microsoft.streamanalytics/streamingjobs'; ServiceName = 'Azure Stream Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.synapse'; ResourceType = 'microsoft.synapse/workspaces'; ServiceName = 'Azure Synapse Analytics'; ServiceCategory = 'Analytics'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.syntex'; ResourceType = 'microsoft.syntex/accounts'; ServiceName = 'Microsoft Syntex'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.syntex'; ResourceType = 'microsoft.syntex/documentprocessors'; ServiceName = 'Microsoft Syntex'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.teams'; ResourceType = 'microsoft.teams/telephonyservices'; ServiceName = 'Microsoft Teams'; ServiceCategory = 'Business Applications'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.testbase'; ResourceType = 'microsoft.testbase/testbaseaccounts'; ServiceName = 'Test Base for Microsoft 365'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.timeseriesinsights'; ResourceType = 'microsoft.timeseriesinsights/environments'; ServiceName = 'Azure Time Series Insights'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.videoindexer'; ResourceType = 'microsoft.videoindexer/accounts'; ServiceName = 'Azure AI Video Indexer'; ServiceCategory = 'AI and Machine Learning'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.visualstudio'; ResourceType = 'microsoft.visualstudio/organizations'; ServiceName = 'Visual Studio'; ServiceCategory = 'Developer Tools'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.voiceservices'; ResourceType = 'microsoft.voiceservices/communicationsgateways'; ServiceName = 'Azure Communitcations Gateway'; ServiceCategory = 'Networking'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/serverfarms'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/connections'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/containerapps'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/hostingenvironments'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/sites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web'; ResourceType = 'microsoft.web/staticsites'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.web.admin'; ResourceType = 'microsoft.web.admin/role'; ServiceName = 'Azure App Service'; ServiceCategory = 'Web'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'microsoft.windowsiot'; ResourceType = 'microsoft.windowsiot/deviceservices'; ServiceName = 'Windows for IoT'; ServiceCategory = 'Internet of Things'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'nginx.nginxplus'; ResourceType = 'nginx.nginxplus/nginxdeployments'; ServiceName = 'NGINX Plus'; ServiceCategory = 'Networking'; PublisherName = 'NGINX'; PublisherType = 'Marketplace'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'northcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'northeurope'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/blobs'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/catalogrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/compute'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/egress'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/events'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/executiontimegbs'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/filestorage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/flatfee'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/insightscredits'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/inventoryreadrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/inventorywriterequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/itemstorage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/lobbyrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/matchmakingrequests'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/messages'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/partyconnectivity'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/playstream'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/reads'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/storage'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/telemetry'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/totalexecution'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'playfabbillingservice'; ResourceType = 'playfabbillingservice/writes'; ServiceName = 'Azure PlayFab'; ServiceCategory = 'Media'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'SaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'southafricanorth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'southcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'southeastasia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'southindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'uaenorth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'uksouth'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'ukwest'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'virtualmachines'; ResourceType = 'microsoft.security/pricings'; ServiceName = 'Virtual Machines'; ServiceCategory = 'Compute'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'westcentralus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'westeurope'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'westindia'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'westus'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
        ,[PSCustomObject]@{ ConsumedService = 'westus2'; ResourceType = 'microsoft.sql/locations'; ServiceName = 'Azure SQL Database'; ServiceCategory = 'Databases'; PublisherName = 'Microsoft'; PublisherType = 'Cloud Provider'; Environment = 'Cloud'; ServiceModel = 'PaaS'; }
    )
}
