name: Publish PowerShell
on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: InvokeBuild, PSScriptAnalyzer, Pester, Az.Accounts, Az.Resources
          shell: pwsh
      - uses: actions/checkout@v3
      - name: PowerShellGallery
        shell: pwsh
        run: ./.build/start.ps1 -Task Publish.PsModule -ApiKey ${{ secrets.POWERSHELLGALLERY }}
