table Advisor
	lineageTag: f0700d7c-8802-444e-a3b8-dc7c44d849a1

	column id
		dataType: string
		lineageTag: af75e945-6338-40a6-b3a2-7e9ac77d11f1
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 7b65f987-a450-4855-bca1-489d17cbc05e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 8a048b79-b717-4699-88b9-b065990d462e
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 826f951f-b9bc-44d1-8949-fbeb8c27dc5a
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: d5719a45-afab-4dcf-8641-6f0c5ff4c68d
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: ef00a906-bf90-472f-b72b-ca7a1a0be230
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 55662cad-46cb-4b19-b33d-7520ccf1bbe3
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 306c5ce1-5a40-4e8f-9694-ce16097d3ffd
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 0ac957c4-f701-46ec-8ec1-5603ed1a32d4
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 8a2680c0-5205-4123-aa17-66701268e772
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: e7f43d1b-a411-447b-824e-baa9a31ec649
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.recommendationTypeId'
		dataType: string
		lineageTag: 3c7502c6-5f18-4bfc-8f4f-89bcaa68c30a
		summarizeBy: none
		sourceColumn: properties.recommendationTypeId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ObservationPeriodStartDate'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8548c789-018e-4149-9dfc-5f068dcbe7ca
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ObservationPeriodStartDate

		variation Variation
			isDefault
			relationship: 9a9a8ff2-6f49-4f61-886e-5c7b393b6127
			defaultHierarchy: LocalDateTable_ebe5ed2a-5f3f-459d-a6cb-cf15814bb4f5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ObservationPeriodEndDate'
		dataType: dateTime
		formatString: General Date
		lineageTag: 898c066b-011e-4827-9cfe-f81fc8fa29a6
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ObservationPeriodEndDate

		variation Variation
			isDefault
			relationship: 77ecc27a-f31d-4241-afd4-d7708086a51d
			defaultHierarchy: LocalDateTable_0aa1ad5c-d7f4-4b27-93cc-875c8aa104c5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.annualSavingsAmount'
		dataType: double
		lineageTag: 7b8cb5e7-9783-4d50-b517-7a95cd0a938b
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.annualSavingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.HasRecommendation'
		dataType: string
		lineageTag: ea2a91d8-adb9-4eaf-8c46-b2305681c1e5
		summarizeBy: none
		sourceColumn: properties.extendedProperties.HasRecommendation

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsCurrency'
		dataType: string
		lineageTag: 2dcc34e5-0144-4b7e-8174-787626fa4516
		summarizeBy: none
		sourceColumn: properties.extendedProperties.savingsCurrency

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.IsInReplication'
		dataType: string
		lineageTag: bdfe2787-3709-4ab8-9b8f-839055891b79
		summarizeBy: none
		sourceColumn: properties.extendedProperties.IsInReplication

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Recommended_DTU'
		dataType: string
		lineageTag: 847d33b8-0d23-4534-b3e1-1b4547bcbdd1
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Recommended_DTU

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Recommended_SKU'
		dataType: string
		lineageTag: 7d8d5556-7d06-4da7-96b9-ad5cba11e4ce
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Recommended_SKU

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ResourceGroup'
		dataType: string
		lineageTag: 364164b2-e8c6-4951-be0d-9e392c2d5e37
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ResourceGroup

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsAmount'
		dataType: double
		lineageTag: bbb24996-db8d-4fb5-a32c-87a814906fba
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.savingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.DatabaseSize'
		dataType: string
		lineageTag: e7f650e3-5ca2-4100-9366-1ef234ed5697
		summarizeBy: none
		sourceColumn: properties.extendedProperties.DatabaseSize

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.DatabaseName'
		dataType: string
		lineageTag: f17910dd-e415-4667-aef9-b1ae6fe0ac7f
		summarizeBy: none
		sourceColumn: properties.extendedProperties.DatabaseName

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.ServerName'
		dataType: string
		lineageTag: 7a55d599-c70a-4b52-8ead-3319b03944ee
		summarizeBy: none
		sourceColumn: properties.extendedProperties.ServerName

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.Region'
		dataType: string
		lineageTag: 09e8de02-9975-412a-8d32-2017bcbd0d6b
		summarizeBy: none
		sourceColumn: properties.extendedProperties.Region

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.lookbackPeriod'
		dataType: string
		lineageTag: 7931942c-7c92-46e6-b761-bcecbbf269c4
		summarizeBy: none
		sourceColumn: properties.extendedProperties.lookbackPeriod

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.subId'
		dataType: string
		lineageTag: b6d82cc6-3421-43bf-885d-204eeaeebc64
		summarizeBy: none
		sourceColumn: properties.extendedProperties.subId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.scope'
		dataType: string
		lineageTag: 751b7d3d-89b3-4cd0-a5a0-3c2918ebdf67
		summarizeBy: none
		sourceColumn: properties.extendedProperties.scope

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.term'
		dataType: string
		lineageTag: 0e598f50-8470-4fac-966b-89fa6d2e4dfe
		summarizeBy: none
		sourceColumn: properties.extendedProperties.term

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.sku'
		dataType: string
		lineageTag: 4dacbd78-0892-44aa-8059-749bac8d4bb2
		summarizeBy: none
		sourceColumn: properties.extendedProperties.sku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.commitment'
		dataType: string
		lineageTag: dd3d13c4-a00d-4174-940b-45e03d6ac528
		summarizeBy: none
		sourceColumn: properties.extendedProperties.commitment

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.currentSku'
		dataType: string
		lineageTag: c20235dd-7474-4d80-96d2-8fc3bbab123a
		summarizeBy: none
		sourceColumn: properties.extendedProperties.currentSku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.targetSku'
		dataType: string
		lineageTag: 9615ad44-2e5e-4548-9559-4d6376f71f20
		summarizeBy: none
		sourceColumn: properties.extendedProperties.targetSku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.recommendationMessage'
		dataType: string
		lineageTag: b642f2df-ee19-4d40-a8e2-cd29e539428b
		summarizeBy: none
		sourceColumn: properties.extendedProperties.recommendationMessage

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.solution'
		dataType: string
		lineageTag: 78310f71-4093-4c50-b666-5226581f13f3
		summarizeBy: none
		sourceColumn: properties.shortDescription.solution

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.problem'
		dataType: string
		lineageTag: 8c863cc1-31e6-4ba9-a79c-180e1ee9c443
		summarizeBy: none
		sourceColumn: properties.shortDescription.problem

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.resourceId'
		dataType: string
		lineageTag: 9331d2f4-372c-4fee-b28f-9077c6d7600c
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.resourceId

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.singular'
		dataType: string
		lineageTag: b4155074-7793-4316-814a-652b57aa03bd
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.singular

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.plural'
		dataType: string
		lineageTag: 51340f3a-416f-42dc-a015-1da05cbc2aab
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.plural

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.action'
		dataType: string
		lineageTag: 6ec793d3-a05e-403e-a003-32823be08f5e
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.action

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.source'
		dataType: string
		lineageTag: 2e638b65-4dc0-4bca-a86a-8b9ee573bbfa
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.source

		annotation SummarizationSetBy = Automatic

	column 'properties.suppressionIds'
		dataType: string
		lineageTag: d9aa656b-fc72-49be-b49f-e6454d9a9ae0
		summarizeBy: none
		sourceColumn: properties.suppressionIds

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedField'
		dataType: string
		lineageTag: d21450c3-b988-4164-9674-c2f3bf3ec359
		summarizeBy: none
		sourceColumn: properties.impactedField

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedValue'
		dataType: string
		lineageTag: 128a2373-5b05-4072-89f0-432b3649a659
		summarizeBy: none
		sourceColumn: properties.impactedValue

		annotation SummarizationSetBy = Automatic

	column 'properties.lastUpdated'
		dataType: dateTime
		formatString: General Date
		lineageTag: e72991e0-a360-4d16-a305-9fa93f499d1b
		summarizeBy: none
		sourceColumn: properties.lastUpdated

		variation Variation
			isDefault
			relationship: 76b49aa3-c4d8-47fb-956e-cc99798c7ab7
			defaultHierarchy: LocalDateTable_53b6ab5d-506b-417f-ae3d-823bdd4fb83c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'properties.category'
		dataType: string
		lineageTag: e749a0a5-6359-4855-b352-e8a575b00ba8
		summarizeBy: none
		sourceColumn: properties.category

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata'
		dataType: string
		lineageTag: 8b5b0b47-acaa-4d74-92c5-0c71fcefd37a
		summarizeBy: none
		sourceColumn: properties.metadata

		annotation SummarizationSetBy = Automatic

	column 'properties.impact'
		dataType: string
		lineageTag: b00d9661-6df3-4bdb-b14b-abe21b4d9f14
		summarizeBy: none
		sourceColumn: properties.impact
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: d97dde1c-3c7b-4ccb-b070-056b6a1bb81b
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: cb3859ae-05c5-417b-b706-f70ea3f9037e
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: f56c303d-573b-4bc1-9a5a-4c3cb5b3d736
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 6b0a44d8-c4b0-4464-a2ca-c76738b19405
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 84828547-b16d-448a-9168-28d1466e556b
		summarizeBy: none
		sourceColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	partition Advisor = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("advisorresources | where type == ""microsoft.advisor/recommendations"" | where properties['category'] == 'Cost'", "Tenant", null, null, [resultTruncated = true]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"recommendationTypeId", "extendedProperties", "shortDescription", "resourceMetadata", "suppressionIds", "impactedField", "impactedValue", "lastUpdated", "category", "metadata", "impact"}, {"properties.recommendationTypeId", "properties.extendedProperties", "properties.shortDescription", "properties.resourceMetadata", "properties.suppressionIds", "properties.impactedField", "properties.impactedValue", "properties.lastUpdated", "properties.category", "properties.metadata", "properties.impact"}),
				  #"Expanded properties.extendedProperties" = Table.ExpandRecordColumn(#"Expanded properties", "properties.extendedProperties", {"ObservationPeriodStartDate", "ObservationPeriodEndDate", "annualSavingsAmount", "HasRecommendation", "savingsCurrency", "IsInReplication", "Recommended_DTU", "Recommended_SKU", "ResourceGroup", "savingsAmount", "DatabaseSize", "DatabaseName", "ServerName", "Region", "lookbackPeriod", "subId", "scope", "term", "sku", "commitment", "currentSku", "targetSku", "recommendationMessage"}, {"properties.extendedProperties.ObservationPeriodStartDate", "properties.extendedProperties.ObservationPeriodEndDate", "properties.extendedProperties.annualSavingsAmount", "properties.extendedProperties.HasRecommendation", "properties.extendedProperties.savingsCurrency", "properties.extendedProperties.IsInReplication", "properties.extendedProperties.Recommended_DTU", "properties.extendedProperties.Recommended_SKU", "properties.extendedProperties.ResourceGroup", "properties.extendedProperties.savingsAmount", "properties.extendedProperties.DatabaseSize", "properties.extendedProperties.DatabaseName", "properties.extendedProperties.ServerName", "properties.extendedProperties.Region", "properties.extendedProperties.lookbackPeriod", "properties.extendedProperties.subId", "properties.extendedProperties.scope", "properties.extendedProperties.term", "properties.extendedProperties.sku", "properties.extendedProperties.commitment", "properties.extendedProperties.currentSku", "properties.extendedProperties.targetSku", "properties.extendedProperties.recommendationMessage"}),
				  #"Changed column type 2" = Table.TransformColumnTypes(#"Expanded properties.extendedProperties", {{"properties.extendedProperties.annualSavingsAmount", type number}}, "en-US"),
				  #"Replaced errors" = Table.ReplaceErrorValues(#"Changed column type 2", {{"properties.extendedProperties.annualSavingsAmount", null}}),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Replaced errors", {{"properties.extendedProperties.savingsAmount", type number}}, "en-US"),
				  #"Replaced errors 1" = Table.ReplaceErrorValues(#"Changed column type 1", {{"properties.extendedProperties.savingsAmount", null}}),
				  #"Expanded properties.shortDescription" = Table.ExpandRecordColumn(#"Replaced errors 1", "properties.shortDescription", {"solution", "problem"}, {"properties.shortDescription.solution", "properties.shortDescription.problem"}),
				  #"Expanded properties.resourceMetadata" = Table.ExpandRecordColumn(#"Expanded properties.shortDescription", "properties.resourceMetadata", {"resourceId", "singular", "plural", "action", "source"}, {"properties.resourceMetadata.resourceId", "properties.resourceMetadata.singular", "properties.resourceMetadata.plural", "properties.resourceMetadata.action", "properties.resourceMetadata.source"}),
				  #"Replaced value" = Table.ReplaceValue(#"Expanded properties.resourceMetadata", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.savingsAmount"}),
				  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.annualSavingsAmount"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Replaced value 1", {{"properties.extendedProperties.ObservationPeriodStartDate", type datetimezone}, {"properties.extendedProperties.ObservationPeriodEndDate", type datetimezone}, {"properties.lastUpdated", type datetimezone}}),
				  #"Inserted conditional column" = Table.AddColumn(#"Changed column type", "SortOrder", each if [properties.impact] = "High" then 1 else if [properties.impact] = "Medium" then 2 else if [properties.impact] = "Low" then 3 else ""),
				  #"Changed column type 3" = Table.TransformColumnTypes(#"Inserted conditional column", {{"SortOrder", Int64.Type}})
				in
				  #"Changed column type 3"

