table 'Compliance calculation'
	lineageTag: 7e7fc609-aead-44a4-9f96-54c8ea4bbd8f

	measure Compliance = [Compliant]/([Compliant]+[NonCompliant])
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: f847d570-6582-428a-885a-00639e5ffa4d

	measure Compliant = [totalResource]-[NonCompliant]-[Error]
		lineageTag: 77b760fb-9db5-42fc-b67f-158dd70e53a5

	measure Error = CALCULATE(COUNTROWS(PolicyStates),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="Error")
		formatString: 0
		lineageTag: 4453f273-dbab-4db2-b146-7d35c259d27f

	measure NonCompliant = CALCULATE(DISTINCTCOUNT(PolicyStates[properties.resourceId]),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="NonCompliant")
		formatString: 0
		lineageTag: 2fb77442-b45e-4e34-9de5-fac821f19fa8

	measure totalResource = DISTINCTCOUNT(PolicyStates[properties.resourceId])
		formatString: 0
		lineageTag: ba585a54-12b8-4aa4-9368-f8d5d1515dc2

	measure Unknown = CALCULATE(COUNTROWS(PolicyStates),RELATEDTABLE('Compliance calculation'),PolicyStates[properties.complianceState] ="Unknown")
		formatString: 0
		lineageTag: 1b85d268-c56a-4c60-ae3a-68d89e660197

	column id
		dataType: string
		lineageTag: 255eae7e-e876-46c6-85c9-01c92bfacd5e
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: PolicyAssignments[id]

		annotation SummarizationSetBy = Automatic

	partition 'Compliance calculation' = calculated
		mode: import
		source = SUMMARIZE(PolicyAssignments,PolicyAssignments[id])

	annotation PBI_Id = 3625d4cfb0034cecb87fbea9fd2c9533

