table Disks
	lineageTag: 5141f3dd-66df-476c-bc17-0e0640251ab4

	column id
		dataType: string
		lineageTag: e5353140-5ac7-4e79-a455-9f3fc4e2cade
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e30fc621-3f8d-4268-8e17-835b2e25d7dd
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 4e0c9742-90db-4adf-9e1b-496020a19ddc
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 5bc13146-6f2e-4a91-a681-d8828067b5c1
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 398dab7f-5c5d-4fa1-8429-47926f32f44d
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: ac68e917-66b6-4a60-850c-1fcbbec10e87
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: e6da767f-f97b-42fb-9355-f1fe29f4a192
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: ff06b232-3c94-4c17-8c7a-d75d1cd61428
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: ce58fefe-21fa-4e80-9bec-8b3af6e9202d
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column 'sku.name'
		dataType: string
		lineageTag: 330346b7-7a03-4e32-80fc-11169c1fc06e
		summarizeBy: none
		sourceColumn: sku.name

		annotation SummarizationSetBy = Automatic

	column 'sku.tier'
		dataType: string
		lineageTag: 53d5c410-1335-43e3-b09c-465b6678efb5
		summarizeBy: none
		sourceColumn: sku.tier

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 11817f6d-c661-4d30-b597-270a9d9eb4de
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: 0535ba1a-4388-491c-8a49-c73c2d0c8206
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.publicNetworkAccess'
		dataType: string
		lineageTag: 961653b2-bde8-42d2-8f8a-e1c11c7272c0
		summarizeBy: none
		sourceColumn: properties.publicNetworkAccess

		annotation SummarizationSetBy = Automatic

	column 'properties.encryption'
		dataType: string
		lineageTag: bcf7f78b-4825-4b0e-927d-abe0c98f6f25
		summarizeBy: none
		sourceColumn: properties.encryption

		annotation SummarizationSetBy = Automatic

	column 'properties.networkAccessPolicy'
		dataType: string
		lineageTag: a350e127-c039-4cbe-af08-3aa6ca2c676a
		summarizeBy: none
		sourceColumn: properties.networkAccessPolicy

		annotation SummarizationSetBy = Automatic

	column 'properties.timeCreated'
		dataType: string
		lineageTag: 82db3e4b-88ec-482b-a463-a671cf6bddda
		summarizeBy: none
		sourceColumn: properties.timeCreated

		annotation SummarizationSetBy = Automatic

	column 'properties.diskSizeGB'
		dataType: double
		lineageTag: 9e5b1f93-0559-44e0-bab3-027878ef5c58
		summarizeBy: sum
		sourceColumn: properties.diskSizeGB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.hyperVGeneration'
		dataType: string
		lineageTag: c0395747-f3f9-4048-8563-7b9b177f8ea2
		summarizeBy: none
		sourceColumn: properties.hyperVGeneration

		annotation SummarizationSetBy = Automatic

	column 'properties.diskSizeBytes'
		dataType: double
		lineageTag: 710492c2-2f29-4b02-b0e6-9094cf24ee40
		summarizeBy: sum
		sourceColumn: properties.diskSizeBytes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.creationData.createOption'
		dataType: string
		lineageTag: c789d1c8-2d8f-4b6c-a638-45546125ebc0
		summarizeBy: none
		sourceColumn: properties.creationData.createOption

		annotation SummarizationSetBy = Automatic

	column 'properties.creationData.imageReference.id'
		dataType: string
		lineageTag: 8591a823-3bad-4080-9ee6-087963c00d33
		summarizeBy: none
		sourceColumn: properties.creationData.imageReference.id

		annotation SummarizationSetBy = Automatic

	column 'properties.osType'
		dataType: string
		lineageTag: 02998f9a-9d3c-4cd6-b60c-59445df7149a
		summarizeBy: none
		sourceColumn: properties.osType

		annotation SummarizationSetBy = Automatic

	column 'properties.LastOwnershipUpdateTime'
		dataType: string
		lineageTag: 44b984aa-39b3-43d4-abfc-3322814360b2
		summarizeBy: none
		sourceColumn: properties.LastOwnershipUpdateTime

		annotation SummarizationSetBy = Automatic

	column 'properties.diskState'
		dataType: string
		lineageTag: 35ef700d-b1d3-4703-a1e0-b3687847e2aa
		summarizeBy: none
		sourceColumn: properties.diskState

		annotation SummarizationSetBy = Automatic

	column 'properties.uniqueId'
		dataType: string
		lineageTag: 5e118f68-dc11-49b9-8616-d09a9b6131a7
		summarizeBy: none
		sourceColumn: properties.uniqueId

		annotation SummarizationSetBy = Automatic

	column 'properties.diskMBpsReadWrite'
		dataType: double
		lineageTag: 96dbb3e0-cc81-4463-a7ac-1f0801113c51
		summarizeBy: sum
		sourceColumn: properties.diskMBpsReadWrite

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.diskIOPSReadWrite'
		dataType: double
		lineageTag: 46f66a80-4a90-4798-b94e-e6cccead2c94
		summarizeBy: sum
		sourceColumn: properties.diskIOPSReadWrite

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.tier'
		dataType: string
		lineageTag: 3442e695-3865-4568-a1fc-d23e130ef2ad
		summarizeBy: none
		sourceColumn: properties.tier

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: fbf2ba73-fc33-4a9a-9695-20c777460ee3
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 4a0d2d4c-01f4-408a-8937-0c3ad2014e17
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 09346ca1-64a1-4041-b4ff-025ce2d56768
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: bf703b44-5b53-48b2-b037-2e2f97ff6c84
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column diskType
		dataType: string
		lineageTag: b7680847-bf6c-4308-932c-33058269be8f
		summarizeBy: none
		sourceColumn: diskType

		annotation SummarizationSetBy = Automatic

	column parentVM
		dataType: string
		lineageTag: 68c0f895-d7c5-4815-a499-8a49a7512c4e
		summarizeBy: none
		sourceColumn: parentVM

		annotation SummarizationSetBy = Automatic

	partition Disks = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources | where type =~ 'microsoft.compute/disks'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "publicNetworkAccess", "encryption", "networkAccessPolicy", "timeCreated", "diskSizeGB", "hyperVGeneration", "diskSizeBytes", "creationData", "osType", "LastOwnershipUpdateTime", "diskState", "uniqueId", "diskMBpsReadWrite", "diskIOPSReadWrite", "tier"}, {"properties.provisioningState", "properties.publicNetworkAccess", "properties.encryption", "properties.networkAccessPolicy", "properties.timeCreated", "properties.diskSizeGB", "properties.hyperVGeneration", "properties.diskSizeBytes", "properties.creationData", "properties.osType", "properties.LastOwnershipUpdateTime", "properties.diskState", "properties.uniqueId", "properties.diskMBpsReadWrite", "properties.diskIOPSReadWrite", "properties.tier"}),
				  #"Expanded sku" = Table.ExpandRecordColumn(#"Expanded properties", "sku", {"name", "tier"}, {"sku.name", "sku.tier"}),
				  #"Expanded properties.creationData" = Table.ExpandRecordColumn(#"Expanded sku", "properties.creationData", {"createOption", "imageReference"}, {"properties.creationData.createOption", "properties.creationData.imageReference"}),
				  #"Expanded properties.creationData.imageReference" = Table.ExpandRecordColumn(#"Expanded properties.creationData", "properties.creationData.imageReference", {"id"}, {"properties.creationData.imageReference.id"}),
				  #"Expanded zones" = Table.ExpandListColumn(#"Expanded properties.creationData.imageReference", "zones"),
				  #"Inserted conditional column" = Table.AddColumn(#"Expanded zones", "diskType", each if [properties.osType] = null then "Data Disk" else "OS Disk"),
				  #"Changed column type" = Table.TransformColumnTypes(#"Inserted conditional column", {{"properties.diskSizeGB", type number}, {"properties.diskSizeBytes", type number}, {"properties.diskMBpsReadWrite", type number}, {"properties.diskIOPSReadWrite", type number}}),
				  #"Duplicated column" = Table.DuplicateColumn(#"Changed column type", "managedBy", "managedBy - Copy"),
				  #"Extracted text after delimiter" = Table.TransformColumns(#"Duplicated column", {{"managedBy - Copy", each Text.AfterDelimiter(Text.From(_), "/", {0, RelativePosition.FromEnd}), type text}}),
				  #"Renamed columns" = Table.RenameColumns(#"Extracted text after delimiter", {{"managedBy - Copy", "parentVM"}})
				in
				  #"Renamed columns"

