table InstanceSizeFlexibility
	lineageTag: 58d5e215-906e-4fa8-8dc4-6ebf58192966

	column InstanceSizeFlexibilityGroup
		dataType: string
		lineageTag: 97ea58b5-02f1-4321-aec2-1f89a0332b2a
		summarizeBy: none
		sourceColumn: InstanceSizeFlexibilityGroup

		annotation SummarizationSetBy = Automatic

	column ResourceLocation
		dataType: string
		lineageTag: a53b7a74-868c-4abb-afa0-84d0c6627bed
		summarizeBy: none
		sourceColumn: ResourceLocation

		annotation SummarizationSetBy = Automatic

	column ArmSkuName
		dataType: string
		lineageTag: 0e96b6de-31e1-4834-91df-dcdbf5fcb675
		summarizeBy: none
		sourceColumn: ArmSkuName

		annotation SummarizationSetBy = Automatic

	column Ratio
		dataType: int64
		formatString: 0
		lineageTag: 51920329-d647-455d-bb18-008cf02a1695
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

	column ComboMeter
		dataType: string
		lineageTag: f613a1ed-303e-47bf-97c7-9f41c36f566c
		summarizeBy: none
		sourceColumn: ComboMeter

		annotation SummarizationSetBy = Automatic

	column HardwareMeter
		dataType: string
		lineageTag: e645e543-3a04-4b61-aefb-8990ac6f0cef
		summarizeBy: none
		sourceColumn: HardwareMeter

		annotation SummarizationSetBy = Automatic

	column SoftwareMeter
		dataType: string
		lineageTag: 3606f443-48f6-4ad2-b804-e736d8c7db62
		summarizeBy: none
		sourceColumn: SoftwareMeter

		annotation SummarizationSetBy = Automatic

	column CompositeKey
		dataType: string
		lineageTag: 408eb26e-8667-43a7-80b3-fdbc7038a0f9
		summarizeBy: none
		sourceColumn: CompositeKey

		annotation SummarizationSetBy = Automatic

	column NormalizedSKU
		dataType: string
		lineageTag: 37812838-014e-4da1-a9fe-5524b6776f98
		summarizeBy: none
		sourceColumn: NormalizedSKU

		annotation SummarizationSetBy = Automatic

	partition InstanceSizeFlexibility = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				    Source = Csv.Document(AzureStorage.BlobContents("https://ccmstorageprod.blob.core.windows.net/costmanagementconnector-data/AutofitComboMeterData.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstanceSizeFlexibilityGroup", type text}, {"ResourceLocation", type text}, {"ArmSkuName", type text}, {"Ratio", Int64.Type}, {"ComboMeter", type text}, {"HardwareMeter", type text}, {"SoftwareMeter", type text}, {"CompositeKey", type text}, {"NormalizedSKU", type text}})
				in
				    #"Changed Type"

