table 'Management Groups'
	lineageTag: aa51f542-78a4-4e06-9892-c3a2b02a26ff

	column id
		dataType: string
		lineageTag: 4c95fe5f-548a-4155-b2b4-700510985bad
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 7ee2e5aa-7760-4199-998d-c35365b562f5
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 96090d28-1fe7-4d96-9b73-019453e514b6
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: ee505f2c-3388-48a0-bd1d-36c40fed93ae
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 9e586fa9-8d72-49ea-8d25-748c7947c5b6
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 4cfdb599-7c52-4125-b778-9df3406d46a1
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 81449745-f2a8-49d6-b181-824634b6eccf
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 9143e8ae-5217-4a33-a967-59b5fa9a5492
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 9a912547-3296-460a-b43a-f7262e4b630c
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: ea3bbd5f-e46f-4421-a320-b5615042fd6c
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: b2f77e0e-b4e6-440c-8c78-66019fc0fe2c
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: b5cf1548-4657-4fd1-a055-10f6f4e38758
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column 'managementGroupAncestorsChain.displayName'
		dataType: string
		lineageTag: 896ed7cd-2b37-46f6-a1ab-47ba99034a9c
		summarizeBy: none
		sourceColumn: managementGroupAncestorsChain.displayName

		annotation SummarizationSetBy = Automatic

	column 'managementGroupAncestorsChain.name'
		dataType: string
		lineageTag: f84a6f13-bbf4-4cdc-9e69-20ca819702a3
		summarizeBy: none
		sourceColumn: managementGroupAncestorsChain.name

		annotation SummarizationSetBy = Automatic

	column updatedTime
		dataType: string
		lineageTag: 5dbefbbf-b9c3-4379-aa91-4fa7e58ab0ac
		summarizeBy: none
		sourceColumn: updatedTime

		annotation SummarizationSetBy = Automatic

	column updatedBy
		dataType: string
		lineageTag: 290f1e92-e37a-40ab-8004-7a0abfa41065
		summarizeBy: none
		sourceColumn: updatedBy

		annotation SummarizationSetBy = Automatic

	column version
		dataType: string
		lineageTag: 9a510efc-881e-4656-8fe0-9f489bf75fd7
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column 'parent.displayName'
		dataType: string
		lineageTag: 77853fb4-51a5-4bb3-bf71-feb894e43705
		summarizeBy: none
		sourceColumn: parent.displayName

		annotation SummarizationSetBy = Automatic

	column 'parent.name'
		dataType: string
		lineageTag: beba2570-01d9-46a2-ba0d-4f39efb7cce2
		summarizeBy: none
		sourceColumn: parent.name

		annotation SummarizationSetBy = Automatic

	column 'parent.id'
		dataType: string
		lineageTag: 6794d9f0-ceb7-408b-bd94-582462962dc6
		summarizeBy: none
		sourceColumn: parent.id

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 00e33054-7d79-42b6-a888-3f8c1da223e5
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 38e9657f-2bed-4641-863b-5f50e1f643a1
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: a92724c9-d35b-429c-b8ef-f7f32058441f
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: dd4a4b8a-1567-4d00-b38c-76ddd71935de
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition 'Management Groups' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("resourcecontainers | where type == 'microsoft.management/managementgroups'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"displayName", "details"}, {"displayName", "details"}),
				  #"Expanded details" = Table.ExpandRecordColumn(#"Expanded properties", "details", {"managementGroupAncestorsChain", "updatedTime", "updatedBy", "version", "parent"}, {"managementGroupAncestorsChain", "updatedTime", "updatedBy", "version", "parent"}),
				  #"Expanded parent" = Table.ExpandRecordColumn(#"Expanded details", "parent", {"displayName", "name", "id"}, {"parent.displayName", "parent.name", "parent.id"}),
				  #"Expanded managementGroupAncestorsChain" = Table.ExpandListColumn(#"Expanded parent", "managementGroupAncestorsChain"),
				  #"Expanded managementGroupAncestorsChain 1" = Table.ExpandRecordColumn(#"Expanded managementGroupAncestorsChain", "managementGroupAncestorsChain", {"displayName", "name"}, {"managementGroupAncestorsChain.displayName", "managementGroupAncestorsChain.name"})
				in
				  #"Expanded managementGroupAncestorsChain 1"

