table 'Network Security Groups'
	lineageTag: ffe8364e-6dbb-4445-becd-210da363cb25

	column id
		dataType: string
		lineageTag: 2892f48c-e3c5-4cef-a76a-3bf7522f10e7
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 3d13273c-84b6-4188-a790-d7ab41b6996e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: af90f30a-4d43-422b-b2df-2b1286c5b662
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: e9dad901-4135-4bfd-8dca-f3588e162069
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 22d4fda6-b9ad-414c-8aad-6cd06b17ba72
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: a9ac1db5-41cf-46e2-9c5f-08e1caa42f29
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 8e5062d0-b216-4348-b166-f51d6a48ff56
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 56e1ae13-5a61-4a27-be50-59dec05a9303
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: d8658b9b-26a9-454d-9437-b00258b2b113
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 3ff6d942-a291-4008-8cec-0ee19fc0a60e
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 6d06d24f-c5e0-4964-a3cc-e8379af238a4
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: 2638ac07-ae2c-4e76-b6a6-7add6831d6bd
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.networkInterfaces.id'
		dataType: string
		lineageTag: 27eeda1b-63c9-40f7-b0d9-21085c31f147
		summarizeBy: none
		sourceColumn: properties.networkInterfaces.id

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceGuid'
		dataType: string
		lineageTag: 94502235-bffd-4ca8-a38f-31d75545a7da
		summarizeBy: none
		sourceColumn: properties.resourceGuid

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.type'
		dataType: string
		lineageTag: e9dddd15-cc27-4cd9-ba0f-9be1b71c61e6
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.type

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.provisioningState'
		dataType: string
		lineageTag: 0fe77811-e8d7-4ba0-b38a-6c28b665a9c2
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationAddressPrefixes'
		dataType: string
		lineageTag: 74d01a32-d8b2-4344-a620-5a36cf1ca23a
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationAddressPrefix'
		dataType: string
		lineageTag: 6394f35a-9599-472c-8d1c-437123692ac8
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationPortRanges'
		dataType: string
		lineageTag: c3c12062-5743-436c-b95c-af50ddb72718
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationPortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourceAddressPrefixes'
		dataType: string
		lineageTag: 2533f540-51f1-4eb3-b606-f2e772c48d33
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourceAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourceAddressPrefix'
		dataType: string
		lineageTag: 5e7e028a-0700-4737-a952-6de403f54644
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourceAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.destinationPortRange'
		dataType: string
		lineageTag: 7f428468-e45b-416b-8575-c68934927ff8
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.destinationPortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourcePortRanges'
		dataType: string
		lineageTag: 7430266b-1ff5-4e2e-9ca2-0aba0e3a19ab
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourcePortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.sourcePortRange'
		dataType: string
		lineageTag: ad038ac2-f96a-4b37-924c-4b0a4c3d7044
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.sourcePortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.description'
		dataType: string
		lineageTag: 42566175-fe59-4401-b086-a8894cef5573
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.description

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.protocol'
		dataType: string
		lineageTag: c377c75a-89a5-48f2-9466-a4b4b5eee2b7
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.protocol

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.direction'
		dataType: string
		lineageTag: d9189e90-b26c-4e0f-9e7f-ab24e97b095b
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.direction

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.priority'
		dataType: string
		lineageTag: 2886281b-9513-43ce-b2f8-8d2b83dd5d95
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.priority

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.properties.access'
		dataType: string
		lineageTag: f4fae996-68cb-466f-adf8-a1316989f1cc
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.properties.access

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.name'
		dataType: string
		lineageTag: fb104d71-93bc-480e-b103-302ca32f6cde
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.name

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.id'
		dataType: string
		lineageTag: cb703ae1-10c6-4da7-9c71-e6173aced9f9
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.id

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecurityRules.etag'
		dataType: string
		lineageTag: c593a1c3-b40c-4ebf-bc88-9b0770617c1d
		summarizeBy: none
		sourceColumn: properties.defaultSecurityRules.etag

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.type'
		dataType: string
		lineageTag: 5e53f2f0-a1fc-4401-bccd-ffc20324a1fa
		summarizeBy: none
		sourceColumn: properties.securityRules.type

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.provisioningState'
		dataType: string
		lineageTag: ba4249d2-b6aa-4352-8bdb-4ddc20b89be2
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationAddressPrefixes'
		dataType: string
		lineageTag: 010a91c2-1ebc-48bf-aa50-f89610461552
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationAddressPrefix'
		dataType: string
		lineageTag: c97fe4b1-f257-4c6e-b743-b8f8dc4d7203
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationPortRanges'
		dataType: string
		lineageTag: 3d1cae05-aaeb-40c3-bf1e-5bf5859b6241
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationPortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourceAddressPrefixes'
		dataType: string
		lineageTag: 84bea4b5-40a6-4d43-a46a-944724335569
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourceAddressPrefixes

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourceAddressPrefix'
		dataType: string
		lineageTag: 01c71888-0504-44d0-b632-9f8b6653e7bb
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourceAddressPrefix

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.destinationPortRange'
		dataType: string
		lineageTag: 2f714571-e23e-4e1d-9c37-ce1b6ba56da5
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.destinationPortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourcePortRanges'
		dataType: string
		lineageTag: 7aef7450-5b98-49a3-bc0f-5e0f5dbdf250
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourcePortRanges

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.sourcePortRange'
		dataType: string
		lineageTag: 09a252f1-a40e-42b7-91ce-6bcc728cefdb
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.sourcePortRange

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.protocol'
		dataType: string
		lineageTag: 1ff13bed-598c-43cd-9b78-6618ce6bc624
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.protocol

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.direction'
		dataType: string
		lineageTag: d7956ed1-ba59-4851-8c97-bec6196f5a0e
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.direction

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.priority'
		dataType: string
		lineageTag: 3fe74790-0788-46c6-8063-cdc8a4b32170
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.priority

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.properties.access'
		dataType: string
		lineageTag: 995645db-f1d9-4e13-938a-1e052489001e
		summarizeBy: none
		sourceColumn: properties.securityRules.properties.access

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.name'
		dataType: string
		lineageTag: f89d78b6-68e0-4fa8-8a28-58b99a10197b
		summarizeBy: none
		sourceColumn: properties.securityRules.name

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.id'
		dataType: string
		lineageTag: 15559c8d-537c-471a-82e8-49fd99404c1d
		summarizeBy: none
		sourceColumn: properties.securityRules.id

		annotation SummarizationSetBy = Automatic

	column 'properties.securityRules.etag'
		dataType: string
		lineageTag: 4976fa7a-e7a1-4add-980f-e39eb2060210
		summarizeBy: none
		sourceColumn: properties.securityRules.etag

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 208beb0a-2c4c-41fd-843c-dcf839b47c51
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: be8d5528-8a94-4a6f-95ec-d709a62c9407
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: b8cf52a6-e295-405b-b7c5-d244ff4997f2
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 213cd670-dd74-4c92-9e01-07aca9f6ac05
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column isWarning = ```
			IF('Network Security Groups'[properties.securityRules.properties.access]="Allow",
			        SWITCH(
			            'Network Security Groups'[properties.securityRules.properties.destinationPortRange],
			            "80", "True",
			            "22", "True",
			            "3389", "True",
			            "False"
			    ), "False" 
			)
			```
		dataType: string
		lineageTag: f1652cc1-b28f-4f76-9c88-a3d714feed08
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Network Security Groups' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources | where type =~ 'microsoft.network/networksecuritygroups'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "networkInterfaces", "resourceGuid", "defaultSecurityRules", "securityRules"}, {"properties.provisioningState", "properties.networkInterfaces", "properties.resourceGuid", "properties.defaultSecurityRules", "properties.securityRules"}),
				  #"Expanded properties.networkInterfaces" = Table.ExpandListColumn(#"Expanded properties", "properties.networkInterfaces"),
				  #"Expanded properties.networkInterfaces 1" = Table.ExpandRecordColumn(#"Expanded properties.networkInterfaces", "properties.networkInterfaces", {"id"}, {"properties.networkInterfaces.id"}),
				  #"Expanded properties.defaultSecurityRules" = Table.ExpandListColumn(#"Expanded properties.networkInterfaces 1", "properties.defaultSecurityRules"),
				  #"Expanded properties.defaultSecurityRules 1" = Table.ExpandRecordColumn(#"Expanded properties.defaultSecurityRules", "properties.defaultSecurityRules", {"type", "properties", "name", "id", "etag"}, {"properties.defaultSecurityRules.type", "properties.defaultSecurityRules.properties", "properties.defaultSecurityRules.name", "properties.defaultSecurityRules.id", "properties.defaultSecurityRules.etag"}),
				  #"Expanded properties.defaultSecurityRules.properties" = Table.ExpandRecordColumn(#"Expanded properties.defaultSecurityRules 1", "properties.defaultSecurityRules.properties", {"provisioningState", "destinationAddressPrefixes", "destinationAddressPrefix", "destinationPortRanges", "sourceAddressPrefixes", "sourceAddressPrefix", "destinationPortRange", "sourcePortRanges", "sourcePortRange", "description", "protocol", "direction", "priority", "access"}, {"properties.defaultSecurityRules.properties.provisioningState", "properties.defaultSecurityRules.properties.destinationAddressPrefixes", "properties.defaultSecurityRules.properties.destinationAddressPrefix", "properties.defaultSecurityRules.properties.destinationPortRanges", "properties.defaultSecurityRules.properties.sourceAddressPrefixes", "properties.defaultSecurityRules.properties.sourceAddressPrefix", "properties.defaultSecurityRules.properties.destinationPortRange", "properties.defaultSecurityRules.properties.sourcePortRanges", "properties.defaultSecurityRules.properties.sourcePortRange", "properties.defaultSecurityRules.properties.description", "properties.defaultSecurityRules.properties.protocol", "properties.defaultSecurityRules.properties.direction", "properties.defaultSecurityRules.properties.priority", "properties.defaultSecurityRules.properties.access"}),
				  #"Expanded properties.defaultSecurityRules.properties.destinationAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties", "properties.defaultSecurityRules.properties.destinationAddressPrefixes"),
				  #"Expanded properties.defaultSecurityRules.properties.destinationPortRanges" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.destinationAddressPrefixes", "properties.defaultSecurityRules.properties.destinationPortRanges"),
				  #"Expanded properties.defaultSecurityRules.properties.sourceAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.destinationPortRanges", "properties.defaultSecurityRules.properties.sourceAddressPrefixes"),
				  #"Expanded properties.defaultSecurityRules.properties.sourcePortRanges" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.sourceAddressPrefixes", "properties.defaultSecurityRules.properties.sourcePortRanges"),
				  #"Expanded properties.securityRules" = Table.ExpandListColumn(#"Expanded properties.defaultSecurityRules.properties.sourcePortRanges", "properties.securityRules"),
				  #"Expanded properties.securityRules 1" = Table.ExpandRecordColumn(#"Expanded properties.securityRules", "properties.securityRules", {"type", "properties", "name", "id", "etag"}, {"properties.securityRules.type", "properties.securityRules.properties", "properties.securityRules.name", "properties.securityRules.id", "properties.securityRules.etag"}),
				  #"Expanded properties.securityRules.properties" = Table.ExpandRecordColumn(#"Expanded properties.securityRules 1", "properties.securityRules.properties", {"provisioningState", "destinationAddressPrefixes", "destinationAddressPrefix", "destinationPortRanges", "sourceAddressPrefixes", "sourceAddressPrefix", "destinationPortRange", "sourcePortRanges", "sourcePortRange", "protocol", "direction", "priority", "access"}, {"properties.securityRules.properties.provisioningState", "properties.securityRules.properties.destinationAddressPrefixes", "properties.securityRules.properties.destinationAddressPrefix", "properties.securityRules.properties.destinationPortRanges", "properties.securityRules.properties.sourceAddressPrefixes", "properties.securityRules.properties.sourceAddressPrefix", "properties.securityRules.properties.destinationPortRange", "properties.securityRules.properties.sourcePortRanges", "properties.securityRules.properties.sourcePortRange", "properties.securityRules.properties.protocol", "properties.securityRules.properties.direction", "properties.securityRules.properties.priority", "properties.securityRules.properties.access"}),
				  #"Expanded properties.securityRules.properties.destinationAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties", "properties.securityRules.properties.destinationAddressPrefixes"),
				  #"Expanded properties.securityRules.properties.destinationPortRanges" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.destinationAddressPrefixes", "properties.securityRules.properties.destinationPortRanges"),
				  #"Expanded properties.securityRules.properties.sourceAddressPrefixes" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.destinationPortRanges", "properties.securityRules.properties.sourceAddressPrefixes"),
				  #"Expanded properties.securityRules.properties.sourcePortRanges" = Table.ExpandListColumn(#"Expanded properties.securityRules.properties.sourceAddressPrefixes", "properties.securityRules.properties.sourcePortRanges")
				in
				  #"Expanded properties.securityRules.properties.sourcePortRanges"

	annotation PBI_ResultType = Table

