table 'Network interfaces'
	lineageTag: a8e69dab-191f-4b88-9efa-7ec426c2175c

	column id
		dataType: string
		lineageTag: 379a4380-0538-4c5a-8947-552cce947e39
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 081469bc-fc87-49af-be82-a854aaa4c084
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: d5a17cfc-36c5-4b2e-be86-eb03a6146ddf
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 4d5807b1-061d-4652-b7ee-08528dcfcf30
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 1229ae37-b21e-4085-82c9-05838e31203b
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: e76c03de-e6b8-44c5-9306-3e5af91db2ff
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 7ae2fc45-1ee4-41a2-a0e8-164cd4083a58
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 97ef8a2c-31a3-4636-98e1-4e79cf419b2e
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: da416139-1345-4eac-b3c6-08fcb47240e2
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: ec799cbb-232c-4e30-bfd7-af9dbf248d64
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: ce708cb8-ee89-4e61-9cce-b64b0ab0240e
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: 542d41d2-e31a-4aa3-8284-cac502957399
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceGuid'
		dataType: string
		lineageTag: 260c5ce3-be73-44f3-8cb5-78329832693f
		summarizeBy: none
		sourceColumn: properties.resourceGuid

		annotation SummarizationSetBy = Automatic

	column 'properties.enableAcceleratedNetworking'
		dataType: string
		lineageTag: 3c73c2f0-a338-4a7c-b90b-dff007826bce
		summarizeBy: none
		sourceColumn: properties.enableAcceleratedNetworking

		annotation SummarizationSetBy = Automatic

	column 'properties.disableTcpStateTracking'
		dataType: string
		lineageTag: 6f5b0700-12b9-41b4-bec2-dddbd6514b84
		summarizeBy: none
		sourceColumn: properties.disableTcpStateTracking

		annotation SummarizationSetBy = Automatic

	column 'properties.vnetEncryptionSupported'
		dataType: string
		lineageTag: 07f06658-891b-417b-929b-dde13b69f9d6
		summarizeBy: none
		sourceColumn: properties.vnetEncryptionSupported

		annotation SummarizationSetBy = Automatic

	column 'properties.networkSecurityGroup.id'
		dataType: string
		lineageTag: 2c121f83-3255-431a-a2f8-d76f2edb5b80
		summarizeBy: none
		sourceColumn: properties.networkSecurityGroup.id

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.type'
		dataType: string
		lineageTag: 093edf87-73f9-4946-a2fd-c1a5a29ef70b
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.type

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.name'
		dataType: string
		lineageTag: 79c6635d-a038-4c72-8db3-0d93ea63436f
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.name

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.provisioningState'
		dataType: string
		lineageTag: 37c87b2d-875f-4e0f-b304-91586c8f20cf
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.privateIPAddressVersion'
		dataType: string
		lineageTag: 96947c09-64b6-4472-a6a5-d10fa34561c1
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.privateIPAddressVersion

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.privateIPAllocationMethod'
		dataType: string
		lineageTag: 965ee011-c9fa-4d36-8581-0d7cd89cc0f9
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.privateIPAllocationMethod

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.subnet'
		dataType: string
		lineageTag: 3ac7ebb0-6d89-4f0f-afa8-a5a86afc06fd
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.subnet

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.privateIPAddress'
		dataType: string
		lineageTag: 397c4af2-d804-409a-a4a4-eaa6204046f7
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.privateIPAddress

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.primary'
		dataType: string
		lineageTag: 0de43591-84f6-4a0c-8179-5bc6d4c124f4
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.primary

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.properties.publicIPAddress.id'
		dataType: string
		lineageTag: ae2da097-80c8-46dc-8c0a-7ccefdf38ed2
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.properties.publicIPAddress.id

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.id'
		dataType: string
		lineageTag: 34f180bc-8cfe-4e4a-9d69-8ffbb67224f8
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.id

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfigurations.etag'
		dataType: string
		lineageTag: 4cc0bd2e-e68a-46da-b31a-70c36573c26b
		summarizeBy: none
		sourceColumn: properties.ipConfigurations.etag

		annotation SummarizationSetBy = Automatic

	column 'properties.enableIPForwarding'
		dataType: string
		lineageTag: 351fe7c2-e474-4c10-b09c-0c008460b6f6
		summarizeBy: none
		sourceColumn: properties.enableIPForwarding

		annotation SummarizationSetBy = Automatic

	column 'properties.tapConfigurations'
		dataType: string
		lineageTag: 200780ed-d41e-4264-b456-6634a99a8eed
		summarizeBy: none
		sourceColumn: properties.tapConfigurations

		annotation SummarizationSetBy = Automatic

	column 'properties.hostedWorkloads'
		dataType: string
		lineageTag: d4b1c1da-aaf6-4876-a195-edd67985098d
		summarizeBy: none
		sourceColumn: properties.hostedWorkloads

		annotation SummarizationSetBy = Automatic

	column 'properties.allowPort25Out'
		dataType: string
		lineageTag: 06ff4669-3a12-4efc-8ff9-81cb0b8541f7
		summarizeBy: none
		sourceColumn: properties.allowPort25Out

		annotation SummarizationSetBy = Automatic

	column 'properties.auxiliaryMode'
		dataType: string
		lineageTag: ab0b4f5b-4a2f-4aed-a205-7c73706ffa4e
		summarizeBy: none
		sourceColumn: properties.auxiliaryMode

		annotation SummarizationSetBy = Automatic

	column 'properties.dnsSettings'
		dataType: string
		lineageTag: 3e474a36-d415-4fb9-b3ea-3851db4595d8
		summarizeBy: none
		sourceColumn: properties.dnsSettings

		annotation SummarizationSetBy = Automatic

	column 'properties.auxiliarySku'
		dataType: string
		lineageTag: aa61105a-78f8-42f1-a3e9-f835877bbbbe
		summarizeBy: none
		sourceColumn: properties.auxiliarySku

		annotation SummarizationSetBy = Automatic

	column 'properties.macAddress'
		dataType: string
		lineageTag: 9841b097-a582-413e-973e-0bd1a6c8c0a2
		summarizeBy: none
		sourceColumn: properties.macAddress

		annotation SummarizationSetBy = Automatic

	column 'properties.nicType'
		dataType: string
		lineageTag: 1d488c42-6d77-4053-9632-fb63085553b5
		summarizeBy: none
		sourceColumn: properties.nicType

		annotation SummarizationSetBy = Automatic

	column 'properties.primary'
		dataType: string
		lineageTag: e41e37aa-21f2-443a-96bd-90055a22b65b
		summarizeBy: none
		sourceColumn: properties.primary

		annotation SummarizationSetBy = Automatic

	column 'properties.virtualMachine.id'
		dataType: string
		lineageTag: 774e8c77-dcc8-4f0a-a9c1-8f98ea99a5ba
		summarizeBy: none
		sourceColumn: properties.virtualMachine.id

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: ff4c36e8-16b8-4a92-8f9a-a398268f8083
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 8cc758bc-0fc2-4d8f-80b4-1c5c360b2a53
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 874a8c0c-5a25-4f99-9407-c8d217727329
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: aefe2fb2-b5e5-4bff-8e4f-7810197d6485
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition 'Network interfaces' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources | where type =~ 'microsoft.network/networkinterfaces'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "resourceGuid", "enableAcceleratedNetworking", "disableTcpStateTracking", "vnetEncryptionSupported", "networkSecurityGroup", "ipConfigurations", "enableIPForwarding", "tapConfigurations", "hostedWorkloads", "allowPort25Out", "auxiliaryMode", "dnsSettings", "auxiliarySku", "macAddress", "nicType", "primary", "virtualMachine"}, {"properties.provisioningState", "properties.resourceGuid", "properties.enableAcceleratedNetworking", "properties.disableTcpStateTracking", "properties.vnetEncryptionSupported", "properties.networkSecurityGroup", "properties.ipConfigurations", "properties.enableIPForwarding", "properties.tapConfigurations", "properties.hostedWorkloads", "properties.allowPort25Out", "properties.auxiliaryMode", "properties.dnsSettings", "properties.auxiliarySku", "properties.macAddress", "properties.nicType", "properties.primary", "properties.virtualMachine"}),
				  #"Expanded properties.virtualMachine" = Table.ExpandRecordColumn(#"Expanded properties", "properties.virtualMachine", {"id"}, {"properties.virtualMachine.id"}),
				  #"Expanded properties.ipConfigurations" = Table.ExpandListColumn(#"Expanded properties.virtualMachine", "properties.ipConfigurations"),
				  #"Expanded properties.ipConfigurations 1" = Table.ExpandRecordColumn(#"Expanded properties.ipConfigurations", "properties.ipConfigurations", {"type", "name", "properties", "id", "etag"}, {"properties.ipConfigurations.type", "properties.ipConfigurations.name", "properties.ipConfigurations.properties", "properties.ipConfigurations.id", "properties.ipConfigurations.etag"}),
				  #"Expanded properties.ipConfigurations.properties" = Table.ExpandRecordColumn(#"Expanded properties.ipConfigurations 1", "properties.ipConfigurations.properties", {"provisioningState", "privateIPAddressVersion", "privateIPAllocationMethod", "subnet", "privateIPAddress", "primary", "publicIPAddress"}, {"properties.ipConfigurations.properties.provisioningState", "properties.ipConfigurations.properties.privateIPAddressVersion", "properties.ipConfigurations.properties.privateIPAllocationMethod", "properties.ipConfigurations.properties.subnet", "properties.ipConfigurations.properties.privateIPAddress", "properties.ipConfigurations.properties.primary", "properties.ipConfigurations.properties.publicIPAddress"}),
				  #"Expanded properties.ipConfigurations.properties.publicIPAddress" = Table.ExpandRecordColumn(#"Expanded properties.ipConfigurations.properties", "properties.ipConfigurations.properties.publicIPAddress", {"id"}, {"properties.ipConfigurations.properties.publicIPAddress.id"}),
				  #"Expanded properties.networkSecurityGroup" = Table.ExpandRecordColumn(#"Expanded properties.ipConfigurations.properties.publicIPAddress", "properties.networkSecurityGroup", {"id"}, {"properties.networkSecurityGroup.id"})
				in
				  #"Expanded properties.networkSecurityGroup"

	annotation PBI_NavigationStepName = Navigation

