table PolicyDefinitions
	lineageTag: 6e9b82e4-1829-4e35-9628-a4f650f2ed0c

	column id
		dataType: string
		lineageTag: 965ab6b8-7db2-4777-9709-1d067691b007
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: cc12a908-35af-40cd-9066-55fcf752b2cf
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: d09bf1b9-0fff-4208-affd-3889a121ac33
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 90e973f1-ad25-47a7-9333-5a9644ab5860
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: e581bc1d-7869-4d45-b89d-ff6b9a2fa1ba
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 5044f8b3-7f08-4f23-911b-92bdc1dd3bff
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 2c4bf999-2f0a-4f69-9b09-b91643dd068e
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: f7a4609c-67ed-405e-8f6a-a568c5c21932
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 3547b6bf-9037-4579-9c0b-1116af8217d2
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 4fb432bc-602e-4788-b604-a89a0d31f3a1
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: f345f747-a108-4c60-af03-87dadccb59f5
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.displayName'
		dataType: string
		lineageTag: 70ca39a0-5508-41e9-a83a-762f1356ed65
		summarizeBy: none
		sourceColumn: properties.displayName

		annotation SummarizationSetBy = Automatic

	column 'properties.policyType'
		dataType: string
		lineageTag: 615d44b4-e7b6-4a8d-9d37-13af786dd2b5
		summarizeBy: none
		sourceColumn: properties.policyType

		annotation SummarizationSetBy = Automatic

	column 'properties.description'
		dataType: string
		lineageTag: 66372477-4891-444e-9b18-1343c97bf20f
		summarizeBy: none
		sourceColumn: properties.description

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata'
		dataType: string
		lineageTag: 1bb9007c-778b-4da7-acff-3bb8268d45c2
		summarizeBy: none
		sourceColumn: properties.metadata

		annotation SummarizationSetBy = Automatic

	column 'properties.version'
		dataType: string
		lineageTag: c6219236-953d-41a8-b976-2c1d144b3e90
		summarizeBy: none
		sourceColumn: properties.version

		annotation SummarizationSetBy = Automatic

	column 'properties.parameters'
		dataType: string
		lineageTag: 0ae5edf1-9c34-4daa-b105-582ce4f67318
		summarizeBy: none
		sourceColumn: properties.parameters

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitions'
		dataType: string
		lineageTag: 9487d5b8-ff3f-47ba-8391-cae86d358cd2
		summarizeBy: none
		sourceColumn: properties.policyDefinitions

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionGroups'
		dataType: string
		lineageTag: c28c2437-fd88-4231-a5fc-8aaf7137c06f
		summarizeBy: none
		sourceColumn: properties.policyDefinitionGroups

		annotation SummarizationSetBy = Automatic

	column 'properties.versions'
		dataType: string
		lineageTag: 7071a1d6-eff7-4aca-9e65-b5f838ddbd50
		summarizeBy: none
		sourceColumn: properties.versions

		annotation SummarizationSetBy = Automatic

	column 'properties.oldVersions'
		dataType: string
		lineageTag: e550a202-1817-46b2-8358-990f5c56f2d9
		summarizeBy: none
		sourceColumn: properties.oldVersions

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 6ff43ba4-72c9-4d04-994c-5b957367755c
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: cffcd29d-5953-4979-b152-b42c6d52f912
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 2fb3d8fb-2e8e-46af-b695-38f42eb63388
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: e05f6921-9e03-4c78-8c33-9dc0d382ca0e
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition PolicyDefinitions = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("policyResources | where type =~'Microsoft.Authorization/PolicySetDefinitions' or type =~'Microsoft.Authorization/PolicyDefinitions'", "Tenant", null, null, [resultTruncated = false]),
				    #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"displayName", "policyType", "description", "metadata", "version", "parameters", "policyDefinitions", "policyDefinitionGroups", "versions", "oldVersions"}, {"properties.displayName", "properties.policyType", "properties.description", "properties.metadata", "properties.version", "properties.parameters", "properties.policyDefinitions", "properties.policyDefinitionGroups", "properties.versions", "properties.oldVersions"})
				in
				  #"Expanded properties"

	annotation PBI_ResultType = Table

