table PolicyAssignments
	lineageTag: b53417b1-ef04-48e6-b513-ec2eca942ec4

	column id
		dataType: string
		lineageTag: be39877a-556f-49f8-bf2c-61b381e20654
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: d86320ed-b29e-4210-a287-7a79eb0ed991
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: cbb7051b-1b87-4a4e-89f8-b247844e18aa
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 4b8dbcc3-4012-48ba-bf8a-57d36b15acc3
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: c544bb4e-f04f-4e72-b0a5-5fe23f051c57
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 5074be75-e970-42f7-9842-da7651a0ea61
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 19122c97-ff52-4901-a872-9c48a0a1b603
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: c8b0201a-debd-4929-bbe9-0207a3da3cb3
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 64ddc663-653a-495a-a42f-084819696f3d
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: f2687968-9681-4b6c-a372-6a923000c349
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 2441408b-7de0-4757-a296-e51612fa7274
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionId'
		dataType: string
		lineageTag: 1b1a758c-15b9-4a47-8100-badacddf1bc6
		summarizeBy: none
		sourceColumn: properties.policyDefinitionId

		annotation SummarizationSetBy = Automatic

	column 'properties.effectiveDefinitionVersion'
		dataType: string
		lineageTag: 3fdd019a-6818-4624-8883-fcbc2fcb5cbf
		summarizeBy: none
		sourceColumn: properties.effectiveDefinitionVersion

		annotation SummarizationSetBy = Automatic

	column 'properties.latestDefinitionVersion'
		dataType: string
		lineageTag: b4d82c72-5088-4e2d-90af-6811e2d05749
		summarizeBy: none
		sourceColumn: properties.latestDefinitionVersion

		annotation SummarizationSetBy = Automatic

	column 'properties.nonComplianceMessages'
		dataType: string
		lineageTag: 9b302262-c1b3-470e-8484-c12e0dbea748
		summarizeBy: none
		sourceColumn: properties.nonComplianceMessages

		annotation SummarizationSetBy = Automatic

	column 'properties.definitionVersion'
		dataType: string
		lineageTag: bf5a225f-7b82-4d2b-85f7-2560b7e061c4
		summarizeBy: none
		sourceColumn: properties.definitionVersion

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceSelectors'
		dataType: string
		lineageTag: 52f9e25e-406a-4b7d-9ac8-1cb60a933544
		summarizeBy: none
		sourceColumn: properties.resourceSelectors

		annotation SummarizationSetBy = Automatic

	column 'properties.enforcementMode'
		dataType: string
		lineageTag: efd04add-4679-4db9-bc73-8b6a2932b3e6
		summarizeBy: none
		sourceColumn: properties.enforcementMode

		annotation SummarizationSetBy = Automatic

	column 'properties.assignmentType'
		dataType: string
		lineageTag: 12c1c5c6-11dc-4d1e-a7f4-6604475332ec
		summarizeBy: none
		sourceColumn: properties.assignmentType

		annotation SummarizationSetBy = Automatic

	column 'properties.description'
		dataType: string
		lineageTag: 55399cef-9b56-4140-9b93-68173263cbab
		summarizeBy: none
		sourceColumn: properties.description

		annotation SummarizationSetBy = Automatic

	column 'properties.displayName'
		dataType: string
		lineageTag: 577b6922-7909-41c7-aa95-26e9375dc07d
		summarizeBy: none
		sourceColumn: properties.displayName

		annotation SummarizationSetBy = Automatic

	column 'properties.parameters'
		dataType: string
		lineageTag: 21fb9078-e018-4a13-84df-58d728972531
		summarizeBy: none
		sourceColumn: properties.parameters

		annotation SummarizationSetBy = Automatic

	column 'properties.notScopes'
		dataType: string
		lineageTag: d1558915-83f7-43cf-a632-ab4cdb4bbc96
		summarizeBy: none
		sourceColumn: properties.notScopes

		annotation SummarizationSetBy = Automatic

	column 'properties.overrides'
		dataType: string
		lineageTag: 1edc0739-a96c-4b26-909c-633876fa20b5
		summarizeBy: none
		sourceColumn: properties.overrides

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.createdOn'
		dataType: string
		lineageTag: 60b52dae-769b-4524-af25-82fee7f6ea5a
		summarizeBy: none
		sourceColumn: properties.metadata.createdOn

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.createdBy'
		dataType: string
		lineageTag: 34df15fe-6fff-4122-ba3f-4eddf7f6ee28
		summarizeBy: none
		sourceColumn: properties.metadata.createdBy

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.assignedBy'
		dataType: string
		lineageTag: 504ac04b-5f15-4b20-b2d1-07ab6e6f3f3f
		summarizeBy: none
		sourceColumn: properties.metadata.assignedBy

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.parameterScopes'
		dataType: string
		lineageTag: 813d4a95-4b1e-44de-83be-f59effdcfa12
		summarizeBy: none
		sourceColumn: properties.metadata.parameterScopes

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.updatedOn'
		dataType: string
		lineageTag: fe4b7dbf-5b28-43d9-af99-09e7e2ad95ad
		summarizeBy: none
		sourceColumn: properties.metadata.updatedOn

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.updatedBy'
		dataType: string
		lineageTag: 1807cb63-219c-4be1-87fa-679944bfdff6
		summarizeBy: none
		sourceColumn: properties.metadata.updatedBy

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.category'
		dataType: string
		lineageTag: 0971ee73-9996-4224-98ed-defb725a779f
		summarizeBy: none
		sourceColumn: properties.metadata.category

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.managedByResourceId'
		dataType: string
		lineageTag: 6c2ddff2-45d2-4e23-865b-666d7756e2c9
		summarizeBy: none
		sourceColumn: properties.metadata.managedByResourceId

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.securityCenter'
		dataType: string
		lineageTag: 80c893a5-ebaf-4f8a-8a51-4919c8f51bce
		summarizeBy: none
		sourceColumn: properties.metadata.securityCenter

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata.excludedOutOfTheBoxStandards'
		dataType: string
		lineageTag: cf7174f5-9cb8-409c-b888-304adbfa4574
		summarizeBy: none
		sourceColumn: properties.metadata.excludedOutOfTheBoxStandards

		annotation SummarizationSetBy = Automatic

	column 'properties.scope'
		dataType: string
		lineageTag: 6c718623-aad0-4ea3-882f-c2d8509e2e6c
		summarizeBy: none
		sourceColumn: properties.scope

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 948994e6-71ed-4922-ba8b-443f2b7a48c6
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column 'identity.userAssignedIdentities'
		dataType: string
		lineageTag: 430d5b43-4f70-4835-ae26-95ee1dfc1e7c
		summarizeBy: none
		sourceColumn: identity.userAssignedIdentities

		annotation SummarizationSetBy = Automatic

	column 'identity.principalId'
		dataType: string
		lineageTag: 3fc62654-b60a-4f8c-9b10-a2cabf31a667
		summarizeBy: none
		sourceColumn: identity.principalId

		annotation SummarizationSetBy = Automatic

	column 'identity.tenantId'
		dataType: string
		lineageTag: d8c88efb-4d9d-4554-b0f1-6d7b616b14ff
		summarizeBy: none
		sourceColumn: identity.tenantId

		annotation SummarizationSetBy = Automatic

	column 'identity.type'
		dataType: string
		lineageTag: 87e445d1-5ff0-4b9e-be11-ab034c486f73
		summarizeBy: none
		sourceColumn: identity.type

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: f97f2c26-57b6-4f89-a0f8-2c6d1d5ea14e
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 9be71b86-100b-4dcd-99e1-282f20e65afb
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition PolicyAssignments = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("policyResources | where type =~'Microsoft.Authorization/PolicyAssignments'", "Tenant", null, null, [resultTruncated = false]),
				    #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"policyDefinitionId", "effectiveDefinitionVersion", "latestDefinitionVersion", "nonComplianceMessages", "definitionVersion", "resourceSelectors", "enforcementMode", "assignmentType", "description", "displayName", "parameters", "notScopes", "overrides", "metadata", "scope"}, {"properties.policyDefinitionId", "properties.effectiveDefinitionVersion", "properties.latestDefinitionVersion", "properties.nonComplianceMessages", "properties.definitionVersion", "properties.resourceSelectors", "properties.enforcementMode", "properties.assignmentType", "properties.description", "properties.displayName", "properties.parameters", "properties.notScopes", "properties.overrides", "properties.metadata", "properties.scope"}),
				    #"Expanded properties.metadata" = Table.ExpandRecordColumn(#"Expanded properties", "properties.metadata", {"createdOn", "createdBy", "assignedBy", "parameterScopes", "updatedOn", "updatedBy", "category", "managedByResourceId", "securityCenter", "excludedOutOfTheBoxStandards"}, {"properties.metadata.createdOn", "properties.metadata.createdBy", "properties.metadata.assignedBy", "properties.metadata.parameterScopes", "properties.metadata.updatedOn", "properties.metadata.updatedBy", "properties.metadata.category", "properties.metadata.managedByResourceId", "properties.metadata.securityCenter", "properties.metadata.excludedOutOfTheBoxStandards"}),
				    #"Expanded identity" = Table.ExpandRecordColumn(#"Expanded properties.metadata", "identity", {"userAssignedIdentities", "principalId", "tenantId", "type"}, {"identity.userAssignedIdentities", "identity.principalId", "identity.tenantId", "identity.type"}),
				    #"Expanded properties.notScopes" = Table.ExpandListColumn(#"Expanded identity", "properties.notScopes")
				in
				    #"Expanded properties.notScopes"

	annotation PBI_ResultType = Table

