table PolicyStates
	lineageTag: ddaaa169-beba-4cab-8e86-a90312768f86

	measure complianceScore = [compliantCount]/[totalResourceCount]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7184c6a4-ef41-4f8f-99f7-145e819cedd3

	measure compliantCount = [totalResourceCount]-[nonCompliantCount]
		lineageTag: f516dcb7-f7dd-42e4-b7cc-528d823e226a

	measure totalResourceCount = DISTINCTCOUNT(PolicyStates[properties.resourceId])
		formatString: 0
		lineageTag: 977845bf-f755-44e1-ada3-65c66a6e3462

	measure nonCompliantCount = CALCULATE(DISTINCTCOUNT(PolicyStates[properties.resourceId]),FILTER(PolicyStates,PolicyStates[properties.complianceState]="NonCompliant"))
		formatString: 0
		lineageTag: bdc393be-71dc-461b-be1e-e1e20e80deb7

	column id
		dataType: string
		lineageTag: 7ba8de0a-f1e6-4260-bd38-ab5b97282edf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 80421f88-6495-4d42-815d-fd640b472663
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 462cea37-c85d-4287-ad75-f0a20ae7dde4
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 61d83c8a-9572-4407-a572-0847c249c5d6
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: ffb41542-24b2-497a-ac8b-25be65481bd5
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 10bfdb76-7ae1-47d1-af19-3af804e98694
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: f14ac2f4-addb-461e-86fe-52c18e293b49
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 626e561c-e32d-461f-b7b7-2774cc3e60a6
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 0dd44396-ad4c-4a22-bb3b-bf0b8b82faef
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: f2995d55-ee1e-4636-b779-366a71c4610b
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: c1dc3db4-50fc-485e-9490-abdc3e3c6703
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.policyAssignmentParameters'
		dataType: string
		lineageTag: 976d4bcc-47a3-4445-be8f-99758a32e340
		summarizeBy: none
		sourceColumn: properties.policyAssignmentParameters

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionAction'
		dataType: string
		lineageTag: b8975dc1-bfc2-4b05-afc0-b17681495582
		summarizeBy: none
		sourceColumn: properties.policyDefinitionAction

		annotation SummarizationSetBy = Automatic

	column 'properties.policyAssignmentScope'
		dataType: string
		lineageTag: 7ad6604a-a34a-4d7f-9696-43b356e3d764
		summarizeBy: none
		sourceColumn: properties.policyAssignmentScope

		annotation SummarizationSetBy = Automatic

	column 'properties.policyAssignmentName'
		dataType: string
		lineageTag: c4cbfde1-e98a-42c3-8f44-3452a16a190f
		summarizeBy: none
		sourceColumn: properties.policyAssignmentName

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionName'
		dataType: string
		lineageTag: 8958b907-827d-4ae0-a0cc-e762a82b9b85
		summarizeBy: none
		sourceColumn: properties.policyDefinitionName

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionReferenceId'
		dataType: string
		lineageTag: fb7a1465-d4b5-4110-b69f-07dc7bab9093
		summarizeBy: none
		sourceColumn: properties.policyDefinitionReferenceId

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionId'
		dataType: string
		lineageTag: e8535074-b10f-4f22-9fe4-a31d578833a6
		summarizeBy: none
		sourceColumn: properties.policyDefinitionId

		annotation SummarizationSetBy = Automatic

	column 'properties.managementGroupIds'
		dataType: string
		lineageTag: 343f4bc3-088f-4e7e-93c5-75e9933a5539
		summarizeBy: none
		sourceColumn: properties.managementGroupIds

		annotation SummarizationSetBy = Automatic

	column 'properties.policyAssignmentId'
		dataType: string
		lineageTag: 9f9bc13f-3a7c-4c05-9df1-a960a7324088
		summarizeBy: none
		sourceColumn: properties.policyAssignmentId

		annotation SummarizationSetBy = Automatic

	column 'properties.policySetDefinitionName'
		dataType: string
		lineageTag: 935887d7-a20e-417f-a3dd-4082d3be7b7c
		summarizeBy: none
		sourceColumn: properties.policySetDefinitionName

		annotation SummarizationSetBy = Automatic

	column 'properties.complianceState'
		dataType: string
		lineageTag: 4a4e349d-4d1d-4540-9009-a9185897ec87
		summarizeBy: none
		sourceColumn: properties.complianceState

		annotation SummarizationSetBy = Automatic

	column 'properties.policySetDefinitionId'
		dataType: string
		lineageTag: 81546c4a-65ec-4382-9850-eab0fdc9c517
		summarizeBy: none
		sourceColumn: properties.policySetDefinitionId

		annotation SummarizationSetBy = Automatic

	column 'properties.subscriptionId'
		dataType: string
		lineageTag: dcd409e4-6287-4752-b902-e5cfe1a06ff6
		summarizeBy: none
		sourceColumn: properties.subscriptionId

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceType'
		dataType: string
		lineageTag: 327ea810-9263-442b-bfb1-30aa6c70807e
		summarizeBy: none
		sourceColumn: properties.resourceType

		annotation SummarizationSetBy = Automatic

	column 'properties.stateWeight'
		dataType: string
		lineageTag: 9d365b85-9fc9-465b-b056-bf75be6ed2be
		summarizeBy: none
		sourceColumn: properties.stateWeight

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceGroup'
		dataType: string
		lineageTag: d1c8ea80-a667-4de4-9a77-d2a9fd54c661
		summarizeBy: none
		sourceColumn: properties.resourceGroup

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceId'
		dataType: string
		lineageTag: 38434022-80c6-474e-9613-e0fa6c1f8a7d
		summarizeBy: none
		sourceColumn: properties.resourceId

		annotation SummarizationSetBy = Automatic

	column 'properties.timestamp'
		dataType: string
		lineageTag: 383a8625-d688-4036-87f1-ea0b7de2aa91
		summarizeBy: none
		sourceColumn: properties.timestamp

		annotation SummarizationSetBy = Automatic

	column 'properties.isDeleted'
		dataType: string
		lineageTag: 5b741dff-1873-495a-962a-60f6cea82e0b
		summarizeBy: none
		sourceColumn: properties.isDeleted

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceLocation'
		dataType: string
		lineageTag: da681ebd-b892-4ca0-bd89-44845dba3973
		summarizeBy: none
		sourceColumn: properties.resourceLocation

		annotation SummarizationSetBy = Automatic

	column 'properties.policySetDefinitionCategory'
		dataType: string
		lineageTag: 8540107c-d194-443c-995e-4ed707a69fc8
		summarizeBy: none
		sourceColumn: properties.policySetDefinitionCategory

		annotation SummarizationSetBy = Automatic

	column 'properties.policyDefinitionGroupNames'
		dataType: string
		lineageTag: 9e43a4ce-4892-4125-bdc8-73b7bb573c64
		summarizeBy: none
		sourceColumn: properties.policyDefinitionGroupNames

		annotation SummarizationSetBy = Automatic

	column 'properties.complianceReasonCode'
		dataType: string
		lineageTag: c91b7bea-b7fb-4919-8f6e-a663800a4264
		summarizeBy: none
		sourceColumn: properties.complianceReasonCode

		annotation SummarizationSetBy = Automatic

	column 'properties.stateDetails'
		dataType: string
		lineageTag: fece490d-d422-4987-ad3d-83bd7e8ef9f3
		summarizeBy: none
		sourceColumn: properties.stateDetails

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 76ebca24-9288-4aaa-b53a-834e0b588b34
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 7cd7f649-2d4b-49d8-bf7c-55dac13d1ac8
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: f80f1302-d82f-486b-b38e-46dfaced7bdd
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 7c3b3f23-60fd-4f2a-8e65-8c85073eb8ef
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition PolicyStates = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("policyResources | where type =~'Microsoft.PolicyInsights/PolicyStates'", "Tenant", null, null, [resultTruncated = false]),
				    #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"policyAssignmentParameters", "policyDefinitionAction", "policyAssignmentScope", "policyAssignmentName", "policyDefinitionName", "policyDefinitionReferenceId", "policyDefinitionId", "managementGroupIds", "policyAssignmentId", "policySetDefinitionName", "complianceState", "policySetDefinitionId", "subscriptionId", "resourceType", "stateWeight", "resourceGroup", "resourceId", "timestamp", "isDeleted", "resourceLocation", "policySetDefinitionCategory", "policyDefinitionGroupNames", "complianceReasonCode", "stateDetails"}, {"properties.policyAssignmentParameters", "properties.policyDefinitionAction", "properties.policyAssignmentScope", "properties.policyAssignmentName", "properties.policyDefinitionName", "properties.policyDefinitionReferenceId", "properties.policyDefinitionId", "properties.managementGroupIds", "properties.policyAssignmentId", "properties.policySetDefinitionName", "properties.complianceState", "properties.policySetDefinitionId", "properties.subscriptionId", "properties.resourceType", "properties.stateWeight", "properties.resourceGroup", "properties.resourceId", "properties.timestamp", "properties.isDeleted", "properties.resourceLocation", "properties.policySetDefinitionCategory", "properties.policyDefinitionGroupNames", "properties.complianceReasonCode", "properties.stateDetails"}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Expanded properties", {{"properties.policyAssignmentScope", each Text.AfterDelimiter(_, "/", {0, RelativePosition.FromEnd}), type text}})
				in
				  #"Extracted Text After Delimiter"

	annotation PBI_ResultType = Table

