table 'Public ip addresses'
	lineageTag: ddccb4e4-02c5-4048-ac45-72976ce44437

	column id
		dataType: string
		lineageTag: 147b6862-e175-49bd-ad7f-409fd482f46f
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e1705444-2a52-4521-9566-288b2d153435
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: e19a2962-6b82-4c1f-904b-102a6a5f6be8
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 62e3ba5d-856a-47f6-88b6-09eaebdb94e4
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: abf0efb3-cda1-473e-abb8-3b45bcd34d38
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: b0265904-5ded-41b5-b68c-7db00a6f3f39
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 5e2a257f-4d9a-4f66-a1da-1256db9ef768
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 9fbe9b32-0a90-4540-acec-d26365b694c8
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: dfd63ab0-3ac8-4b99-9d11-818f938970f5
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 4dda8994-06cb-482b-a1f2-f0519866cbcf
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 6df13bf9-72eb-483a-a712-9556b2fc80c2
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.provisioningState'
		dataType: string
		lineageTag: 3462061e-ef7e-42ed-9bc9-e7dd302141dd
		summarizeBy: none
		sourceColumn: properties.provisioningState

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceGuid'
		dataType: string
		lineageTag: 21f11aee-fc47-4a66-a3a5-3a4ddcae889b
		summarizeBy: none
		sourceColumn: properties.resourceGuid

		annotation SummarizationSetBy = Automatic

	column 'properties.idleTimeoutInMinutes'
		dataType: string
		lineageTag: 17666534-7684-424b-8fe4-b26ac12ea6c1
		summarizeBy: none
		sourceColumn: properties.idleTimeoutInMinutes

		annotation SummarizationSetBy = Automatic

	column 'properties.publicIPAllocationMethod'
		dataType: string
		lineageTag: e3b59f3a-bacc-4160-af94-93ea33ce679a
		summarizeBy: none
		sourceColumn: properties.publicIPAllocationMethod

		annotation SummarizationSetBy = Automatic

	column 'properties.publicIPAddressVersion'
		dataType: string
		lineageTag: dbcfd8f7-9aad-452b-a604-acef95652252
		summarizeBy: none
		sourceColumn: properties.publicIPAddressVersion

		annotation SummarizationSetBy = Automatic

	column 'properties.ipAddress'
		dataType: string
		lineageTag: b0f9799e-568e-4c12-9116-b26f09ae4ee2
		summarizeBy: none
		sourceColumn: properties.ipAddress

		annotation SummarizationSetBy = Automatic

	column 'properties.ipConfiguration'
		dataType: string
		lineageTag: 0977b134-91f7-4122-8ded-a2c3247cc543
		summarizeBy: none
		sourceColumn: properties.ipConfiguration

		annotation SummarizationSetBy = Automatic

	column 'properties.ipTags'
		dataType: string
		lineageTag: ff04ff92-2978-4c37-94fe-dc356a03255b
		summarizeBy: none
		sourceColumn: properties.ipTags

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 093fadb2-d44a-4623-a660-b8cb163339f5
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: a95f92e4-5408-401f-b8b6-7ebd94f941a4
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 7298cba3-c099-427e-897e-4b385f7baba6
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 25de1b56-f565-4a3f-b597-7b183737d401
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition 'Public ip addresses' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources | where type =~ 'microsoft.network/publicipaddresses'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "resourceGuid", "idleTimeoutInMinutes", "publicIPAllocationMethod", "publicIPAddressVersion", "ipAddress", "ipConfiguration", "ipTags"}, {"properties.provisioningState", "properties.resourceGuid", "properties.idleTimeoutInMinutes", "properties.publicIPAllocationMethod", "properties.publicIPAddressVersion", "properties.ipAddress", "properties.ipConfiguration", "properties.ipTags"})
				in
				  #"Expanded properties"

