table Region
	lineageTag: 952a455d-5502-4c7a-b836-9f2a00464182

	column OriginalValue
		dataType: string
		lineageTag: 445129f1-7e5e-488e-9a07-5672e049d26f
		summarizeBy: none
		sourceColumn: OriginalValue

		annotation SummarizationSetBy = Automatic

	column RegionId
		dataType: string
		lineageTag: f47ffeee-54d6-4bd0-8796-d427897eb19a
		summarizeBy: none
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 3369cd13-a700-4c0a-acab-098251fe1879
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = Csv.Document(Web.Contents("https://github.com/microsoft/finops-toolkit/releases/latest/download/Regions.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])
				in
				  #"Promoted headers"

