table 'Reservation recommendations'
	lineageTag: 32d03c9d-1549-44d4-8a29-24c58b034ce6

	column id
		dataType: string
		lineageTag: 1f188e79-f5da-402e-8c9f-cbbbb33d343b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 20ef22a4-f948-4168-854e-dd9e7e106edf
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: a6d78e08-182b-4df3-a696-541bc7e8e749
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 49cb8580-0680-4a0d-84a8-5cf23f6fda0f
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: ad57d40e-da78-4e7a-a0f4-d8b45c6ba213
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: a5573c18-e735-4411-b4be-44d04c31c423
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 874cafe7-0ee6-49cb-9db0-3e9ae2697437
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: c4eeb263-374d-4755-8d4c-4b4f68fae6ef
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 5ff18354-5632-462d-9e63-86f56be68315
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 3864eb7c-2e16-4bfe-ac02-4d78dc1a420f
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 251b1655-17a6-4fbd-8402-674bba67afb8
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.recommendationTypeId'
		dataType: string
		lineageTag: 34fda0dd-c055-4e7b-b560-48ff9172b31c
		summarizeBy: none
		sourceColumn: properties.recommendationTypeId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.reservedResourceType'
		dataType: string
		lineageTag: e1bb433f-77b7-4609-8934-532e6abfefcb
		summarizeBy: none
		sourceColumn: properties.extendedProperties.reservedResourceType

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.annualSavingsAmount'
		dataType: double
		lineageTag: 3d6dc30b-3010-470e-bbeb-bb86375c086b
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.annualSavingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.targetResourceCount'
		dataType: int64
		formatString: 0
		lineageTag: e96df54f-0c6d-4183-8a4b-ee91ee074407
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.targetResourceCount

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsCurrency'
		dataType: string
		lineageTag: ebbb729e-f92c-462f-b641-19ad6e359529
		summarizeBy: none
		sourceColumn: properties.extendedProperties.savingsCurrency

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.lookbackPeriod'
		dataType: string
		lineageTag: 15ba1343-0cb7-453f-8061-d3976a330511
		summarizeBy: none
		sourceColumn: properties.extendedProperties.lookbackPeriod

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.savingsAmount'
		dataType: double
		lineageTag: f7b099d5-c0b8-4e46-a489-a672360878e6
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.savingsAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'properties.extendedProperties.displaySKU'
		dataType: string
		lineageTag: 782dc52b-67a0-4c49-93b5-ae9fac55606a
		summarizeBy: none
		sourceColumn: properties.extendedProperties.displaySKU

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.displayQty'
		dataType: int64
		formatString: 0
		lineageTag: 958867a9-ee32-44e7-af9e-f427c05eacb4
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.displayQty

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.location'
		dataType: string
		lineageTag: 0f879db4-d54b-46f4-bfd7-a965eae4f10e
		summarizeBy: none
		sourceColumn: properties.extendedProperties.location

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.region'
		dataType: string
		lineageTag: 0dcaffff-a657-4817-b26c-da305d613d84
		summarizeBy: none
		sourceColumn: properties.extendedProperties.region

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.vmSize'
		dataType: string
		lineageTag: 316c212d-70b2-4724-b649-c8d3e5afe7c6
		summarizeBy: none
		sourceColumn: properties.extendedProperties.vmSize

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.subId'
		dataType: string
		lineageTag: 6955d4bc-e9a8-4d11-9c18-5155f731b0e6
		summarizeBy: none
		sourceColumn: properties.extendedProperties.subId

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.scope'
		dataType: string
		lineageTag: 07aac04e-19e8-44cc-a36e-04e408877d9b
		summarizeBy: none
		sourceColumn: properties.extendedProperties.scope

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.term'
		dataType: string
		lineageTag: 05c24fce-532b-4b5b-8ea0-94bcdbf208ee
		summarizeBy: none
		sourceColumn: properties.extendedProperties.term

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.sku'
		dataType: string
		lineageTag: ae8c5616-13f1-45fa-899a-05747f11127a
		summarizeBy: none
		sourceColumn: properties.extendedProperties.sku

		annotation SummarizationSetBy = Automatic

	column 'properties.extendedProperties.qty'
		dataType: int64
		formatString: 0
		lineageTag: b5f02789-c583-453f-b9f9-501e1ca97101
		summarizeBy: sum
		sourceColumn: properties.extendedProperties.qty

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.resourceId'
		dataType: string
		lineageTag: 19f80650-65ed-4169-a480-bfc4eb6167b5
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.resourceId

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.singular'
		dataType: string
		lineageTag: e81001eb-0af1-4675-9adb-0daad9ce1937
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.singular

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.plural'
		dataType: string
		lineageTag: 48b10855-2abd-420c-914d-3b41299c7486
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.plural

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.action'
		dataType: string
		lineageTag: 1887c6e0-ab3d-4662-92c4-2d2bdd747bd8
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.action

		annotation SummarizationSetBy = Automatic

	column 'properties.resourceMetadata.source'
		dataType: string
		lineageTag: d87c9d3c-be85-4d73-8000-e50585aac16c
		summarizeBy: none
		sourceColumn: properties.resourceMetadata.source

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.solution'
		dataType: string
		lineageTag: 97e159ba-37f4-4aed-8dfe-008175f2df75
		summarizeBy: none
		sourceColumn: properties.shortDescription.solution

		annotation SummarizationSetBy = Automatic

	column 'properties.shortDescription.problem'
		dataType: string
		lineageTag: 2acdc3e7-e5d4-4ffd-ba71-996db2aa66f4
		summarizeBy: none
		sourceColumn: properties.shortDescription.problem

		annotation SummarizationSetBy = Automatic

	column 'properties.suppressionIds'
		dataType: string
		lineageTag: c7294601-5900-4057-847b-7490b0df9329
		summarizeBy: none
		sourceColumn: properties.suppressionIds

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedField'
		dataType: string
		lineageTag: 8f6a3d84-3eb4-4fa6-8eeb-2c0df310d7f1
		summarizeBy: none
		sourceColumn: properties.impactedField

		annotation SummarizationSetBy = Automatic

	column 'properties.impactedValue'
		dataType: string
		lineageTag: ebd1e40e-4821-42e3-86e3-a38e5dc7f61f
		summarizeBy: none
		sourceColumn: properties.impactedValue

		annotation SummarizationSetBy = Automatic

	column 'properties.lastUpdated'
		dataType: dateTime
		formatString: General Date
		lineageTag: a1744314-846b-40a2-8160-75795180afd1
		summarizeBy: none
		sourceColumn: properties.lastUpdated

		variation Variation
			isDefault
			relationship: e4a57f31-a6db-4961-bb57-f048c5aa2fa0
			defaultHierarchy: LocalDateTable_3d93e1c3-f4b8-441e-a637-90f0b60c40ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'properties.metadata'
		dataType: string
		lineageTag: e8103084-b82c-47c5-8dbf-82a12f52f19a
		summarizeBy: none
		sourceColumn: properties.metadata

		annotation SummarizationSetBy = Automatic

	column 'properties.category'
		dataType: string
		lineageTag: a851a028-6922-4116-84d8-f72a142f92d4
		summarizeBy: none
		sourceColumn: properties.category

		annotation SummarizationSetBy = Automatic

	column 'properties.impact'
		dataType: string
		lineageTag: bc127f8c-fac1-4740-abf2-137d0aa81753
		summarizeBy: none
		sourceColumn: properties.impact

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 17124a5b-2ed9-4c39-b107-3d184059c825
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 447dd6de-33f1-4441-8c72-af3ed2d731cd
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 8dfb4f19-b232-4913-8d3e-8b5d2e1c1844
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: d80e37d8-5e89-43bd-b5b1-fc51ee0fab37
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	column recommendedActions
		dataType: string
		lineageTag: 0213bcd5-c149-410d-92a2-39caa092b7eb
		summarizeBy: none
		sourceColumn: recommendedActions

		annotation SummarizationSetBy = Automatic

	partition 'Reservation recommendations' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("advisorresources | where type == ""microsoft.advisor/recommendations"" | where properties['category'] == 'Cost' | where properties['shortDescription']['solution'] == 'Consider virtual machine reserved instance to save over your on-demand costs'", "Tenant", null, null, [resultTruncated = true]),
				  #"Expanded properties 1" = Table.ExpandRecordColumn(Source, "properties", {"recommendationTypeId", "extendedProperties", "resourceMetadata", "shortDescription", "suppressionIds", "impactedField", "impactedValue", "lastUpdated", "metadata", "category", "impact"}, {"properties.recommendationTypeId", "properties.extendedProperties", "properties.resourceMetadata", "properties.shortDescription", "properties.suppressionIds", "properties.impactedField", "properties.impactedValue", "properties.lastUpdated", "properties.metadata", "properties.category", "properties.impact"}),
				  #"Expanded properties.shortDescription 1" = Table.ExpandRecordColumn(#"Expanded properties 1", "properties.shortDescription", {"solution", "problem"}, {"properties.shortDescription.solution", "properties.shortDescription.problem"}),
				  #"Expanded properties.extendedProperties" = Table.ExpandRecordColumn(#"Expanded properties.shortDescription 1", "properties.extendedProperties", {"reservedResourceType", "annualSavingsAmount", "targetResourceCount", "savingsCurrency", "lookbackPeriod", "savingsAmount", "displaySKU", "displayQty", "location", "region", "vmSize", "subId", "scope", "term", "sku", "qty"}, {"properties.extendedProperties.reservedResourceType", "properties.extendedProperties.annualSavingsAmount", "properties.extendedProperties.targetResourceCount", "properties.extendedProperties.savingsCurrency", "properties.extendedProperties.lookbackPeriod", "properties.extendedProperties.savingsAmount", "properties.extendedProperties.displaySKU", "properties.extendedProperties.displayQty", "properties.extendedProperties.location", "properties.extendedProperties.region", "properties.extendedProperties.vmSize", "properties.extendedProperties.subId", "properties.extendedProperties.scope", "properties.extendedProperties.term", "properties.extendedProperties.sku", "properties.extendedProperties.qty"}),
				  #"Expanded properties.resourceMetadata" = Table.ExpandRecordColumn(#"Expanded properties.extendedProperties", "properties.resourceMetadata", {"resourceId", "singular", "plural", "action", "source"}, {"properties.resourceMetadata.resourceId", "properties.resourceMetadata.singular", "properties.resourceMetadata.plural", "properties.resourceMetadata.action", "properties.resourceMetadata.source"}),
				  #"Changed column type 2" = Table.TransformColumnTypes(#"Expanded properties.resourceMetadata", {{"properties.extendedProperties.annualSavingsAmount", type number}}, "en-US"),
				  #"Replaced errors" = Table.ReplaceErrorValues(#"Changed column type 2", {{"properties.extendedProperties.annualSavingsAmount", null}}),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Replaced errors", {{"properties.extendedProperties.savingsAmount", type number}}, "en-US"),
				  #"Replaced errors 1" = Table.ReplaceErrorValues(#"Changed column type 1", {{"properties.extendedProperties.savingsAmount", null}}),
				  #"Replaced value" = Table.ReplaceValue(#"Replaced errors 1", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.savingsAmount"}),
				  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", null, 0, Replacer.ReplaceValue, {"properties.extendedProperties.annualSavingsAmount"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Replaced value 1", {{"properties.lastUpdated", type datetimezone}}),
				  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Changed column type", "recommendedActions", each [properties.extendedProperties.displaySKU] & " virtual machines in " & [properties.extendedProperties.location]), {{"recommendedActions", type text}}),
				  #"Changed column type 3" = Table.TransformColumnTypes(#"Added custom", {{"properties.extendedProperties.targetResourceCount", Int64.Type}, {"properties.extendedProperties.displayQty", Int64.Type}, {"properties.extendedProperties.qty", Int64.Type}})
				in
				  #"Changed column type 3"

