table 'Resource types'
	lineageTag: 902d6cda-e185-41c6-bdbe-2a61583aba7d

	column ResourceType
		dataType: string
		lineageTag: d8cc809f-456d-497d-9a9d-c49c88271374
		summarizeBy: none
		sourceColumn: ResourceType

		annotation SummarizationSetBy = Automatic

	column SingularDisplayName
		dataType: string
		lineageTag: 5bd71236-7a3d-45c2-a54d-189ed640d710
		summarizeBy: none
		sourceColumn: SingularDisplayName

		annotation SummarizationSetBy = Automatic

	column PluralDisplayName
		dataType: string
		lineageTag: 31eefbf4-3fe8-4f06-8a42-fca1cf60421f
		summarizeBy: none
		sourceColumn: PluralDisplayName

		annotation SummarizationSetBy = Automatic

	column LowerSingularDisplayName
		dataType: string
		lineageTag: db8cfa7a-775b-4d5d-b732-fc5108c38569
		summarizeBy: none
		sourceColumn: LowerSingularDisplayName

		annotation SummarizationSetBy = Automatic

	column LowerPluralDisplayName
		dataType: string
		lineageTag: e3de047c-eefb-48a4-92a2-988071b4f4b4
		summarizeBy: none
		sourceColumn: LowerPluralDisplayName

		annotation SummarizationSetBy = Automatic

	column IsPreview
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab47dbb6-729a-4a74-bab0-c3a49f9620cf
		summarizeBy: none
		sourceColumn: IsPreview

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 5504fbdf-ad32-4a98-8d11-0bd4ec4aa2ba
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Icon
		dataType: string
		lineageTag: bbf94620-0b81-4492-ad0f-703767d0a560
		summarizeBy: none
		sourceColumn: Icon

		annotation SummarizationSetBy = Automatic

	column Links
		dataType: string
		lineageTag: be341d98-870a-4064-a3d2-374878d6a853
		summarizeBy: none
		sourceColumn: Links

		annotation SummarizationSetBy = Automatic

	partition 'Resource types' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = Csv.Document(Web.Contents("https://github.com/microsoft/finops-toolkit/releases/latest/download/ResourceTypes.csv"), [Delimiter = ",", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ResourceType", type text}, {"SingularDisplayName", type text}, {"PluralDisplayName", type text}, {"LowerSingularDisplayName", type text}, {"LowerPluralDisplayName", type text}, {"IsPreview", type logical}, {"Description", type text}, {"Icon", type text}, {"Links", type text}}, "en-US")
				in
				  #"Changed column type"

