table Resources
	lineageTag: c439440e-806c-484a-952d-67405cf2d4e1

	column id
		dataType: string
		lineageTag: 603f47eb-e992-4581-8ccd-18e395111d15
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 5b6aec64-1c3d-490e-b773-89aced5db8f4
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 4d54e914-4c8f-4c18-8ebd-65edd5a549a3
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 36c7ccde-416b-40f0-a1ae-558dde75b380
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 224c2689-cde8-4160-bc50-4c24579cdb34
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 163e3828-e888-4c7e-a39e-a586cd0d8361
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: e73dbbe0-d344-4eb7-b2e5-2ea45b93e2ba
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 9faeb081-cdbc-46eb-8008-16110f28f6a0
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: ef42db3e-6f6f-4cef-8e14-1c16bb46fe38
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column 'sku.name'
		dataType: string
		lineageTag: 21410b01-bc00-47b4-9527-1f665bc6065d
		summarizeBy: none
		sourceColumn: sku.name

		annotation SummarizationSetBy = Automatic

	column 'sku.tier'
		dataType: string
		lineageTag: e9a697e6-58ef-461f-b8ee-8e417ebc4075
		summarizeBy: none
		sourceColumn: sku.tier

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: d0c52cc7-e2f5-41d4-8088-5d560cdb5e4c
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column provisioningState
		dataType: string
		lineageTag: d7e02ed7-e8bf-4971-a2ad-a9498a674778
		summarizeBy: none
		sourceColumn: provisioningState

		annotation SummarizationSetBy = Automatic

	column privateEndpointConnections
		dataType: string
		lineageTag: e842716b-5f83-4829-ab75-56ab1007a37a
		summarizeBy: none
		sourceColumn: privateEndpointConnections

		annotation SummarizationSetBy = Automatic

	column encryption
		dataType: string
		lineageTag: ae2d85e3-96f9-4613-b91a-43006cf2f3f2
		summarizeBy: none
		sourceColumn: encryption

		annotation SummarizationSetBy = Automatic

	column creationTime
		dataType: string
		lineageTag: 4afccf80-da80-47e9-b0ff-74592e8914a6
		summarizeBy: none
		sourceColumn: creationTime

		annotation SummarizationSetBy = Automatic

	column supportsHttpsTrafficOnly
		dataType: string
		lineageTag: 63e65d81-03b7-48fd-889c-c4bbdee34521
		summarizeBy: none
		sourceColumn: supportsHttpsTrafficOnly

		annotation SummarizationSetBy = Automatic

	column allowBlobPublicAccess
		dataType: string
		lineageTag: f57eb8d6-7550-4d05-94e8-963bc32f1e32
		summarizeBy: none
		sourceColumn: allowBlobPublicAccess

		annotation SummarizationSetBy = Automatic

	column minimumTlsVersion
		dataType: string
		lineageTag: b6ce16f4-fc5a-420d-8061-3394a53698df
		summarizeBy: none
		sourceColumn: minimumTlsVersion

		annotation SummarizationSetBy = Automatic

	column primaryEndpoints
		dataType: string
		lineageTag: 11253e4c-7464-49c0-97a6-6bb5d46322cf
		summarizeBy: none
		sourceColumn: primaryEndpoints

		annotation SummarizationSetBy = Automatic

	column keyCreationTime
		dataType: string
		lineageTag: 6d42bc18-47a5-4c41-a47c-40aca7b37fd7
		summarizeBy: none
		sourceColumn: keyCreationTime

		annotation SummarizationSetBy = Automatic

	column primaryLocation
		dataType: string
		lineageTag: 9571faa4-fcc9-4a6b-a901-af14f333ef59
		summarizeBy: none
		sourceColumn: primaryLocation

		annotation SummarizationSetBy = Automatic

	column statusOfPrimary
		dataType: string
		lineageTag: d07b05bc-e112-4506-9535-3f29356c7e95
		summarizeBy: none
		sourceColumn: statusOfPrimary

		annotation SummarizationSetBy = Automatic

	column networkAcls
		dataType: string
		lineageTag: 8a610d77-8ffe-46e3-8a90-94c6fbb4b221
		summarizeBy: none
		sourceColumn: networkAcls

		annotation SummarizationSetBy = Automatic

	column allowCrossTenantReplication
		dataType: string
		lineageTag: a12ef426-b95a-4724-b7bf-b5fd64bb19d3
		summarizeBy: none
		sourceColumn: allowCrossTenantReplication

		annotation SummarizationSetBy = Automatic

	column allowSharedKeyAccess
		dataType: string
		lineageTag: 9af588fa-f8a8-4e98-8535-972a6d43d213
		summarizeBy: none
		sourceColumn: allowSharedKeyAccess

		annotation SummarizationSetBy = Automatic

	column accessTier
		dataType: string
		lineageTag: 486e2ce8-9591-46ce-a950-1134a5f74e52
		summarizeBy: none
		sourceColumn: accessTier

		annotation SummarizationSetBy = Automatic

	column isHnsEnabled
		dataType: string
		lineageTag: 68bce6cf-9b8d-4520-a3cb-88c7bc5d965b
		summarizeBy: none
		sourceColumn: isHnsEnabled

		annotation SummarizationSetBy = Automatic

	column isBlueShiftAccount
		dataType: string
		lineageTag: 08b93fb0-e9e7-48bc-8899-f23495eb8dbe
		summarizeBy: none
		sourceColumn: isBlueShiftAccount

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 96baa77b-5f41-4be4-8413-021e7c681496
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 57a768ae-7c62-4b71-b078-e088f9289572
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 0c57c63d-ffea-4f2c-9c6c-d37bae17e952
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: ca0e010a-d3fe-4b0e-8726-ae28d8c28093
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition Resources = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "privateEndpointConnections", "encryption", "creationTime", "supportsHttpsTrafficOnly", "allowBlobPublicAccess", "minimumTlsVersion", "primaryEndpoints", "keyCreationTime", "primaryLocation", "statusOfPrimary", "networkAcls", "allowCrossTenantReplication", "allowSharedKeyAccess", "accessTier", "isHnsEnabled", "isBlueShiftAccount"}, {"provisioningState", "privateEndpointConnections", "encryption", "creationTime", "supportsHttpsTrafficOnly", "allowBlobPublicAccess", "minimumTlsVersion", "primaryEndpoints", "keyCreationTime", "primaryLocation", "statusOfPrimary", "networkAcls", "allowCrossTenantReplication", "allowSharedKeyAccess", "accessTier", "isHnsEnabled", "isBlueShiftAccount"}),
				  #"Expanded sku" = Table.ExpandRecordColumn(#"Expanded properties", "sku", {"name", "tier"}, {"sku.name", "sku.tier"})
				in
				  #"Expanded sku"

