table 'SQL DB'
	lineageTag: 89addb7d-5b61-4175-8fdd-548239bb8a48

	column id
		dataType: string
		lineageTag: 9f6c15fd-b716-4022-8f06-90f7bf49d7f4
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 1d3a7204-7d84-4244-aed6-7cdbdd03069e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: c2e72aa1-b04d-4eb4-9200-f3181e412485
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: e55b9234-e33f-4125-b1c2-cbf8d453a199
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 1b938d5d-7176-42a5-b5ab-ab1f05cb609f
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: e828edfe-800c-48b3-aa91-025767524402
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: f6222a8d-d150-4fae-9dcd-f9b65f1f3673
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: a6ce31ac-460d-45f9-bb74-b4c0aa8d0077
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 1629a3c5-cc3c-4d97-9def-e6638be39c09
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column 'sku.name'
		dataType: string
		lineageTag: c3aba652-5233-44ef-974c-40a40ed47f48
		summarizeBy: none
		sourceColumn: sku.name

		annotation SummarizationSetBy = Automatic

	column 'sku.tier'
		dataType: string
		lineageTag: dde80fc7-1bae-40b5-b2aa-55528a8a0716
		summarizeBy: none
		sourceColumn: sku.tier

		annotation SummarizationSetBy = Automatic

	column 'sku.capacity'
		dataType: string
		lineageTag: 7565736d-0b96-42c4-9b1f-1ea25d382166
		summarizeBy: none
		sourceColumn: sku.capacity

		annotation SummarizationSetBy = Automatic

	column 'sku.family'
		dataType: string
		lineageTag: ce87078a-93dc-4dc3-b331-44dd26290e0a
		summarizeBy: none
		sourceColumn: sku.family

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: a081a45c-2223-491d-98d9-1bc5d546015e
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column 'properties.status'
		dataType: string
		lineageTag: 34d8673b-8c03-4773-9054-b7764b0bb8af
		summarizeBy: none
		sourceColumn: properties.status

		annotation SummarizationSetBy = Automatic

	column 'properties.requestedBackupStorageRedundancy'
		dataType: string
		lineageTag: 813f61dc-e34d-4e36-8e34-7b6927e64f10
		summarizeBy: none
		sourceColumn: properties.requestedBackupStorageRedundancy

		annotation SummarizationSetBy = Automatic

	column 'properties.currentBackupStorageRedundancy'
		dataType: string
		lineageTag: 3e33bdba-e5a8-4e62-82ad-03d89229a0bc
		summarizeBy: none
		sourceColumn: properties.currentBackupStorageRedundancy

		annotation SummarizationSetBy = Automatic

	column 'properties.requestedServiceObjectiveName'
		dataType: string
		lineageTag: af12a0e4-5f6b-4136-8f66-e758356b3fe4
		summarizeBy: none
		sourceColumn: properties.requestedServiceObjectiveName

		annotation SummarizationSetBy = Automatic

	column 'properties.currentServiceObjectiveName'
		dataType: string
		lineageTag: cd1934b8-dc5c-48cb-8403-65271dc207c0
		summarizeBy: none
		sourceColumn: properties.currentServiceObjectiveName

		annotation SummarizationSetBy = Automatic

	column 'properties.maintenanceConfigurationId'
		dataType: string
		lineageTag: 1cb3c997-f2be-4859-af4d-6f3d36e5c179
		summarizeBy: none
		sourceColumn: properties.maintenanceConfigurationId

		annotation SummarizationSetBy = Automatic

	column 'properties.defaultSecondaryLocation'
		dataType: string
		lineageTag: 2bf59bbd-fc05-430d-b51e-69df2210c81b
		summarizeBy: none
		sourceColumn: properties.defaultSecondaryLocation

		annotation SummarizationSetBy = Automatic

	column 'properties.isInfraEncryptionEnabled'
		dataType: string
		lineageTag: e5b3fd5a-a63b-4157-9f66-044a496ffe59
		summarizeBy: none
		sourceColumn: properties.isInfraEncryptionEnabled

		annotation SummarizationSetBy = Automatic

	column 'properties.earliestRestoreDate'
		dataType: string
		lineageTag: 653f41c0-7694-4f68-bd7f-09e161b33118
		summarizeBy: none
		sourceColumn: properties.earliestRestoreDate

		annotation SummarizationSetBy = Automatic

	column 'properties.zoneRedundant'
		dataType: string
		lineageTag: d9db1e18-acbf-43c1-b16e-ff65408f68ed
		summarizeBy: none
		sourceColumn: properties.zoneRedundant

		annotation SummarizationSetBy = Automatic

	column 'properties.availabilityZone'
		dataType: string
		lineageTag: ef60777a-7cec-4e37-8a43-a28ddee51173
		summarizeBy: none
		sourceColumn: properties.availabilityZone

		annotation SummarizationSetBy = Automatic

	column 'properties.catalogCollation'
		dataType: string
		lineageTag: df1011c7-6c1d-45eb-b046-26883ef3218b
		summarizeBy: none
		sourceColumn: properties.catalogCollation

		annotation SummarizationSetBy = Automatic

	column 'properties.creationDate'
		dataType: dateTime
		formatString: General Date
		lineageTag: b992fe85-3c85-417a-8d10-eabdd4637707
		summarizeBy: none
		sourceColumn: properties.creationDate

		variation Variation
			isDefault
			relationship: f239fb3d-a7a3-415d-a381-6be0ee080c4c
			defaultHierarchy: LocalDateTable_8d91fcb6-a298-4c66-bbd7-6a780b6991d1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'properties.collation'
		dataType: string
		lineageTag: 053e716a-3da5-4ed5-858f-0f6618f430ae
		summarizeBy: none
		sourceColumn: properties.collation

		annotation SummarizationSetBy = Automatic

	column 'properties.licenseType'
		dataType: string
		lineageTag: b9be0a63-ae1e-42ae-8956-4cccf9f6d01d
		summarizeBy: none
		sourceColumn: properties.licenseType

		annotation SummarizationSetBy = Automatic

	column 'properties.maxSizeBytes'
		dataType: string
		lineageTag: 4940f7c9-f6c3-4f10-94b9-44fd09481ef5
		summarizeBy: none
		sourceColumn: properties.maxSizeBytes

		annotation SummarizationSetBy = Automatic

	column 'properties.isLedgerOn'
		dataType: string
		lineageTag: 67367866-5b63-4dfd-83ee-167f300b712d
		summarizeBy: none
		sourceColumn: properties.isLedgerOn

		annotation SummarizationSetBy = Automatic

	column 'properties.databaseId'
		dataType: string
		lineageTag: b42b02cb-edd1-440f-8c26-5eea9a557bdf
		summarizeBy: none
		sourceColumn: properties.databaseId

		annotation SummarizationSetBy = Automatic

	column 'properties.currentSku'
		dataType: string
		lineageTag: 7eadd5d8-035e-4efb-980a-52f021d663f1
		summarizeBy: none
		sourceColumn: properties.currentSku

		annotation SummarizationSetBy = Automatic

	column 'properties.readScale'
		dataType: string
		lineageTag: 4190c5df-985c-43d7-a284-15c82345f51f
		summarizeBy: none
		sourceColumn: properties.readScale

		annotation SummarizationSetBy = Automatic

	column 'properties.maxLogSizeBytes'
		dataType: string
		lineageTag: f2a78803-02cc-43d9-b2cc-660ca517fcb8
		summarizeBy: none
		sourceColumn: properties.maxLogSizeBytes

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: d154f6a6-bc99-4b56-a7ef-57300b466b2e
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 7fbf8855-8f95-4aea-95a6-92ea308ecd0f
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 5f0a07c9-57ba-40c1-a09b-00a2d36cb844
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 38cb854e-62d0-4beb-8998-e866ee7b755b
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition 'SQL DB' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("resources | where type == 'microsoft.sql/servers/databases'", "Tenant", null, null, [resultTruncated = false]),
				    #"Expanded sku" = Table.ExpandRecordColumn(Source, "sku", {"name", "tier", "capacity", "family"}, {"sku.name", "sku.tier", "sku.capacity", "sku.family"}),
				    #"Expanded properties" = Table.ExpandRecordColumn(#"Expanded sku", "properties", {"status", "requestedBackupStorageRedundancy", "currentBackupStorageRedundancy", "requestedServiceObjectiveName", "currentServiceObjectiveName", "maintenanceConfigurationId", "defaultSecondaryLocation", "isInfraEncryptionEnabled", "earliestRestoreDate", "zoneRedundant", "availabilityZone", "catalogCollation", "creationDate", "collation", "licenseType", "maxSizeBytes", "isLedgerOn", "databaseId", "currentSku", "readScale", "maxLogSizeBytes"}, {"properties.status", "properties.requestedBackupStorageRedundancy", "properties.currentBackupStorageRedundancy", "properties.requestedServiceObjectiveName", "properties.currentServiceObjectiveName", "properties.maintenanceConfigurationId", "properties.defaultSecondaryLocation", "properties.isInfraEncryptionEnabled", "properties.earliestRestoreDate", "properties.zoneRedundant", "properties.availabilityZone", "properties.catalogCollation", "properties.creationDate", "properties.collation", "properties.licenseType", "properties.maxSizeBytes", "properties.isLedgerOn", "properties.databaseId", "properties.currentSku", "properties.readScale", "properties.maxLogSizeBytes"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded properties",{{"properties.creationDate", type datetimezone}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

