table Subscriptions
	lineageTag: 758ebf4f-7d8d-43ca-b230-9c82fde7c2c8

	column id
		dataType: string
		lineageTag: 33f65546-b3ec-4a6a-b980-481ea223822b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b2ca4d1f-0c91-42f6-b3c3-1ce8894bc94f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: f7ca7218-ac4e-49be-b2b3-53ab635e9c7a
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 1c8478eb-928f-416f-bf69-dab5e564ed62
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 5d5e6a7d-33c6-40ad-b592-da52bea42fe8
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: f3900bf1-4741-4d10-8a72-6074f8d641b0
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: cb15b543-51b0-49d6-8903-28571a8d6a83
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 9f42bdca-e613-43c2-aab8-ee175e25ad17
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 3f1a1483-2cc9-4b05-b252-051619c07ac8
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 8849c3a9-5a18-46f6-b833-8e379d4b2e4e
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: c895d8b0-bfe2-48e9-9528-d6b06a93cbeb
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column managementGroupAncestorsChain
		dataType: string
		lineageTag: ac10e1ed-656c-4e6d-b5c5-d1f1b4fd2177
		summarizeBy: none
		sourceColumn: managementGroupAncestorsChain

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 990b336f-0b4c-4652-93a1-961e054b9e25
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: e082f5de-4984-41e5-8fbb-3de0779d5e0a
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: b62ac558-e234-42de-8887-9a3f45ad58a9
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 20dff3f5-9fc2-458d-a9fd-4cbb8b987faa
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: 6737ecb8-6329-4e29-9f02-2bd095a3b1f1
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition Subscriptions = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("resourcecontainers | where type == 'microsoft.resources/subscriptions'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"managementGroupAncestorsChain", "state"}, {"managementGroupAncestorsChain", "state"})
				in
				  #"Expanded properties"

