table 'Virtual Machines'
	lineageTag: c8d18cc6-8328-4ec7-871c-770b1b53f96a

	column id
		dataType: string
		lineageTag: 5fdaa6e7-5070-4296-a1d8-cb3846a3a014
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ca681b08-2eb2-4cc9-80f3-11c864611211
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 6760ae60-8923-4b3e-85d4-3e5e71094a28
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column tenantId
		dataType: string
		lineageTag: 9a1270eb-d151-4ef2-8b5f-961226c584bc
		summarizeBy: none
		sourceColumn: tenantId

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: 3299b8b5-cfd7-4166-8872-84d39c595f1c
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 9ffc8b09-d517-445b-bc77-e3c039cdfd73
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column resourceGroup
		dataType: string
		lineageTag: 750c3c78-1204-4435-a60a-38e1b3e9e7a0
		summarizeBy: none
		sourceColumn: resourceGroup

		annotation SummarizationSetBy = Automatic

	column subscriptionId
		dataType: string
		lineageTag: 4ddf17ea-e834-46ed-8da4-d3b5253be0a2
		summarizeBy: none
		sourceColumn: subscriptionId

		annotation SummarizationSetBy = Automatic

	column managedBy
		dataType: string
		lineageTag: 0045f401-73cd-4fa8-a73e-ba1bf3005094
		summarizeBy: none
		sourceColumn: managedBy

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: dd7ff99b-4427-4481-984f-49f2c1d44d9a
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: e696eeec-f56b-4a79-9f06-2fc171b1d30b
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column provisioningState
		dataType: string
		lineageTag: aeaa3163-ba0e-4795-aa04-4d4174ed7f55
		summarizeBy: none
		sourceColumn: provisioningState

		annotation SummarizationSetBy = Automatic

	column timeCreated
		dataType: string
		lineageTag: bd89fa5a-cdf3-4686-be7a-3b6e8606254b
		summarizeBy: none
		sourceColumn: timeCreated

		annotation SummarizationSetBy = Automatic

	column 'networkInterfaces.properties.deleteOption'
		dataType: string
		lineageTag: 825ed5cb-2bcb-47e6-9a98-2261d417070f
		summarizeBy: none
		sourceColumn: networkInterfaces.properties.deleteOption

		annotation SummarizationSetBy = Automatic

	column 'networkInterfaces.id'
		dataType: string
		lineageTag: 2701f0db-4efe-40df-94fd-de49168d6387
		summarizeBy: none
		sourceColumn: networkInterfaces.id

		annotation SummarizationSetBy = Automatic

	column 'osProfile.computerName'
		dataType: string
		lineageTag: 52c2757b-f8c6-4d22-b6e0-9d1327d25ece
		summarizeBy: none
		sourceColumn: osProfile.computerName

		annotation SummarizationSetBy = Automatic

	column 'osProfile.requireGuestProvisionSignal'
		dataType: string
		lineageTag: c3b3c8f6-89ac-43b4-8f27-335384a0c930
		summarizeBy: none
		sourceColumn: osProfile.requireGuestProvisionSignal

		annotation SummarizationSetBy = Automatic

	column 'osProfile.allowExtensionOperations'
		dataType: string
		lineageTag: 435b464d-568d-4de7-8aa1-bf0d027875c8
		summarizeBy: none
		sourceColumn: osProfile.allowExtensionOperations

		annotation SummarizationSetBy = Automatic

	column 'osProfile.adminUsername'
		dataType: string
		lineageTag: bf70d2b7-7b5e-4ad4-86a0-442720f01ad0
		summarizeBy: none
		sourceColumn: osProfile.adminUsername

		annotation SummarizationSetBy = Automatic

	column 'osProfile.secrets'
		dataType: string
		lineageTag: 63d5eaa1-5598-4f9d-a690-806dd0d71799
		summarizeBy: none
		sourceColumn: osProfile.secrets

		annotation SummarizationSetBy = Automatic

	column 'osProfile.linuxConfiguration'
		dataType: string
		lineageTag: a2d71e2c-dc82-4b50-9130-5ca99918f6a9
		summarizeBy: none
		sourceColumn: osProfile.linuxConfiguration

		annotation SummarizationSetBy = Automatic

	column 'osProfile.windowsConfiguration'
		dataType: string
		lineageTag: 3473b502-84b0-4c49-a9a9-0066b4dc1b0d
		summarizeBy: none
		sourceColumn: osProfile.windowsConfiguration

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.imageReference.publisher'
		dataType: string
		lineageTag: 8a352acf-e049-46bc-a1a6-8e8bce01c199
		summarizeBy: none
		sourceColumn: storageProfile.imageReference.publisher

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.imageReference.sku'
		dataType: string
		lineageTag: 21689d18-044e-4525-a59f-d853535cd49d
		summarizeBy: none
		sourceColumn: storageProfile.imageReference.sku

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.imageReference.version'
		dataType: string
		lineageTag: ea183530-ee9c-4e29-9648-4ab19f6c509f
		summarizeBy: none
		sourceColumn: storageProfile.imageReference.version

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.imageReference.exactVersion'
		dataType: string
		lineageTag: a4059653-17d5-413c-819a-8721620f8946
		summarizeBy: none
		sourceColumn: storageProfile.imageReference.exactVersion

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.imageReference.offer'
		dataType: string
		lineageTag: 65d40618-25c7-4358-85cc-416e9659223c
		summarizeBy: none
		sourceColumn: storageProfile.imageReference.offer

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.name'
		dataType: string
		lineageTag: b7acee6f-b2f3-4123-a09e-f54e2fb687e7
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.name

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.createOption'
		dataType: string
		lineageTag: d4926a62-5551-456a-85f2-2380e2d82dc7
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.createOption

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.deleteOption'
		dataType: string
		lineageTag: 6740f178-5f5a-47bf-b419-d147b2164f70
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.deleteOption

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.managedDisk.id'
		dataType: string
		lineageTag: 2d11cb97-57bc-4045-9095-e977f96fedba
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.managedDisk.id

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.caching'
		dataType: string
		lineageTag: 649e8480-d932-4aa0-819d-3960b07c6696
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.caching

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.toBeDetached'
		dataType: string
		lineageTag: 539a0de2-30f8-4d42-8cec-2e22d467e643
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.toBeDetached

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.writeAcceleratorEnabled'
		dataType: string
		lineageTag: 4520cfe0-d4ca-4139-bac9-8b7dc484a8c0
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.writeAcceleratorEnabled

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.dataDisks.lun'
		dataType: string
		lineageTag: 17a31b9d-06cb-417a-af1d-8b46c3bb1913
		summarizeBy: none
		sourceColumn: storageProfile.dataDisks.lun

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.name'
		dataType: string
		lineageTag: 53e51269-5f77-413a-a7fc-964084557dba
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.name

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.createOption'
		dataType: string
		lineageTag: a04d42c2-3164-4e16-921f-ba9e0e118f97
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.createOption

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.osType'
		dataType: string
		lineageTag: cd6ec9d9-9457-43cd-a668-fcbc41f04dd7
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.osType

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.deleteOption'
		dataType: string
		lineageTag: 737bb1f2-0e01-4cb0-bd9a-84aa4a0a93e7
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.deleteOption

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.managedDisk.id'
		dataType: string
		lineageTag: c5207dc5-5e89-415f-8a0f-06776fec2054
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.managedDisk.id

		annotation SummarizationSetBy = Automatic

	column 'storageProfile.osDisk.caching'
		dataType: string
		lineageTag: bea61b2c-c90c-4979-9da4-b7faf11b102c
		summarizeBy: none
		sourceColumn: storageProfile.osDisk.caching

		annotation SummarizationSetBy = Automatic

	column 'hardwareProfile.vmSize'
		dataType: string
		lineageTag: 45fd8f69-49e7-4792-8a5f-a7afbb03763b
		summarizeBy: none
		sourceColumn: hardwareProfile.vmSize

		annotation SummarizationSetBy = Automatic

	column vmId
		dataType: string
		lineageTag: 5abd5355-3ed9-4844-8253-eebc31b831dd
		summarizeBy: none
		sourceColumn: vmId

		annotation SummarizationSetBy = Automatic

	column 'diagnosticsProfile.bootDiagnostics.enabled'
		dataType: string
		lineageTag: 4c6ac9d8-7c72-410e-ae38-e2c388f8e7e8
		summarizeBy: none
		sourceColumn: diagnosticsProfile.bootDiagnostics.enabled

		annotation SummarizationSetBy = Automatic

	column 'diagnosticsProfile.bootDiagnostics.storageUri'
		dataType: string
		lineageTag: c9cdefe7-1c0f-42f4-9409-6730e67181eb
		summarizeBy: none
		sourceColumn: diagnosticsProfile.bootDiagnostics.storageUri

		annotation SummarizationSetBy = Automatic

	column 'powerState.displayStatus'
		dataType: string
		lineageTag: 4e64a079-2386-473a-bec0-47def6a86ba7
		summarizeBy: none
		sourceColumn: powerState.displayStatus

		annotation SummarizationSetBy = Automatic

	column licenseType
		dataType: string
		lineageTag: ba1f41c4-23a1-4b31-8bdc-78200b328a14
		summarizeBy: none
		sourceColumn: licenseType

		annotation SummarizationSetBy = Automatic

	column tags
		dataType: string
		lineageTag: 0fb25d0a-8b48-485c-8ac4-7c0eaa9c3a2a
		summarizeBy: none
		sourceColumn: tags

		annotation SummarizationSetBy = Automatic

	column identity
		dataType: string
		lineageTag: 3a3ff514-56b8-4b9c-a056-2a9db508c36b
		summarizeBy: none
		sourceColumn: identity

		annotation SummarizationSetBy = Automatic

	column zones
		dataType: string
		lineageTag: 0cd4408c-0262-40f2-aeca-ffa3def9d885
		summarizeBy: none
		sourceColumn: zones

		annotation SummarizationSetBy = Automatic

	column extendedLocation
		dataType: string
		lineageTag: dd92087c-35e5-4749-b45b-ce73c19ba9ae
		summarizeBy: none
		sourceColumn: extendedLocation

		annotation SummarizationSetBy = Automatic

	partition 'Virtual Machines' = m
		mode: import
		queryGroup: 'FinOps toolkit'
		source =
				let
				  Source = AzureResourceGraph.Query("Resources | where type =~ 'Microsoft.Compute/virtualMachines'", "Tenant", null, null, [resultTruncated = false]),
				  #"Expanded properties" = Table.ExpandRecordColumn(Source, "properties", {"provisioningState", "timeCreated", "networkProfile", "osProfile", "storageProfile", "hardwareProfile", "vmId", "diagnosticsProfile", "extended", "licenseType"}, {"provisioningState", "timeCreated", "networkProfile", "osProfile", "storageProfile", "hardwareProfile", "vmId", "diagnosticsProfile", "extended", "licenseType"}),
				  #"Expanded osProfile" = Table.ExpandRecordColumn(#"Expanded properties", "osProfile", {"computerName", "requireGuestProvisionSignal", "allowExtensionOperations", "adminUsername", "secrets", "linuxConfiguration", "windowsConfiguration"}, {"osProfile.computerName", "osProfile.requireGuestProvisionSignal", "osProfile.allowExtensionOperations", "osProfile.adminUsername", "osProfile.secrets", "osProfile.linuxConfiguration", "osProfile.windowsConfiguration"}),
				  #"Expanded networkProfile" = Table.ExpandRecordColumn(#"Expanded osProfile", "networkProfile", {"networkInterfaces"}, {"networkInterfaces"}),
				  #"Expanded networkInterfaces" = Table.ExpandListColumn(#"Expanded networkProfile", "networkInterfaces"),
				  #"Expanded networkInterfaces 1" = Table.ExpandRecordColumn(#"Expanded networkInterfaces", "networkInterfaces", {"properties", "id"}, {"networkInterfaces.properties", "networkInterfaces.id"}),
				  #"Expanded networkInterfaces.properties" = Table.ExpandRecordColumn(#"Expanded networkInterfaces 1", "networkInterfaces.properties", {"deleteOption"}, {"networkInterfaces.properties.deleteOption"}),
				  #"Expanded storageProfile" = Table.ExpandRecordColumn(#"Expanded networkInterfaces.properties", "storageProfile", {"imageReference", "dataDisks", "osDisk"}, {"storageProfile.imageReference", "storageProfile.dataDisks", "storageProfile.osDisk"}),
				  #"Expanded storageProfile.imageReference" = Table.ExpandRecordColumn(#"Expanded storageProfile", "storageProfile.imageReference", {"publisher", "sku", "version", "exactVersion", "offer"}, {"storageProfile.imageReference.publisher", "storageProfile.imageReference.sku", "storageProfile.imageReference.version", "storageProfile.imageReference.exactVersion", "storageProfile.imageReference.offer"}),
				  #"Expanded storageProfile.dataDisks" = Table.ExpandListColumn(#"Expanded storageProfile.imageReference", "storageProfile.dataDisks"),
				  #"Expanded storageProfile.dataDisks 1" = Table.ExpandRecordColumn(#"Expanded storageProfile.dataDisks", "storageProfile.dataDisks", {"name", "createOption", "deleteOption", "managedDisk", "caching", "toBeDetached", "writeAcceleratorEnabled", "lun"}, {"storageProfile.dataDisks.name", "storageProfile.dataDisks.createOption", "storageProfile.dataDisks.deleteOption", "storageProfile.dataDisks.managedDisk", "storageProfile.dataDisks.caching", "storageProfile.dataDisks.toBeDetached", "storageProfile.dataDisks.writeAcceleratorEnabled", "storageProfile.dataDisks.lun"}),
				  #"Expanded storageProfile.dataDisks.managedDisk" = Table.ExpandRecordColumn(#"Expanded storageProfile.dataDisks 1", "storageProfile.dataDisks.managedDisk", {"id"}, {"storageProfile.dataDisks.managedDisk.id"}),
				  #"Expanded storageProfile.osDisk" = Table.ExpandRecordColumn(#"Expanded storageProfile.dataDisks.managedDisk", "storageProfile.osDisk", {"name", "createOption", "osType", "deleteOption", "managedDisk", "caching"}, {"storageProfile.osDisk.name", "storageProfile.osDisk.createOption", "storageProfile.osDisk.osType", "storageProfile.osDisk.deleteOption", "storageProfile.osDisk.managedDisk", "storageProfile.osDisk.caching"}),
				  #"Expanded storageProfile.osDisk.managedDisk" = Table.ExpandRecordColumn(#"Expanded storageProfile.osDisk", "storageProfile.osDisk.managedDisk", {"id"}, {"storageProfile.osDisk.managedDisk.id"}),
				  #"Expanded hardwareProfile" = Table.ExpandRecordColumn(#"Expanded storageProfile.osDisk.managedDisk", "hardwareProfile", {"vmSize"}, {"hardwareProfile.vmSize"}),
				  #"Expanded diagnosticsProfile" = Table.ExpandRecordColumn(#"Expanded hardwareProfile", "diagnosticsProfile", {"bootDiagnostics"}, {"diagnosticsProfile.bootDiagnostics"}),
				  #"Expanded diagnosticsProfile.bootDiagnostics" = Table.ExpandRecordColumn(#"Expanded diagnosticsProfile", "diagnosticsProfile.bootDiagnostics", {"enabled", "storageUri"}, {"diagnosticsProfile.bootDiagnostics.enabled", "diagnosticsProfile.bootDiagnostics.storageUri"}),
				  #"Expanded extended" = Table.ExpandRecordColumn(#"Expanded diagnosticsProfile.bootDiagnostics", "extended", {"instanceView"}, {"instanceView"}),
				  #"Expanded instanceView" = Table.ExpandRecordColumn(#"Expanded extended", "instanceView", {"powerState"}, {"powerState"}),
				  #"Expanded powerState" = Table.ExpandRecordColumn(#"Expanded instanceView", "powerState", {"displayStatus"}, {"powerState.displayStatus"}),
				  #"Expanded zones" = Table.ExpandListColumn(#"Expanded powerState", "zones")
				in
				  #"Expanded zones"

